### ISSUE TITLE
ActionBar shadow ignored on Android 4.3

### ISSUE THREAD

**Issue by mobilekosmos** [JakeWharton/ActionBarSherlock#1003]
Starting with Android 4.3 the overlay of the actionbar defined in the styles with:

< item name="android:windowContentOverlay">@drawable/actionbar_shadow< / item >
< item name="windowContentOverlay">@drawable/actionbar_shadow< / item >

is ignored. They changed the implementation of the actionBar as can be seen here:
https://android.googlesource.com/platform/frameworks/base/+/df7221c

so I think the code is not compatible with this change.

**Comment by SimonVT** [comment]
Looks like they just changed it to be an ImageView below the action bar rather than a foreground drawable on the content view (as this would probably be displayed behind the action bar).
Anyway, when behavior changes it's up to you to handle it. Since ABS just delegates to the native implementation, this is not something we can change.

**Comment by snooplsm** [comment]
Looks like the LinearLayout is horizontal as well.  Guess they were not testing for the shadow.

**Comment by SimonVT** [comment]
Haha, good point. Nicely spotted

**Comment by SimonVT** [comment]
Googlers claim they've fixed it internally.

**Comment by snooplsm** [comment]
The hack would be to do something like this:

```
@Override
protected void onPostCreate(Bundle savedInstanceState) {
    super.onPostCreate(savedInstanceState);
    if(Build.VERSION.SDK_INT==Build.VERSION_CODES.JELLY_BEAN_MR2) {
        View view = findViewById(android.R.id.content);
        if(view instanceof FrameLayout) {
            FrameLayout content = (FrameLayout)view;        
            content.setForeground(getResources().getDrawable(R.drawable.actionbar_shadow));
        }
    }
}
```

**Comment by mobilekosmos** [comment]
My solution was to merge the background of the actionbar with the shadow 9path into one drawable.

**Comment by lexer** [comment]
Here is link to google issues tracker: https://code.google.com/p/android/issues/detail?id=58280

**Comment by lxqxsyu** [comment]
很好，解决了我的问题，Thank you
