### ISSUE TITLE
ActionBar with Tabs and custom repeating background looks bad

### ISSUE THREAD

**Issue by jondwillis** [JakeWharton/ActionBarSherlock#101]
This isn't a bug per se, but I wanted to bring it to your attention. In 3.4.0, I am setting a custom background drawable that has a repeating tile mode for my ActionBar. When I later add tabs, and the ActionBar is small (like on a WVGA device in portrait mode) the bar expands its height and the drawable is repeated, which in my case makes the tab look bad. I would expect this portion of the ActionBar to be transparent and show the "window background" - in my case just black. 

Example screenshot:
![](http://i.imgur.com/VlhuU.png)

Example snippet:

```
final Bitmap bmp = BitmapFactory.decodeResource(getResources(), R.drawable.actionbar_bg);

final BitmapDrawable bitmapDrawable = new BitmapDrawable(bmp);
bitmapDrawable.setTileModeXY(Shader.TileMode.REPEAT, Shader.TileMode.REPEAT);

final ActionBar bar = getSupportActionBar();
bar.setBackgroundDrawable(bitmapDrawable);
```

And then later...

```
bar.addTab(...);
```

A possible workaround would be to use `Tab.setCustomView(...)`, but that is not an elegant solution.

**Comment by JakeWharton** [comment]
Do you know how does Android 4.0+ handle this? Is the background limited to existing in the primary action bar only or does it extend it down into the tab bar?

**Comment by jondwillis** [comment]
The tab bar has a slightly off-black color, and scroll horizontally to support extra tabs.
![](http://i.imgur.com/VkiXN.png)

**Comment by JakeWharton** [comment]
It looks like they apply their own grey background to the tab navigation. Can you set your background on the 4.0 action bar and take a screenshot just to confirm.

If that is indeed the case I will update ActionBarSherlock to mimic the same behavior in the forthcoming 3.4.1 release.

**Comment by jondwillis** [comment]
Yes, sorry, my brain's not working 100% today. I meant to do that in the first screenshot. But yeah, that separate grey background seems to be the case.

![](http://i.imgur.com/IQdBr.png)

**Comment by JakeWharton** [comment]
Alright I'll get the implemented tomorrow in the dev branch and the release
is looking to be this weekend.

---

Jake Wharton
http://about.me/jakewharton
On Nov 7, 2011 5:56 PM, "Jon Willis" <
reply@reply.github.com>
wrote:

**Comment by jondwillis** [comment]
Thanks, I switched to the dev branch to try it out and this is working beautifully. The only suggestion I would have is to include the little light grey divider in between tabs for consistency with ICS. Also, are you planning on implementing the scrolling tab bar from ICS?

**Comment by JakeWharton** [comment]
Things like that light grey divider will come with ActionBarSherlock v4.0
which will be a full backport of the Ice Cream Sandwich implementation once
the sources are released.

I thought the scrolling tabs made it into this release... That might only
be for the inline tabs and not the tabs that are below the action bar. I'll
have a look and update the dev branch accordingly

---

Jake Wharton
http://about.me/jakewharton
