### ISSUE TITLE
Cannot reference project on gradle 0.5.+

### ISSUE THREAD

**Issue by alefranz** [JakeWharton/ActionBarSherlock#1011]
I have created a simple test project, but I'm unable to reference the library and build with gradle 0.5.+

I reference the library in setting.gradle:

```
include ':libs:ActionBarSherlock:actionbarsherlock'
```

and I include it in build.gradle:

```
compile project(':libs:ActionBarSherlock:actionbarsherlock')
```

I had to add the following header to the original build.gradle of ActionBarSherlock/actionbarsherlock:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.5.+'
    }
}
```

to avoid the missing plugin 'android-library' error

Now I get the following error:

```
Execution failed for task ':libs:ActionBarSherlock:actionbarsherlock:prepareReleaseDependencies'.
> loader constraint violation: when resolving method "com.android.xml.AndroidManifest.getMinSdkVersi
on(Lcom/android/io/IAbstractFile;)Ljava/lang/Object;" the class loader (instance of org/gradle/util/
MutableURLClassLoader) of the current class, com/android/builder/DefaultManifestParser, and the clas
s loader (instance of org/gradle/util/MutableURLClassLoader) for resolved class, com/android/xml/And
roidManifest, have different Class objects for the type Ljava/lang/Object; used in the signature
```

Any hint?

The test project is at:
https://github.com/alefranz/ActionBarSherlockTestProject

Thanks,
Alessio

**Comment by JakeWharton** [comment]
Why don't you pull it from Maven central?

``` groovy
compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'
```

**Comment by alefranz** [comment]
I prefer to use directly the sources with git submodule, so I could put my hands on the libraries code.
But I can't understand what's wrong with gradle :\

**Comment by JakeWharton** [comment]
Ah, I don't know then. I'm allergic to local dependencies. You should ask on StackOverflow or the ActionBarSherlock mailing list though since that's a better place for discussion and resolution. I'd like to only keep actual issues with the code here.
