### ISSUE TITLE
Disappearing ActioBar after finishing ActionMode

### ISSUE THREAD

**Issue by KamilLelonek** [JakeWharton/ActionBarSherlock#1013]
http://stackoverflow.com/questions/18219605/sherlock-actionmode-bugs

**Comment by JakeWharton** [comment]
If you are filing a bug report then file it here. Don't just link StackOverflow.

**Comment by KamilLelonek** [comment]
I've implemented `ActionMode` with `SherlockActionBar` and everything works fine, but only on devices post `HONEYCOMB`.

On older `APIs` I have the following problem:

Everything is fine when I start my app

![enter image description here](http://i.stack.imgur.com/mZ5Ff.png)

All goes well even when I start action mode and select a couple of items

![enter image description here](http://i.stack.imgur.com/46zve.png)

But when I exit (finish) action mode `ActionBarSherlock` crashes. I mean that it's no loger visible, only when I start or finish action mode, it blinks very shortly that I can see icons
![enter image description here](http://i.stack.imgur.com/EzssT.png)

So only updates show ActionBar for a short moment, but after that it remains "hidden" again.

Has anyone similar problem? Is there any sollution for that?
