### ISSUE TITLE
Does it possible to improve compatibility with new DrawerLayout?

### ISSUE THREAD

**Issue by Alexious-sh** [JakeWharton/ActionBarSherlock#1015]
DrawerLayout may change homeAsUp icon, when open Drawer. But it works only with ActionBar from SupportLibrary.
May be possible to get it working with ABS too?

**Comment by felipecsl** [comment]
There is a Pull Request that was never merged in: https://github.com/JakeWharton/ActionBarSherlock/pull/946

**Comment by JakeWharton** [comment]
Sorry, no. AppCompat is the way to go if you need DrawerLayout support.
