### ISSUE TITLE
SearchView.onSubmitQuery rejects empty Strings

### ISSUE THREAD

**Issue by blacelle** [JakeWharton/ActionBarSherlock#1016]
Hi Jake,

I'd like SearchView to call onSubmitQuery even if the user did not enter anything but it seems there i no proper way to do this.

Could you explain why we check for the input emptiness? And is it possible to introduce an entry point to configure this behavior, for instance by making this method protected?

Here is a related SOF post:
http://stackoverflow.com/questions/13576283/android-searchview-onquerytextlistener-onquerytextsubmit-not-fired-on-empty-quer

Thanks a lot.

**Comment by SimonVT** [comment]
We check for emptiness because https://github.com/android/platform_frameworks_base/blob/master/core/java/android/widget/SearchView.java#L518

**Comment by SimonVT** [comment]
And https://github.com/android/platform_frameworks_base/blob/master/core/java/android/widget/SearchView.java#L1160

**Comment by blacelle** [comment]
Hi Simon,

I understand from the first referred piece of code that calling setQuery with an empty String should not call onSubmitQuery. Still, why not allowing to override this behavior inside onSubmitQuery since this check is done in advance where necessary.

In my case (which is exactly your second reference), the call to onSubmitQuery comes from mOnEditorActionListener: I'd like the search to be executed even if the user did not entered anything. Is there any other way to handle this use-case ?

Thanks

**Comment by SimonVT** [comment]
ABS mirrors the native behavior. If the framework does not offer a way to change this, then neither does ABS.
If native classes does not fit your use-case, you should look writing your own.

**Comment by blacelle** [comment]
Fine. Thanks for your support!
