### ISSUE TITLE
ActionBarSherlock - Action Items in menu overlapped by 'three dots button'

### ISSUE THREAD

**Issue by neonosos** [JakeWharton/ActionBarSherlock#1017]
Hi. Today, I'm fighting a pretty ugly bug.
I want to put some items into bottom menu (not using tabs), but I want that these items only have defined "Title" and not "Icon". Everything works on devices with Android <= ICS. Widths of menu items are calculated correctly (I'd like to use "always" attribute for first three items, others use "ifRoom").
When I start the app on JB device, the last of these menu items is overlaped by "three dots button" hiding other four menu items.

I've tested this on HW Ascend G300 (ICS, hw menu button disabled), where the result was correct. On HTC X (JB), the result was incorrect.

Ps: when I set icon of first menu item (action_menu_map), everything works (I don't want to set it, of course).

<menu xmlns:android="http://schemas.android.com/apk/res/android" >
     <item 
         android:id="@+id/action_menu_map"
         android:showAsAction="always"
         android:title="@string/ab_map"/>
     <item 
         android:id="@+id/action_menu_list"
         android:title="@string/ab_list"
         android:showAsAction="always"/>
     <item 
         android:id="@+id/action_menu_routes"
         android:title="@string/ab_routes"
         android:showAsAction="always"/>
     <item 
         android:id="@+id/action_menu_call"
         android:title="@string/ab_call"
         android:icon="@drawable/call_icon"
         android:showAsAction="ifRoom"/>
     <item 
         android:id="@+id/action_menu_report_event"
         android:title="@string/ab_report_event"
         android:icon="@drawable/message_icon"
         android:showAsAction="ifRoom"/>
     <item 
         android:id="@+id/action_menu_settings"
         android:title="@string/ab_settings"
         android:showAsAction="ifRoom"/>
     <item 
         android:id="@+id/action_menu_info"
         android:title="@string/ab_info"
         android:showAsAction="ifRoom"/>
</menu>

Thanks ;)

**Comment by JakeWharton** [comment]
Both of the devices you list are ICS+ where the native implementation is used.
