### ISSUE TITLE
Robolectric 2.x support

### ISSUE THREAD

**Issue by aahlenst** [JakeWharton/ActionBarSherlock#1019]
What is the current status of Robolectric 2.x support? Are there any plans?

Very basic activity testing (with a very limited stub ActionBar) is possible when using https://gist.github.com/xian/5052673 (Maven users also need http://stackoverflow.com/a/16930396/759042), but as soon as tabs or menus are involved, the stub ActionBar is of no use and one is stuck with NullPointerExceptions. And extending the stub ActionBar does not seem like a sensible solution.

**Comment by JakeWharton** [comment]
ActionBarSherlock is just a widget that wraps the content view of an activity. It's on Robolectric to support it, not me.
