### ISSUE TITLE
Button size changed when using Sherlock Theme

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#1022]
When I use Sherlock theme (Theme.Sherlock.Light.DarkActionbar), the button becomes much bigger than in NoTittleBar. (but this problem does not appear when using ImageButton)

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

    <Button
       android:id="@+id/test"
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:background="@drawable/ic_menu_search"
       android:focusable="false"
       android:gravity="center"
       android:textOff=""
       android:textOn="" />
</LinearLayout>
```

![notitlebar](https://f.cloud.github.com/assets/2217004/1025097/3c1c65e2-0e3a-11e3-9bd4-4e0f82dc49f3.png)
![with_actionbar](https://f.cloud.github.com/assets/2217004/1025098/3c587104-0e3a-11e3-9d05-cc81e0edd0f5.png)

How can I fix this? (because I need ToggleButton and normal Button - with Text)

**Comment by JakeWharton** [comment]
Use `Theme.Light.Holo.NoActionBar`. `Theme.Light.NoTitleBar` is a Gingerbread-y theme which has different button paddings.
