### ISSUE TITLE
Unable to unarchive the .zip file Error when try to unzip the library on Mac OS

### ISSUE THREAD

**Issue by chamikarazin** [JakeWharton/ActionBarSherlock#1026]
Unable to unarchive the .zip file Error when try to unzip the library on Mac OS
![screen shot 2013-08-29 at 5 54 57 pm](https://f.cloud.github.com/assets/2269060/1055232/9779bfca-112d-11e3-9841-5ad5730f4c8c.png)

**Comment by JakeWharton** [comment]
The zip files are created by GitHub automatically. There's a "contact" link at the bottom of every page. I would report it to them.
