### ISSUE TITLE
Typecasting SherlockActivity into a subclass of a SherlockFragmentActivity

### ISSUE THREAD

**Issue by vince015** [JakeWharton/ActionBarSherlock#1032]
Scenario:

```
public class MyFragmentActivity extends SherlockFragmentActivity {}

void myFunc(SherlockActivity activity) {
    MyFragmentActivity fragment = (MyFragmentActivity) activity;
}
```

I cannot cast the variable activity(which is an instance of SherlockActivity) into a subclass of a SherlockFragmentActivity.
When I change remove all 'Shelock' prefixes into Activity subclass the casting works. Any suggestion on how to do it? Thank you.

**Comment by f2prateek** [comment]
You can't do this directly with typecasting.

`Activity` -> `SherlockActivity`
`Activity` -> `FragmentActivity` -> `Watson` -> `SherlockFragmentActivity`

As you can see the, hierarchies are not common. Only `Activity` is common between `SherlockFragmentActivity` and `SherlockActivity`.
