### ISSUE TITLE
Layout No Limits causes menu to show incorrectly

### ISSUE THREAD

**Issue by init2winitapps** [JakeWharton/ActionBarSherlock#1033]
If I use the following flag in my app my menu appears off the screen
WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS
I need the flag above since in some instances my views go off screen however I'm stuck with what's below. Is there any way I can force the menu to show correctly. Maybe a way for me to set the menus coordinates?

![fcbbh](https://f.cloud.github.com/assets/3957990/1085473/d3d3bba8-15d1-11e3-8b97-d45aa6e42b56.jpg)

**Comment by JakeWharton** [comment]
What version of Android?

**Comment by init2winitapps** [comment]
My phone is using 4.1.1 it's a HTC DNA but the issue also occurs on my tablet running 3.2 and it's a Samsung Galaxy Tab 10.1

Thanks for the quick reply

**Comment by JakeWharton** [comment]
Well on Android 4.0+ that's the native action bar. The fact that you get the same behavior on both means ActionBarSherlock is doing its job (emulating the native action bar). Sounds like you should file a bug on http://b.android.com for it.

**Comment by init2winitapps** [comment]
I just ran it again on my tablet and sorry I thought it was exactly the same (been a little while since I've used the tablet) but on my tablet it actually doesn't show the menu at all, nothing is visible on screen but if i press where the menu would be the intents still trigger. 

The issue has affected a few others as well (one example below) but they all solved it by removing the flag. I, however, need the flag unfortunately
http://stackoverflow.com/questions/11603210/overflow-menu-incorrectly-positioned

So my next question, since I haven't gone through your library much yet is there no way to force the menu where to show? Is that all done by Android

**Comment by init2winitapps** [comment]
Is there no way then to force the location of the menu? Is that handled by Android? if so I'll file a bug report but I want to be sure I can't force it by an edit in your library. Thank you

**Comment by JakeWharton** [comment]
There's no way to force it, no. None that I know of at least. On Android 4.0+ ActionBarSherlock does almost nothing. Everything is handled by the normal system. I've never encountered this window flag so I'm afraid I can't help you. Sorry!

**Comment by init2winitapps** [comment]
Okay thank you just wanted to know, before I went all through your library trying to fix it. Thanks for the responses it's much appreciated. I'll close the issue and file an issue with Android thanks for the help!
