### ISSUE TITLE
Themeing ShareActionProvider

### ISSUE THREAD

**Issue by rekire** [JakeWharton/ActionBarSherlock#1036]
I want to theme the `ShareActionProvider` of the ActionBarSherlock. My problem is that I successfully customized the styles of the ActionBar but I cannot style the share popup which comes from the ActionBarSherlock. I digged thrue the soucecode of that class but I found nothing which could been changed with a theme.

![Share and Menu example](http://i.stack.imgur.com/wdiiH.png)

In the Screenshot above you can see the share popup uses the default styles while a normal _more_ popup is styled in that way I like.

See also my question on [StackOverflow](http://stackoverflow.com/q/18694510/995926).

**Comment by JakeWharton** [comment]
This can't be done. Your best bet is to steal a bunch of code from `ShareActionProvider` (the intent lookup and action provider stuff) and just make your own. Like `Switch` this has no public theme attributes to affect its styling, unfortunately.

**Comment by rekire** [comment]
Thank you for your comment! Could you have another look to my [StackOverflow question](http://stackoverflow.com/q/18694510/995926)? I did some more reseach and updated my question there, but I'm stuck again maybe you have an idea? The point `com.actionbarsherlock.R.attr.listPopupWindowStyle` vs `com.android.internal.R.attr.popupWindowStyle` vs `android.R.attr.popupWindowStyle` make me headage. I don't understand the _attr_ and _styleable_ stuff.

**Comment by rekire** [comment]
Finally I got it sloved:

```
<style name="Widget.Sherlock.ListPopupWindow" parent="@style/DropDownNav.MyStyle"></style>

<style name="DropDownNav.MyStyle" parent="@style/Widget.Sherlock.Spinner.DropDown.ActionBar">
    <item name="android:popupBackground">@drawable/menu_dropdown_panel_mystyle</item>
    <item name="android:divider">#081925</item>
    <item name="android:dividerHeight">1dp</item>
</style>
```

Possible that you can inherent that style in some other way. Not sure however that works for me!
