### ISSUE TITLE
ActionBar disappears after update on android 4.2.2 

### ISSUE THREAD

**Issue by vishwasdoth** [JakeWharton/ActionBarSherlock#1039]
I am using Sherlock from last one year and haven't face any issues so far. But yesterday I updated my Samsung Grand DUOS with some os update. This update removed my Sherlockbar and I have no clue what to do?

Note: Application was already installed and it was showing actionbar properly after update on 4.2.2 was success I have checked application and actionbar was missing. 

Any idea why it is happening?

**Comment by JakeWharton** [comment]
Android 4.2.2 uses the native action bar. ABS does nothing except proxy method calls to the native implementation in this case. I don't know what could be causing this, sorry.
