### ISSUE TITLE
Changing background of menu item only

### ISSUE THREAD

**Issue by subairariyil** [JakeWharton/ActionBarSherlock#1041]
How to change background of menu items. When I tried with actionBarItemBackground it changes the background of logo also. Or Can I add a divider if I have only one action item which is to be shown as text only

**Comment by JakeWharton** [comment]
> How to change background of menu items. When I tried with actionBarItemBackground it changes the background of logo also.

You can try a custom action view perhaps. Otherwise, you might not be able to.

> Or Can I add a divider if I have only one action item which is to be shown as text only

No. Divider logic is fixed.

Please ask future questions on the mailing list or StackOverflow.
