### ISSUE TITLE
ActionButton with ActionProvider has no pressed-state

### ISSUE THREAD

**Issue by trybnikova** [JakeWharton/ActionBarSherlock#1045]
Hello,

I'm using an ActionButton with an ActionProvider, which defines its View (onCreateActionView()). The Problem now is, that the Button has no pressed-state (background is not blue).

Is that normal or is there a workaround to fix it?

**Comment by JakeWharton** [comment]
Add the following to the root element in your XML:

``` xml
style="?attr/actionButtonStyle"
```

See `settings_action_provider.xml` for an example in the "demos" sample.
