### ISSUE TITLE
Sherlock spinner style looks different under Gingerbread and JellyBean - unwanted underline

### ISSUE THREAD

**Issue by Neril** [JakeWharton/ActionBarSherlock#1047]
When using an IcsSpinner from Sherlock with the Sherlock Holo themes I found it looks different under Gingerbread and JellyBean. On JellyBean it has an underline, on Gingerbread it does not.

The style attribute for the spinner is set to "actionDropDownStyle", which resolves to Widget.Sherlock.Spinner.DropDown.ActionBar or Widget.Sherlock.Light.Spinner.DropDown.ActionBar

This resolves differently on Gingerbread and Jellybean. Sherlock uses a Sherlock-defined style for Gingerbread. On v14+ it inherits from an android style:

```
<style name="Widget.Sherlock.Spinner.DropDown.ActionBar" parent="android:Widget.Holo.Spinner">
</style>
<style name="Widget.Sherlock.Light.Spinner.DropDown.ActionBar" parent="android:Widget.Holo.Light.Spinner">
</style>
```

To be consistent I think it should actually be:

```
<style name="Widget.Sherlock.Spinner.DropDown.ActionBar" parent="android:Widget.Holo.Spinner.DropDown.ActionBar">
</style>
<style name="Widget.Sherlock.Light.Spinner.DropDown.ActionBar" parent="Widget.Holo.Light.Spinner.DropDown.ActionBar">
</style>
```

**Comment by SimonVT** [comment]
There's no support for using internal classes outside of ABS.
