### ISSUE TITLE
Admob banner ad is not loading in SherlockFragmentActivity

### ISSUE THREAD

**Issue by accuratecompass** [JakeWharton/ActionBarSherlock#1049]
I tried to load Admob banner ads in the SherlockFragmentActivity. It is not loading. But, when I tried the appflood banner ads, it worked.

I tried with the latest Admob SDK 6.4.1, then I tried with older SDK 6.2.1, but I couldn't get any result. No error was recorded in the log cat.

Following is my code : 

public class SampleClass extends SherlockFragmentActivity 
{
private ViewPager _mViewPager;
private ViewPagerAdapter _adapter;
private AdView adView = null;  
private boolean adShown = false;

@Override
public void onCreate(Bundle savedInstanceState)
 {
        super.onCreate(savedInstanceState);  
        setContentView(R.layout.main);
        setUpView();
        setTab();
        _mViewPager.setCurrentItem(1);
        this.adShown = false;
        AdUpdate();
 }

private void setUpView()
{
     _mViewPager = (ViewPager) findViewById(R.id.viewPager);
     _adapter = new ViewPagerAdapter(getApplicationContext(),getSupportFragmentManager());
     _mViewPager.setAdapter(_adapter);
     _mViewPager.setCurrentItem(1);  
}

private void setTab() 
{
_mViewPager.setOnPageChangeListener(new OnPageChangeListener(){                     

@Override
public void onPageScrollStateChanged(int position) 
{}

@Override
public void onPageScrolled(int arg0, float arg1, int arg2) 
{}

@Override
public void onPageSelected(int position) 
{           

switch(position) 
{ 
case 0:  
findViewById(R.id.firstTab).setVisibility(View.VISIBLE);
findViewById(R.id.secondTab).setVisibility(View.INVISIBLE);
break;
case 1:  
findViewById(R.id.firstTab).setVisibility(View.VISIBLE);
findViewById(R.id.secondTab).setVisibility(View.INVISIBLE);
break;
}
}
});  
}

public void AdUpdate()
{
        if(!this.adShown)
        {
            this.adShown = true;  
            this.adView = new AdView(this, AdSize.SMART_BANNER, MY_ID);
            AdRequest adRequest = new AdRequest();  
            RelativeLayout.LayoutParams params = new                RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT, 
                RelativeLayout.LayoutParams.WRAP_CONTENT);  
                params.addRule(RelativeLayout.ALIGN_PARENT_TOP);                _mViewPager.addView(adView, params);
                adView.loadAd(adRequest);

/*
Following code also didn't work for Admob banner ads. But it worked for appflood banner ads.
RelativeLayout relativeLayout = (RelativeLayout)findViewById(R.id.l1root);  
RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.WRAP_CONTENT);  
params.addRule(RelativeLayout.ALIGN_PARENT_BOTTOM);
relativeLayout.addView(adView, params);
*/

}
}

///Code for Layout Fragment
public class LayoutOne extends Fragment 
{
    public static Fragment newInstance(Context context) 
    {
        LayoutOne f = new LayoutOne();
        return f;
    }

```
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,Bundle savedInstanceState) 
```

   {
        ViewGroup root = (ViewGroup) inflater.inflate(R.layout.layout_one, null);
        return root;
    }  
}

**Comment by JakeWharton** [comment]
This is not the appropriate forum for this. Try StackOverflow.

**Comment by IgorGanapolsky** [comment]
There should have been some output in the LogCat, such as it couldn't fetch the ad or there wasn't enough ad inventory.  Are you running into this problem on a real device or in the emulator??

**Comment by accuratecompass** [comment]
Hi Igor,

The issue is fixed. It is working fine now.
It happened in the device only.

Many thanks,
Gurunathan
