### ISSUE TITLE
Android support library reference is wrong (imo)

### ISSUE THREAD

**Issue by artiomchi** [JakeWharton/ActionBarSherlock#1050]
I've recently moved my app to a gradle build, and (mostly) everything is great, except for one thing. I realised that ActionBarSherlock adds a dependency to the Android support library as "com.google.android:support-v4".

Sure, this is what's currently listed on Maven, but when you install Android SDK (which is required to build android apps), it contains a local repository with the android support library. It makes much more sense to use that local repo bundled with the Android SDK than an outdated version on the Maven repository.

The good thing is - the reference is completely transparent. You just reference the library, and the build code will pick it up from the local SDK repo!

The bad thing - ABS is referencing the wrong library! :(
ABS is currently referencing com.google.android:support-v4
The correct reference should be com.android:support:support-v4.

Because of this issue I can't reference ABS from maven, because it causes build errors!  Since there are two completely different libraries with the same code.

In fact, there's a different build of ABS out there that references the correct android support library: com.prolificinteractive:actionbarsherlock:4.3.1

Could this be fixed please? :)

**Comment by artiomchi** [comment]
Seems like There is a way to get it to work. Maybe it's thanks to the new gradle build plugin (I seem to remember they changed the way library packages work) or something.. 

Thanks for the 4.4.0 release with the aar artifacts :)

**Comment by artiomchi** [comment]
Actually, no.. It worked for some reason, but once I ran "gradle clean" it stopped working, complaining about the same classes being added in both libraries. I really think you should be referencing the correct new support library reference.

**Comment by IgorGanapolsky** [comment]
I am getting the same problem.  I must delete the android-support-v4.jar file from actionbarsherlock/libs, and relink it to my own project's /libs folder.  But that creates a circular dependency!

**Comment by JakeWharton** [comment]
Sonatype doesn't allow promoting artifacts which reference non-existent artifacts. The Maven apklib references the support library in Maven central. The Gradle aar doesn't reference any support library but requires you to always have it added manually.

**Comment by artiomchi** [comment]
I understand what you're saying, Jake, but what about this library?  
http://search.maven.org/#artifactdetails%7Ccom.prolificinteractive%7Cactionbarsherlock%7C4.3.1%7Caar

It's been pushed to Maven, and it's got the new Android support library reference, which is not in the global Maven repos.

Also, while the gradle's aar doesn't specifically reference the support library, it's still pulled down and causing compilation issues :(

And as I said in the original issue, everyone building Android apps will have the SDK installed, which means they can get access to the local SDK repo with the support library there

**Comment by JakeWharton** [comment]
> It's been pushed to Maven, and it's got the new Android support library reference, which is not in the global Maven repos.

Then they violated the guidelines.

> Also, while the gradle's aar doesn't specifically reference the support library, it's still pulled down and causing compilation issues :(

Works for me @ https://github.com/JakeWharton/ActionBarSherlock-Gradle-Sample

**Comment by artiomchi** [comment]
> Then they violated the guidelines.

Is that really true? I haven't found any reference forcing all your dependencies to already be there. In fact, I've found this line in their docs:

>  In ideal conditions, all your dependencies should be already in central and central repository is self-contained. 

which makes me thing that they would obviously rather want you to have all your dependencies already available, but that's not a hard requirement.

Later on they also state:

> If some of your dependencies are not in central, please upload them using our 3rd-party artifacts bundle upload service.

So maybe we could upload the current latest Android support library to maven, so that this wouldn't be a problem? What do you think?

**Comment by artiomchi** [comment]
> Works for me @ https://github.com/JakeWharton/ActionBarSherlock-Gradle-Sample

If that's all I build - yes, it does work. But if I try to add another dependency (a library that depends on ABS 4.4.0 and the support library) the build stops working.. (

**Comment by JakeWharton** [comment]
The license you sign when downloading the support library forbids binary
redistribution. You'd have to compile your own from AOSP to upload. Of
course, it depends on Android 4.3 itself so you should also create an
artifact for that...

**Comment by artiomchi** [comment]
Ok, fair enough.. What about my point that Sonatype don't _force_ you to have all the dependencies to be already deployed? Or am I missing some terms of theirs elsewhere that contradict that sentence on their [docs](https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide)?

**Comment by JakeWharton** [comment]
Thousands of projects rely on the apklib artifact having a reference to the support library. It's too late to change. Besides, just because you can do something doesn't mean you should. If you want to reference a different artifact which represents the support library you can add an `<exclusion>` to the dependency declaration.

**Comment by artiomchi** [comment]
Ok.. There's some logic in there.. I would still personally move to the other library with a version bump, but that's your library, and your choice.

Also, the exclusion list is a perfect solution to this issue! I guess I should have thought of that earlier. Thanks :+1:

**Comment by artiomchi** [comment]
By the way, on a slightly related note.. Any chance of you uploading an aar build of ViewPagerIndicator to maven? :)

JakeWharton/Android-ViewPagerIndicator#254
