### ISSUE TITLE
Having unknown error(sometime) when using abs library in my project! 

### ISSUE THREAD

**Issue by ZawnHtut** [JakeWharton/ActionBarSherlock#1055]
10-12 23:40:51.905: I/dalvikvm(1528): Could not find method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.onHoverEvent, referenced from method com.actionbarsherlock.internal.widget.ActionBarContainer.onHoverEvent
10-12 23:40:51.905: W/dalvikvm(1528): VFY: unable to resolve virtual method 4266: Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.onHoverEvent (Landroid/view/MotionEvent;)Z
10-12 23:40:51.905: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x0000
10-12 23:40:51.905: D/dalvikvm(1528): VFY: dead code 0x0003-0004 in Lcom/actionbarsherlock/internal/widget/ActionBarContainer;.onHoverEvent (Landroid/view/MotionEvent;)Z
10-12 23:40:51.915: I/dalvikvm(1528): Could not find method android.widget.FrameLayout.getAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.getAlpha
10-12 23:40:51.915: W/dalvikvm(1528): VFY: unable to resolve virtual method 3019: Landroid/widget/FrameLayout;.getAlpha ()F
10-12 23:40:51.915: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000b
10-12 23:40:51.915: D/dalvikvm(1528): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.getAlpha ()F
10-12 23:40:51.915: I/dalvikvm(1528): Could not find method android.widget.FrameLayout.getTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.getTranslationY
10-12 23:40:51.915: W/dalvikvm(1528): VFY: unable to resolve virtual method 3020: Landroid/widget/FrameLayout;.getTranslationY ()F
10-12 23:40:51.915: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000b
10-12 23:40:51.915: D/dalvikvm(1528): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.getTranslationY ()F
10-12 23:40:51.915: I/dalvikvm(1528): Could not find method android.widget.FrameLayout.setAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.setAlpha
10-12 23:40:51.915: W/dalvikvm(1528): VFY: unable to resolve virtual method 3023: Landroid/widget/FrameLayout;.setAlpha (F)V
10-12 23:40:51.915: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000a
10-12 23:40:51.915: D/dalvikvm(1528): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.setAlpha (F)V
10-12 23:40:51.915: I/dalvikvm(1528): Could not find method android.widget.FrameLayout.setTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.setTranslationY
10-12 23:40:51.915: W/dalvikvm(1528): VFY: unable to resolve virtual method 3030: Landroid/widget/FrameLayout;.setTranslationY (F)V
10-12 23:40:51.915: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000a
10-12 23:40:51.915: D/dalvikvm(1528): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/widget/NineFrameLayout;.setTranslationY (F)V
10-12 23:40:51.925: I/dalvikvm(1528): Could not find method android.content.pm.PackageManager.getActivityLogo, referenced from method com.actionbarsherlock.internal.widget.ActionBarView.<init>
10-12 23:40:51.925: W/dalvikvm(1528): VFY: unable to resolve virtual method 300: Landroid/content/pm/PackageManager;.getActivityLogo (Landroid/content/ComponentName;)Landroid/graphics/drawable/Drawable;
10-12 23:40:51.925: D/dalvikvm(1528): VFY: replacing opcode 0x6e at 0x01d1
10-12 23:40:51.925: I/dalvikvm(1528): Could not find method android.content.pm.ApplicationInfo.loadLogo, referenced from method com.actionbarsherlock.internal.widget.ActionBarView.<init>
10-12 23:40:51.925: W/dalvikvm(1528): VFY: unable to resolve virtual method 296: Landroid/content/pm/ApplicationInfo;.loadLogo (Landroid/content/pm/PackageManager;)Landroid/graphics/drawable/Drawable;
10-12 23:40:51.925: D/dalvikvm(1528): VFY: replacing opcode 0x6e at 0x01df
10-12 23:40:51.925: D/dalvikvm(1528): VFY: dead code 0x01d4-01d8 in Lcom/actionbarsherlock/internal/widget/ActionBarView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;)V
10-12 23:40:51.925: D/dalvikvm(1528): VFY: dead code 0x01e2-01e8 in Lcom/actionbarsherlock/internal/widget/ActionBarView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;)V
10-12 23:40:51.955: I/dalvikvm(1528): Could not find method android.view.ViewGroup.getAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.getAlpha
10-12 23:40:51.955: W/dalvikvm(1528): VFY: unable to resolve virtual method 2789: Landroid/view/ViewGroup;.getAlpha ()F
10-12 23:40:51.955: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000b
10-12 23:40:51.955: D/dalvikvm(1528): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.getAlpha ()F
10-12 23:40:51.955: I/dalvikvm(1528): Could not find method android.view.ViewGroup.getTranslationX, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.getTranslationX
10-12 23:40:51.955: W/dalvikvm(1528): VFY: unable to resolve virtual method 2794: Landroid/view/ViewGroup;.getTranslationX ()F
10-12 23:40:51.955: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000b
10-12 23:40:51.955: D/dalvikvm(1528): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.getTranslationX ()F
10-12 23:40:51.955: I/dalvikvm(1528): Could not find method android.view.ViewGroup.getTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.getTranslationY
10-12 23:40:51.955: W/dalvikvm(1528): VFY: unable to resolve virtual method 2795: Landroid/view/ViewGroup;.getTranslationY ()F
10-12 23:40:51.955: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000b
10-12 23:40:51.955: D/dalvikvm(1528): VFY: dead code 0x000e-000f in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.getTranslationY ()F
10-12 23:40:51.955: I/dalvikvm(1528): Could not find method android.view.ViewGroup.setAlpha, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.setAlpha
10-12 23:40:51.955: W/dalvikvm(1528): VFY: unable to resolve virtual method 2810: Landroid/view/ViewGroup;.setAlpha (F)V
10-12 23:40:51.955: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000a
10-12 23:40:51.955: D/dalvikvm(1528): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.setAlpha (F)V
10-12 23:40:51.955: I/dalvikvm(1528): Could not find method android.view.ViewGroup.setTranslationX, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.setTranslationX
10-12 23:40:51.955: W/dalvikvm(1528): VFY: unable to resolve virtual method 2814: Landroid/view/ViewGroup;.setTranslationX (F)V
10-12 23:40:51.955: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000a
10-12 23:40:51.955: D/dalvikvm(1528): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.setTranslationX (F)V
10-12 23:40:51.955: I/dalvikvm(1528): Could not find method android.view.ViewGroup.setTranslationY, referenced from method com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.setTranslationY
10-12 23:40:51.955: W/dalvikvm(1528): VFY: unable to resolve virtual method 2815: Landroid/view/ViewGroup;.setTranslationY (F)V
10-12 23:40:51.955: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x000a
10-12 23:40:51.955: D/dalvikvm(1528): VFY: dead code 0x000d-000d in Lcom/actionbarsherlock/internal/nineoldandroids/view/NineViewGroup;.setTranslationY (F)V
10-12 23:40:51.985: D/dalvikvm(1528): GC_EXTERNAL_ALLOC freed 1437 objects / 98064 bytes in 28ms
10-12 23:40:52.285: I/dalvikvm(1528): Could not find method com.actionbarsherlock.internal.widget.ActionBarView$HomeView.onHoverEvent, referenced from method com.actionbarsherlock.internal.widget.ActionBarView$HomeView.dispatchHoverEvent
10-12 23:40:52.285: W/dalvikvm(1528): VFY: unable to resolve virtual method 5127: Lcom/actionbarsherlock/internal/widget/ActionBarView$HomeView;.onHoverEvent (Landroid/view/MotionEvent;)Z
10-12 23:40:52.285: D/dalvikvm(1528): VFY: replacing opcode 0x6e at 0x0000
10-12 23:40:52.285: D/dalvikvm(1528): VFY: dead code 0x0003-0004 in Lcom/actionbarsherlock/internal/widget/ActionBarView$HomeView;.dispatchHoverEvent (Landroid/view/MotionEvent;)Z
10-12 23:40:52.285: I/dalvikvm(1528): Could not find method android.widget.FrameLayout.onPopulateAccessibilityEvent, referenced from method com.actionbarsherlock.internal.widget.ActionBarView$HomeView.onPopulateAccessibilityEvent
10-12 23:40:52.285: W/dalvikvm(1528): VFY: unable to resolve virtual method 3022: Landroid/widget/FrameLayout;.onPopulateAccessibilityEvent (Landroid/view/accessibility/AccessibilityEvent;)V
10-12 23:40:52.285: D/dalvikvm(1528): VFY: replacing opcode 0x6f at 0x0006
10-12 23:40:52.345: D/AndroidRuntime(1528): Shutting down VM
10-12 23:40:52.345: W/dalvikvm(1528): threadid=1: thread exiting with uncaught exception (group=0x400259f8)
10-12 23:40:52.355: E/AndroidRuntime(1528): FATAL EXCEPTION: main
10-12 23:40:52.355: E/AndroidRuntime(1528): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.id11313982.freejokesapp/com.id11313982.freejokesapp.activities.MainActivity}: java.lang.NullPointerException
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2787)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2803)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.app.ActivityThread.access$2300(ActivityThread.java:135)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.os.Looper.loop(Looper.java:145)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.app.ActivityThread.main(ActivityThread.java:4937)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at java.lang.reflect.Method.invokeNative(Native Method)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at java.lang.reflect.Method.invoke(Method.java:521)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at dalvik.system.NativeStart.main(Native Method)
10-12 23:40:52.355: E/AndroidRuntime(1528): Caused by: java.lang.NullPointerException
10-12 23:40:52.355: E/AndroidRuntime(1528):     at com.id11313982.freejokesapp.activities.MainActivity.networkStatusMessage(MainActivity.java:202)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at com.id11313982.freejokesapp.activities.MainActivity.onCreate(MainActivity.java:78)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1069)
10-12 23:40:52.355: E/AndroidRuntime(1528):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
10-12 23:40:52.355: E/AndroidRuntime(1528):     ... 11 more

---

please help me out. it dosnet always happen. but when i restart my mobile and it seems like working again. but i dont feel it consistent and my lecture wont like it. pleae help me clear out this problem.

**Comment by SimonVT** [comment]
You have a NullPointerException in your code:

```
10-12 23:40:52.355: E/AndroidRuntime(1528): Caused by: java.lang.NullPointerException
10-12 23:40:52.355: E/AndroidRuntime(1528): at com.id11313982.freejokesapp.activities.MainActivity.networkStatusMessage(MainActivity.java:202)
```

**Comment by ZawnHtut** [comment]
i think that null pointer exception is caused by 
: Could not find method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.onHoverEvent, referenced from method com.actionbarsherlock.internal.widget.ActionBarContainer.onHoverEvent
10-12 23:40:51.905: W/dalvikvm(1528): VFY: unable to resolve virtual method 4266:  

is that right? because whenever i clean my project , delete the app and restart the phone and run the project again, it works again like a magic. i am using abs for the action bar and because i am getting unable to resolve virutal method error ,  i am having null pointer exception when fetching views by their id from the main layout. this is what i think. but please correct me if i am wrong and help me solve this problem. thanks heaps

**Comment by SimonVT** [comment]
No, they are not caused by the verify errors. That's just dalvik evicting calls to methods that don't exist. They aren't called unless they exist.
The error is in your code.

**Comment by ZawnHtut** [comment]
aww ok. but why do u think when i restart the phone and ADT and delete the app and run the project again, it works? i just make me feel my app is not consistent and not reliable at all.
if u want to look at my main code, i can show it to you. thanks million.

**Comment by SimonVT** [comment]
I don't know, try asking on stackoverflow or some other appropriate forum.
