### ISSUE TITLE
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x103001f

### ISSUE THREAD

**Issue by iNoles** [JakeWharton/ActionBarSherlock#106]
11-09 15:18:21.289: E/AndroidRuntime(338): FATAL EXCEPTION: main
11-09 15:18:21.289: E/AndroidRuntime(338): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itnoles.nolesfootball/com.itnoles.nolesfootball.ui.MainActivity}: android.view.InflateException: Binary XML file line #33: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.os.Looper.loop(Looper.java:123)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.ActivityThread.main(ActivityThread.java:3683)
11-09 15:18:21.289: E/AndroidRuntime(338):  at java.lang.reflect.Method.invokeNative(Native Method)
11-09 15:18:21.289: E/AndroidRuntime(338):  at java.lang.reflect.Method.invoke(Method.java:507)
11-09 15:18:21.289: E/AndroidRuntime(338):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
11-09 15:18:21.289: E/AndroidRuntime(338):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
11-09 15:18:21.289: E/AndroidRuntime(338):  at dalvik.system.NativeStart.main(Native Method)
11-09 15:18:21.289: E/AndroidRuntime(338): Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.createView(LayoutInflater.java:518)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
11-09 15:18:21.289: E/AndroidRuntime(338):  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:207)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.Activity.setContentView(Activity.java:1657)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:221)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.support.v4.app.FragmentActivity.setContentView(FragmentActivity.java:292)
11-09 15:18:21.289: E/AndroidRuntime(338):  at com.itnoles.shared.ui.AbstractMainActivity.onCreate(AbstractMainActivity.java:38)
11-09 15:18:21.289: E/AndroidRuntime(338):  at com.itnoles.nolesfootball.ui.MainActivity.onCreate(MainActivity.java:32)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
11-09 15:18:21.289: E/AndroidRuntime(338):  ... 11 more
11-09 15:18:21.289: E/AndroidRuntime(338): Caused by: java.lang.reflect.InvocationTargetException
11-09 15:18:21.289: E/AndroidRuntime(338):  at java.lang.reflect.Constructor.constructNative(Native Method)
11-09 15:18:21.289: E/AndroidRuntime(338):  at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.createView(LayoutInflater.java:505)
11-09 15:18:21.289: E/AndroidRuntime(338):  ... 25 more
11-09 15:18:21.289: E/AndroidRuntime(338): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x103001f
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.content.res.Resources.getValue(Resources.java:892)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.content.res.Resources.loadXmlResourceParser(Resources.java:1869)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.content.res.Resources.getLayout(Resources.java:731)
11-09 15:18:21.289: E/AndroidRuntime(338):  at android.view.LayoutInflater.inflate(LayoutInflater.java:318)
11-09 15:18:21.289: E/AndroidRuntime(338):  at com.actionbarsherlock.internal.widget.ActionBarView.<init>(ActionBarView.java:167)
11-09 15:18:21.289: E/AndroidRuntime(338):  at com.actionbarsherlock.internal.widget.ActionBarView.<init>(ActionBarView.java:100)
11-09 15:18:21.289: E/AndroidRuntime(338):  ... 28 more

I pull from the latest dev branch

**Comment by JakeWharton** [comment]
You probably only need to clean your projects so that all of the `R.java` files are regenerated.

**Comment by iNoles** [comment]
I fixed it by deleting gen and bin folder. :/
