### ISSUE TITLE
Inconsistent spacing between home and custom actionbar icon when menu item is present

### ISSUE THREAD

**Issue by xtreme-bozhidar-lenchov** [JakeWharton/ActionBarSherlock#1062]
I wasn't sure if this was Github or SO appropriate, but seeing as I repro'd on a couple of devices (Nexus 7, Nexus 4, Kindle Fire, Fire HD) of varying Android OS versions (2.3-4.3), and this seems to be out of the box experience on the project I'm working on (which sets pretty straightforward options in the ActionBar), I thought I'd file a bug.

In the project I'm working on, we assign custom icons through the homeAsUpIndicator property in our styles; this is for backwards compatibility. For the normal case with a screen with a drawer we use @drawable/ic_drawer_holo_dark and for no drawer we use @drawable/abs__ic_ab_back_holo_light which we have in our drawable folders. When a menu item is added to the action bar, it forces the spacing between the home icon and the custom actionbar icon to decrease for some reason (see attached screenshots below). We normally don't have a title in the webview screen, but I added one (overflowing even), and it didn't change the outcome (inconsistent spacing is still there).

Consistent spacing:
![actionbar_consistent_spacing](https://f.cloud.github.com/assets/1702613/1469032/d9bdfc50-459b-11e3-9618-fb203c2dd0ed.png)

Inconsistent spacing:
![actionbar_inconsistent_spacing](https://f.cloud.github.com/assets/1702613/1469033/d9c67fb0-459b-11e3-974c-684009265db1.png)

I hope it's not a styles config attribute we missed changing, as this seems an issue many other devs should be having. Thanks for your help.

**Comment by SimonVT** [comment]
If this happens on 4.0+ then it's an issue with your code as ABS just proxies to the native action bar on those platforms. Try stackoverflow.

**Comment by xtreme-bozhidar-lenchov** [comment]
Thanks Simon - turns out setting explcit padding on the home icon did the trick. http://stackoverflow.com/a/19793804/155390 in case it helps someone else in the future.
