### ISSUE TITLE
Where is the javadoc gone?

### ISSUE THREAD

**Issue by rekire** [JakeWharton/ActionBarSherlock#1063]
I was looking for a official javadoc of ActionBarSherlock. I googled this [changelog entry](https://github.com/JakeWharton/ActionBarSherlock/blob/master/CHANGELOG.md#version-210-2011-03-21) which told me that the documentation is somewhere on http://jakewharton.github.com/ActionBarSherlock/. But I cannot find it. I also [checked the repository](https://github.com/JakeWharton/ActionBarSherlock/tree/gh-pages) and could find no tracks of that.

So when is it gone? And will it come back?

**Comment by SimonVT** [comment]
It's a backport of the native action bar, so the javadocs are available here: https://developer.android.com/reference/android/app/ActionBar.html
Usage instructions are here: http://actionbarsherlock.com/usage.html

**Comment by rekire** [comment]
Well I wanted to link to the javadoc like here:

```
-linkoffline http://developer.android.com/reference "file:/android-sdk/docs/reference"
-link http://docs.oracle.com/javase/6/docs/api/
-link http://www.xbill.org/dnsjava/dnsjava-current/doc/
-link http://google-gson.googlecode.com/svn/tags/gson-2.2.4/docs/javadocs/
```

But e.g. com.actionbarsherlock.app.SherlockFragmentActivity uses another namespace and linking is not possible.
