### ISSUE TITLE
problem in integration

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#107]
I have downloaded v-3.4.0 of ActionBarSherlock 

I have build it using 3.2 i also added... android-v4 library, plugins-preference, and plugins- map library

now if i add this in to my project(android 2.2)
my r.java file automatically deleted

am i doing it right?

**Comment by JakeWharton** [comment]
You do not need to include Google's compatibility library jar. It will cause conflicts and your app won't compile. You also need to be building your app with Android 3.2 as well as the library.

For further questions such as this please ask in the forums: http://abs.io/forum

**Comment by ghost** [comment]
okay i got it thanks so...it will compile with 3.2 but it can also run on earlier version right like google iosched project

**Comment by JakeWharton** [comment]
Yes. See the samples for more info. They all run back to 1.6.
