### ISSUE TITLE
Support library version differs from repo to ZIP

### ISSUE THREAD

**Issue by Thorn1089** [JakeWharton/ActionBarSherlock#1072]
In the ZIP archive provided from your website, you include a later version of the Android support library than the JAR in this repository. Notably, this repo's version lacks the WakefulBroadcastReceiver class and friends. Where does this discrepancy arise? Is the ZIP on the site not an archive of the 4.4.0 tag?

**Comment by JakeWharton** [comment]
The zip on the website is automatically generated from the repo's `master` branch by GitHub.

**Comment by Thorn1089** [comment]
Hmm, seems like I had a mix-up somewhere then. Is there any reason the repo can't include the latest version of the support library?

**Comment by JakeWharton** [comment]
Because it's mismatched from what's in Maven central.
