### ISSUE TITLE
Popup menu using ABS

### ISSUE THREAD

**Issue by nitinmishra27** [JakeWharton/ActionBarSherlock#1077]
Is it possible to have POPUP menu like play store attached to each row of adapter 
what i done so far 
holder.rl_overflow.setOnClickListener(new OnClickListener() {

```
            @Override
            public void onClick(View v) {
                PopupMenu popup = new PopupMenu(context, holder.rl_overflow);
                popup.getMenuInflater().inflate(R.menu.overflow, popup.getMenu());  

                popup.setOnMenuItemClickListener(new PopupMenu.OnMenuItemClickListener() {
                    @Override
                    public boolean onMenuItemClick(MenuItem item) {
                        Toast.makeText(context,"You Clicked : " + item.getTitle(),Toast.LENGTH_SHORT).show();
                        return false;
                    }
                });
                popup.show();

            }
        });
```

but constructor for POPUP menu says its available from API 11. I go through the developers.android.com and i found, its can be added using SUPPORT V7 library "https://developer.android.com/reference/android/support/v7/widget/PopupMenu.html" but i'm not able to implement this using ABS, please help someone.

**Comment by serj-lotutovici** [comment]
As far as I know in ABS there is a `com.actionbarsherlock.internal.view.menu` package... I would suggest you to start you're research there. I my self din't try this... if I'll have some more time, I will try to post here an example (if its possible of course).

**Comment by nitinmishra27** [comment]
@serj-lotutovici how about this forked version https://github.com/mihirjoshi21/ActionBarSherlock I think he has ported POPUP MENU, what do you think?

**Comment by serj-lotutovici** [comment]
@androlizer As far as I see, https://github.com/mihirjoshi21/ActionBarSherlock uses the same code of `PopupMenu` as in the `support v7` package. So you can just copy the `PopupMenu` class in you're cloned copy of ABS and use it.

**Comment by nitinmishra27** [comment]
@serj-lotutovici i've implemented & tested it successfully
