### ISSUE TITLE
IcsLinearLayout to support dividers for horizontal orientation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [JakeWharton/ActionBarSherlock#1078]
Hello,

I've used this cool library for a long time (used version 4.2.0), and I've even used IcsLinearLayout just for adding the support of the dividers for certain layouts across the app.

Lately I've tried it while using an RTL language (Hebrew in my case) for the device by setting the device language to Hebrew and adding supportsRtl="true" to the manifest. 
I've noticed that the dividers are gone when using a horizontal orientation.

I've downloaded the newest version (4.4.0) , and not only that this problem still exists, but it occurs for LTR languages (English in my case) too.

Here's a sample to show the problem. note that when I use vertical orientation (or when using the normal LinearLayout on newest Android versions) , it works just fine . 

divider.xml

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" >

<size
    android:height="1dp"
    android:width="1dp" />

<solid android:color="#FF000000" />

</shape>
```

activity_main.xml 

```
<com.actionbarsherlock.internal.widget.IcsLinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:divider="@drawable/divider"
android:gravity="center_horizontal"
android:measureWithLargestChild="true"
android:orientation="horizontal"
android:showDividers="middle"
tools:context=".MainActivity" >

<View
    android:layout_width="0px"
    android:layout_height="wrap_content"
    android:layout_weight="1"
    android:background="#FFff0000" />

<View
    android:layout_width="0px"
    android:layout_height="wrap_content"
    android:layout_weight="1"
    android:background="#FFffff00" />

<View
    android:layout_width="0px"
    android:layout_height="wrap_content"
    android:layout_weight="1"
    android:background="#FFff00ff" />

</com.actionbarsherlock.internal.widget.IcsLinearLayout>
```

Please help...

**Comment by JakeWharton** [comment]
`IcsLinearLayout` is an internal class to the library whose behavior is specific only to the requirements of the action bar. You should not use this directly since it likely will not behave for every use case (just like you are seeing).

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton Could you please refer me to a working class that acts the same, or give me a clue how to do it?

Also, doesn't it mean I've found a problem with a class that you are using within the library, that could affect future library versions?

I've even used IcsListPopupWindow and IcsProgressBar
