### ISSUE TITLE
Tiny issue - naming convention not applied on some resources

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [JakeWharton/ActionBarSherlock#1080]
There are 2 files in the "res/layout" folder (and "layout-v14" folder) that do not have the "abs__" prefix (while all other resources do have this prefix), which makes some confusion as it does belong to the library:

-sherlock_spinner_dropdown_item.xml
-sherlock_spinner_item.xml

Please consider renaming those files. maybe there are other files/resources too that I didn't notice.

**Comment by JakeWharton** [comment]
There are public. Meant to be used by consumers of the library.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton In which way exactly? and why?
And even if they are meant to be used by consumers, why can't they have this prefix?

**Comment by JakeWharton** [comment]
For the adapter that backs the Spinner used for list navigation. They don't
have the same prefix because people shouldn't be using anything prefixed
with "abs__" ever.

**Comment by AndroidDeveloperLB** [comment]
What's the difference?
I mean, people could override them just as they could override any resource that starts with "abs__", no?

**Comment by JakeWharton** [comment]
Right. Libraries can't have private resources like Android so a strong
convention is all there is.

**Comment by AndroidDeveloperLB** [comment]
But those files didn't follow the convention...
Wouldn't it be better to have all of those files have this prefix, and maybe for files you don't wish other to override, add extra text to the prefix?

How do you know which files exactly you can use from the library, to override , customize, etc ... ?

**Comment by JakeWharton** [comment]
They don't follow the convention because they are public. You are supposed
to use them directly. You should never use anything prefixed with"abs__"
directly.

**Comment by AndroidDeveloperLB** [comment]
What about Java code? which files are OK to be used/customized/extended ?

Is there a convention there too?

Maybe you should add a comment at the top of such files, to tell whoever uses the library about such things...

**Comment by AndroidDeveloperLB** [comment]
What about Java code? which files are OK to be used/customized/extended ?

**Comment by JakeWharton** [comment]
Those not in the internal package.

**Comment by AndroidDeveloperLB** [comment]
I see.

Could you please consider adding a comment to the resources files that are allowed to be customized (like those I've mentioned) ?

**Comment by SimonVT** [comment]
You are not supposed to customize any resources. You can use any resources not pre-fixed with abs__, or create your own and use those.

**Comment by AndroidDeveloperLB** [comment]
But you've written that you can customize resources - the files I've mentioned.
I'm confused.

**Comment by SimonVT** [comment]
Noone told you to customize ABS resources. Resources not pre-fixed with abs__ are part of the public API - just like they are part of the public API in Android. Either use them or don't.

**Comment by AndroidDeveloperLB** [comment]
Is it OK to make files with the same name as those that don't have the special prefix (therefore overriding them, and allowing the developers to customize them ) or not?

If so, can you please consider adding a comment to tell others it's ok ?

**Comment by SimonVT** [comment]
You're not supposed to override any resources.

**Comment by AndroidDeveloperLB** [comment]
But you've just said that files without this prefix are safe to be customized, as opposed to those that have this prefix.

If those files are internal to the library and shouldn't be overridden, then they should have this prefix too.

That's the logic I understand of this prefix.

**Comment by JakeWharton** [comment]
They aren't used in the library at all. They are for you to use when making
adapters for list navigation. Overriding them has no effect.

---

Jake Wharton
http://about.me/jakewharton

**Comment by SimonVT** [comment]
Noone said they were safe to customize - just that they are safe to consume.

**Comment by AndroidDeveloperLB** [comment]
So you want them to be safe from being overridden, yet you don't give them the same naming protection as the other files?

I thought that using is the same as customizing, just like I'm allowed to use Java files and therefore can also extend them and customize them. You've just said that Java files in the internal package are unsafe, while the others are safe.
If I use this same logic on XML files, it doesn't match what you've said... :(

**Comment by JakeWharton** [comment]
Well you can't extend layouts...

---

Jake Wharton
http://about.me/jakewharton

**Comment by AndroidDeveloperLB** [comment]
you have a point, but there is more than 1 way to use a layout a library gives me for tinkering:
either copy its content to a new file with the same name (therefore overriding it), or use <include> tag.

if you don't want that I'd copy its content , and wish to protect what is written, use the same technique you've done for the other files. When it has a different file name, it "creates" (sorry, English isn't my main language) questions about its usage.
maybe have an additional text to the prefix, saying it should/shouldn't be used (depending on your preference).
