### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by vipinhelloindia** [JakeWharton/ActionBarSherlock#1083]
SherlockFragmentActivity.java line 122
com.actionbarsherlock.app.SherlockFragmentActivity.dispatchKeyEvent

Doing some operation on SherlockFragment in ViewPager 
I have Asyntask and some operation is going on doInBackground, while this issue is only happening onward 4.0 OS 

Fatal Exception: java.lang.IllegalStateException
Can not perform this action after onSaveInstanceState

**Comment by JakeWharton** [comment]
This is fragment manager complaining which is part of the support library, not ABS. Please ask your question on StackOverflow or the official Android developer mailing list.

**Comment by vipinhelloindia** [comment]
Thanks Jake, I will report accordingly
