### ISSUE TITLE
setSuggestionsAdapter only takes in CursorAdapter?

### ISSUE THREAD

**Issue by chentarry** [JakeWharton/ActionBarSherlock#1084]
Hi,

I was wondering why the setSuggestionsAdapter in SearchView.java only took in CursorAdapters when mQueryTextView.setAdapter will take in any BaseAdapter that implements Filterable. 

Why not allow users of the SearchView provide an Adapter that implements those requirements?

**Comment by JakeWharton** [comment]
SearchView is an Android component. It is only mirrored here for backwards
compatibility reasons. If you would like to suggest improvements you can
file a bug at http://b.android.com
