### ISSUE TITLE
ActionMode title click

### ISSUE THREAD

**Issue by liufsd** [JakeWharton/ActionBarSherlock#1089]
HI.
i use the ActionMode,ok i can set mode title (for example :" mode.setTitle(selectedDownload.size() + " selected");"),so,now,i want add this title label a listener ,when user click here.
how can i do that ?
Thanks.

**Comment by bsvTag** [comment]
You can set customView and not use setTitle/setSubtitle methods

**Comment by liufsd** [comment]
oh yes.
Thanks.
I fixed it.
