### ISSUE TITLE
Option menus items bug

### ISSUE THREAD

**Issue by rock3r** [JakeWharton/ActionBarSherlock#109]
On Android 2.x, if you set a menu item with `android:showAsAction="ifRoom"`, and you call `actionbar.hide()` in your code (i do it in `onCreate()`, by the way), the menu item does not show in the option menu. Instead, you can see it displays in the action bar (by commenting out the `actionbar.hide()` line), regardless of the action bar visibility. In Android 3.0+, the item shows up correctly in the option menu if no action bar is shown. This is probably due to the fact that on those platforms, it falls back on the native actionbar/menu that does not have this bug, while abs' custom implementation for Android < 3.x does.

**Comment by JakeWharton** [comment]
Closing this because the following two apps exhibit the same behavior on ICS. That is, no action bar, and no menu anywhere.

``` java
public class ABSTempActivity extends android.app.Activity {
    public boolean onCreateOptionsMenu(android.view.Menu menu) {
        menu.add("Test").setShowAsAction(android.view.MenuItem.SHOW_AS_ACTION_IF_ROOM | android.view.MenuItem.SHOW_AS_ACTION_WITH_TEXT);
        return true;
    }
    public void onCreate(android.os.Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getActionBar().hide();
    }
}
```

``` java
public class ABSTempActivity extends com.actionbarsherlock.app.SherlockActivity {
    public boolean onCreateOptionsMenu(com.actionbarsherlock.Menu menu) {
        menu.add("Test").setShowAsAction(android.view.MenuItem.SHOW_AS_ACTION_IF_ROOM | android.view.MenuItem.SHOW_AS_ACTION_WITH_TEXT);
        return true;
    }
    public void onCreate(android.os.Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getActionBar().hide();
    }
}
```
