### ISSUE TITLE
Create coverage is failed

### ISSUE THREAD

**Issue by viacheslavtitov** [JakeWharton/ActionBarSherlock#1091]
I try create coverage my project with tests. I use Espresso, Eclipse, Emma and Ant. My project include ActionBarSherlock library. When I run instrument test runner it throw exception. I added all library to my project one by one and it work. But when I added ActionBarSherlock library to my project I had exception:

<blockquote>03-13 15:26:00.277: E/AndroidRuntime(8730): FATAL EXCEPTION: main
03-13 15:26:00.277: E/AndroidRuntime(8730): java.lang.ExceptionInInitializerError
03-13 15:26:00.277: E/AndroidRuntime(8730):     at java.lang.Class.newInstanceImpl(Native Method)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at java.lang.Class.newInstance(Class.java:1409)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.app.Instrumentation.newActivity(Instrumentation.java:1021)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1561)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.app.ActivityThread.access$1500(ActivityThread.java:117)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.os.Looper.loop(Looper.java:123)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at android.app.ActivityThread.main(ActivityThread.java:3683)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at java.lang.reflect.Method.invokeNative(Native Method)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at java.lang.reflect.Method.invoke(Method.java:507)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at dalvik.system.NativeStart.main(Native Method)
03-13 15:26:00.277: E/AndroidRuntime(8730): Caused by: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
03-13 15:26:00.277: E/AndroidRuntime(8730):     at com.eleks.espresso.example.app.MainActivity.$VRi(MainActivity.java)
03-13 15:26:00.277: E/AndroidRuntime(8730):     at com.eleks.espresso.example.app.MainActivity.<clinit>(MainActivity.java)
03-13 15:26:00.277: E/AndroidRuntime(8730):     ... 15 more
</blockquote>

**Comment by JakeWharton** [comment]
> Class ref in pre-verified class resolved to unexpected implementation

You have duplicate dependencies in your real and test APK.
