### ISSUE TITLE
Scrollview of parent goes up and down if i tap on the centered or bottom spinner

### ISSUE THREAD

**Issue by androidoutput** [JakeWharton/ActionBarSherlock#1095]
Hi,

i have used the below code, to generate the issue, If i tap on second or third spinner i feel the parent view scrolls up and down and then spinner populates the data. 

<ScrollView
        xmlns:android="http://schemas.android.com/apk/res/android"
         android:layout_width="match_parent"
         android:descendantFocusability="beforeDescendants"
         android:scrollbars="vertical"

```
     android:layout_height="match_parent">
```

<RelativeLayout

```
android:layout_width="fill_parent"
android:layout_height="fill_parent" >
```

<com.actionbarsherlock.internal.widget.IcsSpinner
        android:id="@+id/ics_spinner"
        style="?android:attr/spinnerStyle"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"

```
    android:scrollbarStyle="outsideOverlay" />
```

<com.actionbarsherlock.internal.widget.IcsSpinner
    android:id="@+id/ics_spinner1"
    android:layout_marginTop="190dp"
        android:layout_below="@+id/ics_spinner"
        style="?android:attr/spinnerStyle"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:scrollbars="vertical" />

<com.actionbarsherlock.internal.widget.IcsSpinner
    android:id="@+id/ics_spinner2"
    android:layout_marginTop="140dp"
        android:layout_below="@+id/ics_spinner1"
        style="?android:attr/spinnerStyle"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:scrollbars="vertical" />

<com.actionbarsherlock.internal.widget.IcsSpinner
    android:id="@+id/ics_spinner3"
    android:layout_marginTop="120dp"
        android:layout_below="@+id/ics_spinner2"
        style="?android:attr/spinnerStyle"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:scrollbars="vertical" />

</RelativeLayout>
</ScrollView>

This issue i have not seen in the default android spinner.

**Comment by JakeWharton** [comment]
`IcsSpinner` is an internal class that shouldn't be used anywhere but inside of ActionBarSherlock.

**Comment by androidoutput** [comment]
Hi thanks for your quick reply. i'm using actionbarsherlock lib. i need to use spinner in my app which should give me same look and feel of ICS even in android 2.2 also, how to do with help of your library?. does your lib support that?.

**Comment by JakeWharton** [comment]
No. ActionBarSherlock only backports the action bar look and functionality. The content of the app is still your responsibility.

**Comment by androidoutput** [comment]
ah, i understood now. So then i will use the default spinner itself. Thanks for your quick reply. Thank you very much :+1:
