### ISSUE TITLE
Native ActionBar does not show up

### ISSUE THREAD

**Issue by rock3r** [JakeWharton/ActionBarSherlock#110]
On Android 3.x+ (on the emulator) the native action bar does not show up. This is what I get:

![Screenshot](http://localhostr.com/file/hRnqelD/5554ICS.png)

This is just a bug-tracker repost of the email I sent you on Nov 1st. In case you want them here handy, here's the details:

I am targeting API 13 and using a custom theme with `parent="Theme.Sherlock.Light"`. It only overrides some attributes, it's not even a complete overhaul.
This is the project.prop file:

```
# Project target.
target=android-13
android.library.reference.3=libs/GreenDroid
android.library.reference.1=libs/ActionBarSherlock
android.library.reference.2=libs/ViewPagerIndicator
```

This is the `uses-sdk` node of the manifest:

```
<uses-sdk android:minSdkVersion="8" android:targetSdkVersion="13"/>
```

The email thread has the full project code attached. I'm sending a newer build soon so you can check it out too. The problem is not solved as of yet.

**Comment by rock3r** [comment]
I have solved the problem. Had to remove `<item name="android:windowNoTitle">true</item>` from my styles xml. This took me a fairly long styles debugging session. Guess you should write it down somewhere in the docs :)

**Comment by JakeWharton** [comment]
I guess because on 3.0+ the action bar _is_ the title bar. Never occurred to me when I was running your example. Very good find.

**Comment by iNoles** [comment]
in Android, there is like Window.FEATURE_CUSTOM_TITLE that allowed developers to create custom title bar.

**Comment by JakeWharton** [comment]
Yes but the user-facing custom title bar is much more limited in what it can do once created which is why I chose not to use it.
