### ISSUE TITLE
How to use ActionBarSherlock with fixed visible tabs

### ISSUE THREAD

**Issue by nologinatgit** [JakeWharton/ActionBarSherlock#1100]
I intend to use ActionBarSherlock in my application.

I add tabs by the following code:

```
getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

for(int i=0;i<countOfTabs;i++) 
{
 ActionBar.Tab tab = getSupportActionBar().newTab();
 tab.setText("Tab"+i);
 tab.setTabListener(this);
 getSupportActionBar().addTab(tab);  
}
```

The problem is that the number of the tabs is _dynamic_ (it can be even 5-6) but I only want to show **1 or 2**, the rest should become visible when I use swipe.

How can I specify the maximum number of visible tabs? Is there a built-in solution for this?

**Comment by JakeWharton** [comment]
You have to use a custom tab bar. This isn't supported by the native action bar (and thus nor ActionBarSherlock).
