### ISSUE TITLE
Android Studio 0.5.9

### ISSUE THREAD

**Issue by alexsilva** [JakeWharton/ActionBarSherlock#1101]
Error:Artifact 'com.actionbarsherlock:library:4.2.0:library.apklib' not found.

Basically does not compile.

Actually never compiled android in studio.

**Comment by alexsilva** [comment]
Try 1:

dependencies {
    compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'
}
Error:Module version com.actionbarsherlock:library:4.2.0 depends on libraries but is not a library itself

Try 2:

dependencies {
    compile 'com.actionbarsherlock:actionbarsherlock:4.4.0'
}
Error:Artifact 'com.actionbarsherlock:library:4.2.0:library.apklib' not found.

Try 3:

dependencies {
    compile project(':library:ActionBarSherlock-v4.4.0:actionbarsherlock')
}
Error:Artifact 'com.actionbarsherlock:library:4.2.0:library.apklib' not found.

**Comment by tevjef** [comment]
can you post your build.gradle?
