### ISSUE TITLE
changing SherlockDialogFragment default animation not working

### ISSUE THREAD

**Issue by dnldd** [JakeWharton/ActionBarSherlock#1102]
Hi, I'd like to change the animation for my dialog fragments in my app. I've tried setting the window animation in my onCreate function but doesn't change the animation.  I'm not getting solutions on StackOverflow. How do I get this done? Thanks.

**Comment by JakeWharton** [comment]
`SherlockDialogFragment` adds no functionality in this regard. It just extends from the normal support library `DialogFragment` so any behavior you are seeing (or not seeing) is from the support library, not ABS.
