### ISSUE TITLE
SearchView doesnt work in SherlockFragmentActivity?

### ISSUE THREAD

**Issue by Thijmen** [JakeWharton/ActionBarSherlock#1105]
Hi,

I have done everything the official google pages are describing; http://developer.android.com/training/search/setup.html

Yet, when I hit enter in the searchview, the new activity defined as SEARCH intent in my manifest doesnt open. Is this a bug in ActionbarSherlock?

**Comment by JakeWharton** [comment]
These aren't related, and `SearchView` definitely works in a `SherlockFragmentActivity`. Please try StackOverflow if you are still having problems.
