### ISSUE TITLE
Android L styles

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#1106]
Is it possible to add:
@android:style/Theme.Material (dark version)
@android:style/Theme.Material.Light (light version)
@android:style/Theme.Material.Light.DarkActionBar
Like adding values-21 folder in ABS with new styles xml?

**Comment by JakeWharton** [comment]
No. ActionBarSherlock is for backporting 4 to pre-4 and I highly encourage you to stop using it and minSdkVersion=15
