### ISSUE TITLE
How can I contribute to this library

### ISSUE THREAD

**Issue by protocol10** [JakeWharton/ActionBarSherlock#1107]
I want to get involved in this project but I am confused how to get started

**Comment by nixlong** [comment]
!@

发自我的小米手机

Akshay Mukadam notifications@github.com编写：

**Comment by protocol10** [comment]
what is this

**Comment by JakeWharton** [comment]
ActionBarSherlock is not being actively developed because the time of its use has come and gone. There's no longer a reason to be using it! All new apps being created and new versions of existing apps should all be targeting API 15 or newer.
