### ISSUE TITLE
do not hide top action bar if tile and home is diable

### ISSUE THREAD

**Issue by chuanY** [JakeWharton/ActionBarSherlock#1109]
see screen shot, 
![screen](https://cloud.githubusercontent.com/assets/3395491/4248183/73d88802-3a63-11e4-9b07-6b9ca8cc36c4.png)
and my option code

mSherlock.setUiOptions(ActivityInfo.UIOPTION_SPLIT_ACTION_BAR_WHEN_NARROW);

```
mSherlock.getActionBar().setDisplayShowTitleEnabled(false);
mSherlock.getActionBar().setDisplayShowHomeEnabled(false);
```

**Comment by JakeWharton** [comment]
You are looking at the behavior of the native action bar, not the compatibility one from this library. This is just how Android behaves.
