### ISSUE TITLE
ICS ActionBar title with no home icon

### ISSUE THREAD

**Issue by henwoods** [JakeWharton/ActionBarSherlock#111]
I think this is Icecream Sandwich specific (my device is a Nexus S).

When I remove the home icon (getSupportActionBar().setDisplayShowHomeEnabled(false);) the title has no left padding. This occurs on my HTC Hero running CM but does happen on my NS running ICS so it is either ICS or the higher resolution screen.

Screenshots below:
Hero
![Hero](http://dl.dropbox.com/u/21587776/device-2011-11-15-164358.png)
Nexus S
![Nexus S](http://dl.dropbox.com/u/21587776/device-2011-11-15-164711.png)

**Comment by iNoles** [comment]
in ActionBarSherlock, on >= 3.0, it use system action bar. It is very likely for ICS.

**Comment by henwoods** [comment]
OK, will give this a shot, sorry for the invalid isse
