### ISSUE TITLE
Sherlock dialog not dislpaying on devices with android v4+?

### ISSUE THREAD

**Issue by taimur97** [JakeWharton/ActionBarSherlock#1119]
Hi,
I have asked the question on stackoverflow but didn't receive an answer yet. Can you please take a look? 
http://stackoverflow.com/questions/26960752/sherlock-dialog-fragment-not-displaying-on-devices-with-android-v4

**Comment by JakeWharton** [comment]
Yes. Simply having the 'actionbarsherlock' tag will notify a bunch of people to look. Closing the issue though.
