### ISSUE TITLE
abBackgroundStacked ; Resource is not a Drawable

### ISSUE THREAD

**Issue by xDragonZ** [JakeWharton/ActionBarSherlock#112]
Yesterday I receive some crash report about  this :

**java.lang.RuntimeException: Unable to start activity ComponentInfo{com.domain.package/com.domain.package.mainActivity}: android.view.InflateException: Binary XML file line # 33: Error inflating c**

Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01001f a=-1}

I have tested the apps on some device and it works without any problem , and most of them downloaded without any problem too, but the report show that someone having some issue with this , I not sure is a bug , 
Phone :HTC HD2 : OS 2.3.4

**So when I check into my R.java is related to :**
public static final int abBackgroundStacked=0x7f01001f;

**Full Stacktrace :**
http://pastebin.com/NTJWjcCU

at line mainActivity.java:26 is "setContentView(R.layout.main);"

**Comment by JakeWharton** [comment]
Any update on this? I've never been able to reproduce and around the time when this was filed ADT was being very buggy with library projects, resources, and 9-patch drawables.

**Comment by xDragonZ** [comment]
I think this issue can be closed because I did't receive any crash report about this issue anymore.
