### ISSUE TITLE
ActionBarSherlock is incompatible with Appcompat

### ISSUE THREAD

**Issue by metalurgus** [JakeWharton/ActionBarSherlock#1121]
I want to use ActionBarSherlock, but I need the features of Appcompat library. For example ActionBarSherlock does not have SwitchCompat widget, which Appcompat does. Also ActionBarSherlock does not have compatibility attributes to customize color of statusbar, which are a must too.  
You shouldn't force people to remove Appcompat from their project if they want to use your library, or at least implement all missing features.

**Comment by intrications** [comment]
It seems that AppCompat has everything you want. Why do you want to use ActionBarSherlock which was deprecated a long time ago?

**Comment by JakeWharton** [comment]
These libraries cannot and should not be used together as they attempt to serve the same purpose.

**Comment by metalurgus** [comment]
@JakeWharton that should be awesome, but they do not. If you just read my question before closing it, you'd realize that ActionBarSherlock does not have a set of important features from AppCompat. But it has the SpinnerICS widget which I wanted to use. They should not be used together once one of them covers functionality of the other. Currently it does not.

**Comment by JakeWharton** [comment]
That widget is in the internal package and not part of the public API.
