### ISSUE TITLE
Various png files generate libpng warnings in Android Studio 1.1.0 or Gradle

### ISSUE THREAD

**Issue by kdhunter** [JakeWharton/ActionBarSherlock#1122]
Using ActionBarSherlock 4.4.0 and the 21.1.2 Android build tools, if you do an Android Studio 1.1.0 or Gradle command-line build, you get libpng warnings on a number of the embedded png files.  (See below)

Apparently this is caused by metadata (iCCP chunk) that applications like PhotoShop have a tendency to add to PNG's.  The newer version of libpng introduced with the 21.1.2 build tools is pickier about these than earlier versions were.  Android doesn't use this information, so there's no reason the iCCP chunk needs to be in the file.

> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-xhdpi/abs__ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-hdpi/abs__ic_clear_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-xhdpi/abs__ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-xhdpi/abs__ic_clear_disabled.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-mdpi/abs__ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-xhdpi/abs__ic_voice_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-hdpi/abs__ic_clear_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-mdpi/abs__ic_voice_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-hdpi/abs__ic_voice_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-hdpi/abs__ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-xhdpi/abs__ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-mdpi/abs__ic_go.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
> .../build/intermediates/exploded-aar/com.actionbarsherlock/actionbarsherlock/4.4.0/res/drawable-hdpi/abs__ic_search.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

The iCCP chunk (and others) can be removed using tools such as pngcrush

pngcrush -rem gAMA -rem cHRM -rem iCCP -rem sRGB infile.png outfile.png

**Comment by kdhunter** [comment]
Have a modified version of the files, but can't attach a ZIP.  Guess I'll have to set up a pull request.

**Comment by JakeWharton** [comment]
These images are copied directly from AOSP. The warning can just be ignored.
