### ISSUE TITLE
Watson.java  mFragmens.mAdded   can't find

### ISSUE THREAD

**Issue by autoool** [JakeWharton/ActionBarSherlock#1129]
**I can't find where define the  mFragment.mAdded .  Anybody can tell me about this error?**

``````
 if (mFragments.mAdded != null) {
                for (int i = 0; i < mFragments.mAdded.size(); i++) {
                    Fragment f = mFragments.mAdded.get(i);
                    if (f != null && !f.mHidden && f.mHasMenu && f.mMenuVisible && f instanceof OnOptionsItemSelectedListener) {
                        if (((OnOptionsItemSelectedListener)f).onOptionsItemSelected(item)) {
                            return true;
                        }
                    }
                }
}  ```        
``````

**Comment by LinkZ-LynX** [comment]
I have the same problem after SDK update. 

http://stackoverflow.com/questions/33047492/actionbarsherlock-type-madded-cannot-be-resolved-or-is-not-a-field-watson-java

**Comment by fmaxx** [comment]
Guys, do you have a solution?

**Comment by LinkZ-LynX** [comment]
Yeah, since this project is deprecated move to the native actionbar bar with AppCompat library.

**Comment by chiaramail** [comment]
That's not a solution, as converting to AppCompat can be time-consuming and difficult, as it is in my case. It's a good long-term solution, but for those (like myself) who need a quick answer to this problem, it's probably best to look to StackOverflow for a helpful solution. Your's is NOT.

**Comment by JakeWharton** [comment]
It is precisely the right solution.

**Comment by chiaramail** [comment]
Actually, it's an arrogant solution, as it does not take into account the difficulties in doing the conversion.

**Comment by JakeWharton** [comment]
ABS has been deprecated for years and the migration to AppCompat was
something you could have done gradually. You extracted value from ABS for
years at no cost, so the arrogance doesn't lie on me.

**Comment by LinkZ-LynX** [comment]
Hahaha @chiaramail you're so, so restitutionary ingrate. I'm so ashamed of your arrogance, no comment.
