### ISSUE TITLE
FragmentMapActivity not working in 3.4.2

### ISSUE THREAD

**Issue by sealskej** [JakeWharton/ActionBarSherlock#113]
Hello,
we have just upgraded from 3.3.1 to 3.4.2 and FragmentMapActivity stopped working. We are getting FC with following stacktrace:

11-19 14:30:15.968: E/AndroidRuntime(743): FATAL EXCEPTION: main
11-19 14:30:15.968: E/AndroidRuntime(743): java.lang.NoSuchFieldError: android.support.v4.app.FragmentActivity.R$styleable$SherlockTheme
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.support.v4.app.FragmentMapActivity.onApplyThemeResource(FragmentMapActivity.java:368)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:100)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:50)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1607)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.os.Looper.loop(Looper.java:130)
11-19 14:30:15.968: E/AndroidRuntime(743):  at android.app.ActivityThread.main(ActivityThread.java:3683)
11-19 14:30:15.968: E/AndroidRuntime(743):  at java.lang.reflect.Method.invokeNative(Native Method)
11-19 14:30:15.968: E/AndroidRuntime(743):  at java.lang.reflect.Method.invoke(Method.java:507)
11-19 14:30:15.968: E/AndroidRuntime(743):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
11-19 14:30:15.968: E/AndroidRuntime(743):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
11-19 14:30:15.968: E/AndroidRuntime(743):  at dalvik.system.NativeStart.main(Native Method)

Otherwise thanks for great work.
Ondra

**Comment by sealskej** [comment]
This bug is invalid. We have upgraded maps plugin yet and everything works fine.

**Comment by JakeWharton** [comment]
Sorry, busy couple days. There were a lot of changes in the plugins from the 3.3.x to the 3.4.x releases. Mostly due to working around ADT bugs. Glad you got it resolved, though.
