### ISSUE TITLE
SherlockActionbar conflicts with latest FacebookSdk facebook-android-sdk:[4,5)

### ISSUE THREAD

**Issue by Techmorphian** [JakeWharton/ActionBarSherlock#1136]
Hey Guys I am having conflict issues with SherlockActionbar when I upgraded my Facebook sdk to latest version because of this warning from Facebook **Reminder: Graph API v2.4 will be deprecated on Oct 09, 2017**

My project is about 3 years old . I can't change SherlockActionbar now 

Please see my post on **Stack**    https://stackoverflow.com/questions/46299215/actionbarsherlock-conflicts-facebooks-sdk-facebook-android-sdk4-5

**Comment by JakeWharton** [comment]
You can't use this library and AppCompat together. You'll need to upgrade to AppCompat only.
