### ISSUE TITLE
Menu bugs on Gingerbread and below

### ISSUE THREAD

**Issue by veeti** [JakeWharton/ActionBarSherlock#114]
There are three bugs with options menus when running on GB or below, which are the following:
- `findItem` can't be used directly to find items from submenus on 2.3. (Trying to find an item returns null). On 3.x and ICS it works as expected.
- `setEnabled` (and `setVisible`) do nothing to items in submenus on 2.3. On 3.x and ICS everything works as expected.
- The menu items sometimes completely vanish from the action bar on 2.3 when using a view pager and fragments (menu items from both the activity and fragment are affected - my demo only shows a menu from the fragment). Sliding the view pager to the next slide fixes it. [I found this discussion](https://groups.google.com/group/actionbarsherlock/browse_thread/thread/68a1fa9a9ff4b3d) which seems to be related. I'm not sure if this always happens in the demo, but it should occur when starting it.

I have a demo [here](https://github.com/veeti/ABSMenuProblems) which is based on the demo I made for #90.

**Comment by JakeWharton** [comment]
Some of these should be fixed in the `dev` branch for the upcoming 3.5 release. Not sure how to exactly handle disabled items in an action-item submenu just yet as I'm quite fond of just using the build-in `AlertDialog` list.

**Comment by JakeWharton** [comment]
Released with 3.5.0.
