### ISSUE TITLE
FragmentMapActivity help

### ISSUE THREAD

**Issue by enkoder** [JakeWharton/ActionBarSherlock#115]
I use Fragments for just about every layout in the application I am designing. I see that you have added the FragmentMapActivity to enable users to add a fragment with MapView capabilities. I use the FragmentManager to switch between fragments, and need to know how to use the FragmentMapActivity to be able to replace a fragment. 

I might be wrong in thinking that I can do such a thing, if so, please tell me. The ultimate goal would be for me to be able to embed the map capabilities on a fragment that contains other widgets. Is this possible? 

Thanks a bunch.

**Comment by JakeWharton** [comment]
The `FragmentMapActivity` class is exactly the same as `FragmentActivity` except that it extends from `MapActivity`. As you rightly guessed, this allows you to use a single `MapView` anywhere in your view whether it be inflated from XML or created in code on either the activity directly or through a fragment.

Using a map with fragments will not be an easy road and you have to be very careful. It is also not supported by Google and the official compatibility library.

Any future questions like this should be directed toward the [mailing list](http://abs.io/forum).
