### ISSUE TITLE
Can I see subtitle on actionbar tab style on landscape screen

### ISSUE THREAD

**Issue by kim2509** [JakeWharton/ActionBarSherlock#116]
I'd like to see title on the action bar in landscape mode using actionbar tab mode.

like same as the one in portrait mode.

Can I do it?

**Comment by JakeWharton** [comment]
I think the 4.0 action bar behaves this way to ActionBarSherlock 4.0 will provide this support. There is no way to do this with ABS 3.x. If you have further questions please direct them to the mailing list: http://abs.io/forum
