### ISSUE TITLE
List navigation does not work in landscape mode

### ISSUE THREAD

**Issue by devisnik** [JakeWharton/ActionBarSherlock#117]
In the demo app the list navigation drop down box does not seem to work in landscape mode, at least not on my NexusOne running Android 2.3.6.

**Comment by JakeWharton** [comment]
I see this too. Looks like a problem with touch interaction only as using the trackball still works.

**Comment by UweTrottmann** [comment]
Stumbled over this by accident, too. Trackball really still works. ABS 3.4.2
In addition it seems to work in the Eclair emulator, but not in the Gingerbread one if that may help.

**Comment by SelvinPL** [comment]
List navigation not working ... not only in landscape but at all on samsung galaxy tab(P1000) with 2.3.3(it was working few (library, not android) versions ago but i don't know exactly version's number)  ... but it's workig on galaxy s(GT-I9000) with 2.3.5 ... 

EDIT: on GT-I9000 not working in landscape too :/
some meaningless logcat output: (0 on touch Down, 1 on touch Up)

12-12 11:29:49.574: I/InputReader(135): dispatchTouch::touch event's action is 0
12-12 11:29:49.574: I/InputDispatcher(135): Delivering touch to current input target: action: 0, channel '409bb880 pl.osadkowski.mobiletrader/pl.osadkowski.mobiletrader.ui.Goods.GoodsListActivity (server)'
12-12 11:29:49.671: I/InputReader(135): dispatchTouch::touch event's action is 1
12-12 11:29:49.671: I/InputDispatcher(135): Delivering touch to current input target: action: 1, channel '409bb880 pl.osadkowski.mobiletrader/pl.osadkowski.mobiletrader.ui.Goods.GoodsListActivity (server)'

**Comment by Xomo** [comment]
Hi,

I did found the issue: in landscape the tabView parent (HorizontalScrollView) is always visible and is messing with the listView.
Check out my fix:
https://github.com/Xomo/ActionBarSherlock/commit/9b485fbc1718a95282a50c1d9fad20c72afa2908

**Comment by JakeWharton** [comment]
Good catch. I'm going to try to pull in the ICS version of tabs (animated & scrollable) for 3.5 but if it doesn't make it I'll pull in your commit. Thanks.

**Comment by SelvinPL** [comment]
you should add null check before 

mTabsScrollView.setVisibility(isTab ? View.VISIBLE : View.GONE);

coz it will crash on devices where it works before ...(coz there is no R.id.abs__nav_tabs_layout view in layout there)

if(mTabsScrollView!=null)
    mTabsScrollView.setVisibility(isTab ? View.VISIBLE : View.GONE);

**Comment by Xomo** [comment]
Right!
https://github.com/Xomo/ActionBarSherlock/commit/c22a00d1492c27730e6a16e88c8e26350274e550

**Comment by JakeWharton** [comment]
Released with 3.5.0.
