### ISSUE TITLE
getSupportActionBar() returns null

### ISSUE THREAD

**Issue by redochka** [JakeWharton/ActionBarSherlock#118]
Hi,

Just installed the demos app on a galaxy tab 10.1 and getSupportActionBar() returns null.

How to reproduce:

Home screen -> Action Bar -> Tab Navigation -> FORCE CLOSE

12-05 23:24:11.300: E/AndroidRuntime(6677): FATAL EXCEPTION: main
12-05 23:24:11.300: E/AndroidRuntime(6677): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.actionbarsherlock.sample.demos/com.actionbarsherlock.sample.demos.app.ActionBarTabNavigation}: java.lang.NullPointerException
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1751)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1767)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.app.ActivityThread.access$1500(ActivityThread.java:122)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1005)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.os.Handler.dispatchMessage(Handler.java:99)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.os.Looper.loop(Looper.java:132)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.app.ActivityThread.main(ActivityThread.java:4028)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at java.lang.reflect.Method.invokeNative(Native Method)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at java.lang.reflect.Method.invoke(Method.java:491)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at dalvik.system.NativeStart.main(Native Method)
12-05 23:24:11.300: E/AndroidRuntime(6677): Caused by: java.lang.NullPointerException
12-05 23:24:11.300: E/AndroidRuntime(6677):     at com.actionbarsherlock.sample.demos.app.ActionBarTabNavigation.onCreate(ActionBarTabNavigation.java:19)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1048)
12-05 23:24:11.300: E/AndroidRuntime(6677):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1715)
12-05 23:24:11.300: E/AndroidRuntime(6677):     ... 11 more

**Comment by JakeWharton** [comment]
Should be fixed. Just deployed.
