### ISSUE TITLE
problem with fragmentation actionbar and viewpager 

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#119]
Hi,

I am using actionbarsherlock library to have action-bar in my application, 

I am also using view-pager to switch between the page,

Now the problem is **i want only one tab with two fragment** to display data regarding each other.

What could be the possible way to do this?

I have been going through like the one below but unsuccessful

In main fragment i am inflating a xml like this 

<code>
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {

```
    View fragView = inflater.inflate(R.layout.album_view_main, container, false);

    return fragView;
}
```

</code>
xml fie is look like this

<code>
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="horizontal" >

```
<fragment
    android:id="@+id/fragment_album_view"
    android:layout_width="0px"
    android:layout_height="fill_parent"
    android:layout_weight="3"
    class="com.nix.music.activity.fragments.AlbumFragMent" />

<FrameLayout
    android:id="@+id/frame_list_song"
    android:layout_width="0px"
    android:layout_height="fill_parent"
    android:layout_weight="2" >
</FrameLayout>
```

</LinearLayout>
</code>

but the problem is i cannot find "frame_list_song" in AlbumFragment class it appears null

what could be the way around ?

thank you

**Comment by JakeWharton** [comment]
Please as questions on the mailing list: http://abs.io/forum, though this question has nothing to do with ActionBarSherlock itself so you might find better luck on the official Android mailing list ( http://groups.google.com/group/android-developers ) or on [StackOverflow](http://stackoverflow.com).
