### ISSUE TITLE
Latest (dec 5 market update) "ActionBarSherlock Demos" crushes

### ISSUE THREAD

**Issue by megatronxxx** [JakeWharton/ActionBarSherlock#120]
Here's stacktrace:

12-07 18:26:24.308: E/AndroidRuntime(5387): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.actionbarsherlock.sample.demos/com.actionbarsherlock.sample.demos.app.ActionBarMenuSupport}: android.view.InflateException: Binary XML file line #33: Error inflating class <unknown>
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.app.ActivityThread.access$2200(ActivityThread.java:119)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.os.Handler.dispatchMessage(Handler.java:99)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.os.Looper.loop(Looper.java:123)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.app.ActivityThread.main(ActivityThread.java:4363)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at java.lang.reflect.Method.invokeNative(Native Method)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at java.lang.reflect.Method.invoke(Method.java:521)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:862)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at dalvik.system.NativeStart.main(Native Method)
12-07 18:26:24.308: E/AndroidRuntime(5387): Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class <unknown>
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.view.LayoutInflater.createView(LayoutInflater.java:513)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:565)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:618)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:621)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:198)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.app.Activity.setContentView(Activity.java:1631)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:219)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:241)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:241)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:241)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:241)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:241)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:241)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:241)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.getSupportActionBar(FragmentActivity.java:1074)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:568)
12-07 18:26:24.308: E/AndroidRuntime(5387):     at android.support.v4.ap

**Comment by JakeWharton** [comment]
This is fixed in the `dev` branch. Will be released soon.

**Comment by JakeWharton** [comment]
Released with 3.5.0. Actual market APK update will be later tonight.
