### ISSUE TITLE
FragmentActivity.onContentChanged() gets fired at the wrong time

### ISSUE THREAD

**Issue by wuman** [JakeWharton/ActionBarSherlock#122]
On pre-Honeycomb devices, if you try to set a layout in your FragmentActivity subclass and expect to find some view in that layout upon onContentChanged(), you won't find it.

This is because in FragmentActivity.setContentView(...), ensureSupportActionBarAttached() actually fires first and calls setContentView() on your behalf.  That causes the parent Activity class to think that a layout has been set and calls onContentChanged() prematurely.  The user's own layout doesn't get inflated and added until after onContentChanged().

**Comment by JakeWharton** [comment]
This should be fixed in v3.5 which will be out in a few days. I pulled some stuff from the development of v4 to fix some nasty stuff that's been around in 3.x for far too long.

**Comment by JakeWharton** [comment]
Released with 3.5.0.
