### ISSUE TITLE
Home button doesn't respect abLogo\abIcon drawables' selected states

### ISSUE THREAD

**Issue by pechlambda** [JakeWharton/ActionBarSherlock#123]
Subj. If I set abLogo (or abIcon) drawables with specified images for pressed\focused states they are not respected by home button. There is still no pressing\focusing behavior on them while tapping. It is odd since action bar buttons do respect their drawables' states.

How can I get it fixed? :) Thanks.

**Comment by JakeWharton** [comment]
I get this a lot but no one has been able to definitively tell me whether or not the native action bar on 3.0+ supports this.

**Comment by pechlambda** [comment]
Yep, seems that you are right about home icon's states. 

But there is another thing: "selectableItemBackground" option isn't respected by home button as well, but it is respected on 3.0+ devices (WARNING: don't try to test it on Samsung devices, it doesn't respect this option even for action bar buttons other than home, as usual with Samsung). Tested and confirmed.

Maybe that was already fixed in post 3.4.2 commits?
