### ISSUE TITLE
Missing drawable for ?homeAsUpIndicator in XHDPI

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#125]
Release 3.4.2

Hi, 

I'm using the theme dependent drawable for the home-as-up-indicator in that way:

``` xml
<ImageButton 
        ....
        android:src="?homeAsUpIndicator" />   
```

Running this on Galaxy Nexus leads to a crash due to a missing resource. 

Stack trace from Android 4 emulator:

12-17 09:08:59.651: E/AndroidRuntime(972): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01000d a=-1}
12-17 09:08:59.651: E/AndroidRuntime(972):  at android.content.res.Resources.loadDrawable(Resources.java:1899)
12-17 09:08:59.651: E/AndroidRuntime(972):  at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
12-17 09:08:59.651: E/AndroidRuntime(972):  at android.widget.ImageView.<init>(ImageView.java:119)
12-17 09:08:59.651: E/AndroidRuntime(972):  at android.widget.ImageButton.<init>(ImageButton.java:85)
12-17 09:08:59.651: E/AndroidRuntime(972):  at android.widget.ImageButton.<init>(ImageButton.java:81)

**Comment by JakeWharton** [comment]
When an app is running on Android 3.0+ it uses the native action bar and not the implementation from the library.

**Comment by drsoran** [comment]
I understand. This means there is no homeAsUpIndicator for the native implementation?

**Comment by JakeWharton** [comment]
I've tested about 15 apps using ActionBarSherlock on my Galaxy Nexus and they all work fine. Are you positive that the error is related to this library? What attribute does `0x7f01000d` map to in your `R.java`? Can you provide a test project that produces this behavior?

**Comment by drsoran** [comment]
>  Are you positive that the error is related to this library?
> Yes. As I said, I tested on Android 4 emulator
> 
> What attribute does 0x7f01000d map to in your R.java?
> From com.actionbarsherlock.R.
> public static int homeAsUpIndicator=0x7f01000d;

It happened to me if I used the ImageButton from above in an arbitrary layout. If the layout is shown on devices which are using your implementation, everything works fine. But If I try this on native devices, I get the error. To be honest, I didn't tried on 3.x devices.

I worked around the problem by copying your abs__ic_ab_back_holo_dark.png file to my drawable folder.

I still use your Theme.Sherlock.Light theme as my parent theme on all platforms. Is it possible that the attribute "homeAsUpIndicator" is not defined on native platforms?

**Comment by JakeWharton** [comment]
It is a custom attribute defined in the library. It will always be present because it gets put in your apps `R.java` and thus is present no matter what platform you are running it on.

Things like this are usually a result of having different versions of ADT and the ADT Eclipse Plugin. If you can create a reproducible test case I'd be happy to take a look.

**Comment by AndroidDeveloperLB** [comment]
I'm having this problem too, and I don't understand it. 
Why is this issue closed?
How do I fix it?
