### ISSUE TITLE
Add Theme.Sherlock.Light.DarkActionBar

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#126]
...which inherits from `Theme.Holo.Light.DarkActionBar`.

**Comment by chrisbanes** [comment]
I was just looking at doing this exact thing this morning. Shouldn't it be called DarkActionBar to follow [ICS](http://developer.android.com/reference/android/R.style.html#Theme_Holo_Light_DarkActionBar)'s?

**Comment by JakeWharton** [comment]
Er, yeah. Don't know why I thought it was inverse.

**Comment by JakeWharton** [comment]
Trumped by #143.
