### ISSUE TITLE
Exclusive checkable submenu is not closed on selection

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#129]
Release 3.5.0

I have a submenu with exclusive checkable items. After a click on the menu item in the action bar opens a dialog with the items to select one. So far everything works as expected. But after clicking one item, the menu action is performed by the dialog is not closed.

The closing after selection is explicitly commented at _com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.onSubMenuSelected_ line 200.

Has this a reason?

**Comment by JakeWharton** [comment]
Fixed on `dev` branch. Feel free to use that until a proper 3.5.1 is released.

**Comment by JakeWharton** [comment]
Released with v3.5.1. Sorry for the delay!
