### ISSUE TITLE
Custom ActionView can't be clicked in 3.5.0 release

### ISSUE THREAD

**Issue by ai212983** [JakeWharton/ActionBarSherlock#131]
Just noticed - with 3.5.0 version I can't click custom ActionView:

```
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.main_menu, menu);

        MenuItem checkout = menu.findItem(R.id.menu_checkout);

        mCheckoutView = new ActionBarCheckoutView(this);
        checkout.setActionView(mCheckoutView);

        return super.onCreateOptionsMenu(menu);
    }
```

ActionBarCheckoutView is just a subclass of LinearLayout containing image and some text field. Its not clickable with latest version. In previous version everything was fine.

**Comment by ai212983** [comment]
Moreover, it has no separator now... I guess something is wrong with MenuItem.setActionView logic.

**Comment by ai212983** [comment]
Any chance this bug will be fixed / looked into (or at least this issue commented) any time soon?

Looks like showstopper severity to me. Maybe custom action views aren't used in many projects, but if they ARE used, 3.5.0 breaks project completely.

**Comment by JakeWharton** [comment]
Separator logic was changed to match ICS. Looking into this now...

**Comment by ai212983** [comment]
It's not working with both pre-ICS (Nexus S 2.2.3) and ICS (Galaxy Nexus 4.0.1) devices, btw.

**Comment by JakeWharton** [comment]
Yeah I just added a demo for it. It appears you have to handle clicks yourself on 4.0+ and since ABS 3.5's action menu is ported from the ICS it behaves the same.

**Comment by ai212983** [comment]
Not sure how it will work on 4.0+, but I wasn't able to capture click event on pre-ICS device for some reason, making the whole idea of using custom action views in ABS meaningless. Besides, separators are still bugged. I guess the best idea would be to avoid custom action views at all...

Will look into your demo though, thanks.

**Comment by JakeWharton** [comment]
The action menu will place a divider _before_ an action item if the previous action item is non-custom and has text or if the current item is non-custom and has both text and an icon.

See [this](https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/view/menu/ActionMenuView.java#L502-513) and [this](https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/view/menu/ActionMenuItemView.java#L198-204) for the code.
