### ISSUE TITLE
ActionBar not hidden on request

### ISSUE THREAD

**Issue by Cpasjuste** [JakeWharton/ActionBarSherlock#134]
Hi, i'm not sure if it's a bug or a bad usage from me, but i'm trying to hide the action bar from code :

if ( Build.VERSION.SDK_INT < Build.VERSION_CODES.HONEYCOMB ) 
{
            getSupportActionBar().setDisplayShowTitleEnabled(false);
            getSupportActionBar().setDisplayShowCustomEnabled(false);
            getSupportActionBar().setDisplayHomeAsUpEnabled(false);
            getSupportActionBar().setDisplayUseLogoEnabled(false);
            getSupportActionBar().setDisplayShowHomeEnabled(false);
}
- On my Samsung Galaxy note (android 2.3.6, 1280*720 screen res), the actionbar view is gone, which is what i except.
- On my LG Optimus 2x (android 2.3.7, 800*480 screen res), while all the bar components are hidden, the actionbar view is still shown as you can see on this screenshot :  http://imageshack.us/photo/my-images/9/actionsherlockbug.png/  so it take some place on the whole view while it should be gone.

**Comment by SimonVT** [comment]
Have you tried getSupportActionBar().hide() ?

**Comment by Cpasjuste** [comment]
Yes, if i do that it works but the tabs (ActionBar.Tab: Downloads,Filer,Logs on the screenshot) are hidden too.

By the way, here is the (good) result on my galaxy note (when using the code on my first message) : http://imageshack.us/photo/my-images/845/actionsherlockbug2.png/

**Comment by JakeWharton** [comment]
This is a feature of the Ice Cream Sandwich action bar and thus will work in ABS 4.0. It is not possible in v3.x.
