### ISSUE TITLE
Eclipse/IDEA UI preview bug

### ISSUE THREAD

**Issue by stepango** [JakeWharton/ActionBarSherlock#135]
When applying Theme.Sherlock to any project there are StackOverflow exception in UI preview. More info about this bug http://youtrack.jetbrains.net/issue/IDEA-77946 

When i'm apply Theme.Holo in preview screen instead of Theme.Sherlock there are no errors.

**Comment by JakeWharton** [comment]
This is a bug in the layout display code. What ABS v3.x does with themes is unconventional but still perfectly valid. I filed a bug on the Android bug tracker a couple months ago about this but it still seems unresolved (http://code.google.com/p/android/issues/detail?id=19599).

ABS v4 will not have this problem.
