### ISSUE TITLE
Progress Bars Do Not Display

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#140]
Both determinate and indeterminate progress bars are being shy.

**Comment by iNoles** [comment]
While I am looking in the docs for this, it show the progress bar in the title. Did we use "NoTitle" as theme?

**Comment by JakeWharton** [comment]
Yes the Android system title bar is hidden. I think it's probably the fact that I didn't set up methods in the base activities for this yet. The issue is just serving as a reminder.
