### ISSUE TITLE
VFY error on android 1.6

### ISSUE THREAD

**Issue by felixb** [JakeWharton/ActionBarSherlock#144]
hi jake,
one of my users is getting this VFY error on his 1.6 htc tattoo.
i'm on your master with the 29878f cherry-picked from your dev (issue #137).
cheers,
felix

12-29 18:58:46.227 E/dalvikvm( 1154): Could not find method com.actionbarsherlock.internal.widget.IcsLinearLayout.onConfigurationChanged, referenced from method com.actionbarsherlock.internal.view.menu.ActionMenuView.onConfigurationChanged
12-29 18:58:46.227 W/dalvikvm( 1154): VFY: unable to resolve virtual method 3763: Lcom/actionbarsherlock/internal/widget/IcsLinearLayout;.onConfigurationChanged (Landroid/content/res/Configuration;)V
12-29 18:58:46.227 W/dalvikvm( 1154): VFY:  rejecting opcode 0x6f at 0x0006
12-29 18:58:46.227 W/dalvikvm( 1154): VFY:  rejected Lcom/actionbarsherlock/internal/view/menu/ActionMenuView;.onConfigurationChanged (Landroid/content/res/Configuration;)V
12-29 18:58:46.227 W/dalvikvm( 1154): Verifier rejected class Lcom/actionbarsherlock/internal/view/menu/ActionMenuView;
12-29 18:58:46.237 D/AndroidRuntime( 1154): Shutting down VM
12-29 18:58:46.237 W/dalvikvm( 1154): threadid=3: thread exiting with uncaught exception (group=0x4001db88)
12-29 18:58:46.237 E/AndroidRuntime( 1154): Uncaught handler: thread main exiting due to uncaught exception
12-29 18:58:46.307 E/AndroidRuntime( 1154): java.lang.VerifyError: com.actionbarsherlock.internal.view.menu.ActionMenuView
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at java.lang.Class.getDeclaredConstructors(Native Method)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at java.lang.Class.getConstructor(Class.java:484)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at android.view.LayoutInflater.createView(LayoutInflater.java:474)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:564)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at com.actionbarsherlock.internal.view.menu.BaseMenuPresenter.getMenuView(BaseMenuPresenter.java:70)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at com.actionbarsherlock.internal.view.menu.ActionMenuPresenter.getMenuView(ActionMenuPresenter.java:111)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at com.actionbarsherlock.internal.widget.ActionBarView.setMenu(ActionBarView.java:351)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at com.actionbarsherlock.internal.app.ActionBarImpl.setMenu(ActionBarImpl.java:83)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:730)
12-29 18:58:46.307 E/AndroidRuntime( 1154):     at de.ub0r.android.websms.WebSMS$1.afterTextChanged(WebSMS.java:313)

**Comment by JakeWharton** [comment]
Man 1.6 is annoying. I'll get a commit for this in tonight. Thanks for reporting!

**Comment by JakeWharton** [comment]
FIxed on `dev`.

**Comment by JakeWharton** [comment]
Released with v3.5.1. Sorry for the delay!
