### ISSUE TITLE
Resource not Found under 4.0-wip branch

### ISSUE THREAD

**Issue by iNoles** [JakeWharton/ActionBarSherlock#145]
There is android:textAllCaps under Widget.Sherlock.ActionBar.TabText with parent Widget and can't be found. I did searched for "android:textAllCaps" and is under TextView.

**Comment by JakeWharton** [comment]
`textAllCaps` is an API 14+ attribute which is probably why it showed as an error for you. It will be ignored on previous platforms. ABS 4 requires Android 4.0 for compilation.

**Comment by iNoles** [comment]
I set project target to 15 in project.properties. In AndroidMainfest.xml, I have < uses-sdk android:minSdkVersion="8" android:targetSdkVersion="15" / >[/code] Maybe Android SDK has "textallCaps" is under a different theme?

**Comment by JakeWharton** [comment]
What are you compiling with in Eclipse though? It has to be 4.0 or 4.0.3 and not 3.2 like ABS v3.x.

**Comment by iNoles** [comment]
I am compiling with Apache's ant build system.

**Comment by iNoles** [comment]
In other hand, it doesn't looks like a problem anymore.
