### ISSUE TITLE
List Navigation Text Color Black

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#149]
On 2.1. Probably 2.2 and 2.3 as well.

**Comment by UweTrottmann** [comment]
Confirmed for 2.3.

**Comment by thorinside** [comment]
I am seeing this on a 2.1 emulator too. Just getting my head wrapped around all of the great 4.0-wip changes.

**Comment by JakeWharton** [comment]
Closing as dup of #143.

**Comment by UweTrottmann** [comment]
May I get punished. This was caused (at least on my side) by not using the correct layout as demonstrated in [your sample](https://github.com/JakeWharton/ActionBarSherlock/blob/master/samples/demos/src/com/actionbarsherlock/sample/demos/app/ActionBarListNavigation.java).
You have to use `R.layout.abs__simple_spinner_item` for the adapter.

However I did not test it with 4.x, yet (I use the 3.x version on my dev trunk). My original report above was for a 4.0 beta though.

**Comment by thorinside** [comment]
Well, abs__simple_spinner_item doesn't exist in the 4.0-wip branch. I've been trying to figure out how to make my spinner items have the right text colour for a while now. I have a couple of incomplete workarounds so far.
