### ISSUE TITLE
support for setIcon/setLogo

### ISSUE THREAD

**Issue by bvgastel** [JakeWharton/ActionBarSherlock#151]
It would be really helpful if setIcon(Drawable) and setLogo(Drawable) are supported, so custom icons can be shown.

See also http://developer.android.com/reference/android/app/ActionBar.html#setIcon(android.graphics.drawable.Drawable)

**Comment by JakeWharton** [comment]
This will come with ABS v4. See http://beta.abs.io/ to try the beta.
