### ISSUE TITLE
Action Items Disappearing in ViewPager

### ISSUE THREAD

**Issue by UweTrottmann** [JakeWharton/ActionBarSherlock#153]
edit: this is a ABS 4 beta bug.

Using the 2.2.2 release of ViewPagerIndicator. Only on Android 4.0 so far.
1. Jump into any page, but not the first or last one.
2. Swipe to the first or last page
3. The action items disappear.

Also, if you swipe away from the first/last page, it reappears.
It is displayed if you start with the first/last page. As soon as you swipe away and back again, split action bar disappears.

Check out the abs4 branch of SeriesGuide (pager is imlemented in [EpisodeDetailsActivity](https://github.com/UweTrottmann/SeriesGuide/blob/abs4/SeriesGuide/src/com/battlelancer/seriesguide/ui/EpisodeDetailsActivity.java#L115), but can't see a problem there)

**Comment by JakeWharton** [comment]
Probably related to https://groups.google.com/d/topic/actionbarsherlock/pWsWWXZp5nQ/discussion. Investigating.

**Comment by JakeWharton** [comment]
Can't figure this out! I'll try stepping through with the debugger this weekend.

**Comment by ChrisSmith** [comment]
I've been stepping through the code for the last couple hours and am getting closer to figuring out what is happening.

Currently in `ActionBarSherlock.dispatchInvalidateOptionsMenu` the method returns early `if (!dispatchPrepareOptionsMenu())` which is related to why the menu items are disappearing. Sending an additional call to `invalidateOptionsMenu` from the Activity will cause the action bar to be refilled.  Checking the logs it appears when the menus are working normally they are invalidated one extra time compared to when they are misbehaving.  If we stop the method from returning early they get an extra invalidate and work normally.

I have no idea if this is an appropriate fix (going with no), but its a start.

old 

> ```
>    if (!dispatchPrepareOptionsMenu()) {
>        if (mActionBar != null) {
>            mActionBar.setMenu(null, mMenuPresenterCallback);
>        }
>        mMenu.startDispatchingItemsChanged();
>        return;
>    }
> ```

new

> ```
>    if (!dispatchPrepareOptionsMenu()) {
>       if (mActionBar != null) {
>            mActionBar.setMenu(null, mMenuPresenterCallback);
>        }
>        mMenu.startDispatchingItemsChanged();
>    } 
> ```

The other places that are potential issues are `FragmentActivity.dispatchPrepareOptionsMenu()` and `ActionBarView.setMenu`

**Comment by JakeWharton** [comment]
Well I fixed _this_ bug (the one where they disappear). Now I just have to figure out why the initial state and page don't get their action items displayed. So close!

**Comment by JakeWharton** [comment]
It's definitely fixed. Action items are there when inspected with hierarchy viewer. Seems to be some kind of view invalidation problem.

**Comment by JakeWharton** [comment]
Just built the latest `dev` branch of SeriesGuide with the latest `4.0-wip` of ActionBarSherlock and I no longer observe this problem. Nor do I observe the problem described in my previous comment where non-split action items would be created but not shown anymore. Closing!
