### ISSUE TITLE
Split action bar shown on non-narrow screens

### ISSUE THREAD

**Issue by UweTrottmann** [JakeWharton/ActionBarSherlock#154]
ABS 4 beta bug

The split action bar is used on non-narrow screens, e.g. in landscape mode or on tablets.
1. Use uiOptions="splitActionBarWhenNarrow" on an activity as mentioned in the ['Using split action bar' developers guide](https://developer.android.com/guide/topics/ui/actionbar.html#SplitBar).
2. Display the activity in landscape mode or on an xlarge device.
3. Split action bar is used despite having a 'non-narrow' screen.

Is this behavior explicitly different from the Android implementation? In short: bug or feature?

For an example look at the [abs4 branch](https://github.com/UweTrottmann/SeriesGuide/tree/abs4) of SeriesGuide.

**Comment by JakeWharton** [comment]
Definitely a bug. There should be no perceivable difference between the native action bar and ABS4.

**Comment by SimonVT** [comment]
Split actionbar is still shown in landscape on phones.

**Comment by JakeWharton** [comment]
Good catch.

---

Jake Wharton
http://about.me/jakewharton

On Tue, Jan 3, 2012 at 2:20 PM, SimonVT <
reply@reply.github.com

**Comment by JakeWharton** [comment]
Released in beta 4 @ http://beta.abs.io/

**Comment by UweTrottmann** [comment]
I hope it's a problem on my end, but I still get the same behavior (Galaxy Nexus on 4.0.1, Galaxy Tab on 3.1). I debugged with an WVGA800 emulator (4.0.3) and [this value here](https://github.com/JakeWharton/ActionBarSherlock/blob/4.0-wip/library/src/com/actionbarsherlock/ActionBarSherlock.java#L842) always returns true no matter if it's portrait or landscape. No clue why this doesn't load from the correct resource.

**Comment by JakeWharton** [comment]
Yeah odd. It should be hitting the `-w480p` when in landscape which disables that. I'll re-open and investigate later.

**Comment by JakeWharton** [comment]
I forgot to prefix the booleans with `abs__`.... *facepalm*

**Comment by UweTrottmann** [comment]
I'm feeling for you :-) Glad to see you're still a human being regarding
the mawesomeness (learned from a friend: short for MEGAawesome) of the 4.0
release.
On Jan 4, 2012 4:48 AM, "Jake Wharton" <
reply@reply.github.com>
wrote:

**Comment by monicager** [comment]
Hi, Sherlockbar is a great api!, and sorry that I'm commenting here, but i need to split the action bar in Tablets 7", then I deleted de abs__bools from w480 and I put this in values xlarge, but it doesn't work, I tried deleting abs__bools from xlarge too, and no works, what should i do?

Thanks very very much!

**Comment by JakeWharton** [comment]
Even if you modify ABS the behavior won't change on Android 4.0 and newer. I suspect you're running on a newer device which is why you don't see the changes reflected.

**Comment by monicager** [comment]
Hi Jake, thanks for your quick response, yes I'm trying in android 4.1.1, then is not possible in newer devices?
