### ISSUE TITLE
splitActionBarWhenNarrow doesn't load for <application> manifest element

### ISSUE THREAD

**Issue by DDRBoxman** [JakeWharton/ActionBarSherlock#157]
ICS allows it to be set from the <application> manifest element.
http://developer.android.com/guide/practices/tablets-and-handsets.html#SplitActionBar

**Comment by JakeWharton** [comment]
Duplicate of #156. Will be released with beta 4 today. Thanks!

**Comment by JakeWharton** [comment]
Released in beta 4 @ http://beta.abs.io/
