### ISSUE TITLE
SplitActionBar doesn't unsplit in landscape mode...

### ISSUE THREAD

**Issue by thorinside** [JakeWharton/ActionBarSherlock#158]
On ICS, the split action bar (on bottom of screen) combines with the top part of the action bar in landscape mode. This is not occurring with ABS 4.0-wip.

**Comment by JakeWharton** [comment]
Did you try beta 4?

---

Jake Wharton
http://about.me/jakewharton

On Tue, Jan 3, 2012 at 5:11 PM, Neal Sanche <
reply@reply.github.com

**Comment by thorinside** [comment]
I must riding in the 4.0-wip branch today. I'll check for the beta.

**Comment by JakeWharton** [comment]
Fixed by 77bab795581a119e914cbb7b52ce76407bbfeec4. Will be in beta 5.

**Comment by thorinside** [comment]
I've pulled from your 4.0-wip branch and have confirmed that the action bar unsplits now. Thanks.
