### ISSUE TITLE
Overflow menu not showing in 2.2 (galaxy S)

### ISSUE THREAD

**Issue by beirigo** [JakeWharton/ActionBarSherlock#163]
I've noticed that the overflow menu is not shown when runing on android 2.2 (galaxy s). The action bar is trying to fit all menu itens, but only the ones who actually fits are shown. On the motorola xoom(3.1) it works fine.

**Comment by JakeWharton** [comment]
The overflow should go into the normal options menu (triggered by menu key) on pre-3.0 by default. If you want to force an overflow menu on the action bar set `absForceOverflow` to `true` in your theme.

**Comment by beirigo** [comment]
Is it avaible on build 3.5.1?

**Comment by JakeWharton** [comment]
No, sorry. I thought you were referring to ABS 4.0. On 3.x the overflow menu gets pushed to the normal system options menu.

**Comment by beirigo** [comment]
ok, I'll try 4.0.
Thank you

**Comment by zhen9ao** [comment]
Current 4.0-wip branch don't have this problem, the overflow shows automatically. But It only worked for the activity extends SherlockActivity or SherlockFragmentActivity, won't work for the Activity extends an customize base Activity which extends SherlockActivity, and in this case, have to set `absForceOverflow` to `true` to make the overflow work.
