### ISSUE TITLE
hardware menu button doesnt work correctly in forced menu action item mode

### ISSUE THREAD

**Issue by daverix** [JakeWharton/ActionBarSherlock#166]
When using my Asus EEEPad Transformer (Android 3.2) and clicking on the hardware menu button on the keyboard dock or using forced menu button on HTC Sensation (Android 2.3.4) and then clicking on the hardware menu button following happens:
- When pressing the hardware menu button, the option menu appears.
- When then releasing the menu button, it disappears. The option menu should stay visible until is pressed again just as without forced mode.
- When first clicking on the forced overflow action item and then pressing hardware menu button and releasing it, the menu disappears as it should.

Using Actionbar Sherlock 4.0 beta. Same behaviour on both my app and on the support demos app.

**Comment by JakeWharton** [comment]
I think I use calls to `onPrepareOptionsMenu` to trigger this but I probably should be using `onKeyDown` or something...

**Comment by shreeshga** [comment]
In ActionBarSherlock.java

```
@Override
    public boolean onKeyUp(int keyCode,KeyEvent event) {        
        if ( keyCode == KeyEvent.KEYCODE_MENU ) {
            getSupportBar().dispatchOpenOptionsMenu();        
            return true;
            }
        return false;
   }
```

instead of

``` @Override
    public final boolean onPrepareOptionsMenu(android.view.Menu menu) {
        return mSherlock.dispatchPrepareOptionsMenu(menu);
    }
```

Fixes the issue
