### ISSUE TITLE
Title won't show if you show subtitle first

### ISSUE THREAD

**Issue by eburnette** [JakeWharton/ActionBarSherlock#169]
In the 4.0 beta run the Feature Toggles demo. Press these buttons in order:
1. Title Display: Hide
2. Subtitle Display: Show
3. Title Display: Show

The title is not displayed. It should be. Now press:

a. Subtitle Display: Show
b. Subtitle Display: Hide

The title is displayed now. But showing and hiding the subtitle should't have made any difference.

If you start over and reverse steps 2 and 3, it works ok.

**Comment by JakeWharton** [comment]
I wonder if this happens with the native action bar too? Crazy use case but awesome little bug!

**Comment by JakeWharton** [comment]
Happens in native action bar too but only when the title is specified explicitly. http://b.android.com/24034

**Comment by JakeWharton** [comment]
Going to close this. Since we now proxy to native on 4.0+ I can't fix any bugs like this because the behavior will differ across platforms. However, I did start contributing fixes to AOSP for action bar-related things so I'll try to get to this one so it makes it into the next Android release.
