### ISSUE TITLE
Back button behaviour with collapsible action items

### ISSUE THREAD

**Issue by scottkennedy** [JakeWharton/ActionBarSherlock#172]
In ICS's implementation, if I expand a collapsible action item, the back button will collapse it.  A subsequent back press will close my Activity.

In ABS, it does not collapse the action item.  It simply closes my Activity

You can see this behaviour in Maps.  Select the Search item, it expands the search bar, and back will dismiss it.

**Comment by daverix** [comment]
Also needed for the actionmode. You should be able to either press the done-button or press back. Only done works now.

**Comment by MarcusWolschon** [comment]
A workaround for the app, until this is fixed would be:

private ActionMode mActionMode = null;
  ...
   mActionMode = startActionMode(new ActionMode.Callback() {
       ...

```
        @Override
        public void onDestroyActionMode(ActionMode mode) {
            mActionMode = null;
        }
    });
```

  ....
   @Override
    public void onBackPressed() {
        if (mActionMode != null) {
            mActionMode.finish();
            return;
        }
