### ISSUE TITLE
Overflow ListView is incorrectly full screen height following window hide

### ISSUE THREAD

**Issue by JamesCurry** [JakeWharton/ActionBarSherlock#175]
To reproduce:
- Start the ABS demo app
- Select 'Forced Overflow Item'
- Tap Overflow icon and observe four items
- Press HOME
- Long press HOME and select ABS demo app
- Observe that the list height is double the original list height

4.0 behaviour appears to be to hide it (i.e. it's not shown when coming back to the app).

**Comment by SimonVT** [comment]
I believe this is related to line 407 in measureHeightOfChildren of IcsListPopupWindow:

int returnedHeight = mDropDownList.getTop() + mDropDownList.getBottom();

On first measure, returnedHeight is 0. When leaving the activity and returning, measureHeightOfChild is called again, and this time returnedHeight is the height from last measure.

I can confirm that the overflow menu is dismissed when leaving activity in the ICS implementation, which would also solve this problem.

**Comment by JakeWharton** [comment]
Guess I'll have to dispatch `onPause` to the `ActionBarSherlock` class to hide the overflow if it's open. I briefly looked through the window manager code last night to see where it does this but couldn't locate it quick enough.
