### ISSUE TITLE
Stackoverflow Error related to the Issue 19599 you submitted to Google

### ISSUE THREAD

**Issue by ChristopheVersieux** [JakeWharton/ActionBarSherlock#177]
Hello Jake,

While playing with your awesome ActionBarSherlock library, I noticed some issues in my project.
If I use 

  style name="Theme.MyTheme" parent="@style/Theme.Light"

I can open the Layout Editor without any issue...

When changing my Theme to:

   style name="Theme.MyTheme" parent="@style/Theme.Sherlock.Light"

I got the issue you mentioned here:

http://code.google.com/p/android/issues/detail?id=19599#c0
com.android.ide.common.resources.ResourceResolver.resolveResValue(ResourceResolver.java:333)

Is there a fix or a workaround to avoid this?

**Comment by JakeWharton** [comment]
There is no workaround that I know of. I usually just use `Theme.Holo` when previewing my XML in the layout editor. We're just stuck waiting for the next version of ADT.

ABS v4 won't have this problem.

**Comment by ChristopheVersieux** [comment]
Ok, thanks works fine!

Just an extra question: Is that possible this keep this theme by default?
Each time I open a layout, Eclipse give me all tehse annoying crash popups.

**Comment by JakeWharton** [comment]
There doesn't seem to be any way for it to stick unfortunately. All we can do is hope the next version of ADT comes along quickly with a fix. Worst part is the fix was supposed to come out with v16 already...
