### ISSUE TITLE
Items don't overflow on 2.3

### ISSUE THREAD

**Issue by dcaunt** [JakeWharton/ActionBarSherlock#179]
I'm inflating a menu from XML which contains five items, the last three using `showAsAction="ifRoom"`. On ICS, I see the first two items and the overflow vertical ellipsis. On my 2.3 device I see the first three items.

**Comment by JakeWharton** [comment]
Overflow on devices with a menu key go into the normal options menu. If you want to force an overflow action item you can do so with the `absForceOverflow` theme attribute. See the 'Forced Overflow' sample in the demos.

There is also a `Theme.Sherlock.ForceOverflow` which you can use/inherit from.

**Comment by dcaunt** [comment]
Sorry, I'd tried absForceOverflow but had applied it to the wrong style. You're absolutely right, thank you.
