### ISSUE TITLE
Overflow Measurement Intermittently Filling Screen 

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#181]
That pesky @scottkennedy discovered this gem:

![](http://i.imgur.com/s22uN.png)

**Comment by dcaunt** [comment]
I'm seeing this when scrolling a ListView on a phone and opening the overflow menu. It seems more likely to happen if the list is scrolling quickly, but it doesn't always happen. Height varies, doesn't always fill the screen.

**Comment by shreeshga** [comment]
I just debugged and ...

``` Java
//icsListPopupWindow.java
private int measureHeightOfChildren(int widthMeasureSpec, int startPosition, int endPosition,
            final int maxHeight, int disallowPartialChildPosition) {
....
//int returnedHeight = 0;//DropDownList.getTop() + mDropDownList.getBottom();
int returnedHeight = 0;
```

icsListPopupWindow.show() is called multiple times and the padding keeps getting added and hence `returnedHeight` overflows. Need to debug more to understand the issue though :-/

**Comment by iNoles** [comment]
Did you look for returnedHeight += child.getMeasuredHeight();
