### ISSUE TITLE
Error building with Android 4.0.3

### ISSUE THREAD

**Issue by nalitzis** [JakeWharton/ActionBarSherlock#183]
Eclipse shows the following error message:

 The type ActionMenuItem must implement the inherited abstract method MenuItem.expandActionView()ActionMenuItem.java /ActionBarSherlock/src/com/actionbarsherlock/internal/view/menu line 11 Java Problem

There is a thread on Stackoverflow as well:
http://stackoverflow.com/questions/8073829/actionbarsherlock-hand-holding-please

**Comment by JakeWharton** [comment]
ABS v3.x only support compiling with Android 3.2. If you need to compile with 4.0+ then you will need to add additional (empty) methods to `MenuItemImpl` and `MenuItemWrapper` to correspond to those added to `MenuItem` in ICS.

Support for Android 4.0 will come with ABS 4.0.
