### ISSUE TITLE
MenuItem must have android:title attribute set otherwise Exception thrown

### ISSUE THREAD

**Issue by carlospuk** [JakeWharton/ActionBarSherlock#184]
Steps to reproduce:

Define a menu item with no android:title attribute, e.g.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >
        <item android:id="@+id/mnuItem"
          android:icon="@drawable/icon"
          android:showAsAction="always"           />        
</menu>
```

When the item is clicked, a NullReferenceException is thrown in MenuItemImpl.java in method toString():

```
@Override
public String toString() {
    return mTitle.toString();     <<<<<---  HERE
}
```

Suggested fix:

```
@Override
public String toString() {
    return (mTitle != null) ? mTitle.toString() : "";
}
```

**Comment by JakeWharton** [comment]
Is this for ABS v3.5 or the v4.0 betas?

**Comment by carlospuk** [comment]
This is for beta 5 of ABS v4.0.

The docs do suggest that a title attribute is always set, but it might be useful to handle it more gracefully.

**Comment by JakeWharton** [comment]
FYI The platform returns `mTitle.toString()` so they must do something different somewhere else...

**Comment by JakeWharton** [comment]
This bug only exists because debug logging is enabled in the betas (which implicitly calls the `toString()` method). I'll make sure it's disabled by default in the next beta and release so you'll get no problems.
