### ISSUE TITLE
MenuItems randomly don't show when loading Fragments

### ISSUE THREAD

**Issue by christopherperry** [JakeWharton/ActionBarSherlock#186]
I'm creating options menus in my Fragments. When I navigate to another Fragment that does not have any MenuItems, then navigate back to the previous Fragment, the MenuItem(s) will not be displayed.

**Comment by JakeWharton** [comment]
May be a dupe of #153. There's definitely something odd going on with the compat lib.

**Comment by JakeWharton** [comment]
This should be fixed for the next beta. I redid the support library's `FragmentActivity` and it appears to be behaving a bit better. There's still small bugs (see comments on #153) but I'm closing this for now. If you find problems when I release beta 6 please re-file.
