### ISSUE TITLE
NullPointerException When Menu Title is not set

### ISSUE THREAD

**Issue by xeudoxus** [JakeWharton/ActionBarSherlock#188]
The NullPointerException happens when the "Menu Title" is not set (It was not an issue in the non 4.0 beta).
# Example:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:icon="@drawable/ic_refresh" android:id="@+id/menu_refresh" android:showAsAction="always" />
</menu>
```
# Current

``` java
@Override
    public String toString() {
        return mTitle.toString();
    }
```
# ToFix

``` java
@Override
    public String toString() {
        if (mTitle != null) {
            return mTitle.toString();
        }
        return "";
    }
```

http://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/internal/view/menu/MenuItemImpl.java#L489

Its really not a critical issue, Ill let you know if I find more.

Thanks,
-Matt

**Comment by JakeWharton** [comment]
Fixed with #189.
