### ISSUE TITLE
Contexual Support

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#19]
The native 3.0 action bar supports a contexual action bar which is wholly different from the activity action bar and is tied to a specific piece of content. This needs its own abstraction though a `HasXxx` interface.

**Comment by JakeWharton** [comment]
Done in dev branch.

**Comment by LorneLaliberte** [comment]
The contextual action bar is a pretty sweet interface design IMO...I was impressed by the examples shown in this year's I/O livestream. Reusing the action bar is not only efficient, it serves a purpose by hiding the global actions while in the context of a modal step. I thought making the bar appear "shifted to the right" with the button on the top left was a nice affordance.

**Comment by JakeWharton** [comment]
I agree. I actually still need to port this back to the pre-3.0 action bar now that I think about it...

**Comment by JakeWharton** [comment]
See #23.
