### ISSUE TITLE
invalidateOptionsMenu() while Overflow dropdown is displayed

### ISSUE THREAD

**Issue by xeudoxus** [JakeWharton/ActionBarSherlock#191]
In my activity I have a TextView that is updated every 1.5 secs, in this sample project I use "invalidateOptionsMenu()" to get the bug to show. Although in my application I do not use "invalidateOptionsMenu()" in that run/thread.

The bug looks identical to this
- User/Project#Num: JakeWharton/ActionBarSherlock#181
# Sample Project

http://www.xeudoxus.com/android/BugTest.zip

To get the bug to show, run application and press the "Overflow" icon.
This issue was tested in Beta 5

Thanks,
-Matt

**Comment by JakeWharton** [comment]
Sample app appears to be fixed! New beta coming soon!
