### ISSUE TITLE
Proxy to Native Action Bar on API 14+

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#195]
This is going to raise all kinds of hell internally but it's for the best. Styling will suffer horribly... :(

**Comment by carlospuk** [comment]
Just out of curiosity on my part, can you expand on this?  Wondering what exactly is the issue.

**Comment by JakeWharton** [comment]
The action bar affordance is a platform feature for a reason and if it is available there no reason that we should not be using it. I choose to skip Honeycomb because it's implementation is nowhere near as powerful as ICS and its market share will likely never get above a few percent anyways.

By deferring to the native implementation we also stand to gain from any future modifications to how the action bar is displayed. Though never implemented, Google TV experimented with displaying the action bar on the left side of the screen rather than across the top. We don't know what the action bar will evolve into in the coming platforms and its best if we didn't restrict applications to essentially being stuck with an API 14 action bar on every new platform. There's a good chance that a lot of applications won't be updated anyways so by using the native version we can at least ensure their look evolves somewhat with the platform.

In any case, it's the right thing to do despite being a hard thing to do. Ignoring that platform implementation altogether would be a mistake.

**Comment by carlospuk** [comment]
Ah, now I understand what you are talking about - thanks.  It wasn't that I didn't agree, it was that I didn't understand what "Proxy to Native Action Bar on API 14+" meant - i.e. "there is an issue because of a proxy" vs "we must implement a proxy".

Yes, I think it's a bold but necessary decision - and by making the decision now, at least developers can make intelligent choices based on the knowledge that the implementation of the AB is not a static one.

Excellent library, by the way.

**Comment by robholmes** [comment]
I'm 100% behind you here Jake, you're making the right decision for the future of the project, as far as I'm concerned.

**Comment by UweTrottmann** [comment]
I support this, too. Considering a(nother) potential new release of Google TV this year, this might save us all some headaches.

**Comment by JakeWharton** [comment]
Closing as this is coming along nicely. Lots of wrinkles to iron out but the main implementation is done.
