### ISSUE TITLE
ActionBar not showing

### ISSUE THREAD

**Issue by gabrielittner** [JakeWharton/ActionBarSherlock#196]
Hi
I'm using the Beta of ActionBarSherlock 4.0 and discovered something where I'm not sure whether it's a bug or wanted behaviour.

So I got a Fragment Activity  (theme is Theme.Sherlock) which has an embedded DialogFragment. This is it's onCreathe mehtod:

``` java
    @Override
    public void onCreate (Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
        DialogFragment newFragment = new MyDialogFragment();
        newFragment.setArguments(getIntent().getExtras());
        ft.add(android.R.id.content, newFragment, "dialog");
        ft.commit();
    }
```

The problem is the ActionBar isn't shown as long as I don't access it in any way at either the Activities onCreate or the Fragments onCreate. For example it is shown when I add this (Activity)

``` java
    Log.i("", Boolean.toString(getSupportActionBar().isShowing()));
```

or (@ Fragment)

``` java
        setHasOptionsMenu(true);
```

Keep on with your great work and  if it isn't a bug I hope I didn't steal much of your time.

**Comment by gabrielittner** [comment]
Some additional things:

It's enough to just call `getSupportActionBar()` without doing anything with it.

In my Fragment I add a Custom View to the ActionBar, which looks like this http://goo.gl/JE1QE . When the ActionBar isn't accessed in onCreate the CustomView is drawn to the background http://goo.gl/CAcpB . The Buttons in the CustomView aren't usable in the second case.

**Comment by JakeWharton** [comment]
I think `getSupportFragmentManager()` is supposed to initialize the action bar. I'll have to check the platform's `Activity` source code later tonight. Calling `getSupportActionBar()` will do it explicitly too which is why that works.

**Comment by iNoles** [comment]
According to FragmentActivity.java, getSupportFragmentManager() is only return FragmentManagerImpl ;)

**Comment by JakeWharton** [comment]
Well I was referring to the native `Activity` class but it does essentially the same. I ended up going with firing `initActionBar` when `onPostCreate` is dispatched which should work well enough.

**Comment by slartus** [comment]
hello, can you tell me why in android 4.x action bar not showing?
all items showing in simple menu.
in 2.x it's showing correctly
thanks!
actionbarsherlock 4.0.0
android 4.0.3

androixmanifest.xml
 activity android:name="MainActivity" android:theme="@style/Theme.Sherlock"

public class MainActivity extends SherlockFragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

```
    this.requestWindowFeature(Window.FEATURE_NO_TITLE);

    setContentView(R.layout.main);

    FragmentManager fm = getSupportFragmentManager();
    FragmentTransaction ft = fm.beginTransaction();
    mFragment1 = (MenuFragment) fm.findFragmentByTag("f1");
    if (mFragment1 == null) {
        mFragment1 = new MenuFragment();
        ft.add(mFragment1, "f1");
    }
    ft.commit();

}
```

**Comment by JakeWharton** [comment]
You're not targeting API 11 or newer in your manifest.

**Comment by slartus** [comment]
I tried
uses-sdk android:minSdkVersion="5" android:targetSdkVersion="11"
and
uses-sdk android:minSdkVersion="5" android:targetSdkVersion="8"
and
uses-sdk android:minSdkVersion="5" android:targetSdkVersion="14"

http://clip2net.com/s/1Hq3w

**Comment by iNoles** [comment]
in 4.0.3, that is system bar. You may have set to actionbar disabled in ICS. I would like you to check your styles.xml

**Comment by slartus** [comment]
"You may have set to actionbar disabled in ICS" it is in Android settings? 
I do not use until the ICS. Only testing in the emulator.

**Comment by slartus** [comment]
I created a test project.
http://www.2shared.com/file/qWaXfZcX/test.html
ActionBar showing in the top of Activity in 2.x and not showing in 4.x

What am I doing wrong?

**Comment by slartus** [comment]
requestWindowFeature(Window.FEATURE_NO_TITLE);
that's my fault.
