### ISSUE TITLE
Google TV: d-pad cannot reach all items

### ISSUE THREAD

**Issue by larham** [JakeWharton/ActionBarSherlock#198]
On Google TV, which uses a directional pad (d-pad), the d-pad cannot reach context items show on Action Bar demo, "tabs and pager" sample, tab 4 (items labeled "Populate Clear")

**Comment by JakeWharton** [comment]
Is this for v3.x or the 4.0 betas?

**Comment by JakeWharton** [comment]
Fixed with the latest from `4.0-wip`. Closing.
