### ISSUE TITLE
ActionBar icon size is bigger on Gingerbread than on ICS

### ISSUE THREAD

**Issue by StefanBossbaly** [JakeWharton/ActionBarSherlock#200]
I noticed that on my Ice Cream Sandwich device (Galaxy Nexus 4.0.2) the icon in the action bar has some padding around it (http://imgur.com/BFRIW). However this is not true for my Gingerbread device. The icon does not have any padding around it and it seems to extend to the height of the action bar (http://imgur.com/QNGkY). Changing the orientation of the device to landscape causes the icon height to go beyond the action bar (http://imgur.com/aRiZO) as opposed to the action bar on my nexus (http://imgur.com/GUjoC). I checked on the theme page and did not see an option for changing the padding around the icon.

**Comment by sebastianherp** [comment]
Are you sure you are using the correct pixel size for your icons? The home icon (and other actionbar icons) size should be 32dp x 32dp and the icon itself 24dp x 24dp inside of that. See http://developer.android.com/design/style/iconography.html

**Comment by JakeWharton** [comment]
Padding isn't applied as generously on the pre-3.0 action bar as is the native variant (the native version is also 56dp as opposed to our 48dp). If you follow the edge guidelines on the icon docs you'll be alright.

In any case, version 4.0 handles this properly even if you do not follow the guides.
