### ISSUE TITLE
android:uiOptions="splitActionBarWhenNarrow" in Activity not working

### ISSUE THREAD

**Issue by mcnicholls** [JakeWharton/ActionBarSherlock#201]
android:uiOptions="splitActionBarWhenNarrow" gives a split ActionBar when placed in the application node,
but fails to do so when placed in an Activity node.
Switching my app to use native ActionBar support confirms a split ActionBar is shown when placed in the Activity node.

The activity is a FragmentActivity that contains one fragment. This fragment adds the action items to the ActionBar.

I'm using ABS 4.0 Beta 5.

**Comment by JakeWharton** [comment]
Can you paste your full manifest? Or at least the root tag, application tag, and the activity tag in question (and all their attributes)?

**Comment by mcnicholls** [comment]
Just had a look into the ABS code and I can see what is happening.

The name attribute of my activity node is just my class name. ABS code is looking for the . at the start of the name to decide if it
is within our package. My name attribute didn't have the . and so it didn't use the uiOptions.

If I put a . at the start of the class in my activities node name then I get the split ActionBar.

Is this still a bug as the system allows unqualified class names in the activity's name attribute?

**Comment by JakeWharton** [comment]
The activity name is _supposed_ to be either a fully qualified class name or a relative name from your manifest package (hence the leading period). I suppose that we should also account for ones without it, though, since the Android OS does the same. I'll leave the bug open as a reminder.

**Comment by mcnicholls** [comment]
I have implemented a simple fix for this locally.

Want me to fork and put in a pull request with it in?
