### ISSUE TITLE
Can't setTitle

### ISSUE THREAD

**Issue by fuadhamidan** [JakeWharton/ActionBarSherlock#203]
I am trying to setTitle in actionbar like this:

``` java
Bundle bundle   = getIntent().getExtras();
String keyword  = bundle.getString("com.taste.android.keyword");

getSupportActionBar().setTitle(keyword);
```

But the results didn't show the text of the keyword
the result is the name of the application

**Comment by JakeWharton** [comment]
Is this for version 3 or the version 4 betas?

**Comment by fuadhamidan** [comment]
I'm uses version 4 beta #5 ...

**Comment by SimonVT** [comment]
I use getSupportActionBar().setTitle(...) several places in my applications, never had an issue. You might want to check that keyword isn't null.

**Comment by fuadhamidan** [comment]
I tried getSupportActionBar().setSubtitle(...) .. it runs fine
but when I try getSupportActionBar().setTitle(...) keyword is not out, only show text from application name
