### ISSUE TITLE
action bar splitting and number of action buttons should be determined only by the device independent resolution

### ISSUE THREAD

**Issue by mattcoz** [JakeWharton/ActionBarSherlock#210]
In beta 5 you disable splitting the action bar on large screens, but when a large 1024x600 screen uses HDPI it is only 400dip wide in portrait mode.  That is much too small to fit a logo, title, four action buttons, and the overflow button.

**Comment by JakeWharton** [comment]
I'll have to write a wrapper of some sort around `getResources().getBoolean()` for pre-3.2 platforms that provides hard coded values for checks against the display metrics to determine the smallest-width dp and regular dp resource qualifiers. I initially had something like this but had hoped I could get away with things like the 'normal' and 'large' metrics. Oh well.
