### ISSUE TITLE
Evaluate ShareActionProvider Implementation

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#211]

**Comment by iNoles** [comment]
While I am looking for this type of provider, you already have some implementation of it. 

ShareActionProvider is just extending ActionProvider with Intent.

**Comment by JakeWharton** [comment]
I spent two hours trying to get it working. It's in the `share-action-provider` branch if anyone wants to have a go. Demo is included.

**Comment by navarr** [comment]
Should there be any issues merging the master branch into the share-action-provider branch?
i.e. Theoretically, will the same code run if copied into 4.0 release?

**Comment by JakeWharton** [comment]
It should merge fine as it's mostly new files only. I probably should rebase it against master and push that up.

**Comment by mattiasbe** [comment]
This might be of interest for further development.

The just released r7 support lib has this entry:

Changes for v4 support library:
Added ShareCompat, which provides helper classes for sending and receiving content for social sharing applications, including new metadata for attributing shared data to the source app. This class also provides compatible integration with the newShareActionProvider in Android 4.0.
