### ISSUE TITLE
1.6 LoaderCursorSupport

### ISSUE THREAD

**Issue by fredgrott** [JakeWharton/ActionBarSherlock#214]
Do not worry about android.provider.ContactsContract.Contacts

Under android 1.6 we have a simpler class verifier that rejects ALL classes that refer to any static fields not in 1.6 according to fadden..so it will never be fixed..as 1.6 is below 1% share anyway..

I am changing my demo minSDKVersion to 5 and see if I can find more bugs to fix..

we use different build systems which is why I did not fork yet and do it that way..some of us hate maven:)

Will still post any code changes I have to make on issues anyway..

**Comment by JakeWharton** [comment]
You don't have to use Maven, the projects use the standard Android directory layout.

Anything to do with loaders is part of the official support library and you should file bugs on http://b.android.com.

Also, ABS v4 drops support for 1.6.
