### ISSUE TITLE
extends FragmentActivity Error

### ISSUE THREAD

**Issue by xeigen** [JakeWharton/ActionBarSherlock#220]
An error occurs when i extends FragmentActivity using beta5 compat-lib. I tried changing Simple.java to extend FragmentActivity in demo and got the same error. Occurs in both gingerbread and ics

D/AndroidRuntime( 5672): Shutting down VM
W/dalvikvm( 5672): threadid=1: thread exiting with uncaught exception (group=0x4
0015560)
E/AndroidRuntime( 5672): FATAL EXCEPTION: main
E/AndroidRuntime( 5672): java.lang.NoSuchMethodError: com.actionbarsherlock.ActionBarSherlock.asDelegateFor
E/AndroidRuntime( 5672):        at android.support.v4.app.FragmentActivity.<init>(FragmentActivity.java:122)
E/AndroidRuntime( 5672):        at com.actionbarsherlock.sample.demos.Simple.<init>(Simple.java:24)
E/AndroidRuntime( 5672):        at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime( 5672):        at java.lang.Class.newInstance(Class.java:1409)
E/AndroidRuntime( 5672):        at android.app.Instrumentation.newActivity(Instrumentation.java:1021)
E/AndroidRuntime( 5672):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1561)
E/AndroidRuntime( 5672):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
E/AndroidRuntime( 5672):        at android.app.ActivityThread.access$1500(ActivityThread.java:117)
E/AndroidRuntime( 5672):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
E/AndroidRuntime( 5672):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5672):        at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 5672):        at android.app.ActivityThread.main(ActivityThread.java:3683)
E/AndroidRuntime( 5672):        at java.lang.reflect.Method.invokeNative(NativeMethod)
E/AndroidRuntime( 5672):        at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 5672):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
E/AndroidRuntime( 5672):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 5672):        at dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
If you're using the beta5 compat lib you have to use the beta5 ABS snapshot as well. It is not compatible with the current 4.0-wip branch.

**Comment by xeigen** [comment]
Thank you very much SimonVT..
Spent hours trying to figure out the problem, but never thought of such solution..
