### ISSUE TITLE
Possibility to turn off action bar by theme [4.0-wip]

### ISSUE THREAD

**Issue by tprochazka** [JakeWharton/ActionBarSherlock#224]
I have all Activities as child of FragmentActivity, but some of them are without action bar. For Android 3.0+ is possible simply use theme with `<item name="android:windowActionBar">false</item>` but on Android older than 3.0 crash by 
`java.lang.IllegalStateException: You must use Theme.Sherlock, Theme.Sherlock.Light,
 Theme.Sherlock.Light.DarkActionBar, or a derivative.`

What about allow the some with:
`<item name="windowActionBar">false</item>`

Now, when I try it, it crash something later, so it doesn't turn off SherlockActionBar

I'm testing dev version of 4.0

**Comment by IHNEL** [comment]
When I use .NoActionBar theme, the actionbar and menu items are hidden. How to show menu items without title bar?

**Comment by SimonVT** [comment]
You don't. No action bar means no menu items.
