### ISSUE TITLE
LoaderManager bug with orientation change

### ISSUE THREAD

**Issue by ichrisanderson** [JakeWharton/ActionBarSherlock#227]
There appears to be a bug that's introduced with the onLoadComplete method for the LoaderManager class.

Is there any reason the following line is added in? It's not part of the official support framework.

```
        if (mActivity != null && !hasRunningLoaders()) {
            mActivity.getInternalCallbacks().getFragments().startPendingDeferredFragments();
        }
```

It seems to cause an issue when handling orientation changes. In my code I have an actionbar that has a number of framents which load data to display in a list via the loaderManager. If you select an item in the list I open a new activity to display the item detail. At this point if you rotate the screen and click the back button the above line triggers a null pointer exception in the FragmnentManager code.

Speifically a null pointer exception is thrown  when the moveToState method gets hit in the a result of triggering startPendingDeferredFragments.

 case Fragment.ACTIVITY_CREATED:
                    if (newState < Fragment.ACTIVITY_CREATED) {
                        if (DEBUG) Log.v(TAG, "movefrom ACTIVITY_CREATED: " + f);
                        if (f.mView != null) {
                            // Need to save the current view state if not
                            // done already.
                            if (!mActivity.isFinishing() && f.mSavedViewState == null) {
                                saveFragmentViewState(f);
                            }
                        }

At this point mActivity. is null I assume due to the activity being recreated from the orientation change.

My code works with the offical support pack in Honeycomb.

**Comment by JakeWharton** [comment]
Version 4 uses the binary `.jar` from Google rather than modify any of the sources. The first version will be released tomorrow. Thanks for reporting though! Sorry it took so long for me to respond.

**Comment by ichrisanderson** [comment]
No problem. After a bit of digging about it seems to be present in the current Android release for certain scenarios.

The following might be of use to you if you want to look a little deeper.

http://www.mentby.com/Group/android-developers/scenario-where-initloader-does-not-call-onloadfinished.html
