### ISSUE TITLE
Setting abDisplayOptions to showHome|showTitle hides the home icon on Honeycomb

### ISSUE THREAD

**Issue by sebastianherp** [JakeWharton/ActionBarSherlock#229]
Whenever I use `<item name="abDisplayOptions">showHome|showTitle</item>` my Honeycomb tablet will stop showing the home icon on the actionbar. It works fine on 2.x and ICS. The option "useLogo" works fine everywhere.

My workaround is to use the standard (shows the home icon everywhere) and use "useLogo" in a special theme for some activities. However, I'd like to use it the other way around. Am I doing something wrong?

**Comment by JakeWharton** [comment]
This is due to the interesting way Android handles enum attributes in themes. You're better of specifying those options in code, unfortunately.

The way these are specified changes a bit in version 4 which should mitigate this behavior. The first version of 4 will be released tomorrow night.

**Comment by sebastianherp** [comment]
I confirm hat it works better on Version 4, but in the february 14th release it was still not possible to use UseLogo without displaying the title. Except when I Set it in code (which ins fine to me).
