### ISSUE TITLE
4.0.0 - LayoutParams of CustomView

### ISSUE THREAD

**Issue by MarcusWolschon** [JakeWharton/ActionBarSherlock#233]
On API-Level 14 the system ActionBar is used and a CustomView is handed through to it.
However if that CustomView has some com.actionbarsherlock.appActionBar.LayoutParams on it,
no effort is made to map these to the corresponding android.app.ActionBar.LayoutParams

**Comment by JakeWharton** [comment]
This should be handled properly on [calls to `setContentView(View, LayoutParams)`](https://github.com/JakeWharton/ActionBarSherlock/blob/88d255c885b33a27c8dcaab2a1fb2e21a209a0aa/library/src/com/actionbarsherlock/internal/app/ActionBarWrapper.java#L33-42). Or are you referring to something else?

**Comment by MarcusWolschon** [comment]
cool! Thanks

**Comment by MarcusWolschon** [comment]
Cool!

On Thu, Feb 9, 2012 at 14:43, Jake Wharton <
reply@reply.github.com
