### ISSUE TITLE
spinner not on right side of CustomView in split action bar

### ISSUE THREAD

**Issue by MarcusWolschon** [JakeWharton/ActionBarSherlock#237]
In a split action bar the spinner is shown to the right of any custom view.
Thus it is shown superimposed above the custom view until that changed location to the left to free up layout space at the right border.
(this custom view has gravity RIGHT. while the default gravity is LEFT.)

It should be displayed left of any custom view like it is in a non-split action bar.

**Comment by JakeWharton** [comment]
Can you provide a quick .zip or pastebin of the code to demonstrate this? I'll be able to debug much faster and want to make sure I fix specifically what you're looking for.

**Comment by MarcusWolschon** [comment]
A customView with gravity right...

``` java
final ActionBar supportActionBar = getSupportActionBar();
            final ImageView dashboard = new ImageView(this);
                final LayoutParams layoutParams = new ActionBar.LayoutParams(
                        LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT,
                        Gravity.RIGHT | Gravity.CENTER_VERTICAL);

                dashboard.setLayoutParams(layoutParams);
            dashboard.setImageDrawable(this.getResources().getDrawable(
                    R.drawable.icn_raster));
            supportActionBar.setCustomView(dashboard);
```

and in onCreate:

``` java
        requestWindowFeature(Window.FEATURE_PROGRESS);
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
                super.onCreate(savedInstanceState);
        setContentView(R.layout....);
```

and then actually show the spinner at some random point in time while the activity is showing.

``` java
        setSupportProgressBarVisibility(true);
        setSupportProgressBarIndeterminateVisibility(true);
        setSupportProgress(Window.PROGRESS_END);
```

**Comment by JakeWharton** [comment]
When I use `setCustomView(dashboard, layoutParams)` I don't see the problem (I think).

Is this what it's supposed to look like or is this the bug?

http://i.imgur.com/K7La1.png
http://i.imgur.com/kUaVt.png
http://i.imgur.com/18zny.png

**Comment by MarcusWolschon** [comment]
When the spinner runs for just a second or so, it looks like it is
superimposed on the customView because the customView has not yet
animated/moved to the left.
Before it gets a chance to do so, the spinner is already gone.
Is there a way to get the spinner to display to the left of the customView?
That would be a simple solution without having icons shifting around.
This way http://i.imgur.com/18zny.png looks quite wrong.

On Fri, Feb 10, 2012 at 04:42, Jake Wharton <
reply@reply.github.com

**Comment by JakeWharton** [comment]
The only way to do this would be to include the spinner in your custom view. The action bar can only be so dynamic to support all of these cases and it seems that something like this wasn't accounted for unfortunately.

That being said, I don't disagree with you that this should be considered as an option. File a bug on http://b.android.com and paste the link to it here for reference. I've already sent in a couple tiny fixes to the AOSP so maybe one day I'll get around to tackling this (or Google will).
