### ISSUE TITLE
actionBarSplitStyle doesn't work

### ISSUE THREAD

**Issue by sealskej** [JakeWharton/ActionBarSherlock#238]
I have tried to set this style for actionBarSplitStyle attr in theme:
`<style name="Widget.Cepro.SplitActionBar" parent="Widget.Sherlock.ActionBar">
        <item name="background">@color/black</item>
 </style>
`this way:
`<item name="actionBarSplitStyle">@style/Widget.Cepro.SplitActionBar</item>
`and there were no effect.

**Comment by JakeWharton** [comment]
If you are setting a background for the split style you still need to use `backgroundSplit` in the style.

The following worked for me:

``` xml
<style name="Theme.Issue238" parent="Theme.Sherlock">
    <item name="actionBarSplitStyle">@style/Widget.Issue238.ActionBar</item>
</style>
<style name="Widget.Issue238.ActionBar" parent="Widget.Sherlock.ActionBar">
    <item name="backgroundSplit">@drawable/abs__list_pressed_holo_dark</item>
</style>
```

Remember, this will only work on pre-4.0. You need to provide a native version of the styling too if you want it to work on ICS as per the discussion on #225.

**Comment by JakeWharton** [comment]
There will be styling samples in the next beta/release candidate.

**Comment by sealskej** [comment]
Thanks! I appreciate your work.
