### ISSUE TITLE
setSelectedNavigationItem Does Not Work in Collapsed Tab Navigation

### ISSUE THREAD

**Issue by mykola-dev** [JakeWharton/ActionBarSherlock#240]
Another old issue. I use ViewPager with tabs (code based on Support4Demo). When I flip page, I use this code in PagerAdapter to update tab selection:

``` java
public void onPageSelected(int position) {
 mActionBar.setSelectedNavigationItem(position);
}
```

This works great until I add few actionbar items and tabs collapsed to expandable list (it happens in landscape mode). Then selection of current tab just didnt work. Is I should use some other method instead of setSelectedNavigationItem()?
This issue appears in beta5 and beta6

**Comment by JakeWharton** [comment]
This is a platform bug. [This code](https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/widget/ScrollingTabContainerView.java#L168-179) doesn't not check if `mTabSpinner` is being used. It always assumes `mTabLayout`.

Submitted a patch to AOSP: https://android-review.googlesource.com/32492

**Comment by mykola-dev** [comment]
I see. Thanks Jake.
Will try to reduce my tabs amount and width :)

**Comment by toulouse** [comment]
@deviant-studio Here's a workaround that may work for you: https://gist.github.com/2657485

**Comment by commonsguy** [comment]
FWIW, since there didn't seem to be an official issue filed for the underlying Android bug, [I went ahead and filed one](http://code.google.com/p/android/issues/detail?id=38500).

**Comment by mohitum007** [comment]
I was also experiencing the same issue. Making a lot of research I found the solution here: 
    https://gist.github.com/toulouse/2657485
I hope this may help someone else too.

Mohit Sharma
http://mohitum.wordpress.com
