### ISSUE TITLE
When actionmode is enabled the hardware menu button should be disabled

### ISSUE THREAD

**Issue by daverix** [JakeWharton/ActionBarSherlock#241]
When using the emulator running Android 4.0.3 the hardware menu button (the buttons at the right of the screen) does nothing. On my Android 2.3 device it shows the menu.

I would rather have the menu button show the overflow menu (in actionmode) but it doesn't seem to be that way in the emulator at least.

Running beta 6 of ABS4.0

**Comment by JakeWharton** [comment]
Good catch.
