### ISSUE TITLE
Style attribute "windowSplitActionBar" not working under ICS 4.0.3

### ISSUE THREAD

**Issue by raymanzhang** [JakeWharton/ActionBarSherlock#243]
I have create a custom style with "windowSplitActionBar" set to true. The actionbar splited under Android 2.1/2.2, but not in ICS 4.0.3 emulator even with uiOptions="splitActionBarWhenNarrow".

**Comment by raymanzhang** [comment]
I tested it with the latest 4.0-wip branch

**Comment by JakeWharton** [comment]
Did you put a theme in `values-v14/` with `android:windowSplitActionBar` as `true` as per #225? Theming is not fully documented nor fully ironed out yet.

If your emulator is small enough, though, the manifest attribute should have been enough. There are examples of split action bars/modes in the sample. Did you take a look at that?

**Comment by raymanzhang** [comment]
I copyed the style.xml to both values-v14 and values-v15, it still doesn't work. Please see my sample project in #235.

**Comment by JakeWharton** [comment]
Sorry for the confusion, the style attribute is actually an internal attribute and shouldn't be used. The problem was that you didn't have the `android`-prefix on the XML attribute in your manifest. Once adding it the split action bar worked.

``` xml
<activity android:label="@string/app_name" android:name=".ActionbarTestActivity"    android:theme="@style/Theme.MDict"
          android:configChanges="orientation|keyboardHidden" android:launchMode="singleTop"
          android:uiOptions="splitActionBarWhenNarrow">
```

**Comment by raymanzhang** [comment]
Sorry, my fault...
