### ISSUE TITLE
Strange action mode layout  in split actionbar

### ISSUE THREAD

**Issue by raymanzhang** [JakeWharton/ActionBarSherlock#245]
I started an action mode with two action items in a split actionbar. these two icons were put in the most left and most right side of the acionbar. And the title of both of them are not shown.

**Comment by JakeWharton** [comment]
Please provide a sample .zip or pastebin of the class and any menu XMLs required to recreate the bug.

**Comment by raymanzhang** [comment]
Please download the sample project for #243,#244, #245 from here: http://infolib.net/ActionbarTest.zip. There is a screen-shot directory, You may have a look there first. Also, I manually replace those classes in android-support-v4.jar, wish this is not the cause of the problem.
BTW, The project can be debugged under IDEA 11. But under eclipse, the IDE can't attach to the debug process, don't know why.

**Comment by JakeWharton** [comment]
This is the proper behavior (as per 4.0.3). Once I added the XML `android` prefix to your `uiOptions` in the manifest I got this:

![](http://i.imgur.com/A3HkT.png)
