### ISSUE TITLE
Option menu crashes in orientation change

### ISSUE THREAD

**Issue by naoak** [JakeWharton/ActionBarSherlock#248]
Using ABS 4 beta 6 on API 10,

Open the option menu, and change the orientation. 
NPE occurs..

Sample code is here.

```
public class MainActivity extends FragmentActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main);
    }
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater inflater = getSupportMenuInflater();
        inflater.inflate(R.menu.main_menu, menu);
        return super.onCreateOptionsMenu(menu);
    }
}
```

Menu xml is here.

```
<?xml version="1.0" encoding="utf-8"?>
<!-- main_menu.xml -->
<menu xmlns:android="http://schemas.android.com/apk/res/android">
<item android:id="@+id/menu_first"
    android:title="first"
    android:icon="@drawable/ic_menu_item"
    android:showAsAction="ifRoom" />
<item android:id="@+id/menu_second"
    android:title="second"
    android:icon="@drawable/ic_menu_item"
    android:showAsAction="ifRoom" />
<item android:id="@+id/menu_third"
    android:title="third"
    android:icon="@drawable/ic_menu_item"
    android:showAsAction="never" />
</menu>
```

The log is here.

02-10 22:59:11.895: E/AndroidRuntime(3551): java.lang.NullPointerException
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:326)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.actionbarsherlock.ActionBarSherlock.callbackPrepareOptionsMenu(ActionBarSherlock.java:464)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchPrepareOptionsMenu(ActionBarSherlockCompat.java:389)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.support.v4.app.FragmentActivity.onPrepareOptionsMenu(FragmentActivity.java:280)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.app.Activity.onPreparePanel(Activity.java:2180)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:340)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.android.internal.policy.impl.PhoneWindow.openPanel(PhoneWindow.java:428)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.android.internal.policy.impl.PhoneWindow.openPanelsAfterRestore(PhoneWindow.java:1623)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.android.internal.policy.impl.PhoneWindow.access$900(PhoneWindow.java:91)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.android.internal.policy.impl.PhoneWindow$DecorView.onAttachedToWindow(PhoneWindow.java:2077)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.view.View.dispatchAttachedToWindow(View.java:6209)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:1122)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.view.ViewRoot.performTraversals(ViewRoot.java:773)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.os.Looper.loop(Looper.java:130)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at android.app.ActivityThread.main(ActivityThread.java:3691)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at java.lang.reflect.Method.invokeNative(Native Method)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at java.lang.reflect.Method.invoke(Method.java:507)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
02-10 22:59:11.895: E/AndroidRuntime(3551):     at dalvik.system.NativeStart.main(Native Method)

With overflow menu or inheriting SherlockAcitivity, NPE does not occur.

**Comment by JakeWharton** [comment]
I don't get a crash. Are you handling any configuration changes in the manfest?

**Comment by naoak** [comment]
No. My manifest file is simple like this.

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="com.test.mypackage"
android:versionCode="1"
android:versionName="1.0" >
<uses-sdk android:minSdkVersion="7" android:targetSdkVersion="15" />
<application
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/Theme.Sherlock" >
    <activity android:name=".MainActivity"
        android:label="@string/app_name"  >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
</application>
</manifest>
```

Anything wrong with this?
Should be target sdk 14?

**Comment by JakeWharton** [comment]
No that all looks fine. I know what is causing the problem I just want to be able to reproduce it myself so that I can ensure the fix is the right one to make. I'll keep trying.

**Comment by naoak** [comment]
Thanks Jake.
I created a repo for this issue.
https://github.com/bossturbo/testabs

**Comment by JakeWharton** [comment]
No crash for me on 2.1 emulator, 2.3.3 emulator, 4.0.3 emulator, and 4.0 device. Are you using the latest from the `4.0-wip` branch and the beta 6 version of the support-lib plugin?

**Comment by naoak** [comment]
No. Both are the beta 6 version. 
I'll test  on other environments, but it may take a while.
Sorry to take up your time.

**Comment by JakeWharton** [comment]
Try the latest for the library itself: https://github.com/JakeWharton/ActionBarSherlock/zipball/4.0-wip

**Comment by JakeWharton** [comment]
Closing as I'm pretty sure this has been fixed. If that's not the case with the latest from `4.0-wip` please let me know.

**Comment by naoak** [comment]
Sorry, I was badly held up on building support-lib plug-in with maven...
I met the same issue on 2.3.3 emulator with the latest from 4.0-wip.
Changing device orientation with option menu open surely causes my app to crash.

**Comment by JakeWharton** [comment]
Whoops I should have mentioned that you didn't need to rebuild the support-lib plugin. 

Do you think you could provide a .zip of a simple example where it crashes? Perhaps just by modifying one of the demos or something? I haven't been able to reproduce it locally.

**Comment by naoak** [comment]
I met the same issue, if I change the file Simple.java in demos to the following.

``` java
package com.actionbarsherlock.sample.demos;

import android.os.Bundle;
import android.widget.TextView;

// import com.actionbarsherlock.app.SherlockActivity;
import android.support.v4.app.FragmentActivity;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuItem;

// public class Simple extends SherlockActivity {
public class Simple extends FragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        setTheme(SampleList.THEME); //Used for theme switching in samples
        super.onCreate(savedInstanceState);
        setContentView(R.layout.text);
        ((TextView)findViewById(R.id.text)).setText(R.string.actionbar_simple_content);
    }
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        menu.add("Save")
            .setIcon(R.drawable.ic_compose)
            .setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
        menu.add("Search")
            .setIcon(R.drawable.ic_search)
            .setShowAsAction(MenuItem.SHOW_AS_ACTION_NEVER);
        return super.onCreateOptionsMenu(menu);
    }
}
```

**Comment by naoak** [comment]
It works perfectly!
Amazed at your quick fix. Thanks.

**Comment by JakeWharton** [comment]
I had an idea of what was causing it. Just wanted to make sure I was reproducing the issue correctly before applying a fix. Thanks for reporting!
