### ISSUE TITLE
java.lang.VerifyError when using FragmentActivity

### ISSUE THREAD

**Issue by romainpiel** [JakeWharton/ActionBarSherlock#249]
I've just included latest version of ABS (4.0.0-SNAPSHOT) and imported the plugin support for ABS.
When I extend FragmentActivity I get that error:

02-10 15:48:38.103: E/AndroidRuntime(636): FATAL EXCEPTION: main
02-10 15:48:38.103: E/AndroidRuntime(636): java.lang.VerifyError: android.support.v4.app.FragmentManagerImpl
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.support.v4.app.FragmentActivity.<init>(FragmentActivity.java:109)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.support.v4.app.FragmentActivity.<init>(FragmentActivity.java:151)
02-10 15:48:38.103: E/AndroidRuntime(636):  at com.fidelpass.fidelpass.ui.FidelPassActivity.<init>(FidelPassActivity.java:13)
02-10 15:48:38.103: E/AndroidRuntime(636):  at com.fidelpass.fidelpass.ui.LoginActivity.<init>(LoginActivity.java:9)
02-10 15:48:38.103: E/AndroidRuntime(636):  at java.lang.Class.newInstanceImpl(Native Method)
02-10 15:48:38.103: E/AndroidRuntime(636):  at java.lang.Class.newInstance(Class.java:1429)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.app.Instrumentation.newActivity(Instrumentation.java:1021)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2577)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.app.ActivityThread.access$2300(ActivityThread.java:125)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.os.Handler.dispatchMessage(Handler.java:99)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.os.Looper.loop(Looper.java:123)
02-10 15:48:38.103: E/AndroidRuntime(636):  at android.app.ActivityThread.main(ActivityThread.java:4627)
02-10 15:48:38.103: E/AndroidRuntime(636):  at java.lang.reflect.Method.invokeNative(Native Method)
02-10 15:48:38.103: E/AndroidRuntime(636):  at java.lang.reflect.Method.invoke(Method.java:521)
02-10 15:48:38.103: E/AndroidRuntime(636):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
02-10 15:48:38.103: E/AndroidRuntime(636):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
02-10 15:48:38.103: E/AndroidRuntime(636):  at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
On what OS?

**Comment by romainpiel** [comment]
API 8

**Comment by romainpiel** [comment]
I'm using latest code from branch 4.0-wip. Should I try using a beta instead?

**Comment by JakeWharton** [comment]
You can use `4.0-wip` for the library but the plugin needs to be the latest .jar pulled from the beta page.

**Comment by romainpiel** [comment]
Ok cool. The only way I got it working is using the jar file. Sorry to have created an issue for that ;)
