### ISSUE TITLE
Action Item Submenus

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#25]
Submenus on action items should popup a list dialog.

**Comment by zumpar** [comment]
Hi, 

could you post some example code that uses submenus? I'm unable to create them programmatically or through a xml menu resource.

edit: I forgot to mention I'm trying to create them on a phone. Is this possible?

Thanks!
Paul

**Comment by JakeWharton** [comment]
The 'styled' sample contains two submenus which are created from a menu XML. Here is a snippet of one of them:

``` xml
<item android:id="@+id/menu_nav" android:title="@string/action_label_nav">
    <menu>
        <group android:id="@+id/menu_nav_group" android:checkableBehavior="single">
            <item android:id="@+id/menu_nav_tabs" android:title="@string/action_label_nav_tabs" android:checked="true" />
            <item android:id="@+id/menu_nav_drop_down" android:title="@string/action_label_nav_drop_down" />
            <item android:id="@+id/menu_nav_label" android:title="@string/action_label_nav_label" />
        </group>
    </menu>
</item>
```

The `<group>` tag is only utilized here because the sub-menu items are all checkable.

Creating the above menu prorgammatically would start something like this:

``` java
public void onCreateOptionsMenu(Menu menu) {
    SubMenu subMenu = menu.addSubMenu(0, R.id.menu_nav, 0, R.string.action_label_nav);
    subMenu.addItem(0, R.id.menu_nav_tabs, 0, R.string.action_label_nav_tabs);
    subMenu.addItem(0, R.id.menu_nav_drop_down, 0, R.string.action_label_nav_drop_down);
    subMenu.addItem(0, R.id.menu_nav_label, 0, R.string.action_label_nav_label);
}
```

In this example I use `R` attributes for the ids and titles but you may use literal numbers and strings as well.

**Comment by zumpar** [comment]
Thank you!

On a tablet, this works great, but I'm unable to get it working on pre-3.0 devices, so I'm guessing it's just for tablets.

**Comment by segundoacosta** [comment]
Hola, como puedo hacer que al hacer touch en un item se despliegue una lista ??

**Comment by segundoacosta** [comment]
Como se puede hacer el siguiente menú por código sin usar un layout.xml.
Translate:
Can this be done straight through Java or must I use layout.xml?

<menu xmlns:android="http://schemas.android.com/apk/res/android" >

```
<item
android:icon="@drawable/menu"
android:showAsAction="ifRoom">
<menu android:id="@+id/menuopciones">

    <item
        android:id="@+id/vivo"
        android:title="VIVO"
        android:showAsAction="ifRoom|withText"    
        android:icon="@drawable/vivoon"
    />

    <item
        android:title="VOD"
        android:id="@+id/vod"
        android:showAsAction="ifRoom|withText"    
        android:icon="@drawable/vodon"
    />

    <item
        android:title="RPVR"
        android:id="@+id/npvr"
        android:showAsAction="ifRoom|withText"        
        android:icon="@drawable/npvron"        
    />

</menu>
```

</item>

</menu>
