### ISSUE TITLE
Issue with grouped options menu

### ISSUE THREAD

**Issue by mykola-dev** [JakeWharton/ActionBarSherlock#250]
Hi there. I have another one issue. I have a group of menu items:

``` xml
<menu xmlns:android="http://schemas.android.com/apk/res/android">

    <item
        android:id="@+id/im_sort"
        android:icon="@drawable/ic_action_sort"
        android:title="Sort by..."
        android:showAsAction="ifRoom"
        android:orderInCategory="1">
        <menu>

            <group
                android:id="@+id/im_sort_group"
                android:checkableBehavior="single">
                <item
                    android:id="@+id/im_sort_artistic"
                    android:checked="true"
                    android:title="Artistic" />
                <item
                    android:id="@+id/im_sort_original"
                    android:title="Original" />
                <item
                    android:id="@+id/im_sort_technic"
                    android:title="Technic" />
            </group>
        </menu>
    </item>


</menu>
```

Note that group have android:checkableBehavior="single" attribute. That means if I choose one of items from that group and check it in the code, another items should to be unchecked automatically:

``` java
public boolean onOptionsItemSelected(MenuItem item) {
        int index = -1;
        switch (item.getItemId()) {
        case R.id.im_sort_artistic:
            index = SORT_ARTISTIC;
            break;
        case R.id.im_sort_original:
            index = SORT_ORIGINAL;
            break;
        case R.id.im_sort_technic:
            index = SORT_TECHNICAL;
            break;

        }
        if (index != -1) {
            item.setChecked(true);      
        }

        return super.onOptionsItemSelected(item);
    }
```

On device with 2.3.3 this code works fine, But on Emulator with ICS items do not unchecks.
Here is screenshot: ![](http://gyazo.com/af60e0a1e9c00eddf2e1f5d9ec316d93.png?1328895435)

Also I have a problem with appearing action items on emulator 2.1, but I think I should post another issue here

**Comment by JakeWharton** [comment]
I can reproduce. Investigating...

**Comment by JakeWharton** [comment]
This deals with the fact that `setExclusiveChecked` is a method on `MenuItemImpl` so when we are inflating to the native version we were unable to set it properly. Now we just call on the native menu inflater to inflate directly to the native menu. This is better anyways since it will enable new features on new APIs automatically.

Get the latest `4.0-wip` branch for the fix.

**Comment by mykola-dev** [comment]
Awesome! Now it works perfect. Thank you for quick response.
