### ISSUE TITLE
MenuItems show only at bottom splitActionBar

### ISSUE THREAD

**Issue by MAW016** [JakeWharton/ActionBarSherlock#252]
I am not able to add any MenuItem to upper actionBar at split mode ... 
![bug pic](http://www.sn.hys.cz/maw016/bug.png)

**Comment by JakeWharton** [comment]
It's only one or the other. That's the nature of the beast, I'm afraid. More info here: http://developer.android.com/guide/topics/ui/actionbar.html#SplitBar
