### ISSUE TITLE
ActionBar still received events when hidden

### ISSUE THREAD

**Issue by namnx** [JakeWharton/ActionBarSherlock#254]
I hid the action bar to detect the touch events on the top of the screen, but this does not happen. The action bar was still received events from user. Is this a bug?

**Comment by JakeWharton** [comment]
Are you using beta 6 or the latest from the `4.0-wip` branch?

**Comment by namnx** [comment]
I am using the beta 6 version downloaded from http://beta.abs.io/

**Comment by JakeWharton** [comment]
Download the latest `4.0-wip` branch for the library and give it a try: https://github.com/JakeWharton/ActionBarSherlock/zipball/4.0-wip

**Comment by namnx** [comment]
It is still the same :(

**Comment by namnx** [comment]
I use the action bar in overlay mode. At the beginning, I hide the it, my app works correctly. But when I show it and then hide it again, this problem happens.

**Comment by JakeWharton** [comment]
Was able to reproduce. Investigating...

**Comment by JakeWharton** [comment]
And fixed!
