### ISSUE TITLE
Add Theme.Sherlock.Dialog Styles

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#255]
To mimic `Theme.Holo.Dialog`.

**Comment by tprochazka** [comment]
I don't understand it. this theme should allow to use ActionBar on the dialog? Because I don't found way how to do it on the android 3.0+.

**Comment by JakeWharton** [comment]
In `4.0-wip`

**Comment by dcaunt** [comment]
I see that this can be used to make an Activity look like a Dialog, but does it allow us to make pre-honeycomb Dialogs look like Holo Dialogs?

**Comment by JakeWharton** [comment]
It does not. That may be a possibility, however. I'll have to evaluate just how well the pre-3.0 alert dialogs can be styled.
