### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by ChrisSmith** [JakeWharton/ActionBarSherlock#258]
A serious leak was introduced recently (I'm using 123438d9bc5d97deb12d9f007bc351290073c774)

Initial indications point toward a modification in NineOldAndroids (or an internal portion of abs that uses it) that is causing the view hierarchy to leak. I'm looking into it and creating a demo app.

**Comment by ChrisSmith** [comment]
Its worth noting that there isn't an issue on ICS but I see it on Gingerbread. (Because you don't create a proxy on Honeycomb/ICS)

`com.actionbarsherlock.internal.nineoldandroids.view.animation.AnimatorProxy` is leaking with it's static PROXIES variable. While the key is getting cleaned up because it is a weak reference, the value is not (which is a AnimatorProxy in this case). The proxy keeps a reference to the view which is in turn, leaking the entire hierarchy. You should either avoid using WeakHashMap here or keep a weak reference to the view.

**Comment by JakeWharton** [comment]
Awesome find. I probably would have totally missed this. Updated to use a weak reference in the proxy. Thanks!
