### ISSUE TITLE
Different behavior from ICS 4.0.3 in pre 4.0 device when action items are all "showAsAction=never"

### ISSUE THREAD

**Issue by raymanzhang** [JakeWharton/ActionBarSherlock#259]
Not sure is this a proper behavior:
If  I set all the action item with android:showAsAction="never" , then press the menu button. In pre 4.0 devices, the options menu will be shown in the OS's original style not the ICS one.  Sample project here: http://www.infolib.net/ActionbarTest.zip

**Comment by JakeWharton** [comment]
If you always want the ICS-style overflow on pre-ICS devices you should use `Theme.Sherlock.ForceOverflow` (or set the theme attribute `absForceOverflow` to `true` in your own theme). By default, though, we'll use the normal options menu to remain consistent.
