### ISSUE TITLE
Mention should be made of likely bugs in the F.A.Q.

### ISSUE THREAD

**Issue by Esteth** [JakeWharton/ActionBarSherlock#26]
I ran into two problems which I suspect are reasonably common, but for which I could not find docs regarding.

existing styles need to not use @+id, but must be ported to use @id, with the ID declared in the ids.xml file. This was causing unparsable resource errors in aapt.

Also, it should be mentioned that ABS _replaces_ the compat library, and will _not_ work alongside it in a project.

**Comment by JakeWharton** [comment]
Can you elaborate more on point 1? I'm not sure what you mean as there is only one ID specified in the `ids.xml` and it is for the layout.

**Comment by Esteth** [comment]
Perhaps it was an issue specific to my particular configuration, but when I tried to add ABS as a library project, to an existing app, I needed to change all of my styles to not declare IDs, but to reference IDs defined in ids.xml.

This is likely an issue related to my particular app, and me simply having an issue that didn't come to light until using ABS exposed it, so this is a non-issue, I expect.
