### ISSUE TITLE
ShareActionProvider bug in 2.1 Emulator

### ISSUE THREAD

**Issue by iNoles** [JakeWharton/ActionBarSherlock#263]
02-14 01:08:19.723: E/AndroidRuntime(236): java.lang.ExceptionInInitializerError
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.actionbarsherlock.widget.ShareActionProvider.setShareIntent(ShareActionProvider.java:266)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.itnoles.shared.fragments.WebDetailsFragment.onCreateOptionsMenu(WebDetailsFragment.java:140)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:1881)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:311)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:446)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:318)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentActivity.invalidateOptionsMenu(FragmentActivity.java:264)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentActivity.supportInvalidateOptionsMenu(FragmentActivity.java:270)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:714)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.itnoles.shared.fragments.WebDetailsFragment.onActivityCreated(WebDetailsFragment.java:69)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:892)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1081)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:622)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1417)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:794)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.app.Activity.performStart(Activity.java:3723)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.app.ActivityThread.access$2200(ActivityThread.java:119)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.os.Handler.dispatchMessage(Handler.java:99)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.os.Looper.loop(Looper.java:123)
02-14 01:08:19.723: E/AndroidRuntime(236):  at android.app.ActivityThread.main(ActivityThread.java:4363)
02-14 01:08:19.723: E/AndroidRuntime(236):  at java.lang.reflect.Method.invokeNative(Native Method)
02-14 01:08:19.723: E/AndroidRuntime(236):  at java.lang.reflect.Method.invoke(Method.java:521)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
02-14 01:08:19.723: E/AndroidRuntime(236):  at dalvik.system.NativeStart.main(Native Method)
02-14 01:08:19.723: E/AndroidRuntime(236): Caused by: java.lang.NoClassDefFoundError: java.util.ArrayDeque
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.actionbarsherlock.widget.ActivityChooserModel$SerialExecutor.<init>(ActivityChooserModel.java:570)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.actionbarsherlock.widget.ActivityChooserModel$SerialExecutor.<init>(ActivityChooserModel.java:569)
02-14 01:08:19.723: E/AndroidRuntime(236):  at com.actionbarsherlock.widget.ActivityChooserModel.<clinit>(ActivityChooserModel.java:567)
02-14 01:08:19.723: E/AndroidRuntime(236):  ... 29 more

**Comment by iNoles** [comment]
according to https://developer.android.com/reference/java/util/ArrayDeque.html, API Level 9

**Comment by JakeWharton** [comment]
Should be a simple fix then. You're not even supposed to be using this yet! :)

I don't think it works at all on any platform if I remember correctly...

**Comment by iNoles** [comment]
excuse me to live in the edge. :) at least, I know what is works or not. :P

**Comment by JakeWharton** [comment]
Going to close for now because finishing this is still a week or two away. Hold off on filing bugs until it's integrated into the `dev` branch (`4.0-wip` branch is becoming `dev` branch tonight) rather than sitting in a topic branch like it is now. I only pushed it in case someone else wants to take a stab at finishing it.
