### ISSUE TITLE
Verify Error on 1.6

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#269]
Hello,

Beta #6 seems to cause a VerifyError on my Sony 1.6 device, apologies if this was already caught or if it's my error!

02-15 09:22:16.947: E/AndroidRuntime(1802): java.lang.VerifyError: com.actionbarsherlock.internal.widget.ActionBarContainer
02-15 09:22:16.947: E/AndroidRuntime(1802):     at java.lang.Class.getDeclaredConstructors(Native Method)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at java.lang.Class.getConstructor(Class.java:484)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.view.LayoutInflater.createView(LayoutInflater.java:474)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:564)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:617)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.generateLayout(ActionBarSherlockCompat.java:952)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:502)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:668)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at com.actionbarsherlock.ActionBarSherlock.setContentView(ActionBarSherlock.java:549)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.support.v4.app.FragmentActivity.setContentView(FragmentActivity.java:372)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at com.demostrike.gui.activity.MainActivity.onCreate(MainActivity.java:93)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2422)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.app.ActivityThread.access$2100(ActivityThread.java:116)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.os.Handler.dispatchMessage(Handler.java:99)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.os.Looper.loop(Looper.java:123)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at android.app.ActivityThread.main(ActivityThread.java:4232)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at java.lang.reflect.Method.invokeNative(Native Method)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at java.lang.reflect.Method.invoke(Method.java:521)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
02-15 09:22:16.947: E/AndroidRuntime(1802):     at dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
ABS4 only supports 2.1+

**Comment by ghost** [comment]
My bad, I did do a search but didn't see anything obvious - apologies :)

**Comment by SimonVT** [comment]
No worry. I believe Jake mentioned supporting it later, but for now 2.1 is all it does :)

**Comment by ru-nekit-android** [comment]
I has same error on emulator 2.3.3 - what a solution?

**Comment by marcardar** [comment]
ABS 4.1.0

I got a report of this in my dev console today. minSdkVersion is 9.  Sadly dev console gives no further details (such as SDK level, device etc).

**Comment by jaysidri** [comment]
I'm getting this on devices running 2.3.6

Exception Type: java.lang.VerifyError
Reason: com.actionbarsherlock.app.ActionBar

ActionBarSherlockCompat.java line 146
com.actionbarsherlock.internal.ActionBarSherlockCompat.initActionBar

ActionBarSherlockCompat.java line 129
com.actionbarsherlock.internal.ActionBarSherlockCompat.getActionBar
