### ISSUE TITLE
Wrong visible action item count in split actionbar after rotation

### ISSUE THREAD

**Issue by raymanzhang** [JakeWharton/ActionBarSherlock#270]
1create an optionmenu with 5 or moreitems in a splitwhennarrow singletop activity:
2 rotate emulator to landscape and start the activity,the actionbar was shown in the upper right with 4-5 items shown
3 rotate the emulator, the actionbar will be split but with only 2 items in it

**Comment by JakeWharton** [comment]
Tracking this under #279. Thanks for reporting.
