### ISSUE TITLE
Intermediate progress under landscape is broken on android 2.3.7

### ISSUE THREAD

**Issue by willlunniss** [JakeWharton/ActionBarSherlock#273]
Firstly, thank you for your work. I've been trying out 4.0-wip (from 2 days ago, haven't moved to RC1 yet) and noticed today that the intermediate progress flashes and then disappears when in landscape mode on android 2.3.7 on my HTC Wildfire (LDPI - 320x240 screen)

I've just downloaded the latest sample app (RC1) to see if it still exists and the same things happens when turning it on under 'Feature Toggles' when in landscape mode. When launching the dedicated 'Intermediate Progress' under landscape, the app force closes.

**Comment by JakeWharton** [comment]
Supporting LDPI may be a bit of a challenge but I'll try.

**Comment by willlunniss** [comment]
OK. So far, everything else I have tried in the sample app and in my app that i'm moving to use ABS in work as expected.

**Comment by JakeWharton** [comment]
That's good to know. I'll be sure to try all the samples on LDPI before the next release candidate.

**Comment by JakeWharton** [comment]
I fixed the crash but there still appears to be a measuring problem.

**Comment by willlunniss** [comment]
I think it is because the actionbar is smaller in landscape mode than portrait and on an LDPI screen its too small for the default progress bar?

I've overridden the progress bar size to be a smaller and that allows it to display correctly in landscape mode.

**Comment by AnderWeb** [comment]
Hi Jake, I've tested a simple fix and it works, seems to be cause of a bug within RotateDrawable on android 2.1.
Here on line 991 https://github.com/JakeWharton/UnbreakMe/blob/master/src/asdf/afsd/adsf/IcsProgressBar.java#L991 change to 
<code>
mIndeterminateDrawable.setBounds(0, 0, right-left, bottom-top);
mRealLeftBound=left;
mRealTopBound=top;
</code>
Also you need to store in 2 new class members the real left and top bounds coordinates so we can later move the canvas in line 1008 https://github.com/JakeWharton/UnbreakMe/blob/master/src/asdf/afsd/adsf/IcsProgressBar.java#L1008
<code>
canvas.translate(getPaddingLeft()+mRealLeftBound, getPaddingTop()+mRealTopBound);
</code>

Sorry for not sending a pull request, but I don't have my ssh keys at work.
