### ISSUE TITLE
"ifRoom" without title or Home

### ISSUE THREAD

**Issue by jeanmatthieud** [JakeWharton/ActionBarSherlock#277]
When we set [showAsAction="ifRoom"] on menu items, without Title or Home logo, menu items don't take all the space available.

Tested with :
- 4.0.0 RC1
- SherlockMapActivity,
- Called in onCreate() :

`````` getSupportActionBar().setDisplayShowTitleEnabled(false);
getSupportActionBar().setDisplayShowHomeEnabled(false);```
- Android 2.2
``````

**Comment by JakeWharton** [comment]
This is the behavior of the native action bar. The number of action items is limited by a certain number based on the smallest width device-independent pixels of the device and they must extend no further than half of the width of the action bar.

Feel free to file a bug on http://b.android.com if you feel that it should behave more like the split action bar when both the icon and the title are hidden. Link to it here if you do so I can star it.
