### ISSUE TITLE
Support Setting UI Options Programmatically

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#278]
Currently not exposed when using a base activity.

**Comment by JakeWharton** [comment]
Pick one:
- `supportSetUiOptions(..)`
- `setSupportUiOptions(..)`
- `setUiOptions(..)`
- `getSupportWindow().setUiOptions(..)`

as executed in the context of the Sherlock activities?

**Comment by naoak** [comment]
I'll support any of your decisions.
If I had to choose one, `getSupportWindow().setUiOptions(..)` or `setSupportUiOptions(..)` is better.

**Comment by xeigen** [comment]
So which one of the four did you implement? I cant find any method related to setUiOptions..

**Comment by JakeWharton** [comment]
`getSherlock().setUiOptions(...)`

**Comment by xeigen** [comment]
My bad, i did try getSherlock() before posting here but doesnt match any method, turns out its due to the version that i'm using (RC1)..its working great with the 4.0 release, thanks for the answer anyway..
