### ISSUE TITLE
Action bar dimensions defined differently than in ICS

### ISSUE THREAD

**Issue by mattcoz** [JakeWharton/ActionBarSherlock#292]
Dimensions for the action bar and buttons are defined in the following folders and they shouldn't be:

values-large-land
values-large-land-hdpi
values-large-mdpi
values-xlarge

In ICS they are defined only in these folders

values
values-land
values-sw600dp

This is causing the action bar to be sized incorrectly on 7" tablets like the original Galaxy Tab.

**Comment by JakeWharton** [comment]
The 'sw' qualifier is only available on 3.2+ which means we have to do our
best to fake it using the old crappy filtering.

I'm open to additional filters to try and emulate the correct behavior. I'd
like to get "correct" behavior on pre-3.0 devices that are popular. The
Kindle Fire, Nook Touch, and original Galaxy Tab probably will have the
largest market share.

What is the screen size (normal, large, xlarge), density (mdpi, hdpi,
xhdpi), and exact resolution of that Tab?
On Feb 18, 2012 4:05 PM, "Matt Cosentino" <
reply@reply.github.com>
wrote:

**Comment by JakeWharton** [comment]
Also what do you mean by 'incorrectly sized'? Is it 48dp and you think it
should be 56dp or is it 56dp and you think it should be 48dp? Or are you
referring to it in landscape?

**Comment by mattcoz** [comment]
Oh, I see, that makes sense.  The Tab is large, hdpi, and has a resolution of 1024x600.  I believe that the reason they use sw600dp is for devices this size that use mdpi, like the Kindle and Nook, so using large-mdpi and xlarge should be pretty close.  It is the other two that are causing the problem on the Tab, especially large-land-hdpi which makes the action bar 56dp when it should be 40dp.  Unfortunately large-mdpi would then incorrectly match some cheap 7" tablets that have a resolution of 800x480, but I guess it can't be perfect.

**Comment by JakeWharton** [comment]
Check this logic for portrait/landscape configurations please:

Default: `values` @ 48dp and `values-land` @ 40dp
Large: `values` @ 48dp and `values-large-land` @ 48dp
Large MDPI: `values-large-mdpi` @ 56dp and `values-large-land` @ 48dp (e.g., Nook Color and Kindle Fire)
Large HDPI: `values-large-hdpi` @ 56dp and `values-large-land` @ 48dp (e.g., original Galaxy Tab)
Xlarge: `values-xlarge` @ 56dp (e.g., XOOM)
3.2+: `values-sw600dp` @ 56dp

**Comment by mattcoz** [comment]
That's still not right.  The Galaxy Tab should be using `values` and `values-land` and the Nook and Fire should be using `values-sw600dp`.  56dp on the Tab is huge.  `values-large-land` and `values-large-hdpi` should be removed.  Honestly, I think 48dp for the Nook and Fire in landscape would be better, but that's not what ICS uses.

**Comment by JakeWharton** [comment]
If I remove `values-large-hdpi` you'll get 48dp in both portrait and landscape.

_edit_: I'm not so concerned about what matches ICS in this regard as to what looks right on the popular pre-3.0 tablets.

**Comment by SimonVT** [comment]
I guess the problem is that it translates 56dp into 84px, instead of the correct 56px if it had reported itself as mdpi.

**Comment by mattcoz** [comment]
I guess it comes down to your definition of what looks right.  I'll just change it in my code to match ICS.

**Comment by JakeWharton** [comment]
Why didn't Samsung just update the OS to fix their screw-up in the first place?

**Comment by JakeWharton** [comment]
http://realmike.org/blog/2010/12/21/multiple-screen-sizes-with-processing-for-android/

> Apparently, that’s also what Samsung found when they made the Galaxy Tab. The Galaxy Tab has a 7″, 1024×600 screen with 170 dpi. Yet, the Tab does not report its density as “mdpi” but as “hdpi”, so the layout looks exactly as in the second screenshot. If they used “mdpi”, the icons would be .28″ wide, with “hdpi”, they are .42″ wide—not a big deal, and I must admit, the layout does look prettier this way.

http://android-developers.blogspot.com/2010/09/screen-geometry-fun.html

> Similarly, the Galaxy Tab’s screen is at the large end of “large”, so declaring it as high-density applies a useful compensation.

Meh. Crappy pre-3.0 tablets cause nothing but problems...

**Comment by iNoles** [comment]
if you use just values-large, would it be work with Nook Color, Kindle Fire and Galaxy Tab?

**Comment by JakeWharton** [comment]
Yes but the Nook and the Kindle look good with a 56dp action bar because they're MDPI. We put them at 48dp in landscape because they _just_ don't have the room for 56dp in that configuration.

The Galaxy Tab and its HDPI looks like complete crap at 56dp because of scaling so we knock it down to 48dp in the portrait case.

The key here is getting things to look right on these devices because there will be a lot of them. I'm sure there are plenty of other pre-3.0 tablets where the action bar may be slightly too large or slightly too small but their case is insignificant since they have no market share (and the difference isn't really that bad since the whole OS looks like crap on them anyways).

**Comment by iNoles** [comment]
But, I see values-large-mdpi and values-large-hdpi have 56 dpi or I miss something here.

**Comment by mattcoz** [comment]
I didn't think it was a screw-up but a design decision.  What's interesting though is that both the Galaxy Tab 7.0 and Galaxy Tab 2 use MDPI, so for whatever reason they changed their mind.

If you think the Nook and Kindle don't have enough room for 56dp in landscape, why would you think the Tab would have enough room for 48dp?  56dp on the Nook/Kindle is 56px while 48dp on the Tab is 72px.  This is why ICS's use of 40dp looks better on the Tab.

**Comment by JakeWharton** [comment]
Yeah this needs a second look. Thinking back I was doing the pixel math wrong in my head because of the different DPI.
