### ISSUE TITLE
Pre-3.0: Spinner takes up entire available width in list mode

### ISSUE THREAD

**Issue by petar-bogdanov** [JakeWharton/ActionBarSherlock#295]
Steps to reproduce:
1. Create any activity with list navigation, for example:
///......
    String[] ROOT_VIEWS = {"Some view", "Other view"}; 
        ActionBar actionbar = getSupportActionBar();
        actionbar.setNavigationMode(ActionBar.NAVIGATION_MODE_LIST);
        ArrayAdapter<String> adapter = new  ArrayAdapter<String>(this, R.layout.abs__simple_spinner_item, ROOT_VIEWS);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        actionbar.setListNavigationCallbacks(adapter, this);
///.......
2. Run in Android 2.2 simulator 
3. Title is gone
4. Run in android 4.0 simulator
5. Title is there

This hides any actionbar element, except the home icon, and not only the title.

**Comment by JakeWharton** [comment]
The current released version of ActionBarSherlock (v3) was developed before ICS was a blip on anyone's radar and as such accounted for the lack of space on phones differently than the Android team chose to. The next major version (which is only about two weeks away) is a backport of the ICS action bar including all of its behavior. It properly mirrors the behavior of the native ICS action bar on small devices when dealing with list navigation and titles. Keep and eye out for it or [try the betas](http://beta.abs.io/).

**Comment by petar-bogdanov** [comment]
I wish this had been advertised:

On 02/22/2012 07:07 AM, Jake Wharton wrote:

> The current released version of ActionBarSherlock (v3) was developed before ICS was a blip on anyone's radar and as such accounted for the lack of space on phones differently than the Android team chose to.
> The next major version (which is only about two weeks away) is a backport of the ICS action bar including all of its behavior. It properly mirrors the behavior of the native ICS action bar on small devices when dealing with list navigation and titles. Keep and eye out for it or [try the betas](http://beta.abs.io/).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/JakeWharton/ActionBarSherlock/issues/295#issuecomment-4098310
> I'll definitely try it. How is it, stability-wise? Would you chance 
> releasing an application with it?

## 

Petar Bogdanov
Software developer

MentorMate
2101 Hennepin Avenue S, Suite 202
Minneapolis, MN 55405 USA

mobile: +359878611948
skype: mentormate_petar.bogdanov

www.mentormate.com http://mentormate.com

```
<http://mentormate.com>
```

This e-mail may contain confidential and/or privileged information. If 
you are not the intended recipient (or have received the e-mail in 
error) please notify the sender immediately and delete this e-mail. 
Thank you.
