### ISSUE TITLE
Hiding the ActionBar doesn't restore menu items

### ISSUE THREAD

**Issue by GeorgeBills** [JakeWharton/ActionBarSherlock#300]
I have a menu item which is showAsAction="always":

```
<item
    android:id="@+id/search"
    android:title="@string/menu_search"
    android:icon="@android:drawable/ic_menu_search"
    android:showAsAction="always" />
```

In my Activity I hide the ActionBar in landscape mode:

```
    ActionBar ab = getSupportActionBar();
    int orientation = getResources().getConfiguration().orientation; 
    if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
        ab.hide();
    }
```

I would expect the search menu item to now show up back in the menu button menu, as there is no longer any ActionBar for it to display in. Instead, I lose the search button completely.

The workaround is to check the orientation in onCreateOptionsMenu() and instantiate different menus based on whether we're in portrait or landscape.

**Comment by JakeWharton** [comment]
Are you using version 3 or the version 4 betas?

**Comment by GeorgeBills** [comment]
According to the AndroidManifest.xml - Version 3.5.1, version code 55.

**Comment by JakeWharton** [comment]
I'm fairly certain this is the correct behavior though. The action bar still exists which is why it is being used as the target for the menu items. If you wanted to remove the action bar altogether you would have to request the window `NO_TITLE` feature.

**Comment by GeorgeBills** [comment]
Sorry about the late reply - I'm requesting FEATURE_NO_TITLE (from com.abs.view.Window) and everything's working correctly. I guess "hide" is just for temporary hiding? Either way, works now and thanks for the help.
