### ISSUE TITLE
ShareActionProvider causes split action bar to take up the whole screen

### ISSUE THREAD

**Issue by nelenkov** [JakeWharton/ActionBarSherlock#303]
I am trying to use a ShareActionProvider with a split action bar. I have a simple wrapper that uses the ABS ActionProvider base class instead of the SDK one:

http://code.google.com/p/wwwjdic/source/browse/branches/2.0/wwwjdic/src/org/nick/wwwjdic/actionprovider/ShareActionProvider.java

The menu looks like this:

http://code.google.com/p/wwwjdic/source/browse/branches/2.0/wwwjdic/res/menu-v11/example_breakdown.xml

When I open the activity, the bottom (split) AB takes up the whole height. I tried removing the the theme declaration from the manifest, but that doesn't change anything. 

(BTW, I tried to port ShareActionProvider to 2.x, but even though it sort of works, it just looks out of place on 2.x. Additionally there's too much stuff that needs to be pulled in.)

**Comment by jgilfelt** [comment]
I believe this is a framework issue:

http://stackoverflow.com/questions/9162521/shareactionprovider-with-a-split-actionbar

**Comment by JakeWharton** [comment]
FYI I have a port started in the `share-action-provider` branch which is nearly complete to work with ABS v4. Hopefully I'll get some time after the 4.0 release to finish it up (maybe as a plugin).

And I'd agree this looks like a platform bug. Feel free to file on http://b.android.com and post a link here so I can track it. Perhaps if the aforementioned backport is completed we can solve the bug in our version.

**Comment by jgilfelt** [comment]
Platform bug report filed: http://code.google.com/p/android/issues/detail?id=26027

The only workaround I've found is to force it into overflow with `android:showAsAction="never"`. That seems not to break the lower action bar layout.

**Comment by nelenkov** [comment]
Thanks. I've starred the platform issue and will have a look at the share-action-provider branch when I get some more time.

**Comment by scottkennedy** [comment]
https://github.com/JakeWharton/ActionBarSherlock/pull/503

I'm submitting the same thing to Google.

**Comment by friscoMad** [comment]
Just FYI I found you fixed this on dev but I was able to fix it without resource changes in this 2 commits: b2c18a9d175f9092f928dcbda7a5971ab31d6b6b
4bbfacb16e72dd7c827c929ca53aba66c09c2e1c

Not sure if the rebase is fully needed but it seemed to fix several glitches on layout changes also.

**Comment by tinspu** [comment]
Some how creating a share history file fixes this issue  

this can be fixed by using a custom share history file on app install.

e.g. call CreateShareHisotryFile() on App Create()

```
 public class YourBrokenAPP extends Application {

      public static SHARE_HISTORY_FILE_NAME = "c_share_hist.xml";

     @Override
     public void onCreate() {
         super.onCreate();  
         CreateShareHisotryFile(); 
     }

     private void CreateShareHisotryFile() {

        String data = "<?xml version='1.0' encoding='UTF-8' standalone='yes' ?> "+
                     "<historical-records>" +
                      "<historical-record activity=\"com.google.android.apps.plus/com.google.android.libraries.social.gateway.GatewayActivity\" time=\"1426500217970\" weight=\"1.0\" />"+
                "</historical-records>";
        try {
            OutputStreamWriter outputStreamWriter = new     OutputStreamWriter(openFileOutput(SHARE_HISTORY_FILE_NAME, Context.MODE_PRIVATE));
             outputStreamWriter.write(data);
            outputStreamWriter.close();
        }
        catch (IOException e) {
            Log.e("Exception", "File write failed: " + e.toString());
        } 
    }
```

then on the fragments on onCreateOptionsMenu use share hist file we just created ....

```
     @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
         inflater.inflate(R.menu.main, menu);

      // Set up ShareActionProvider's default share intent
        MenuItem shareItem = menu.findItem(R.id.action_share);
        mShareActionProvider = (ShareActionProvider)
               MenuItemCompat.getActionProvider(shareItem);
        mShareActionProvider.setShareHistoryFileName(c_share_hist.xml);
    }
```

then it's all good
ENJOY.......
