### ISSUE TITLE
ForceOverflow theme not working on ICS device

### ISSUE THREAD

**Issue by Goddchen** [JakeWharton/ActionBarSherlock#304]
Hey everyone,
i'm trying to use the Theme.Sherlock.ForceOverflow theme:

styles.xml

```
<style name="MyTheme" parent="@style/Theme.Sherlock.ForceOverflow"></style>
```

AndroidManifest.xml

```
<application
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/MyTheme" >
```

It is working fine in an Android 2.1 emulator but on my ICS (4.0.3) phone it simply doesn't work and the normal behaviour is still present (press menu button to show overflowed menu items on the bottom of the screen).

Any ideas what might be wrong on my side or whether this is a bug?

Goddchen

**Comment by SimonVT** [comment]
It uses the native actionbar on ICS, which has no way to force the overflow icon.

**Comment by JakeWharton** [comment]
Force overflow only works on pre-ICS. The native action bar is used on 4.0
and up and its behavior in this manner cannot be controlled.
On Feb 25, 2012 11:02 AM, "Goddchen" <
reply@reply.github.com>
wrote:

**Comment by Goddchen** [comment]
ok i see, thanks

**Comment by lnanek** [comment]
Disappointing change. Users have no clue the menu options exist without this. They don't try to hit the menu button on every activity they go to. I've even seen developers posting about wanting functionality that they think doesn't exist in the Market app that was hidden behind the menu button. So even power users don't check.
