### ISSUE TITLE
requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by ericklee** [JakeWharton/ActionBarSherlock#310]
When using `requestWindowFeature()`, it works fine when the activity is first started.

Then I press the home key, so that the activity becomes stopped.
And after 1 minute I go back to the activity, following exception will occur.

`AndroidRuntimeException: requestFeature() must be called before adding content
at com.actionbarsherlock.internal.ActionBarSherlockCompat.requestFeature(ActionBarSherlockCompat.java:618)`

Sample codes:

```
public class Sample extends FragmentActivity {

public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
        setSupportProgressBarIndeterminateVisibility(false);
        setContentView(R.layout.main);
}

}
```

**Comment by talklittle** [comment]
On ActionBarSherlock 3.5.1 I got around this by moving requestWindowFeature() before the super.onCreate() call.

**Comment by keyboardr** [comment]
I get the same issue when doing orientation changes on Gingerbread

**Comment by JakeWharton** [comment]
Recommending any `requestWindowFeature` calls are done before `super.onCreate` calls. This ensures nothing will have triggered decor view creation.
