### ISSUE TITLE
Navigation list's popup not readable on Pre 3.0

### ISSUE THREAD

**Issue by MrArtichaut** [JakeWharton/ActionBarSherlock#314]
On Pre 3.0, the popup window opened when clicking on the navigation list has its text in white on a white background (with default Sherlok Light Theme). So the entries aren't visible.

**Comment by JakeWharton** [comment]
Is this for the v4.0 betas or v3.x.

If it's for 4.0, there is an example which shows you how to work around this in the 'demos' sample.

**Comment by JakeWharton** [comment]
Fixed for `4.0-wip`
