### ISSUE TITLE
Collapsed Tab Navigation has wrong text color

### ISSUE THREAD

**Issue by ericklee** [JakeWharton/ActionBarSherlock#315]
4.0.0 RC1

using Theme.Sherlock

Tested on 2.1 emulator and 2.3 device

![Alt Text](http://i39.tinypic.com/vhzsdv.jpg)

**Comment by Sleepybear** [comment]
Same as issue #314

**Comment by JakeWharton** [comment]
Yeah this is arguably a platform bug but it's not like it can be fixed (old platforms). Take a look at the '[List Navigation](https://github.com/JakeWharton/ActionBarSherlock/blob/4.0-wip/samples/demos/src/com/actionbarsherlock/sample/demos/ListNavigation.java#files)' example in the demos sample for how to get around this styling limitation.

**Comment by ericklee** [comment]
But the list is generated by the library.

It is a tab navigation when there is enough room for the tabs.

**Comment by Sleepybear** [comment]
It's the way the framework does the default styling. In order to have it correct you need to style it manually

**Comment by ericklee** [comment]
Can I explicitly define the list layout only?

Or do I need to create a separate adapter which includes all items to handle it?

**Comment by JakeWharton** [comment]
So you're using tabs but in this case there are so many that it has collapsed it down to a list?

**Comment by ericklee** [comment]
Yes.
