### ISSUE TITLE
Crashes if a sub-menu is added and 'showAsAction' is not set on the su-menu

### ISSUE THREAD

**Issue by guidedways** [JakeWharton/ActionBarSherlock#318]
The following XML causes ActionBarSherlock to crash while parsing showAsAction (as it can't find it):

<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item
            android:id="@+id/menu_delete"
            android:title="@string/delete"
            android:icon="@drawable/ic_action_delete"
            android:showAsAction="always"
            >
        <menu>

```
        <item android:id="@+id/delete_confirm"
              android:title="@string/delete"
              android:icon="@drawable/ic_action_deletelight" />

        <item android:id="@+id/cancel_delete"
              android:title="@string/cancel"
              android:icon="@drawable/ic_action_cancellight" />
    </menu>
</item>
```

</menu>

I then added 'android:showAsAction="never"' to the sub-menus and the crashing stopped.

**Comment by JakeWharton** [comment]
Dupe #317.
