### ISSUE TITLE
Split ActionBar with ViewPager stops responding on page change

### ISSUE THREAD

**Issue by barees63** [JakeWharton/ActionBarSherlock#324]
Hi there,

I have attached a very simple project which illustrates the problems I'm seeing on android 2.3.7 (CM) with ABS RC 1 (and also WIP 4.0)

If you run the app in portrait and touch the icon on the ActionBar you'll see a sub menu, if you swipe to the next fragment the ActionBar  is now apparently unresponsive no matter which page you swipe to (if you switch to landscape at this point you'll actually see the missing sub menu).

In landscape mode everything works normally, if you remove splitActionBarWhenNarrow it all works fine.

The eclipse project is here: http://dl.dropbox.com/u/3822661/ABSTest.zip

Hope it helps!
Bruce

**Comment by JakeWharton** [comment]
You didn't happen to try with the latest from the 4.0-wip branch did you? I'm pretty sure we solved this with a completely rewritten `IcsLinearLayout` class. If not, I will over the weekend...

**Comment by barees63** [comment]
I used the library project  from WIP 4.0 but the support jar from RC1

**Comment by Sleepybear** [comment]
Using your provided project, if I switch FragmentActivity and Fragment for SherlockFragmentActivity and SherlockFragment, respectively, I get the correct behavior expected with no unresponsive menus. Are you sure you're using the latest from the 4.0-wip branch as well as the correct imports from the support-lib?

**Comment by barees63** [comment]
OK, you're right.. my apologies for the confusion, using Sherlock\* classes the original problem is gone.  

I do see a problem if I use the configChanges attribute to bypass the default orientation handling, then the ActionBar loses its items if you change to landscape and switching back to portrait leaves the AB unresponsive on all pages again.. not sure if this is an issue or just the way things are?

**Comment by JakeWharton** [comment]
There is another issue already for handling config changes and I really
hope to resolve it before 4.0. You should only be doing that as a very last
resort as per the official documentation. I highly suggest you make every
attempt to avoid such a requirement, if possible.
On Mar 2, 2012 7:58 PM, "barees63" <
reply@reply.github.com>
wrote:

**Comment by barees63** [comment]
No problem, thanks for your responsiveness and good luck with the release.. it's looking really nice :)
