### ISSUE TITLE
Tabs appear above ActionBar when calling setDisplayShowHomeEnabled(false)

### ISSUE THREAD

**Issue by plackemacher** [JakeWharton/ActionBarSherlock#327]
When you call setDisplayShowHomeEnabled(false) in onCreate() and are using a tab navigation mode, the tabs will appear above the action bar as opposed to below it.

This bug can be replicated in the sample from the latest code in the repository. It was tested with an HTC Desire running Android 2.2 and a Motorola Droid RAZR running a CM9 alpha build (ICS 4.0.3).

Just throw setDisplayShowHomeEnabled(false) somewhere in the onCreate function in the tab navigation sample.

**Comment by plackemacher** [comment]
I'm a little bit new to GitHub. FYI: This applies to the 4.0-wip branch.

**Comment by JakeWharton** [comment]
This is how the native action bar behaves. I have no explanation for it. I have no idea whether it was an intentional design decision or not. We mimic what the native action bar does...

I'm sure it was part of the collapsed tab navigation feature but it seems odd to me too. Either hide the home icon and the title or show both to avoid this behavior. You can file a bug on http://b.android.com if you think the behavior is incorrect and feel free to paste the link here if you do.

**Comment by JakeWharton** [comment]
Welcome to GitHub then :)  This place is awesome.

**Comment by cocoahero** [comment]
I am also experiencing this weird defect with the action bar. I opened an issue on the android bug tracker and can be found here: http://code.google.com/p/android/issues/detail?id=36191

Hopefully we will get a definite answer on whether or not this is desired behavior. I for one hope it is a bug.

**Comment by chaturadilan** [comment]
Create a 1px \* 1px .png image and name it noimage.png upload it to your drawable folder and set

getSupportActionBar().setIcon(R.drawable.noimage);

in the action

**Comment by thomas-marchaud** [comment]
Hi. Just found a simple workaround.

use the following in your onCreate method :

View homeIcon = findViewById(android.R.id.home);
((View) homeIcon.getParent()).setVisibility(View.GONE);

this collapses the home button completely.

PS : i'm using standard ActionBar but this should work the same

**Comment by wojanek** [comment]
Hellol I had the same problem i solved it with this code .

```
    actionBar.setLogo(null); // forgot why this one but it helped

    View homeIcon = findViewById(
            Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB ? 
            android.R.id.home : R.id.abs__home);
    ((View) homeIcon.getParent()).setVisibility(View.GONE);
    ((View) homeIcon).setVisibility(View.GONE);

    actionBar.setDisplayShowTitleEnabled(false);
```

well its like this because in PRE HONEYCOMB there is no android.R.id.home resource.

**Comment by czechnology** [comment]
The problem with these workarounds is that the title doesn't work as a "Up" button like it does when `setDisplayShowTitleEnabled` is set.

**Comment by makovkastar** [comment]
Or you can use this code: <code> actionBar.setLogo(new ColorDrawable(Color.TRANSPARENT)); </code>

**Comment by Leandros** [comment]
Is there a workaround, where the icon / logo is hidden but the title can act as Up button?

**Comment by chunyan** [comment]
This is an old topic but I would like to add one comment about a caveat. The workaround only works if you display options enable DISPLAY_SHOW_HOME. So if for some reason you set your action bar's display options to something else, you need this line: 
        getSupportActionBar().setDisplayOptions(ActionBar.DISPLAY_SHOW_HOME | your_other_settings);

**Comment by arunantoney** [comment]
All workaround that post above collapsing the home icon but leaving a blank space. For avoiding that you need to set the logo size to zero . Below added my code snippet

```
actionBar.setLogo(new ColorDrawable(Color.TRANSPARENT));

          View homeIcon = findViewById(
                    Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB ? 
                    android.R.id.home : R.id.abs__home);
            ((View) homeIcon.getParent()).setLayoutParams(new LinearLayout.LayoutParams(0, 0));
            ((View) homeIcon).setVisibility(View.GONE);
```

**Comment by AruntejaMididoddy** [comment]
This worked perfectly fine for me...in all devices
getActionBar().setDisplayOptions(-1, ActionBar.DISPLAY_SHOW_CUSTOM | ActionBar.DISPLAY_SHOW_HOME);
