### ISSUE TITLE
Ugly EditText inner padding with wip-4.0 on Gingerbread

### ISSUE THREAD

**Issue by ginkel** [JakeWharton/ActionBarSherlock#329]
When declaring my application's theme as `android:theme="@style/Theme.Sherlock.Light.DarkActionBar"`, the inner padding of EditText views is not what one would expect for the Gingerbread layout: The text is not vertically centered and too close to the left border of the view. For details, refer to this screenshot (while this has been taken on a device running HTC Sense the effect is also visible on AOSP): https://secure.tgbyte.de/dropbox/Quuidae8.png

This is the EditText declaration I am using:

```
<EditText android:id="@+id/username" android:hint="User Name" android:layout_width="fill_parent" android:layout_height="wrap_content" android:padding="4dp" android:inputType="textEmailAddress"/>
```

**Comment by JakeWharton** [comment]
You're setting the padding yourself as 4dp on all sides which is why you're seeing the collapse on the left and right. There is already a default padding set on the widget which you're overriding.

**Comment by ginkel** [comment]
You are absolutely right. Exchanging the padding for a layout_margin fixed the problem. Thanks a lot!
