### ISSUE TITLE
Calling MenuItem.setVisible( false ) seems to have no effect

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#33]
Release 3.0.2

A call to _com.actionbarsherlock.internal.view.menu.MenuItemImpl.setVisible( false )_ seems to be without effect. If the MenuItem was shown in the ActionBar, it is still visible after a call to _setVisible( false )_ and a call to _android.support.v4.app.FragmentActivity.invalidateOptionsMenu()_.

**Comment by JakeWharton** [comment]
This is a consequence of me writing my own view mechanism for menus. In the `native-backport` branch I copy the method used by Android which updates any views associated with menu items as methods are called on them. This is the functionality which allows you to hold on to `Menu` and `MenuItem` instances beyond creation and affect how they are displayed.

I will do my best to port this functionality into the upcoming 3.1 release scheduled in the next few days. It might have to be pushed to a 3.1.1 release if I cannot do it in time or simply cannot find the time.

**Comment by JakeWharton** [comment]
Re-opening and changing to milestone 3.2. The release of Android 3.2 SDK and compat lib r3 delayed this. Sorry.

**Comment by drsoran** [comment]
Regarding Release 3.1.0:

Does this issue still involves the fix for not calling onPrepareOptionsMenu()? See https://groups.google.com/group/actionbarsherlock/browse_thread/thread/9b71ee3d77f27323

Otherwise there is no chance to initialize an exclusive checkable SubMenu to the correct state.

**Comment by JakeWharton** [comment]
The MenuItem-related fixes that I told you would be in 3.1 unfortunately did
not make the cut. With the recent release of the Android 3.2 OS (and its
SDK) as well as the third revision of the official compatibility library it
was simply too much. The support for it was almost completed prior to the
release of the two aforementioned items so I assure you it's not far off. I
realize that a lot of people are dependent on this as I have gotten numerous
questions related to it. I am still pedal to the floor on development as I
have a few other features I really want to get integrated (like action
modes).

---

Jake Wharton
http://about.me/jakewharton
On Jul 23, 2011 5:19 AM, "drsoran" <
reply@reply.github.com>
wrote:

**Comment by JakeWharton** [comment]
Released with 3.1.3.
