### ISSUE TITLE
Dropdown illegible on <3.0 devices with dark theme

### ISSUE THREAD

**Issue by app2go** [JakeWharton/ActionBarSherlock#330]
Since "Internalize ICS's Spinner for more elegant pre-3.0 dropdowns" was committed the dropdown with dark theme is illegible on pre-Honeycomb devices (black text on dark grey background, the light theme works well). Tested on a Motorola Atrix and a Nexus One (both on 2.36)

**Comment by JakeWharton** [comment]
Did you follow the 'List Navigation' sample? There are special layouts that must be used.

**Comment by app2go** [comment]
I'm using the sample app included in the 4.0-wip branch (ActionBarSherlock / samples / demos) not my own one. I can send you a screen shot if you need one.

**Comment by JakeWharton** [comment]
Please. All the themes work fine on my N1.

**Comment by JakeWharton** [comment]
Ok here's the image:

![](http://i.imgur.com/UJOdl.jpg)

It looks like you're using `android.R.layout.simple_dropdown_list_item` instead of `R.layout.sherlock_dropdown_list_item`.

Are you sure you've updated the sample app to the latest code? I updated it when I updated the Spinner to be a dropdown.

**Comment by app2go** [comment]
Ok found the problem. FeatureToggles is still using the android.R.layout.simple_spinner_dropdown_item instead of R.layout.sherlock_spinner_dropdown_item (you were referring to ListNavigation that was changed with the commit).
I guess you will do the change? Thanks for your quick answer and solution.

Is there a way to donate some money? I really like your work and it helps me a lot with my current project and I'd like to show my appreciation somehow.

**Comment by JakeWharton** [comment]
Ah! I totally missed that it was the 'Feature Toggles' and not 'List Navigation'. Good eye!

If you'd like to donate, there's a page at http://abs.io/donate. And I thank you in advance :)
