### ISSUE TITLE
IndeterminateProgressBar does not disappear

### ISSUE THREAD

**Issue by navarr** [JakeWharton/ActionBarSherlock#335]
On Pre-ICS devices, using ABS 4.0, calling setProgressBarIndeterminateVisibility(Boolean.FALSE); will not cause the progress bar to disappear under certain conditions.

An example is included:

```
import com.actionbarsherlock.app.SherlockActivity;
import com.actionbarsherlock.view.Window;
import android.os.Bundle;
public class IndetermianteProgressBarAsyncActivity extends SherlockActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);

        setContentView(R.layout.main);
        setProgressBarIndeterminateVisibility(Boolean.TRUE);
        setProgressBarIndeterminateVisibility(Boolean.FALSE);
    }
}
```

It is my theory this is because they are called in quick succession, and although this does not appear to be an issue it can be when using an AsyncTask that _can_ run long, but runs short.

Build Target: 15
minSdkVersion: 7

**Comment by JakeWharton** [comment]
You need to be using setSupportProgressXxx for 4.0. Take a looks at the
demos sample for a full example.
On Mar 6, 2012 11:35 AM, "Navarr Barnier" <
reply@reply.github.com>
wrote:

**Comment by navarr** [comment]
My mistake @.@;
