### ISSUE TITLE
Update ProGuard F.A.Q. To Save @Implementaion Annotation

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#345]

**Comment by SimonVT** [comment]
Keeping annotations is actually the default in ADT17

**Comment by JakeWharton** [comment]
Good to know. For those wondering the following was reported as an addition for now:

```
-keepattributes *Annotation*
```

I'll keep this open until its release and then update the documentation to recommend using ADT 17 only.
