### ISSUE TITLE
Document Forced Overflow Affects Pre-4.0 Only

### ISSUE THREAD

**Issue by k0smik0** [JakeWharton/ActionBarSherlock#348]
Old title: overflow button not always showed with 4.0.x 

Hi, 
i have a strange problem ...
i'm using static attach and Theme_Sherlock_Light_DarkActionBar_ForceOverflow as theme... and if I run app in 2.2/sdk8 emulator, I can see overflow button, in top-right corner and so on - instead, if I run app in 4.0/sdk14 emulator, overflow button doesn't appear, but only "as_action_always" ones.
Is it a bug or i'im missing something?
I'm using dev branch from github.

Here the code for activity:
http://pastebin.com/PzC8vfc4

and here screenshot:
http://imageshack.us/photo/my-images/85/sdk8.jpg/
http://imageshack.us/photo/my-images/205/sdk14.jpg/

Tnx,
Max

**Comment by JakeWharton** [comment]
The action item can only be forced on pre-4.0 (this is noted on the example in the 'Demos' sample). There is no way to control its presence on 4.0 and up. The reason it doesn't show up on the emulator is that it is reporting that it has a hardware menu key. At present, all ICS devices (and likely the vast majority moving forward) will not have a menu key so the action item will always be displayed. It will only be a very, very small minority of devices.

I'll leave this issue open as a reminder to document this on the website for 4.0.1

**Comment by k0smik0** [comment]
Ok, i understood about "no force in 4.x" and "no hardware button and other stuff"... 
but however it is still something strange.... 
i saw in demos, and i found that ActionModes.java: it shows overflow button in emulator sdk14 and in my phone (froyo)... 
and i would my activity like this. so i modified mine, almost exactly as "actionmodes": 

http://pastebin.com/Z1mMzWCf

but overflow button still doesn't appear in sdk14 emulator ;/

[ using "setTheme(R.style.Theme_Sherlock_Light_DarkActionBar_ForceOverflow);" appears in 2.2 emulator (as expecting) ]

what's wrong, now ;/ ?

**Comment by JakeWharton** [comment]
The action bar will always use an overflow item because all of its menu items are relevant to the action mode only. Whereas when you are adding a menu to a full activity, it is understood that you have control of the whole device (which then includes the menu button).

**Comment by k0smik0** [comment]
a full activity is an activity which extends a sherlockactivity ?
i'm using the static attach way 'cause i'll use roboguice, and then i have to extends from roboguice etc.

yes, i know it exists a robosherlockactivity, but static attach "delegate" way seems cleaner, for me.

however, now extends from sherlockactivity:

http://pastebin.com/05vBnNzA

but no overflow button in my activity - and yes in actionmodes ;/

ok, it's 0.51 a.m. - i'm tired and perhaps it's easy to fall in wrong code. i have to sleep.

however, do u find any errors in last code ?
