### ISSUE TITLE
Native ActionBar doesn't respond to the Theme attributes

### ISSUE THREAD

**Issue by thorinside** [JakeWharton/ActionBarSherlock#349]
I read the new documentation on mirroring the theme attributes so that the native action bar becomes themed like the non-native action bar. However, I cannot seem to make my native action bar use a drawable as a background like I can with the non-native action bar. When I run my application on Android 2.3, the actionbar background looks as I have specified, and when on Android 4.0 devices, the colors do not show.

I have something like the following in my themes.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<resources>

    <style name="Theme" parent="Theme.Sherlock">
        <item name="android:actionBarStyle">@style/Widget.Sherlock.ActionBar.ResMD</item>
        <item name="actionBarStyle">@style/Widget.Sherlock.ActionBar.ResMD</item>
    </style>

    <style name="Theme.ResMDActivity" parent="Theme" />

    <style name="Widget.Sherlock.ActionBar.ResMD" parent="Widget.Sherlock.ActionBar.Solid">
        <item name="android:background">@drawable/actionbar_bg</item>
        <item name="android:backgroundStacked">@drawable/actionbar_bg</item>
        <item name="android:backgroundSplit">@drawable/actionbar_bg</item>

        <item name="background">@drawable/actionbar_bg</item>
        <item name="backgroundStacked">@drawable/actionbar_bg</item>
        <item name="backgroundSplit">@drawable/actionbar_bg</item>
    </style>

</resources>
```

As you can see I have both the `<android:name>` and the one that the non-native uses. My actionar_bg.xml is:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<shape
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">

    <gradient
        android:angle="-90"
        android:startColor="@color/actionbar_start"
        android:endColor="@color/actionbar_end"/>

</shape>
```

And I have a couple of colors in colors.xml:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="actionbar_start">#F00</color>
    <color name="actionbar_end">#000</color>    
</resources>

```

When I run the app on Android 4.0, the red gradient doesn't show up. But on Android 2.3, it does. What am I doing wrong?

**Comment by thorinside** [comment]
I've tried the sample app, and it seems to be working as advertised. I'm not sure, yet, how my application gets confused. Still looking, this may indeed be an issue somewhere in my code.

**Comment by thorinside** [comment]
Okay, yes, it was a problem with my code. It was so embarassing that I'll keep the details to myself. Oh, by the way (to change the subject quickly) thanks so much for all of your hard work on ABS. You are, indeed, the man (and I am not).

**Comment by JakeWharton** [comment]
Haha well you're welcome. Glad you were able to get it resolved. I'm stil waiting on who's going to be the first to report some major oversight on my part.

_*knocks on wood*_
