### ISSUE TITLE
FragmentActivity.onCreate() involves menu creation

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#35]
Release 3.0.2

A call to _android.support.v4.app.FragmentActivity.onCreate(Bundle)_ creates the options menu in the same call by calling _invalidateOptionsMenu()_. See line 327. 

In my case this causes problems cause I create my options menu depending on the fragment configuration, which is created during _FragmentActivity.onCreate()_ of my concrete type. Either from the stored instance state or a default configuration. But I have to call through _super.onCreate()_ which calls _invalidateOptionsMenu()_ which synchronously calls _onCreateOptionsMenu()_ before I had a chance to create my configuration.

One suggestion: Wouldn't it be better if _invalidateOptionsMenu()_ calls _onCreateOptionsMenu()_ asynchronous by scheduling a message  to the Handler?

**Comment by JakeWharton** [comment]
I've ported more work from the `native-backport` branch which addresses this activity lifecycle issue. The action bar is now not initialized until you call `setContentView()` in the activity or `commit()` a fragment transaction. Once the action bar is attached, an initial `invalidateOptionsMenu()` is performed. If you are committing a fragment transaction an additional invalidation will occur again once the asynchronous attachment has completed.

This should hopefully allow you to perform your operations before the call to one of the two above methods. Please report back any troubles you find with it as I have only done fairly simple testing so far.
