### ISSUE TITLE
Home button not clickable

### ISSUE THREAD

**Issue by rock3r** [JakeWharton/ActionBarSherlock#356]
I'm using static attachment in an Activity, and I found that the Home button isn't clickable "out of the box". This behaviour was present in RC1 as well but I did not have time to report it, but now I updated to 4.0 final and I still see the same issue.

This is the code I have to use to initialize the ActionBar in onCreate:

```
private void initializeABS() {
    mSherlock.requestFeature((int) com.actionbarsherlock.view.Window.FEATURE_INDETERMINATE_PROGRESS);
    mSherlock.setContentView(R.layout.device_list);

    // Workaround to get a clickable Home button
    mSherlock.getActionBar().setDisplayShowHomeEnabled(true);
    mSherlock.getActionBar().setDisplayHomeAsUpEnabled(true);
    mSherlock.getActionBar().setDisplayHomeAsUpEnabled(false);

    mSherlock.setProgressBarIndeterminate(true);
    mSherlock.setProgressBarIndeterminateVisibility(false);

    mSherlock.setTitle(R.string.select_device);

    // This is a workaround for http://b.android.com/15340 from http://stackoverflow.com/a/5852198/132047
    if (!ImSyncApplication.isICS()) {
        BitmapDrawable bg = (BitmapDrawable) getResources().getDrawable(R.drawable.bg_striped);
        bg.setTileModeXY(Shader.TileMode.REPEAT, Shader.TileMode.REPEAT);
        mSherlock.getActionBar().setBackgroundDrawable(bg);
    }
}
```

What am I missing? I kinda copy-pasted the ABS-related code from the demos...

**Comment by JakeWharton** [comment]
setHomeButtonEnabled?

If you target 14+ its disabled by default.
On Mar 9, 2012 7:37 AM, "Sebastiano" <
reply@reply.github.com>
wrote:

**Comment by rock3r** [comment]
Yup, that is the target and that call does indeed enable the Home button. It's just the most obvious thing, the one that I tend to rule out, that works in the end. Sorry I wasted your time, just dodn't know it's disabled by default (I'm used to v3.x and assumed it's enabled by default). Better add that to documentation, thou.

Thanks again for the great work!

PS: about my indeterminate progress bar and padding/margin, I'm not opening another issue unless you tell me so...

**Comment by JakeWharton** [comment]
Yeah it's still in my inbox. I have quite a backlog as you can imagine
On Mar 9, 2012 7:49 AM, "Sebastiano" <
reply@reply.github.com>
wrote:
