### ISSUE TITLE
Problems installing the library

### ISSUE THREAD

**Issue by Linoxps** [JakeWharton/ActionBarSherlock#362]
First I would like to apologize for my poor English level. I'm starting to develop on Android, and I am a relative novice.
I have problems trying to install the library in eclipse to use for my project. These are the steps I followed:

-First download the latest version of ActionBarSherlock (4.0) and unzip the folder "JakeWharton-ActionBarSherlock-df676ad" in my workspace.
-Then go eclipse and new project/existing source with name "ActionBarSherlock" and sdk15.

And this is the first error it gives me: "AndroidManifest.xml file missing!", so what I did was to copy directly the contents of the folder "library" into "ActionBarSherlock". But I get many errors of imports and override. So I tried to add the external libraries support v4 android at  "ActionBarSherlock" project but nothing change.

I have also tried with "import/existing project into workspace" but it gives me "No project are found to import".

I have ADT and SDK at v16.

Thank for all.

**Comment by navarr** [comment]
I had a problem similar to this.  copying all the code is a good start, as is importing the support-lib.  But you should also make sure that your Java is set to 1.6 instead of 1.5 with the default suppoprt settings.

**Comment by Linoxps** [comment]
I have the Version 6 Update 31.

**Comment by navarr** [comment]
In your eclipse settings though, make sure Java is set to 1.6

**Comment by JakeWharton** [comment]
See: https://groups.google.com/d/topic/actionbarsherlock/4RcYSvW3D3g/discussion

Java settings are at Project Properties > Java Compiter for Eclipse. Ensure they're set to 1.6 like @navarr said.

Questions like this are best for the mailing list going forward.

**Comment by Linoxps** [comment]
Sorry Jake, and Thanks to all, that was the problem. Really thk.
