### ISSUE TITLE
Custom tab view vanishes after orientation change

### ISSUE THREAD

**Issue by shaversport** [JakeWharton/ActionBarSherlock#365]
After setting a custom view on an actionbar tab via setCustomView,  and using 

android:configChanges="orientation|keyboard|keyboardHidden"

and changing screen orientation, the custom icon disappears and will not reappear until the application is completely shutdown and restarted.

**Comment by shaversport** [comment]
This is for abs 4.0

Program that recreate the issue can be found here: http://bit.ly/wIsVLy

**Comment by JakeWharton** [comment]
Closing as part of #279. I **strongly** recommend you avoid handing configuration changes as [per the documentation suggests](http://developer.android.com/guide/topics/manifest/activity-element.html#config). I have some ideas on how to fix this but it's not top priority at the moment.

**Comment by shaversport** [comment]
Hey Jake, Thanks for the recommendation.

I've taken your advice and removed the configChanges but I find that the custom view still disappears after an orientation change.  Since this happens in ICS as well, this is not an ABS problem.  (Differently than before, the view will reappear if I rotate back.) Can you think of any reason the custom view would not be shown?  Is this an android bug?

Thanks.

**Comment by shaversport** [comment]
Just upgraded to 4.1 and I don't have this issue with abs or 4.0 anymore.  Does that make any sense at all?

**Comment by JakeWharton** [comment]
Nope. But I'll allow it!

**Comment by shaversport** [comment]
No, it doesn't make sense!

Sorry, last  comment was incorrect.  I forgot to first move to the tab with the custom view before doing the orientation.  Doing that shows the problem still exists in abs and in ICS.

**Comment by JakeWharton** [comment]
Why must you toy with my emotions like this! I'll give it another look with config change handling off and see what I can come up with.

**Comment by marianeum** [comment]
Actually, this also happens when the actionbar is not in stacked mode, the search view gets expanded and the tabs no longer fit.
the selected custom tab view disappears, sometimes the tabs change to a list navigation (which is fine) and when i try to change the fragment from there both items disappear and never come back until the activity is being recreated

**Comment by ericps** [comment]
I experience this with ActionBarCompat and customviews, the selected tab disappears on rotation.

seem to have solved it for myself by removing the configChanges from my activity android:configChanges="keyboardHidden|orientation|screenSize"

https://code.google.com/p/android/issues/detail?id=43213

**Comment by pamepros** [comment]
@ericps yes, that's what's breaking the tab, but what if I still want it to rotate ? I still need the line:
android:configChanges="keyboardHidden|orientation|screenSize"
so as to not restart the activity.
