### ISSUE TITLE
Mention SherlockFragment requirement

### ISSUE THREAD

**Issue by commonsguy** [JakeWharton/ActionBarSherlock#368]
The Usage page mentions that your activity needs to inherit from a `Sherlock*` activity class. However, it does not mention that if you inherit from `SherlockFragmentActivity` that you need to have your fragments inherit from `SherlockFragment`. Failing to do that makes your code go "boom".

I suggest adding a sentence about that to the "Action Bar API" section in the Usage page.

**Comment by jdamcd** [comment]
I've been using `SherlockFragmentActivity` with fragments inheriting from the compatibility package `Fragment` without issues. I've only found it necessary to inherit from `SherlockFragment` when the fragment contributes menu items. However, I agree that some clarification on when to use `SherlockFragment` in the docs would be useful.

**Comment by JakeWharton** [comment]
@jdamcd You've already got the answer. The _only_ difference is that the `Sherlock`-prefix fragments allow for use of the menus properly. You'll get a nice runtime exception if you attempt to access them without meeting this requirement. It may be worth noting on the docs, however.
