### ISSUE TITLE
Imports and MenuInflater

### ISSUE THREAD

**Issue by commonsguy** [JakeWharton/ActionBarSherlock#369]
IMHO, `MenuInflater` is likely to be encountered frequently enough that listing it in your Usage page's "Imports" section is probably worthwhile. I am sure there are some people who create their menus purely from Java, but I am willing to be more create their menus as resources, will hit `MenuInflater`, and will need to switch to the Sherlockian version of that class.

**Comment by veeti** [comment]
I think that it would also be a good idea to mention that context menus use the native classes. Confused me for a while when moving over to ABS4.

**Comment by wuman** [comment]
I'm curious as to what led to the design decision to use native classes for context menus.  Isn't it easier for developers to use Menu/MenuItem classes from the same package?

**Comment by JakeWharton** [comment]
@wuman Context menus are very integrated into the platform and it would require a great deal of effort to change them to use the "Sherlockian" versions (to quote @commonsguy). If you're using an IDE it should immediately warn you if you're doing something wrong.

@veeti That is a very good idea indeed. I will include that change along with patch for this issue. I'm going to file a separate issue too for adding an example to the Demos sample to show context menu usage along with action items.
