### ISSUE TITLE
ActionBar menu option text disappearing when clicking on it

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#376]
i am experiencing the following issue:

I have an activity that extends from SherlockFragmentActivity. For that activity I have configured an ActionBar with a navigation list and a menu.  Clicking on the overflow menu icon, I get the dropdown list with all my menu options. When I select one of the menu options a call is made to the onOptionsItemSelected, where I create a new intent and start another activity. What I see on the screen of the device is that the text for the menu option that I just clicked disappears, is not visible any more for a sec before the dropdown list disappears and the content of the new activity is displayed. 

I have built my project with android library 4.0.3. I am using ActionBarSherlock 4.0.0 and in the AndroidManifest.xml I have set:

```
<uses-sdk
    android:minSdkVersion="4"
    android:targetSdkVersion="15" />
```

For my application I am using a theme that extends Theme.Sherlock and I have just changed the following:

<?xml version="1.0" encoding="utf-8"?>
<resources>

```
<style name="Theme.MyTheme" parent="Theme.Sherlock">
    <item name="android:actionBarStyle">@style/MyActionBar</item>
    <item name="android:logo">@drawable/mini_icon</item>
</style>

<style name="MyActionBar" parent="android:Widget.Holo.ActionBar">
    <item name="android:background">@drawable/action_bar_background</item>
</style>
```

</resources>

I have tested everything in a Samsung Galaxy Nexus with Android 4.0.2.

Has someone else experienced this behaviour too? Am I doing something wrong?

Thanks

**Comment by JakeWharton** [comment]
This is a native bug in Android that does not exist in the library (strangely enough). You can observe its behavior in the native apps like GMail.

I had initially assumed it was the `onOptionsItemSelected` blocking the UI thread for a fraction of a second causing the text's state to remain in 'selected' but it doesn't appear to be the case. I guess it has to do with differences between the native `ListPopupWindow` and my backport `IcsListPopupWindow`.

**Comment by ghost** [comment]
Oh true, you are right, I also occurs in the Gmail app. I thought I had
checked , but it apparently I did not :).

Thanks for the prompt answer.

2012/3/13 Jake Wharton <
reply@reply.github.com

**Comment by malacavilla** [comment]
Do you know if there is an issue already logged in the Android Open Source issue list (http://code.google.com/p/android/issues/list)?
