### ISSUE TITLE
No ActionBar implementation found when testing using Robolectric

### ISSUE THREAD

**Issue by scompt** [JakeWharton/ActionBarSherlock#377]
When ActionBarSherlock [looks for an implementation](https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/ActionBarSherlock.java#L194), it bases the decision on the `Build.VERSION.SDK_INT` constant. When running tests using Robolectric, this constant is set to zero, which means no implementation will be found and an exception is thrown:

```
java.lang.IllegalStateException: No implementations match configuration.
```

It'd be great if ABS could detect that SDK_INT is zero and still return an implementation. It probably wouldn't be functional, but it would at least provide something that Robolectric could mock over.

What do you think ABS' behavior should be in this situation? I can whip up a pull request if I know it'll get merged.

Thanks for your work on ABS!

**Comment by JakeWharton** [comment]
Yeah I've been considering making this a plugin for the library. Basically what I have seen done is something like this:

``` java
@ActionBarSherlock.Implementation(api = 0)
public class ActionBarSherlockRobolectric extends ActionBarSherlockNative {
    public ActionBarSherlockRobolectric(Activity activity, int flags) {
        super(activity, flags);
    }

    @Override 
    public void setContentView(int layoutResId) {
        LayoutInflater layoutInflater = LayoutInflater.from(mActivity);
        View contentView = layoutInflater.inflate(layoutResId, null);

        shadowOf(mActivity).setContentView(contentView);
    }

    @Override 
    public void setContentView(View view) {
        shadowOf(mActivity).setContentView(view);
    }
}
```

The you must call `ActionBarSherlock.registerImplementation(ActionBarSherlockRobolectric.class)` in the application setup of your test suite.

I'll leave this open and revisit it soon and decide what the appropriate course of action is.

**Comment by scompt** [comment]
Awesome, that should work good. I'll give it a shot tomorrow.

It'd be nice to have this as a plugin since both ABS and robolectric are best practices for android development. I haven't looked too closely at the plugins, but it'd be cool if there was a roboguice plugin with subclasses for all of the Sherlock classes (SherlockFragment, etc.).

**Comment by Macarse** [comment]
I am also getting this when running my app in 1.6 emulators.

**Comment by JakeWharton** [comment]
@Macarse ABS v4 is 2.1+ only.

**Comment by Macarse** [comment]
@JakeWharton: oh. interesting. Hello android:minSdkVersion="7"!

**Comment by pocmo** [comment]
This approach (registering an implementation for testing) does not work anymore?

Deriving ActionBarSherlockNative fails when it tries to get the native action bar through getActionBar() (Robolectric seems to not support the ActionBar yet). And ActionBarSherlockCompat fails in installDecor(). There are several small issues but at the end it will fail because Robolectric can't load the resources from the library project.

Has anyone managed to use Robolectric in conjunction with ActionBarSherlock (4.1.0) successfully?

**Comment by christopherperry** [comment]
@scompt You could set Build.VERSION.SDK_INT in your test runner, I'm not sure why Robolectric doesn't set this for you based on the info in your AndroidManifest.xml, it is a useful value to set. Several projects I've worked on have logic flows based on Android version. For example, you could set it based on the OS version you built Robolectric against:

``` java
public class CustomTestRunner extends RobolectricTestRunner  { 

    private static final int SDK_INT = Build.VERSION.SDK_INT; 

    public CustomTestRunner(Class<?> testClass) throws  InitializationError { 
        super(testClass); 
    } 

    @Override 
    protected void bindShadowClasses() { 
        super.bindShadowClasses(); 
        Robolectric.bindShadowClass(ShadowSherlockActivity.class); 
    } 

    @Override 
    public void beforeTest(final Method method) { 
            final int targetSdkVersion = robolectricConfig.getSdkVersion(); 
            setStaticValue(Build.VERSION.class, "SDK_INT", targetSdkVersion); 
    } 

    @Override 
    public void afterTest(final Method method) { 
            resetStaticState(); 
    } 

    @Override 
    public void resetStaticState() { 
            setStaticValue(Build.VERSION.class, "SDK_INT", SDK_INT); 
    } 
} 
```

**Comment by JakeWharton** [comment]
At Square we had to do some epic changes to the Robolectric internals to add proper support for non-native menu classes which was a major blocker on this. It works, but it's a huge pain. We may make an effort to upstream this support but we're putting a larger effort behind dropping Robolectric altogether.

For now a simple solution is creating a `ShadowSherlockFragmentActivity` and returning your own instance of an `ActionBar` implementation in `getSupportActionBar()`.

**Comment by christopherperry** [comment]
@JakeWharton I'm curious, what will you be dropping Robolectric for? I know Pivotal had a Robolectric 2.0 that was never released to the public, based on actual implementations of Android but it was far from being released. From what I've seen Robolectric is the only way to do effective TDD on Android. Anything that has to run on an emulator will be useless IMO.

**Comment by JakeWharton** [comment]
Robolectric is too slow and too sparsely (and incorrectly) implemented for our needs. In most cases it ends up slowing down proper testing of controls. It's also a giant hassle to do anything custom (like support ABS MenuItems) to justify its use. We use pure JUnit in most places without any hassle. We have our own, non-generalized solution for running the actual Android code on the JVM which yields much faster results.

**Comment by christopherperry** [comment]
@JakeWharton That's odd, I haven't noticed Robolectric being slow, especially compared to other 'run your tests on the emulator' type solutions. As far as implementation, it's not meant to be an exact duplication of Android and doesn't claim to be. I don't know at what level you are testing things (I tend to test more behavior rather than implementation details), but I've found it to be quite adequate, and I'm pretty grateful for its existence, given that Google didn't give us developers a proper way to unit test our code. Of course you can use straight JUnit on your pojos, but as far as trying to run Android on the JVM I'm at a loss. Care to share your solution?

**Comment by oliver-snowden-phe** [comment]
Hi Jake, this isn't really the forum to be discussing the future of android testing but I am sure many are keen to hear your thoughts...especially with your comments on the sad state of the android build system.  Clearly robolectric could probably do with some love directly from Google.

Obviously you have some great folk at Square and by the sounds of it you are probably using an MVP/controller approach to bypass awkward areas and simplify testing...and possibly enable code sharing between platforms.  Perhaps controllers and DI are all we need...

**Comment by mkarnicki** [comment]
@JakeWharton Hi Jake. I've read elsewhere a comment by you that Square's Robolectric fork is 99.9% in sync with upstream Pivotal Robolectric. Does it mean you no longer regard it as pain/not worth to use for Square needs? If you still think of moving away from Robolectric, I'm quite sure lots of folks here would like to hear you elaborate on "We have our own, non-generalized solution for running the actual Android code on the JVM which yields much faster results." :) Thanks.

**Comment by JakeWharton** [comment]
@MichalKarnicki We're driving a lot of this as a potential Robolectric version 2. It should be available in some form early next year.

**Comment by mkarnicki** [comment]
@JakeWharton Sounds like fantastic news, thank you for your work, Jake!

**Comment by JakeWharton** [comment]
Robolectric 2 is coming soon which doesn't make you want to stab yourself in the face (or at least, not as quickly)! Closing this issue since providing shadows for everything is an awful idea. Use v2 when it comes out.

**Comment by kennedyshead** [comment]
This is not solved by 2.0, as far as I can see anyway

**Comment by JakeWharton** [comment]
Works for me with 2.0-alpha1 if you change your Build.VERSIONS.SDK_INT to 7-13 for the compat impl or 14+ for the native impl.

**Comment by kingori** [comment]
@JakeWharton ABS works well with 2.0-alpha2 when set Build.VERSIONS.SDK_INT to 14. But, when I set Build.VERSIONS.SDK_INT < 14 (I've set it to 10 ) I got this exception. Anyway, test runs well.

```
java.lang.NullPointerException
at      com.actionbarsherlock.internal.ActionBarSherlockCompat.loadUiOptionsFromManifest(ActionBarSherlockCompat.java:1095)
    at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:949)
at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:849)
at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
....
```

I've traced error and I got null from  am.openXmlResourceParser("AndroidManifest.xml") in `ActionbarSherlockCompat.java` , line 1093 and I assumed that I got this exception cause `ShadowAssetManager` in Robolectric does not shadow `openXmlResourceParser()` method. 

Is there any other way to avoid this exception? I think this problem is related to Robolectric, but I think you can give good advice on it.

**Comment by lisawray** [comment]
I just tried 2.0-alpha3 and I'm getting the same error as @kingori.  Has anyone found a solution?

**Comment by denevell** [comment]
I'm also getting a NPE on getSupportActionBar() in 2.1.

**Comment by rossimo** [comment]
I'm setting the `reportSdk` config var to 16, using ABS 4.3.1 & Robolectric 2.1.1. The NPE throws for me as well.

Code:

``` java
package com.example;

import android.os.Bundle;
import com.actionbarsherlock.app.SherlockActivity;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

@RunWith(RobolectricTestRunner.class)
@Config(reportSdk = 16)
public class ActionBarTest {
    private static class ActionBarActivity extends SherlockActivity {
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);

            getSupportActionBar().setTitle("Test");
        }
    }

    @Test
    public void test() {
        ActionBarActivity activity = Robolectric.buildActivity(ActionBarActivity.class).create().get();
    }
}
```

Exception:

``` java
java.lang.NullPointerException
    at com.example.ActionBarTest$ActionBarActivity.onCreate(ActionBarTest.java:19)
    at android.app.Activity.performCreate(Activity.java:5008)
    at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:119)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:256)
    at org.robolectric.util.ActivityController.create(ActivityController.java:114)
    at org.robolectric.util.ActivityController.create(ActivityController.java:126)
    at com.example.ActionBarTest.test(ActionBarTest.java:25)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:241)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
```

**Comment by kennedyshead** [comment]
As Jake stated earlier in this thread the following will work when using getSupportActionBar()

``` java
import android.support.v4.view.ViewPager;
import android.view.View;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;
import org.robolectric.util.ActivityController;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.instanceOf;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

/**
 * Created with IntelliJ IDEA.
 * User: magnusknutas
 * Date: 8/27/13
 * Time: 6:25 PM
 * To change this template use File | Settings | File Templates.
 */

@RunWith(RobolectricTestRunner.class)
@Config(reportSdk = 13)
public class MainActivityTest
{
    @Test
    public void shouldHavePager() throws Exception {
        MainActivity app = Robolectric.buildActivity(MainActivity_.class).create().get();
        ViewPager pager = (ViewPager) app.findViewById(R.id.pager);
        assertThat(pager, instanceOf(ViewPager.class));
    }
}
```

Notice: @Config(reportSdk = 13)

**Comment by shashidhar502** [comment]
i want to use actionbar sherlock even though if the api is greater than 14..
i dont want to use actionbar Native how ?
