### ISSUE TITLE
ActionBar Option Menu item ignores setVisibility(View.VISIBLE) when set invisible in menu resource.

### ISSUE THREAD

**Issue by knaak** [JakeWharton/ActionBarSherlock#380]
ActionBarSherlock v4.0.0 version code 50.
Built against Google API 4.0.3
MinSDK of 10 (my app).

I believe I have found a bug in your implementation.  In my application there is a context sensitive spinner in the action bar menu which is showAsAction always.  I need to dynamically hide/show that spinner depending on the current state of the application.

I have code that checks for whether it should be shown and either calls subUniverseSpinner.setVisibility(View.VISIBLE); or subUniverseSpinner.setVisibility(View.GONE); depending on the situation.

That works fine if the initial android:visible="false" is omitted (default = true) but if I set the initial state of the menu resource as "false" then future calles to setVisibility(View.Visible) are ignored/unsuccessful.

```
<item android:id="@+id/menu_universe" android:actionViewClass="android.widget.Spinner"
      android:showAsAction="always"
      android:visible="false"
      />
```

If I set visible = false here, I can not programmatically Show/Hide the item in code.  If I set it to true, I can control it later.  Problem for me is that initially I should not show it and TabSelected is called before OnCreateOptionsMenu.

**Comment by JakeWharton** [comment]
You should be using [`MenuItem#setVisibility(boolean)`](http://developer.android.com/reference/android/view/MenuItem.html#setVisible%28boolean%29) to re-enable the item. Seems like you are using `View#setVisibility(int)` on the actual action view which has no way of notifying the action bar of its change.

**Comment by kingori** [comment]
I got same problem with ActionBarSherlock v4.1.0 version code 90.
I have two action item and I will show only 1 at a time. 

So I coded like this.

``` xml
<menu xmlns:android="http://schemas.android.com/apk/res/android" >

    <item
        android:id="@+id/menu_1"
        android:showAsAction="always"
        android:title="menu1"
        android:visible="false"/>
    <item
        android:id="@+id/menu_2"
        android:showAsAction="always"
        android:title="menu2"
        android:visible="false"/>

</menu>
```

``` java
@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getSupportMenuInflater().inflate(R.menu.menu_file);
        menu1 = menu.findItem(R.id.menu_1);
        menu2 = menu.findItem(R.id.menu_2);
        return true;
    }

private void toggleOptions( boolean show1) {
 menu1.setVisible( show1 );
 menu2.setVisible( ! show1 );
}
```

In this case, I can not see any menu at all. 

But if I put a dummy action item, it works well.

``` xml
<menu xmlns:android="http://schemas.android.com/apk/res/android" >

 <item
        android:id="@+id/menu_dummy"
        android:showAsAction="always"
        android:title=""
        android:visible="true"/>
    <item
        android:id="@+id/menu_1"
        android:showAsAction="always"
        android:title="menu1"
        android:visible="false"/>
    <item
        android:id="@+id/menu_2"
        android:showAsAction="always"
        android:title="menu2"
        android:visible="false"/>

</menu>
```

``` java
@Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getSupportMenuInflater().inflate(R.menu.menu_file);
            menuDummy = menu.findItem(R.id.menu_dummy);
        menu1 = menu.findItem(R.id.menu_1);
        menu2 = menu.findItem(R.id.menu_2);
        return true;
    }

private void toggleOptions( boolean show1) {
 menuDummy.setVisible( false ); // I don't want to display dummy anymore
 menu1.setVisible( show1 );
 menu2.setVisible( ! show1 );
}
```

**Comment by steveej** [comment]
Why is this issue closed?
I'm still experiening it on v4.1.0

**Comment by veonua** [comment]
still exists =(

**Comment by tasomaniac** [comment]
I had the same problem which @kingori faced. I was not using ABS at all. I did the same thing and it worked.

If at the first time, none of the menuitems are visible in the actionbar, you cannot make them visible afterwards programatically. Thats the problem. And it is not just the problem of ABS. Do you know is there a bug report already filed on Android?

**Comment by kingctan** [comment]
if this problem have any progress,I also meet it,I set a action bar button invisible and can't change it visible programmaticlly later in code.

**Comment by peterdk** [comment]
Are you guys sure you are refreshing the menu itself by calling invalidateoptionsmenu?

**Comment by newairhost** [comment]
I have just occured this as well but without using sherlock so i think it's android itself.

invalidateoptionsmenu doesn't help, for me it make things worst

**Comment by josejuansanchez** [comment]
The problem continues to exist, but the solution proposed by @kingori works well for me. Thanks!

**Comment by chamikarazin** [comment]
invalidateoptionsmenu() doesnt work, Kingori solution works for me!

**Comment by SiarheiAnkuda** [comment]
Kingori solution works for me too :) Thanks!!!

I only want add, that this issue reproduced not only for ABS, but for usual Action bar too

**Comment by gaj-programmer** [comment]
I am also struggling with this issue then I applied a small hack: 

menu1.setEnabled(false);
 menu1.setTitle("");

Then where you want to visible it again : 
 menu1.setEnabled(true);
 menu1.setTitle("Okay"); //or you can set text acording to yours given updated values
