### ISSUE TITLE
LICENSE.txt - copyrights mark missing

### ISSUE THREAD

**Issue by jfsso** [JakeWharton/ActionBarSherlock#381]
I noticed that copyright mark is missing in LICENSE.txt

https://github.com/JakeWharton/ActionBarSherlock/blob/master/LICENSE.txt#L190

**Comment by JakeWharton** [comment]
You're the second person to notice this. I have to reasons why it stays like it is:
1. That section is technically just part of the license which tells you how to apply it to your files and not actually something that should be licensed.
2. This is the only file that exists unmodified from the very first commit. Call me sentimental...

The license properly includes my name and the year in the `README.md` file and in the headers of some files. Good eye though!

**Comment by jfsso** [comment]
Thank you for pointing the reasons. I liked the second one! :)
