### ISSUE TITLE
API 6 and below cannot use requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);

### ISSUE THREAD

**Issue by timothyjc** [JakeWharton/ActionBarSherlock#386]
This is the offending line of my SherlockActivity:

```
requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
```

And the stack trace from API 6:

/AndroidRuntime(  260): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.citc.ud/com.citc.ud.activities.DefinitionActivity}: ja
a.lang.IllegalStateException: No implementations match configuration.
/AndroidRuntime(  260):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
/AndroidRuntime(  260):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2497)
/AndroidRuntime(  260):        at android.app.ActivityThread.access$2200(ActivityThread.java:119)
/AndroidRuntime(  260):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
/AndroidRuntime(  260):        at android.os.Handler.dispatchMessage(Handler.java:99)
/AndroidRuntime(  260):        at android.os.Looper.loop(Looper.java:123)
/AndroidRuntime(  260):        at android.app.ActivityThread.main(ActivityThread.java:4338)
/AndroidRuntime(  260):        at java.lang.reflect.Method.invokeNative(Native Method)
/AndroidRuntime(  260):        at java.lang.reflect.Method.invoke(Method.java:521)
/AndroidRuntime(  260):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
/AndroidRuntime(  260):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
/AndroidRuntime(  260):        at dalvik.system.NativeStart.main(Native Method)
/AndroidRuntime(  260): Caused by: java.lang.IllegalStateException: No implementations match configuration.
/AndroidRuntime(  260):        at com.actionbarsherlock.ActionBarSherlock.wrap(ActionBarSherlock.java:224)
/AndroidRuntime(  260):        at com.actionbarsherlock.app.SherlockActivity.getSherlock(SherlockActivity.java:26)
/AndroidRuntime(  260):        at com.actionbarsherlock.app.SherlockActivity.requestWindowFeature(SherlockActivity.java:226)
/AndroidRuntime(  260):        at com.citc.ud.activities.DefinitionActivity.onCreate(DefinitionActivity.java:114)
/AndroidRuntime(  260):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
/AndroidRuntime(  260):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
/AndroidRuntime(  260):        ... 11 more

**Comment by iNoles** [comment]
I believe ActionBarSherlockv4 minimum is 2.1

**Comment by JakeWharton** [comment]
It is. See #352.
