### ISSUE TITLE
ActionBar menu items do not honor Menu.Category 

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#39]
Release 3.0.2

In the compatibility ActionBar implementation, menu items will be added to the ActonBar either if they are forced by _MenuItem.SHOW_AS_ACTION_ALWAYS_ or if there is space and they have set _MenuItem.SHOW_AS_ACTION_IF_ROOM_. But the implementation does not respect their set category. So _SHOW_AS_ACTION_IF_ROOM_ menu items with a low category like Menu.CATEGORY_ALTERNATIVE are added before menu items with category Menu.NONE.

I don't know how this is handled in the native implementation, but the normal menu arranges it's items also by the category. 

I would suggest to add _SHOW_AS_ACTION_ALWAYS_ always as long as there is space and then _SHOW_AS_ACTION_IF_ROOM_ depending on their category and order inside the category.

**Comment by JakeWharton** [comment]
I think the `dev` branch version should do this (even though it's currently not displaying items properly). I'll do some testing on the native action bar and see how it operates and make sure the custom implementation mirrors it.

**Comment by JakeWharton** [comment]
Can you provide demo code for this? Either a full activity source, just the `onCreateOptionsMenu`, or something equivalent and what the correct output should be. I'm very near being able to test this.

**Comment by drsoran** [comment]
Sample code for expected menu item ordering:

``` java
   @Override
   public boolean onCreateOptionsMenu( Menu menu )
   {
      super.onCreateOptionsMenu( menu );

      // Category SECONDARY, SHOW_AS_ACTION_ALWAYS 
      menu.add( Menu.SECONDARY, R.id.item_a, 0, "ItemA" )
              .setShowAsAction( MenuItem.SHOW_AS_ACTION_ALWAYS );

      // Category NONE, SHOW_AS_ACTION_ALWAYS 
      menu.add( Menu.NONE, R.id.item_b, 0, "ItemB" )
              .setShowAsAction( MenuItem.SHOW_AS_ACTION_ALWAYS );

      // Category NONE, SHOW_AS_ACTION_IF_ROOM
      menu.add( Menu.NONE, R.id.item_c, 0, "ItemC" )
              .setShowAsAction( MenuItem.SHOW_AS_ACTION_IF_ROOM );

      // Category NONE, SHOW_AS_ACTION_IF_ROOM, Order 1
      menu.add( Menu.SECONDARY, R.id.item_d, 1, "ItemD" )
              .setShowAsAction( MenuItem.SHOW_AS_ACTION_IF_ROOM );

      // Category NONE, SHOW_AS_ACTION_IF_ROOM, Order 0
      menu.add( Menu.SECONDARY, R.id.item_e, 0, "ItemE" )
              .setShowAsAction( MenuItem.SHOW_AS_ACTION_IF_ROOM );

      return true;
   }
```

I would expect to see the icons in the following order (assuming there is enough space to show them all):

**ItemB** <- SHOW_AS_ACTION_ALWAYS, Category NONE
**ItemC** <- SHOW_AS_ACTION_IF_ROOM, Category NONE
**ItemA** <- SHOW_AS_ACTION_ALWAYS, Category SECONDARY, Order 0
**ItemE** <- SHOW_AS_ACTION_IF_ROOM, Category SECONDARY, Order 0 but added later
**ItemD** <- SHOW_AS_ACTION_IF_ROOM, Category SECONDARY, Order 1

If there is space for only 2 icons, I would expect to see:

**ItemB** <- SHOW_AS_ACTION_ALWAYS, Category NONE
**ItemA** <- SHOW_AS_ACTION_ALWAYS, Category SECONDARY

And, for example, there is space for 3 items, I would expect to see:

**ItemB** <- SHOW_AS_ACTION_ALWAYS, Category NONE
**ItemC** <- SHOW_AS_ACTION_IF_ROOM, Category NONE
**ItemA** <- SHOW_AS_ACTION_ALWAYS, Category SECONDARY, Order 0

**Comment by JakeWharton** [comment]
Released with 3.1.3.

**Comment by drsoran** [comment]
Release 3.1.3:

I think there is a problem with the defined _CATEGORY_TO_ORDER_ look up table in _com.actionbarsherlock.internal.view.menu.MenuBuilder_. _CATEGORY_TO_ORDER_ is defined as follows:

``` java
 private static final int[] CATEGORY_TO_ORDER = new int[] {
        1, /* No category */
        4, /* CONTAINER */
        5, /* SYSTEM */
        3, /* SECONDARY */
        2, /* ALTERNATIVE */
        0, /* SELECTED_ALTERNATIVE */
    };
```

I think _CONTAINER = 4_ should swap the value with _ALTERNATIVE = 2_. According to the Android category values, _CATEGORY_CONTAINER_ has the value 0x10000 and _CATEGORY_ALTERNATIVE_ has the value 0x40000. Lower values mean higher priority.

So currently _CATEGORY_ALTERNATIVE_ is more prior than _CATEGORY_CONTAINER_ what leads to unexpected icon ordering and appearance in the ActionBar.

**Comment by JakeWharton** [comment]
While I agree with your logic, the following is from the decompiled sources of Android 3.2's framework.jar file:

```
fill-array-data v0, :array_3
sput-object v0, Lcom/android/internal/view/menu/MenuBuilder;->sCategoryToOrder:[I

:array_3
.array-data 0x4
    0x1t 0x0t 0x0t 0x0t
    0x4t 0x0t 0x0t 0x0t
    0x5t 0x0t 0x0t 0x0t
    0x3t 0x0t 0x0t 0x0t
    0x2t 0x0t 0x0t 0x0t
    0x0t 0x0t 0x0t 0x0t
.end array-data
```

Unfortunately I have to elect mirroring the behavior of Android 3.0+ rather than what may seem correct. This order is also present in [current versions](https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/view/menu/MenuBuilder.java#L92-99) of the class as well.
