### ISSUE TITLE
v3.5.1 had tab.getTabListener() but v4.0.0 does not

### ISSUE THREAD

**Issue by mlwilliamson** [JakeWharton/ActionBarSherlock#390]
Hi,

Great work on the library. As the title says, in the previous release of Actionbar Sherlock I had used the tab.setTabListener and tab.getTabListener methods but in the new version 4.0.0 the get function no longer appears to be available. Could this be feature be returned?

Best,
Mark

**Comment by JakeWharton** [comment]
There is no `getTabListener` in the [`ActionBar.Tab`](http://developer.android.com/reference/android/app/ActionBar.Tab.html) API. If it was exposed in previous versions it was by accident and meant for internal use only.
