### ISSUE TITLE
Support for setCustomSelectionActionModeCallback()

### ISSUE THREAD

**Issue by commonsguy** [JakeWharton/ActionBarSherlock#397]
`TextView` has an `setCustomSelectionActionModeCallback()` method, where we can supply an `ActionMode.Callback` on API Level 11+ to be blended in with the built-in `ActionMode.Callback` used when users select text. Alas, this wants a native `ActionMode.Callback`, not a Sherlockian one. So, the feature request is for a pattern to make this work.

I started down the path of trying to make a "thunk" for `ActionMode.Callback`, to bridge native API calls over to your `ActionMode.Callback` implementation. That ran aground when I realized that I would need to make a similar thunk for `ActionMode` itself, since ABS's callbacks take an ABS `ActionMode`. Preliminary tests suggest that I can't make a single class cleanly implement both `ActionMode.Callback` interfaces. And it's all probably moot anyway, as the work I need to do inside my `ActionMode.Callback` will depend on whether I am working with a `SherlockActivity` or a regular `Activity`.

I'll wind up just duplicating a bunch of code, using native `ActionMode.Callback` on API Level 11+ and using ABS on prior versions (where `setCustomSelectionActionModeCallback()` doesn't exist anyway).

But, I figured I'd file the issue, in case it triggers useful thoughts for you... :-)

**Comment by JakeWharton** [comment]
If this hasn't happened yet, it's not going to...
