### ISSUE TITLE
Actionbar home icon scaling

### ISSUE THREAD

**Issue by sareninden** [JakeWharton/ActionBarSherlock#398]
The home icon in the actionbar isn't scaled to fit. This causes by me that the icon is oversized and parts on top and below are cut off. This is easily fixed by doing this:

```
<style name="Widget.Sherlock.ActionButton.Home">
    <item name="android:scaleType">centerInside</item>
    <item name="android:paddingLeft">0dip</item>
    <item name="android:paddingRight">0dip</item>
</style>
```

Instead of

```
<style name="Widget.Sherlock.ActionButton.Home">
    <item name="android:paddingLeft">0dip</item>
    <item name="android:paddingRight">0dip</item>
</style>
```

**Comment by JakeWharton** [comment]
Provide a screenshot.

If you provide xhdpi/hdpi/mdpi icons as [per the documentation](http://developer.android.com/design/style/iconography.html#launcher) in all three configurations of the action bar (40dp, 48dp, 56dp) the icon should fit perfectly.

**Comment by sareninden** [comment]
That might have been the problem, the action bar loads the launcher icon by default which are in my case lhdpi: 36px; M: 48px; H: 72px. Those are the default sizes eclipse creates for me.

I was looking for a screenshot but i deleted all the old ones when I made screenshots of the new version.

Kind regards

btw: great actionbar
