### ISSUE TITLE
Action Mode title

### ISSUE THREAD

**Issue by nicomott** [JakeWharton/ActionBarSherlock#399]
I can't find a way to display the title while in action mode. The goal is to display something like "2 items selected" as we can see here : http://developer.android.com/design/patterns/actionbar.html#contextual, but the title is never displayed.

I'm on Gingerbread, latest commit of the project (tried older versions too).

**Comment by JakeWharton** [comment]
The [`ActionMode` instance](http://developer.android.com/reference/android/view/ActionMode.html) has [`setTitle(CharSequence)` and `setTitle(int)`](http://developer.android.com/reference/android/view/ActionMode.html#setTitle%28java.lang.CharSequence%29) methods.
