### ISSUE TITLE
Unable to build with SDK tools r12 / platform tools r6

### ISSUE THREAD

**Issue by felixb** [JakeWharton/ActionBarSherlock#40]
I'm not sure, which update broke the build system, and I'm not sure, if this is a bug related to this project, or to the android SDK:

Since the update to latest Android API / SDK tools and eclipse plugin, I can not build the project, as some references to the platform's resources are unknown. Even when leaving the referenced API untouched (E.g. to API-11 or 12).

I can reproduce the problem on both systems here.
One of it was building the project yesterday without the updates.

The marked resources are:
android:actionModePopupWindowStyle
android:actionModeStyle

with the four lines

<item name="android:actionModePopupWindowStyle">?actionModePopupWindowStyle</item>
<item name="android:actionModeStyle">?actionModeStyle</item>

**Comment by JakeWharton** [comment]
I am working on this right now actually. Version 3.1 of the library will
include support for building against Android 3.2 and include everything from
the new compatibility library revision 3.

Expect release within the next week.

---

Jake Wharton
http://about.me/jakewharton

**Comment by JakeWharton** [comment]
You can use the `v13-hotfix` branch to fix this for now. If you don't want to compile against 3.2, delete the `values-v13` folder and it should work for 3.0 and 3.1.

**Comment by JakeWharton** [comment]
Fixed in 3.0.3.
