### ISSUE TITLE
Action Mode menuItem width (text + icon)

### ISSUE THREAD

**Issue by nicomott** [JakeWharton/ActionBarSherlock#400]
I'm referring to the ABS: Demos.

First, when the orientation changes, the CAB is always dismissed.

Then if only add one menu like this : 

 @Override
        public boolean onCreateActionMode(ActionMode mode, Menu menu) {
            //Used to put dark icons on light action bar
            boolean isLight = SampleList.THEME == R.style.Theme_Sherlock_Light;

```
        menu.add("Save")
            .setIcon(isLight ? R.drawable.ic_compose_inverse : R.drawable.ic_compose)
            .setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM | MenuItem.SHOW_AS_ACTION_WITH_TEXT);
        return true;
    }
```

I never have the icon + text in portrait orientation, despite all the width available. Only the icon is displayed.

I'm on a Desire with Gingerbread.

**Comment by ai212983** [comment]
AFAIK, the only way you can have both icon and text in actionbar is to create your own actionview, SHOW_AS_ACTION_WITH_TEXT is not mandatory for actionbar and doesn't work in portrait mode (both Sherlock and native)

**Comment by JakeWharton** [comment]
The activity is recreated when you rotate which is why the action mode disappears. In your app you would have to restart the action mode on rotate.

You will never see both the icon and text on small views on any screen with a width less than 480dp. That is a rule from the native action bar.
