### ISSUE TITLE
No way to change ActionBar.TabText text size

### ISSUE THREAD

**Issue by nelenkov** [JakeWharton/ActionBarSherlock#401]
There is no ABS 'textSize' attribute and the size is set to 12sp which is quite small for CJK languages. Cf. screenshot, fonts are almost unreadable. 

![ABS4](http://dl.dropbox.com/u/342975/small-ab-font.png)

Cf. same thing with the native HC action bar and ABS 3.5

![ABS3.5](http://dl.dropbox.com/u/342975/hc-ab-font.png)

**Comment by JakeWharton** [comment]
``` xml
<style name="Theme.MyTheme" parent="Theme.Sherlock">
    <item name="android:actionBarTabTextStyle">@style/Widget.MyTabText</item>
    <item name="actionBarTabTextStyle">@style/Widget.MyTabText</item>
</style>

<style name="Widget.MyTabText" parent="Widget.Sherlock.ActionBar.TabText">
    <item name="android:textSize">14sp</item>
</style>
```

**Comment by nelenkov** [comment]
I tried this, but it seems to have no effect. Will experiment a bit more tomorrow. Probably shouldn't file issues after 1 o'clock though...

**Comment by nelenkov** [comment]
Scratch that, wrong style. Works as expected, just released a bug fix version of the app.

**Comment by ghost** [comment]
@JakeWharton - thank u sir for the styles.. it does change the size of the tab text, but then when using the same style for android 2.3 infact lower versions than android level 11, lint errors say that the android:actionBarTabTextStyle requires API level 11 (current min is 8) , i tend to clear the lint errors, but then is there any way i could also add these styles to android versions lower than 11?
thank u once again.
