### ISSUE TITLE
FragmentActivity.supportInvalidateOptionsMenu cannot be overwritten

### ISSUE THREAD

**Issue by jan-kiszka** [JakeWharton/ActionBarSherlock#403]
Minor issue, but it's the only warning ActionBarSherlock causes here:

"The method SherlockFragmentActivity.supportInvalidateOptionsMenu() does not override the inherited method from FragmentActivity since it is private to a different package"

Not sure if something is really broken due to this or if that method could simply be deleted.

I'm building under Eclipse against SDK revision 14.

**Comment by SimonVT** [comment]
Update android-support-v4.jar to the newest, and change visibility of SherlockFragmentActivity.supportInvalidateOptionsMenu() to public

**Comment by jan-kiszka** [comment]
So is this something that is already fixed in some branch? I'm on master/4.0.0 ATM.

**Comment by SimonVT** [comment]
No, it's not fixed in a branch yet. Jake is waiting for the new support lib to be available in his some Maven repo before updating the bundled lib.

**Comment by jan-kiszka** [comment]
Great, thanks for the information!

**Comment by JakeWharton** [comment]
See #394. I'll update as soon as possible. I'm blocked by Google not pushing the new changes to the `frameworks/support.git` AOSP repository.
