### ISSUE TITLE
Size considerations

### ISSUE THREAD

**Issue by theomega** [JakeWharton/ActionBarSherlock#404]
This is not a bugreport but a question:

Adding ActionbarSherlock to a Project roughly adds 1MB of installed size on a device. I checked this on my 2.3 android device. Is there anything I could do for reducing the size, especially if I'm using only the actionbar implementation, so no animation, no tabs, etc. 
The graphics contribute some part to the size. 

So are there any hints?

1MB might not seem much on todays ICS devices which there huge (>1GB) memories, but as ActionBarSherlock is designed for backporting features to older devices, application size comes back into focus. Some devices have only 100MB of application storage, then every MB counts.

**Comment by SimonVT** [comment]
This question is probably better suited for google groups: https://groups.google.com/group/actionbarsherlock

**Comment by JakeWharton** [comment]
If you look at the downloads a zipaligned APK with ActionBarSherlock probably only adds ~500KB to the size. In my opinion, a small price to pay to not have to waste time implementing your own pre-Honeycomb action bar.

You can also fork the project and delete either the light or dark resources depending on which theme you will be using. That should shave off an additional ~150KB.

If you have any further concerns please continue the discussion on the Google Group as @SimonVT said and I'll be happy to answer.
