### ISSUE TITLE
addPreferencesFromResource deprecated

### ISSUE THREAD

**Issue by AYastrebov** [JakeWharton/ActionBarSherlock#411]
In demo samples in Preference.java on line 49 addPreferencesFromResource(R.xml.preferences); is deprecated

**Comment by iNoles** [comment]
greater than 3.0, It is deprecated in the PreferenceActivity so they want to use it in PreferenceFragment
less than 3.0, it is okay to use it in the SherlockPreferenceActivity.

**Comment by JakeWharton** [comment]
Yeah it's only deprecated because of the introduction of `PreferenceFragment` as @iNoles said. It's still perfectly fine to use for that specific example since we are demonstrating `PreferenceActivity`.

**Comment by xDragonZ** [comment]
It is possible to have PreferenceFragment / SherlockPreferenceFragment support for up coming ActionBarSherlock?

Because I want to use PreferenceFragment with Sherlock from Android API less than 3.0

**Comment by JakeWharton** [comment]
@xDragonZ No, it relies on hidden methods in `PreferenceManager` which we do not have access to. The only way to support it would be to bring along the entire preference package into a library and that's way out of scope for ActionBarSherlock.

**Comment by rcristobalm** [comment]
Hello, I have this code, and when trying to adapt it for use actionbarsherlock I can not use the getFragmentManager, that I can do?

Change to SherlockPreferenceActivity and actionbar by getSupportActionBar, but getFragmentManager fails me ... Why?

public class Settings extends PreferenceActivity{

 @Override
 protected void onCreate(Bundle savedInstanceState) {
  // TODO Auto-generated method stub
  super.onCreate(savedInstanceState);

  ActionBar actionBar = getActionBar();
    actionBar.setTitle(R.string.preferencias);
    actionBar.setDisplayHomeAsUpEnabled(false);
    actionBar.setHomeButtonEnabled(true);
    actionBar.setIcon(R.drawable.actionbar_cerrar);

  getFragmentManager().beginTransaction().replace(android.R.id.content,
                new SettingsFragment()).commit();
 }
