### ISSUE TITLE
Overflow menu is not displayed with Gingerbread

### ISSUE THREAD

**Issue by pierrre** [JakeWharton/ActionBarSherlock#412]
In the ABS Demos app, the overflow menu is not displayed with Gingerbread.
I use an emulator, with a 320x480 mdpi screen and Gingerbread.

It perfectly works on my Galaxy Nexus, 720x1280 xhdpi Ice Cream Sandwich.

<a target="_blank" href="http://img263.imageshack.us/i/gbactionitems.png/"><img src="http://img263.imageshack.us/img263/7154/gbactionitems.th.png" border="0"/></a><a target="_blank" href="http://img38.imageshack.us/i/icsactionitems.png/"><img src="http://img38.imageshack.us/img38/6063/icsactionitems.th.png" border="0"/></a><br>
<a target="_blank" href="http://img263.imageshack.us/i/gbactionproviders.png/"><img src="http://img263.imageshack.us/img263/9351/gbactionproviders.th.png" border="0"/></a><a target="_blank" href="http://img192.imageshack.us/i/icsactionproviders.png/"><img src="http://img192.imageshack.us/img192/4482/icsactionproviders.th.png" border="0"/></a><br>
<a target="_blank" href="http://img689.imageshack.us/i/gbcontextmenus.png/"><img src="http://img689.imageshack.us/img689/6875/gbcontextmenus.th.png" border="0"/></a><a target="_blank" href="http://img269.imageshack.us/i/icscontextmenus.png/"><img src="http://img269.imageshack.us/img269/347/icscontextmenus.th.png" border="0"/></a><br>
<a target="_blank" href="http://img703.imageshack.us/i/gbpreference.png/"><img src="http://img703.imageshack.us/img703/198/gbpreference.th.png" border="0"/></a><a target="_blank" href="http://img708.imageshack.us/i/icspreference.png/"><img src="http://img708.imageshack.us/img708/4994/icspreference.th.png" border="0"/></a><br>
<a target="_blank" href="http://img821.imageshack.us/i/gbsubmenus.png/"><img src="http://img821.imageshack.us/img821/677/gbsubmenus.th.png" border="0"/></a><a target="_blank" href="http://img703.imageshack.us/i/icssubmenus.png/"><img src="http://img703.imageshack.us/img703/8132/icssubmenus.th.png" border="0"/></a><br>

**Comment by JakeWharton** [comment]
That's because your device has a hardware menu key. Try the 'Force Overflow' sample and you'll see it on the action bar (for pre-3.0). Or try it on an ICS device with a menu key and you won't see the overflow on ICS.

**Comment by pierrre** [comment]
Ok, thank you very much!
It was not a bug, but a feature :P
