### ISSUE TITLE
Heap size increases on every screen orientation change

### ISSUE THREAD

**Issue by westward** [JakeWharton/ActionBarSherlock#413]
I use ActionBarSherlock (4.0.0, from yesterday 4.0.1) in a project that is being developed and debugged on the phone with Android 2.2. Today I opened DDMS tab in Eclipse, turned on the Update Heap option and noticed that at every turn of the screen heap size and the number of objects in memory increases.

Then I temporarily removed ABS from the project - a memory leak problem disappeared.

Next, I tried to compile one of the ABS demo projects named "styled" and run it on the same phone with Android 2.2. With each new turn of the screen, I saw again in the DDMS increase in the number of objects and the heap size.

Maybe I'm wrong, but maybe it's a memory leak in the ABS?

**Comment by JakeWharton** [comment]
Do you have any insights as to where the leak was occurring? I can look into this eventually but I'm not sure when I'll have the time.

**Comment by westward** [comment]
At this moment - no, I haven't any idea. But maybe I can help in any way?

10 min ago I did make a completely new, emply Android project with min sdk=7 and target=14, theme=@style/Theme.Sherlock for the single activity and change owner class from Activity to SherlockActivity. ABS 4.0.1 (and in the next test, 4.0.0) was included as library project.That's all, just empty activity + ABS.

Then, a project has been launched on the phone with android 2.2. Here the mem size values from DDMS:
Change orientation #1: 2546kb / 51340 objects
Change orientation #2: 2576kb / 51822 objects
Change orientation #3: 2606kb / 52304 objects
Change orientation #4: 2637kb / 52786 objects
Change orientation #5: 2667kb / 53268 objects

**Comment by westward** [comment]
Upd: after every iteration there is +30kb allocated memory and +482 objects

**Comment by ChrisSmith** [comment]
@JakeWharton I'll look into this also. For some weird reason I like fixing these issues (and need to because my app is memory intensive as it is)

**Comment by ChrisSmith** [comment]
I don't see any evidence there is a leak, my native heap increases (because I'm testing with an image) but that is expected. I saw a total of 11kB unaccounted for after 30 changes so I'm not too concerned. 

Just because the number of objects in DDMS is shown as increasing doesn't mean there is a leak, just that they haven't been collected yet. Use the "Cause GC" button to verify that, if they aren't decreasing then dump the HPROF and look for leaks with MAT

This was running 2.3, but I'm going to check 2.2 now.

The [test activity](https://github.com/ChrisSmith/ActionBarSherlock/blob/bug_memleak/samples/demos/src/com/actionbarsherlock/sample/demos/BugLeaks.java) can be found in my branch. 

<table>
<th>State</th>
<th>Dalvik Size</th><th>Davlik Allocated</th>
<th>Native Size</th><th>Native Allocated</th>

<tr><td>Launched Demos</td><td>5575</td><td>2946</td><td>6104</td><td>4732</td></tr>
<tr><td>Launched BugLeaks</td><td>5575</td><td>2999</td><td>10448</td><td>9064</td></tr>
<tr><td>30 rotations</td><td>5575</td><td>3038</td><td>14972</td><td>13478</td></tr>
<tr><td>Multiple Forced GC</td><td>5575</td><td>2989</td><td>14972</td><td>9103</td></tr>
<tr><td>Back to SampleList</td><td>5575</td><td>2957</td><td>14972</td><td>4782</td></tr>

</table>

The table was creating using `adb shell dumpsys meminfo com.actionbarsherlock.sample.demos`

EDIT: Same story for 2.2

<table>
<th>State</th>
<th>Dalvik Size</th><th>Davlik Allocated</th>
<th>Native Size</th><th>Native Allocated</th>

<tr><td>Launched Demos</td><td>3015</td><td>2491</td><td>5080</td><td>3672</td></tr>
<tr><td>Launched BugLeaks</td><td>3015</td><td>2535</td><td>9368</td><td>7996</td></tr>
<tr><td>30 rotations</td><td>3015</td><td>2559</td><td>16432</td><td>8017</td></tr>
<tr><td>Multiple Forced GC</td><td>3015</td><td>2538</td><td>16432</td><td>8018</td></tr>
<tr><td>Back to SampleList</td><td>3015</td><td>2506</td><td>16432</td><td>3718</td></tr>

</table>

**Comment by westward** [comment]
I pressed the "Cause GC" button after each rotation of the device. Ok, will try to use MAT to analyse a dump. For the first time, but I hope that it will be easier than finding the Higgs boson.

**Comment by westward** [comment]
Chris, another test using adb, 5 screen rotations. "Cause GC" after every screen rotation.

```
   Dalvik          Native
```

#1  3271/2721    6460/5102
#2  3463/2752    6492/5224
#3  3463/2782    6616/5241
#4  3463/2813    6632/5361
#5  3463/2844    6756/5378

**Comment by ChrisSmith** [comment]
It may take multiple GCs for heap space to be reclaimed, Android uses a mark sweep algorithm that takes multiple passes before reclaiming the memory, in my test I would press it a few times until the alloc. heap stayed constant.

I still find it odd that you are losing 100's of kB while I lost 10.  Which phone are you testing this on? Can you reproduce it in the emulator?

**Comment by westward** [comment]
I used Samsung Vibrant, rooted, custom 2.2 ROM.

After midnight it's too difficult to understand unknown tool. I have not read the tutorial for MAT and tried to use this tool on the move. Therefore, most likely I'm wrong, but trying to analyse hprof dump after 14 orientation changes, I find the MAT's "Dominator Tree" button and here is a part of its report:

```
Class Name                                                      | Shallow Heap | Retained Heap | Percentage
------------------------------------------------------------------------------------------------------------
com.actionbarsherlock.internal.widget.ActionBarView @ 0x483ed6c8|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x483f6750|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x483fd298|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x48403d18|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x48404688|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x484071e0|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x48423b50|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x4842af28|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x484314d0|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x484394a0|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x484486f8|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x48449c50|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x48450138|          480 |        12 872 |      0,54%
com.actionbarsherlock.internal.widget.ActionBarView @ 0x48457f60|          480 |        12 872 |      0,54%
```

Only ActionBarView repeated 14 times in this report.

Will try to make another test in the emulator.

**Comment by westward** [comment]
Have the same issue on the 2.3.3 emulator. And have absolutely no problems with the same test on the Asus Transformer Prime/ICS tablet. I think, (possible) memory leak appears only in the ABS compatibility mode for pre-honeycomb devices.

**Comment by ChrisSmith** [comment]
Since its the ActionBarView yes, its the pre-ics implementation. Do you have a copy of the project you are testing this with? (github or zip) Or is it just an empty project with ABS? (I can set that up myself)

Which branch are you using to test this with? Master or Dev?

**Comment by westward** [comment]
Just empty project with minimal ABS requirements: theme, api level and SherlockActivity instead of Activity. ABS 4.0.1 Master configured as library project.

I'm a very beginner at GitHub and don't know how to upload a project here. I can send you zip in the morning, have only 6 hours left to sleep. :) Please tell me email or something else.

**Comment by JakeWharton** [comment]
You can post on the Google Group: http://abs.io/forum/

**Comment by ChrisSmith** [comment]
I still can't reproduce it, once you post your code maybe I can find the source but I'm beginning to think its related to your phone's custom rom. No matter how many rotations, I always endup with one instance of `ActionBarView`.

Some quick tips on MAT:

Use the histogram to see the instances of a class (find one you think is leaking like `ActionBarView`), right click -> merge paths to gc roots -> exclude week/soft references. You should only have one instance held by the ViewRoot.

The Dominator Tree and Leak Suspects are also good at finding leaking classes, but use the "path to roots" feature to actually find where its leaking from.

**Comment by westward** [comment]
@JakeWharton Cannot open your URL

TypeError: Cannot call method 'indexOf' of undefined
    at ServerResponse.redirect (/app/node_modules/express/lib/response.js:343:13)

**Comment by JakeWharton** [comment]
Works for me. Must be Heroku troubles. It redirects to: https://groups.google.com/forum/?fromgroups#!forum/actionbarsherlock

**Comment by westward** [comment]
@JakeWharton @ChrisSmith Posted ABS library & test projects to the Google Group.
https://groups.google.com/forum/?fromgroups#!topic/actionbarsherlock/BlKRj39ssPM

**Comment by SimonVT** [comment]
Can't reproduce this either. Maybe upload your hprof file as well, so we can check it out.

**Comment by westward** [comment]
@SimonVT hprof dump posted to the same Google Group

**Comment by SimonVT** [comment]
@westward Do you have a hprof without ABS?

**Comment by westward** [comment]
@SimonVT Posted another HPROF dump, without ABS (removed theme in the manifest and changed LeakTestActivity parent from SherlockActivity to Activity.

**Comment by SimonVT** [comment]
I have no idea. I see no obvious reasons for it to be leaking. I mean, the whole Activity is leaking, which most certainly would lead to some serious issues with larger apps. The only common root they have is a WeakHashMap in the NineOldAndroids implementation, but that's not going to cause any issues.
I too suspect it could be related to a buggy rom, but that doesn't explain how you're able to reproduce it on the 2.3 emulator

**Comment by westward** [comment]
@SimonVT Maybe you have any idea, why other person cannot reproduce this leak with my absolutely empty test project? Eclipse or compiler options, build target version... ?

**Comment by SimonVT** [comment]
I have no idea, strange if that would be the case. Either way, here's an apk compiled by me. I've been unable to reproduce it so far: http://dl.dropbox.com/u/100261/LeakTest.apk

**Comment by westward** [comment]
@SimonVT I downloaded and installed your APK. Can't run app it in debug mode, but I can see it in the DDMS. No problems with allocated memory and objects count. So, there is no memory leak problem in ABS.

Please tell me, which ABS version you used when compiling my test? And what I can't understand the difference, why your computer produce the right APK and my make the leaked app. :-( 

P.S. And what version / size of android-support-v4.jar are you using?

**Comment by SimonVT** [comment]
Huh, weird. Built with the latest dev branch, tho earlier I tried both current master and the ABS you uploaded. No issues there either. Maybe check your setup, update java, eclipse, sdk, etc

**Comment by ChrisSmith** [comment]
I tested with the Master and Dev branches, Eclipse 3.6.2, ADTr17, my android-support-v4.jar is 247,894 bytes but I forget which version it is.

**Comment by westward** [comment]
Ok, maybe it's time to say thank you to all the participants and close the issue. And reinstall the Java, OS and the whole damn world.

**Comment by westward** [comment]
@JakeWharton @SimonVT @ChrisSmith I found the difference between "leaked" and "correct" versions, but I can not explain it. 
If the project is run in debug mode from Eclipse, DDMS showing a memory leaks. But if you just run APK on your phone, DDMS shows no memory leaks.

**Comment by micHar** [comment]
Really, can't you explain it? Because I have the same problem. If I rotate phone several times (say 8) I get 8 instances of actionbar (seen in hprof in MAT). GC doesn't help. I guess I'll try running apk...

Well... :O

Exaclty. After launching app from phone menu instead of debug perspective - no memory leak...
Any comments appreciated

**Comment by westward** [comment]
I still can not explain this behavior, sorry.

**Comment by zaxon** [comment]
is it because view stack didn't recycled?
