### ISSUE TITLE
Strange behavior with configChanges and splitActionBarWhenNarrow

### ISSUE THREAD

**Issue by SteveKChiu** [JakeWharton/ActionBarSherlock#414]
I have a project with the following setup in the manifest:

```
<application
    android:name=...
    android:icon=...
    android:label=...
    android:theme="@style/Theme.Sherlock"
    android:uiOptions="splitActionBarWhenNarrow" >
    <activity
        android:name=...
        android:configChanges="locale|orientation"
        ...
```

I run into a strange problem after screen rotation the Intent or OnMenuItemClickListener of action bar menu item is not executed until other ui is clicked or after another screen rotation. Here is the steps to reproduce:
1. launch an app with above manifest setup (in portrait mode)
2. rotate screen (now in landscape mode)
3. rotate screen yet again (now in portrait mode again)
4. tap any item in the split action bar (let's refer it as item "X")
5. no action, no visual feedback
6. tap other ui (other than action bar), or rotate screen again
7. the intent or OnMenuItemClickListener of item "X" is now executed (and you can see the visual feedback of the item)
8. it looks like the action has been queued somewhere (actually you can tap item "X" multiple times in step 4, and you will see multiple result in step 7)

Test device: Nexus One 2.3.6

**Comment by SteveKChiu** [comment]
It's on ActionBarSherlock 4.0.1

**Comment by JakeWharton** [comment]
Handling config changes is not (yet) supported. The Android documentation [strongly recommends](http://developer.android.com/guide/topics/manifest/activity-element.html#config) avoiding them in the first place.

See #279. I'll get to this eventually as I'm pretty sure I have a clever solution for this.
