### ISSUE TITLE
Cannot compile any of your samples

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/ActionBarSherlock#416]
I cannot use any of your samples.  I get a ton of compilation errors.  Like:
Description Resource    Path    Location    Type
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.Sherlock.Light.DarkActionBar'.    themes.xml  /ActionBarDemos/res/values  line 4  Android AAPT Problem

Description Resource    Path    Location    Type
error: Error retrieving parent for item: No resource found that matches the given name 'Widget.Sherlock.Light.ActionBar.Solid.Inverse'. themes.xml  /ActionBarDemos/res/values  line 8  Android AAPT Problem

Description Resource    Path    Location    Type
error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.Sherlock').    AndroidManifest.xml /ActionBarFragments line 29 Android AAPT Problem

Description Resource    Path    Location    Type
error: Error: No resource found that matches the given name (at 'theme' with value '@style/Theme.Sherlock').    AndroidManifest.xml /ActionBarRoboguice line 8  Android AAPT Problem

Description Resource    Path    Location    Type
error: Error: No resource found that matches the given name: attr 'actionBarStyle'. themes.xml  /ActionBarDemos/res/values  line 5  Android AAPT Problem

Description Resource    Path    Location    Type
error: Error: No resource found that matches the given name: attr 'background'. themes.xml  /ActionBarDemos/res/values  line 9  Android AAPT Problem

Description Resource    Path    Location    Type
error: Error: No resource found that matches the given name: attr 'backgroundSplit'.    themes.xml  /ActionBarDemos/res/values  line 12 Android AAPT Problem

Description Resource    Path    Location    Type
SherlockActivity cannot be resolved to a type   ActionModesNoActionBar.java /ActionBarDemos/src/com/actionbarsherlock/sample/demos  line 29 Java Problem

And many many more...

**Comment by JakeWharton** [comment]
Did you add the core library as a library project?

See: http://www.youtube.com/watch?v=4GJ6yY1lNNY

**Comment by JakeWharton** [comment]
If you are still having troubles, please post to the mailing list: http://abs.io/forum
