### ISSUE TITLE
Action mode crashing when using collapsed tab navigation

### ISSUE THREAD

**Issue by emilsjolander** [JakeWharton/ActionBarSherlock#417]
When using collapsed tab navigation via following code a crash occurs when starting the action mode. crash log below

getSupportActionBar().setDisplayShowHomeEnabled(false);
getSupportActionBar().setDisplayShowTitleEnabled(false);

03-29 20:02:17.253: E/AndroidRuntime(1626): java.lang.NullPointerException
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.nineoldandroids.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:515)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:386)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:539)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:929)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:952)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:364)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.widget.ScrollingTabContainerView.animateToVisibility(ScrollingTabContainerView.java:237)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.app.ActionBarImpl.animateToMode(ActionBarImpl.java:632)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.app.ActionBarImpl.startActionMode(ActionBarImpl.java:407)
03-29 20:02:17.253: E/AndroidRuntime(1626):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.startActionMode(ActionBarSherlockCompat.java:176)

**Comment by JakeWharton** [comment]
This was fixed with v4.0.1.

**Comment by emilsjolander** [comment]
ok great!, sorry had not noticed the update

**Comment by mttkay** [comment]
What was causing this? I am seeing the same error in my app bubbling up from NineOldAndroids even though I don't even use ActionBarSherlock.

Any suggestions how to resolve this? It seems to happen randomly, but when it happens, I cannot start my app again without it crashing immediately. Very strange.

**Comment by JakeWharton** [comment]
Animating a property whose corresponding method doesn't exist on a certain API level. In this case it was calling `setAlpha` on a `FrameLayout` directly.

**Comment by mttkay** [comment]
interesting, thanks for the swift reply!
