### ISSUE TITLE
ShareActionProvider crashes with Light Dark Actionbar

### ISSUE THREAD

**Issue by defer** [JakeWharton/ActionBarSherlock#418]
This is easily reproducible:

In the samples, select Light (DarkActionBar) select the Share Action Providers samples and hit the share ActionButton. It will fail with the following stacktrace (on 4.0.3):

E/AndroidRuntime(27038): FATAL EXCEPTION: main
E/AndroidRuntime(27038): android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
E/AndroidRuntime(27038):    at android.view.LayoutInflater.createView(LayoutInflater.java:606)
E/AndroidRuntime(27038):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
E/AndroidRuntime(27038):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
E/AndroidRuntime(27038):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
E/AndroidRuntime(27038):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
E/AndroidRuntime(27038):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime(27038):    at com.actionbarsherlock.widget.ActivityChooserView$ActivityChooserViewAdapter.getView(ActivityChooserView.java:721)
E/AndroidRuntime(27038):    at com.actionbarsherlock.widget.ActivityChooserView$ActivityChooserViewAdapter.measureContentWidth(ActivityChooserView.java:760)
E/AndroidRuntime(27038):    at com.actionbarsherlock.widget.ActivityChooserView.showPopupUnchecked(ActivityChooserView.java:357)
E/AndroidRuntime(27038):    at com.actionbarsherlock.widget.ActivityChooserView.access$2(ActivityChooserView.java:329)
E/AndroidRuntime(27038):    at com.actionbarsherlock.widget.ActivityChooserView$Callbacks.onClick(ActivityChooserView.java:580)
E/AndroidRuntime(27038):    at android.view.View.performClick(View.java:3511)
E/AndroidRuntime(27038):    at android.view.View$PerformClick.run(View.java:14105)
E/AndroidRuntime(27038):    at android.os.Handler.handleCallback(Handler.java:605)
E/AndroidRuntime(27038):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(27038):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(27038):    at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime(27038):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(27038):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(27038):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
E/AndroidRuntime(27038):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
E/AndroidRuntime(27038):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(27038): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(27038):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(27038):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
E/AndroidRuntime(27038):    at android.view.LayoutInflater.createView(LayoutInflater.java:586)
E/AndroidRuntime(27038):    ... 21 more
E/AndroidRuntime(27038): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010038 a=-1}
E/AndroidRuntime(27038):    at android.content.res.Resources.loadDrawable(Resources.java:1930)
E/AndroidRuntime(27038):    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
E/AndroidRuntime(27038):    at android.view.View.<init>(View.java:2785)
E/AndroidRuntime(27038):    at android.view.ViewGroup.<init>(ViewGroup.java:385)
E/AndroidRuntime(27038):    at android.widget.LinearLayout.<init>(LinearLayout.java:174)
E/AndroidRuntime(27038):    at android.widget.LinearLayout.<init>(LinearLayout.java:170)
E/AndroidRuntime(27038):    ... 24 more

**Comment by iNoles** [comment]
Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010038 a=-1}

did you do full clean?

**Comment by defer** [comment]
Yes, please see the pull request, there are a bunch of missing styles.
