### ISSUE TITLE
ViewPager Action Bar items disappear

### ISSUE THREAD

**Issue by mario20340** [JakeWharton/ActionBarSherlock#422]
I'm using viewpager to switch between 4 actionbar tabs... there is a fragment in every tab with different action menu items defined in onCreateOptionsMenu()... When I switch too fast between tabs (using slide guesture) action menu items suddenly disappear...  it's same problem as issue #351 but that didnt helped

**Comment by JakeWharton** [comment]
Probably related to #331.

**Comment by JakeWharton** [comment]
Dupe #351, like you said.
