### ISSUE TITLE
Evaluate PreferenceFragment Support

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#43]
Evaluate how difficult emulating a [`PreferenceFragment`](http://developer.android.com/reference/android/preference/PreferenceFragment.html) will be since `PreferenceActivity` can not be used.

**Comment by JakeWharton** [comment]
Can't be done because of method visibility on `PreferenceManager` and `PreferenceScreen`.

**Comment by JakeWharton** [comment]
This may be possible with a bit of work on second thought...

**Comment by iNoles** [comment]
I have a some idea of this. 

PreferenceFragment is just abstract class that extends Fragment that depend on PreferenceActivity.

**Comment by JakeWharton** [comment]
I have the beginnings of the class here: https://gist.github.com/1108374

It is based on the decompiled source of Android 3.1. It doesn't compile at present but it's a start. There are a lot of internal APIs in use on the official version of the class. We can't depend on `PreferenceActivity` so some of these methods will have to have their implementations duplicated. I don't have the time to look at it just yet.

**Comment by JakeWharton** [comment]
This is being worked on in a private repo for now. Once it is compiling I'll make it public. It will be at https://github.com/JakeWharton/Android-PreferenceFragment.

**Comment by ChristopheVersieux** [comment]
Have you made any progress since Augustus 2010? I would like to set my preference in a ViewPager but that gives me serious headache!

**Comment by JakeWharton** [comment]
Haven't touched it since. Working on ABS v4 now. I might try it once that is completed.

**Comment by chrisbanes** [comment]
@ChristopheVersieux it shouldn't be too difficult to do it yourself, here's the ICS source for [PreferenceFragment](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/preference/PreferenceFragment.java)

**Comment by JakeWharton** [comment]
I believe it uses internal `PreferenceManager` and `PreferenceScreen` APIs which is why I gave up on it initially until the sources were available. The tricky part will be ensuring it can still work with things that extend `android.preference.Preference`. It's not a requirement, but would be great for a proper solution.

**Comment by ChristopheVersieux** [comment]
Thank a lot for your help, I found this one in the meanwhile: http://forum.xda-developers.com/showpost.php?p=19719977&postcount=1
With a perfectly working example.

Great job everybody and thank for your quick help.

**Comment by JakeWharton** [comment]
Cool. Thanks for the link. That method uses reflection to access the internal APIs so I'll still probably have a go at creating a proper implementation eventually. Glad that works for you for now though.

**Comment by pommedeterresautee** [comment]
Hi Jake, do you plan to work on it? It s not the most useful class in the world, but it would help to have it :)

**Comment by pc-jkoren** [comment]
Please continue development on this, I beg you.

**Comment by oleg-codaio** [comment]
Yes - I need to use loaders and fragments in preference activity when some items are clicked and cannot!

**Comment by paulpv** [comment]
Here seems to be an impressive Unified solution:
https://github.com/saik0/UnifiedPreference

**Comment by jeancaffou** [comment]
@paulpv did you manage to use UnifiedPreference as a SherlockFragment? I am experienceing the following issue: 

04-18 03:59:26.000: E/AndroidRuntime(8437): FATAL EXCEPTION: main
04-18 03:59:26.000: E/AndroidRuntime(8437): java.lang.ClassCastException: si.neanonimen.Settings$NetSettingsPrefsFragment cannot be cast to android.support.v4.app.Fragment
04-18 03:59:26.000: E/AndroidRuntime(8437):     at android.support.v4.app.Fragment.instantiate(Fragment.java:384)

NetSettingsPrefsFragment extends UnifiedPreferenceFragment 

http://stackoverflow.com/questions/16081706/using-preferencefragment-in-sherlockfragmentactivity-with-tabs

**Comment by rcristobalm** [comment]
Hello, I have this code, and when trying to adapt it for use actionbarsherlock I can not use the getFragmentManager, that I can do?

Change to SherlockPreferenceActivity and actionbar by getSupportActionBar, but getFragmentManager fails me ... Why?

public class Settings extends PreferenceActivity{

 @Override
 protected void onCreate(Bundle savedInstanceState) {
  // TODO Auto-generated method stub
  super.onCreate(savedInstanceState);

  ActionBar actionBar = getActionBar();
    actionBar.setTitle(R.string.preferencias);
    actionBar.setDisplayHomeAsUpEnabled(false);
    actionBar.setHomeButtonEnabled(true);
    actionBar.setIcon(R.drawable.actionbar_cerrar);

  getFragmentManager().beginTransaction().replace(android.R.id.content,
                new SettingsFragment()).commit();
 }

**Comment by SebastianEngel** [comment]
Hi Jake,

are you still working on this or do you plan to?

**Comment by kolavar** [comment]
I wrote a compatibility layer for PreferenceFragment. Java reflection is used extensively to access private/hidden methods and fields. It's available here:

https://github.com/kolavar/android-support-v4-preferencefragment

**Comment by mszaro** [comment]
@kolavar, your compatibility layer is brilliant, and working perfectly in my app. Thank you so much for the contribution. I have mostly had success using it in combination with ABS by having your PreferenceFragment class extend from SherlockFragment instead of the Fragment class in the support library.

**Comment by 3mph4515** [comment]
@kolavar , yep, compatibility is great! Thank you very much!
