### ISSUE TITLE
ShareActionProvider wrong rendering

### ISSUE THREAD

**Issue by vRallev** [JakeWharton/ActionBarSherlock#430]
If the activity uses a split action bar and it contains the share action provider, the entire window is rendered wrong:

http://dl.dropbox.com/u/18897350/Bilder/Screen_1.png

If you click the action provider:

http://dl.dropbox.com/u/18897350/Bilder/Screen_3.png

Howevery, if the action provider has a history (e.g. you select a share app and restart the app) everything gets rendered right:

http://dl.dropbox.com/u/18897350/Bilder/Screen_4.png

I had have this issue in the x86 emulator running Android 2.3.3 and it also appeared on my Samsung Galaxy S II with Android 4.0.3. 

Before you released ActionBarSherlock 4.0.1, I used this class for Android 4 devices:

@TargetApi(14)
public class MyShareActionProvider extends ActionProvider {

```
private android.widget.ShareActionProvider icsActionProvider;




public MyShareActionProvider(Context context) {
    super(context);
    icsActionProvider = new android.widget.ShareActionProvider(context);
}




@Override
public View onCreateActionView() {
    return icsActionProvider.onCreateActionView();
}




@Override
public boolean hasSubMenu() {
    return icsActionProvider.hasSubMenu();
}




@Override
public void onPrepareSubMenu(final SubMenu subMenu) {
    icsActionProvider.onPrepareSubMenu((android.view.SubMenu) ((MenuWrapper) subMenu).unwrap());
}




public void setShareIntent(Intent shareIntent) {
    icsActionProvider.setShareIntent(shareIntent);
}




public void setShareHistoryFileName(String filename) {
    icsActionProvider.setShareHistoryFileName(filename);
}
```

}

This class had have the same issue.

**Comment by JakeWharton** [comment]
This is an Android bug. See #303.

**Comment by vRallev** [comment]
Thanks for the clarification.
