### ISSUE TITLE
ArrayAdapter used in NAVIGATION_MODE_LIST doesn't display dynamic image resources

### ISSUE THREAD

**Issue by ddewaele** [JakeWharton/ActionBarSherlock#432]
I'm using a custom ArrayAdapter with a custom layout containing an imageview and a textview.
Both text and images are set in the arrayadapter.

When loading up the ArrayAdapter outside ActionBarSherlock, everything is rendered fine.
When attaching the ArrayAdapter in the ActionBarSherlock using setListNavigationCallbacks, the images aren't shown in the dropdown list. However, when selecting an image from the list, the correct image is shown in the actionbar.

<img src="http://dl.dropbox.com/u/13246619/Random%20stuff/Screen%20Shot%202012-04-08%20at%2021.25.12.png"/>

**Comment by JakeWharton** [comment]
How are you declaring the adapter? Are you calling `setDropDownViewResource`?

**Comment by ddewaele** [comment]
Most likely issue with the adapter.... images renders fine when popped in a AlertDialog.Builder setSingleChoiceItems but not when used with a spinner control. Also doesn't work in standalone spinner control so issue is not related to ActionBarSherlock.

**Comment by ddewaele** [comment]
Overriding the getDropDownView method in the customer ArrayAdapter to call getView solved the issue. Images are working fine....
