### ISSUE TITLE
tabnavigation bug

### ISSUE THREAD

**Issue by xiangyuan** [JakeWharton/ActionBarSherlock#433]
in the tab navigation demo ,
when you add the android:configChanges="orientation"
as show :
<activity
            android:name=".TabNavigation"
            android:label="@string/tab_navigation"
            android:configChanges="orientation">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="com.actionbarsherlock.sample.demos.EXAMPLE" />
            </intent-filter>
        </activity>

when the phone screen turn around the tab can't be touched and change their state

**Comment by JakeWharton** [comment]
Dupe #279
