### ISSUE TITLE
Dialog Divider is hardcoded to holo blue

### ISSUE THREAD

**Issue by madhu314** [JakeWharton/ActionBarSherlock#436]
In the layout  file abs__dialog_title_holo.xml , a View divides the Dialog title with its content, I noticed that this view does not encompass styling. Therefore, when customizing colors and themes it does not scale.

Instead I have done following to fix it

in layout file changed divider to include a style

```
<View android:id="@+id/abs__titleDivider"
        android:layout_width="fill_parent"
        android:layout_height="2dip"
        style="@style/TextAppearance.Sherlock.Light.Dialog.Divider" />
```

in style

```
<style name="TextAppearance.Sherlock.Light.Dialog.Divider" parent="Widget">
    <item name="android:background">@color/abs__holo_blue_light</item>
</style>    
```

**Comment by madhu314** [comment]
If the solution is ok, then this issue can be closed

**Comment by JakeWharton** [comment]
It's hardcoded in the platform too: https://github.com/android/platform_frameworks_base/blob/master/core/res/res/layout/dialog_title_holo.xml#L36

File a bug on http://b.android.com if you think it should be changed.

**Comment by madhu314** [comment]
ok np..I will check that out..thanks

**Comment by davidvavra** [comment]
We have released a library this week which allows to style all dialogs in custom colors while maintaining Holo theme. It might be useful for you:

https://github.com/inmite/android-styled-dialogs
