### ISSUE TITLE
Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment

### ISSUE THREAD

**Issue by slartus** [JakeWharton/ActionBarSherlock#440]
On some devices, such an error falls at the start.
sherlok manifest info:
android:versionCode="50"
android:versionName="4.0.0"

04-17 20:34:21.919 E/AndroidRuntime( 6767): FATAL EXCEPTION: main
04-17 20:34:21.919 E/AndroidRuntime( 6767): java.lang.IllegalStateException: Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment.
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.actionbarsherlock.internal.view.menu.MenuMule.clear(MenuMule.java:77)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:424)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.actionbarsherlock.app.SherlockFragmentActivity.onPreparePanel(SherlockFragmentActivity.java:263)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.actionbarsherlock.ActionBarSherlock.callbackPrepareOptionsMenu(ActionBarSherlock.java:564)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:491)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:269)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:968)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at android.os.Handler.handleCallback(Handler.java:587)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at android.os.Handler.dispatchMessage(Handler.java:92)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at android.os.Looper.loop(Looper.java:130)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at android.app.ActivityThread.main(ActivityThread.java:3849)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at java.lang.reflect.Method.invokeNative(Native Method)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at java.lang.reflect.Method.invoke(Method.java:507)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
04-17 20:34:21.919 E/AndroidRuntime( 6767): at dalvik.system.NativeStart.main(Native Method)

device sample:
build.board: tass
build.bootloader: unknown
build.brand: samsung_tass
build.cpu_abi: armeabi-v6l
build.cpu_abi2: armeabi
build.device: tass
build.display: GWK74
build.fingerprint: samsung/GT-S5570/GT-S5570:2.3.4/GINGERBREAD/XXKPI:user/release-keys
build.hardware: gt-s5570
build.host: squadzone-MXC062
build.id: GRI40
build.manufacturer: samsung
build.model: GT-S5570
build.product: GT-S5570
build.radio: unknown
build.serial: unknown
build.tags: test-keys
build.time: 0
build.type: user
build.user: squadzone
version.codename: REL
version.incremental: eng.squadzone.20120408.194634
version.release: 2.3.7
version.sdk_int: 10

**Comment by dschuermann** [comment]
I have the same issue.
I got 30 errors/week in the google play publisher backend with the following comments:
- force closes as soon as opened
- Force close on start, reinstall won't help.
- getting force close at app startup
- force closes after giving root permissions...I'm running a cm7 nightly
- Force close after migrated to cyanmobile Rom (Galaxy mini/pop)
  ...

I have no more information about this issue. The stacktrace is the same as above.

**Comment by iNoles** [comment]
"Make sure you using both SherlockFragmentActivity and SherlockFragment." It is very picky on which class you uses.

**Comment by JakeWharton** [comment]
It is using `SherlockFragmentActivity` and the error occurs outside of a fragments. That's not the problem.

**Comment by jameswald** [comment]
I'm seeing many reports that mention "cm7.2".  I haven't ever tried CyanogenMod myself.  I wonder if that could be related this issue.

**Comment by dschuermann** [comment]
I don't know excatly what caused this, but I have no more bug reports in Google Play backend after I released the new version of my app. Eventually it was the update of ActionBarSherlock 4.0 to 4.0.2

**Comment by slartus** [comment]
confirm. 4.0.2 solves the problem.
thanks!

**Comment by jameswald** [comment]
So I've confirmed that this specific trace is fixed with 4.0.2, but I am seeing a very similar issue with 4.0.2.  I will log a separate report for that one.

**Comment by FireZenk** [comment]
Crash again on Jelly Bean!

**Comment by JakeWharton** [comment]
Upgrade to 4.1.0
On Jun 28, 2012 12:41 PM, "Jorge Garrido" <
reply@reply.github.com>
wrote:

**Comment by FireZenk** [comment]
Oh, ok, thanks!

**Comment by codeversed** [comment]
Confirmed that 4.1.0 fixes this issue running on Jelly Bean.

**Comment by lalitsharma1607** [comment]
upgrading to 4.4 solved the issue Thanks
