### ISSUE TITLE
Directory structure incompatible to Eclipse

### ISSUE THREAD

**Issue by schildbach** [JakeWharton/ActionBarSherlock#444]
When I try to import the "library" folder into Eclipse as an existing project, Eclipse always imports the folder above and as a consequence, cannot find "AndroidManifest.xml". 

Although this bug appears to be an Eclipse bug, I suggest using a

root
+- library
+- project2

structure rather than the current

project2
+- library

root should contain nothing but maybe a parent pom and some readme.

**Comment by DHuckaby** [comment]
Import the subdirectory, works perfectly for me.

**Comment by JakeWharton** [comment]
Yeah I'm not too sure exactly what you're suggesting. I'm using the standard eclipse/ADT project layout in both the library folder and each of the sample folders which works with Maven, Eclipse, and ADT command line builds. I have personally tested all three. I'm not sure modifying the directory structure would solve anything.

**Comment by schildbach** [comment]
@Jake: Currently you are nesting projects. This is not supported with Eclipse 3.x (will probably be fixed by 4.x though). What I am suggesting is that each project should be a leaf in the tree.

@DHuckaby: importing the library subdirectory does not work, it always imports the root directory instead. I am not alone with this problem, I know of several people who gave up on using ABS because of this. Even if I will solve it with your help at some day, I cannot expect that of fellow developers of my project. Its really a big issue that ABS is such a pita to set up )-:

**Comment by SimonVT** [comment]
There is nothing but a pom file and some random not-project-related files in the root dir. Where exactly is the nesting?

**Comment by DHuckaby** [comment]
@Goonie I am using Eclipse 3.6.2v2 with nested projects (Not explicitly just ABS) and they work perfectly fine.

**Comment by schildbach** [comment]
Finally solved my problem of not being able to import the library directory by hand-crafting my own .project/.classpath file.

**Comment by JakeWharton** [comment]
No IDE-specific project files are provided. In Eclipse you should be
creating a new project with existing sources.
On Apr 22, 2012 10:33 AM, "pink" <
reply@reply.github.com>
wrote:
