### ISSUE TITLE
Error retrieving parent for item

### ISSUE THREAD

**Issue by schildbach** [JakeWharton/ActionBarSherlock#445]
I am using ABS 4.0.2. I have set android:targetSdkVersion="11" as documented on http://actionbarsherlock.com/faq.html. Nevertheless, I am getting loads of errors similar to this:

/action-bar-sherlock/library/res/values-v14/abs__styles.xml:6: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Holo.ActionBar.Solid'.

**Comment by JakeWharton** [comment]
You need to compile with Android 4.0 or newer.
On Apr 22, 2012 10:31 AM, "pink" <
reply@reply.github.com>
wrote:
