### ISSUE TITLE
SherlockPreferencesActivity: sub-screens are not themed

### ISSUE THREAD

**Issue by locationad** [JakeWharton/ActionBarSherlock#447]
On Android 2.3.5 sub-screens of the SherlockPreferencesActivity don't apply the theme/ themed context.

E.g. 
- Set the theme to Theme.Sherlock.Light (application tag in the manifest file)
- Define some Preference entries in res/xml/preferences.xml (at least one sub-group defined by the screen tag)
- Load these preferences in the onCreate method of the SherlockPreferencesActivity
- Call the Preference button to open the sub-screen

The first preferences screen appears in Theme.Sherlock.Light. On the second screen only the group headers appear in the light theme.

**Comment by SimonVT** [comment]
Does this only happen when using SherlockPreferenceActivity, or also PreferenceActivity?
Maybe try and apply the theme to the activity tag directly, instead of the application tag.

**Comment by JakeWharton** [comment]
I'm 99% confident this it out of my control. I'll investigate if I can find time but anyone else is welcome to.

**Comment by DHuckaby** [comment]
This is a known bug in the framework: (Not just abs)
http://stackoverflow.com/questions/2615528/preferenceactivity-and-theme-not-applying

**Comment by JakeWharton** [comment]
Good to know. Thanks for the link! There are two workarounds, the one posted on StackOverflow as the accepted answer and one posted on the bug on the Android bug tracker. Both should work with ABS.
