### ISSUE TITLE
setSupportProgressBarIndeterminateVisibility(false) not in effect

### ISSUE THREAD

**Issue by deckerj** [JakeWharton/ActionBarSherlock#449]
I noticed that "setSupportProgressBarIndeterminateVisibility(false)" had no effect on my HTC Legend running Froyo. The ProgressBar-Icon was spinning every time the SherlockFragmentActivity was created.

Though, on an ICS-Emulator, setting the visible-flag to false was effective - the Activity was started and the progress dialog did not spin from the beginning on.

I noticed that I had to call getSupportActionBar() in the onCreate-Method in order to hide the progressBar by default on Froyo.

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    setTheme(...);
    requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
    super.onCreate(savedInstanceState);
    setSupportProgressBarIndeterminateVisibility(false);
    // init action bar, this is needed in order to hide the progress dialog on Froyo
    getSupportActionBar();
```

...

**Comment by eeVoskos** [comment]
I have the same problem on all ICS devices, but only when I call setSupportProgressBarIndeterminateVisibility() before I call setContentView(). Hence, a workaround that works for me is to call setSupportProgressBarIndeterminateVisibility() for the first time in the onPostCreate() method of a base FragmentActivity class, instead the onCreate(). All my other Activities extend from this one and setContentView() is called in the onCreate() of the subclasses. Subsequent calls via listeners, etc, work without problem.

This is indeed strange behavior though, connected also to issue #310.

**Comment by JakeWharton** [comment]
The decor view hasn't been initialized yet. Will have to investivate ICS behavior and make sure we're duplicating whatever behavior it exhibits.

**Comment by richhollis** [comment]
Sample problem here on both ICS and Motorola Milestone (2.1-update1). onPostCreate as suggested by @eeVoskos  resolves - thanks for the suggestion.

**Comment by JakeWharton** [comment]
Cool. Working as intended then. You should wait to call this method after `setContentView` or calling `getSupportActionBar`.

**Comment by richhollis** [comment]
Awesome - thanks Jake! Working perfectly now.
