### ISSUE TITLE
android.support.v4.view.MenuItem.getSubMenu() should return a android.support.v4.view.SubMenu type

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#45]
Release 3.1.0:

Currently _android.support.v4.view.MenuItem.getSubMenu()_ returns the type _android.view.SubMenu_. This may lead to a MethodNotFoundException on devices with API level < 11 if _android.view.SubMenu_ gets extended in the future.

Related to issue #36

**Comment by JakeWharton** [comment]
Released with 3.1.1.
