### ISSUE TITLE
onMenuItemExpand

### ISSUE THREAD

**Issue by stdiopt** [JakeWharton/ActionBarSherlock#450]
i Added an EditText as actionView (for a search purpose) 

``` java
public boolean onMenuItemActionExpand(MenuItem item) {
                setPage(1);
                ev.post(new Runnable() {
                      public void run() {
                            ev.requestFocus();
                            InputMethodManager mgr = (InputMethodManager)                 
                                                             activity.getSystemService(Context.INPUT_METHOD_SERVICE);
                            mgr.showSoftInput(ev, InputMethodManager.SHOW_IMPLICIT);
                          }
                        });

                return true;
            }
```

ev is the editView it seems the first time it isn't focusing and input not showing.., it does work after collaps and expand again
my thinking is that at the first time the view is not attatched to window (this method works normally in android 4.0.4) so this function is somehow being called before the view creation or attaching not sure if it is an issue here..

**Comment by JakeWharton** [comment]
There is now a `SearchView` on the `dev` branch which does this. I suggest you look at what it's doing and copy its behavior (or simply use it instead).
