### ISSUE TITLE
enhancement to setAlphabeticShortcut in ActionMenuItem

### ISSUE THREAD

**Issue by levinotik** [JakeWharton/ActionBarSherlock#453]
Jake, I noticed that you wanted to make findItemWithShortcut a bit smarter in ActionMenu. Right now, it simply loops through the actionitems to see if there's a match between the keycode and the shortcut. Could it make sense to do something like this in setAlphabeticShortcut in ActionMenuItem:

``` java
 public MenuItem setAlphabeticShortcut(char alphaChar) {
        android.view.Window window = ((FragmentActivity)mContext).getWindow();
        View decor =window.getDecorView().findViewById(android.R.id.content);

        KeyEvent.DispatcherState ds = decor.getKeyDispatcherState();

        ds.startTracking(new KeyEvent(KeyEvent.ACTION_UP, getKeyCodeForChar(alphaChar)), decor);


        mShortcutAlphabeticChar = alphaChar;
        return this;
    }
```

where getKeyCodeForChar simply returns a keyCode based on something like 

``` java

HashMap<Character, Integer> keyCodeMap  = new HashMap<Character, Integer>();
        keyCodeMap.put('a', KeyEvent.KEYCODE_A);
```

I'm not fully up to speed on how the wrapping works here, so I'm not sure if I'm getting the right decorView or View altogether. But if we used something like this, then in ActionMenu, we could maybe do something smarter like 

``` java
Window window = (Window) parent.getWindow();
        View decor = window.getDecorView().findViewById(R.id.content);

        KeyEvent.DispatcherState ds = decor.getKeyDispatcherState();
        if (ds == null || !ds.isTracking(event))
            return null;
```

Wanted to hear your thoughts before I go forward with a pull request

**Comment by SimonVT** [comment]
The comment in ActionMenu is actually from the AOSP source, so it's Google who wants to make it smarter ;p

**Comment by levinotik** [comment]
@SimonVT Well there goes that lol. Thanks!
