### ISSUE TITLE
LinearLayout does not stretch the entire width of the dialog

### ISSUE THREAD

**Issue by westward** [JakeWharton/ActionBarSherlock#458]
Hello,

I need an activity, which looks like dialog, using for this an example from ActionBarSherlock demo (@style/Theme.Sherlock.Dialog). This activity contains the following layout:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#355555"
    android:orientation="vertical" >

```
<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:padding="@dimen/app_padding" >

    <TextView
        android:id="@+id/date"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="TextView"
        android:textColor="@color/date_color" />

    <TextView
        android:id="@+id/text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="TextView"
        android:textColor="@color/app_text_color" />
</LinearLayout>

<LinearLayout
    style="@style/HoloButtonBar"
    android:layout_width="match_parent"
    android:layout_height="wrap_content" >

    <Button
        android:id="@+id/list_btn"
        style="@style/HoloButton.Borderless"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:text="@string/btn_news_list" />

    <View
        android:layout_width="3px"
        android:layout_height="match_parent"
        android:background="@drawable/divider_vertical_holo_dark" />

    <Button
        android:id="@+id/ok_btn"
        style="@style/HoloButton.Borderless"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:text="@android:string/ok" />
</LinearLayout>
```

</LinearLayout>

Specifying match_parent for the root and the last LinearLayout, I'm expecting that my button bar occupies the entire width of the dialog. Unfortunately, when the dialog is displayed on a real device, the button bar looks like I specified for them the wrap_content width. They occupy only a small place in the lower left corner of the dialog. I have a screenshot, but don't know, how to attach a picture to this message.

Thanks in advance to all who can help solve this problem.
Best regards.

**Comment by SimonVT** [comment]
This is not related to ABS. You should try either stackoverflow or the android developers google group.

**Comment by westward** [comment]
Yes... you're right. Trying to remove ABS for this activity and its width does not change.

Okay, one more question, please. I think, ABS uses FakeDialogPhoneWindow.java code to get more comfortable width and height, than minimums to wrap content. Maybe you know, how to tell ABS to resize its contents according to the new dimensions?

**Comment by SimonVT** [comment]
ABS should behave the same as the native ActionBar. If there are any differences, feel free to report them. As for ActionBar functionality, use an appropriate forum (stackoverflow, android developers google group) for questions related to this.

**Comment by westward** [comment]
Please, try to understand me. Maybe I'm wrong, but I think that native ActionBar don't have an ability to show some activity that look like a floating dialog. And it is not nesessary, because with native ActionBar developer have all API 11+ system environment including Holo theme.

Jake make the excellent work and one of ABS cool features is ability to create an activity that looks like a Holo dialog. Another ABS cool feature is auto resizing this 'dialog' to be more bigger (and comfortable) if its contents are not so large. I think, this auto resize feature realized in FakeDialogPhoneWindow. Unfortunately, I have enough experience to quickly understand why when 'dialog' resized, its contents (LinearLayout with buttons) don't follows the parent's new dimensions.

Ok, thank you for response. If there is no other answers, I will close this issue.

**Comment by westward** [comment]
Okay, here is the possible and very simple workaround: ABS\res\layout folder, abs__dialog_title_holo.xml

```
<FrameLayout
    android:layout_width="wrap_content" android:layout_height="0dp"
```

change to

```
    android:layout_width="fill_parent"
```
