### ISSUE TITLE
Duplicated actions with Fragment / setRetainInstance(true)

### ISSUE THREAD

**Issue by schildbach** [JakeWharton/ActionBarSherlock#461]
I believe this is not connected to issue 460, so I'm opening a new one.

I've got a fragment that has both an options menu and shall retain its instance:

``` java
setRetainInstance(true);
setHasOptionsMenu(true);
```

Of course, it also has onCreateOptionsMenu() implemented the usual way:

``` java
public void onCreateOptionsMenu(final Menu menu, final MenuInflater inflater)
{
    inflater.inflate(R.menu.options, menu);
    super.onCreateOptionsMenu(menu, inflater);
}
```

Now when the "retain case" happens, for example when rotating the screen, action buttons are duplicated in the action bar. I think onCreateOptionsMenu is called multiple times, which I'd expect to not happen.

This is on Android 4.04 (Nexus Galaxy).

**Comment by SimonVT** [comment]
I'm gonna go ahead and guess you're adding the fragment in onCreate, even if it already exists.

**Comment by JakeWharton** [comment]
Provide full code sample please.

**Comment by schildbach** [comment]
I just compiled a sample project showing the bug but this issue tracker does not allow to attach files. Here is a pasted version of the Activity and the Fragment:

``` java
package de.schildbach.bug;

import android.os.Bundle;

import com.actionbarsherlock.app.SherlockFragmentActivity;
import com.actionbarsherlock.view.Menu;

public class MyActivity extends SherlockFragmentActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.main);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu)
    {
        getSupportMenuInflater().inflate(R.menu.activity_options, menu);

        return super.onCreateOptionsMenu(menu);
    }
}
```

``` java
package de.schildbach.bug;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.actionbarsherlock.app.SherlockFragment;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;

public class MyFragment extends SherlockFragment
{
    public MyFragment()
    {
    }

    @Override
    public void onCreate(final Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);

        setRetainInstance(true);
        setHasOptionsMenu(true);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
    {
        return inflater.inflate(R.layout.fragment, null);
    }

    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater)
    {
        inflater.inflate(R.menu.fragment_options, menu);

        super.onCreateOptionsMenu(menu, inflater);
    }
}
```

``` java
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >

    <item
        android:id="@+id/option"
        android:icon="@drawable/ic_launcher"
        android:showAsAction="always|withText"
        android:title="FFF"
        android:titleCondensed="f"/>

</menu>
```

**Comment by schildbach** [comment]
FYI: I just reproduced the bug on a Nexus One (Android 2.3.6).

**Comment by schildbach** [comment]
@SimonVT I'm adding the fragment via a layout file, which is a very common pattern.

**Comment by SimonVT** [comment]
Can reproduce with ABS, support lib and native implementation if Fragment doesn't have an id or tag. Can not reproduce on any of them if Fragment has an id or tag.

**Comment by JakeWharton** [comment]
So always include an ID and/or a tag for your fragments. Good to know moving forward. Thanks @SimonVT.

**Comment by schildbach** [comment]
This also happens if I use an id in landscape mode, but create the fragment in a ViewPager programmatically (and thus cannot set an id) in portait mode. Fragments in ViewPager cannot be assembled by a layout.

**Comment by schildbach** [comment]
Also, I think you should assert for an ID rather than letting this strange duplication issue happening.

**Comment by SimonVT** [comment]
Neither Fragment not ViewPager is a part of ABS, so any issue you're experiencing with these should be taken to the appropriate forums (stackoverflow or Android Developers on Google Groups).
There's no "letting" duplication issues happen. This is how Fragments work, it's up to you to ensure issues like this doesn't happen. If you need to give your fragments in a viewpager a specific ID, make an adapter that lets you give them that.

**Comment by schildbach** [comment]
> If you need to give your fragments in a viewpager a specific ID, make an adapter that lets you give them that.

Do you mean a PagerAdapter? How does that help to set an ID (@+id) on a fragment? Can you give an example?

**Comment by SimonVT** [comment]
It doesn't, but you can use the same tag in your xml and your adapter for the same fragment.

**Comment by schildbach** [comment]
How can I use a PagerAdapter to set tags on its contained fragments? This is not obvious from the JavaDoc.

**Comment by SimonVT** [comment]
By passing a tag to FragmentTransaction.add(...). Now, please take questions like this to the appropriate forums.

**Comment by supermanmwg** [comment]
You could add
 <activity
        android:name="MyActivity"
        android:configChanges="orientation|keyboardHidden|screenSize" />
