### ISSUE TITLE
android:configChanges="fontScale"

### ISSUE THREAD

**Issue by locationad** [JakeWharton/ActionBarSherlock#462]
If you switch the font size using "Settings -> Display -> Font Size" (e. g. from normal to large or extra large) the config change is not reflected by several components of Action Bar Sherlock.

The native implementation of the ActionBar, the CAB, overflow menu, collapsible actions (e. g. search) using the specific font settings based on the default font style definitions.

Some elements (e. g. the menus/ actions) using the new font settings, but not the action bar title / subtile / cab title.

**Comment by JakeWharton** [comment]
Is it reflected when you rotate the activity?

**Comment by locationad** [comment]
Unfortunately not. Specific elements are changing the font size except the action bar and the CAB.

**Comment by JakeWharton** [comment]
On what versions of Android are you seeing this behavior?
