### ISSUE TITLE
Weird action mode behaviour when rotating screen

### ISSUE THREAD

**Issue by schildbach** [JakeWharton/ActionBarSherlock#463]
All on Android 4.04, Nexus Galaxy.

For example, when I open an action mode in landscape, I get two buttons plus their titleCondensed plus an overflow menu. There would be enough space for a third button.

When I rotate this into portrait, no re-layouting happens in respect to which buttons and which titles to show. I'd expect to reduce to just the buttons without any titles. Instead, the action bar primary/secondary title is cut to an unreadable one char. Interestingly, if I open the action mode in portrait to start with, everything looks as expected.

**Comment by iNoles** [comment]
greater than or equal to 4.0, use system action bar
< 4.0, use compatibility

**Comment by Sleepybear** [comment]
ABS automatically uses the native action bar on 4.0+, so this might be an ICS bug. Try testing it without ABS if you can.

**Comment by pierrre** [comment]
Do you use android:configChanges="orientation" ?

**Comment by schildbach** [comment]
When I include 'orientation' in configChanges, ABS does not adapt to the changed config. This means labels do not dis/appear.

When I don't include 'orientation' in configChanges, the action mode entirely disappears when rotating the device.

Both behaviours are not expected. I'd expect the action mode to not disappear unless explicitely instructed by API or user. Stil, the action mode should adapt to config changes.

**Comment by SimonVT** [comment]
ABS does not support android:configChanges="orientation" yet. It is not recommended doing this anyway.
And yes, ActionMode disappearing on configuration changes is entirely expected. It's how the native ActionBar works.

**Comment by pierrre** [comment]
+1 @SimonVT 
android:configChanges="orientation" is not recommended

**Comment by schildbach** [comment]
Take a look at Google Mail for Android. Its ActionMode stays open during orientation changes. The ActionBar overflow menu also stays open (even with ABS).

**Comment by schildbach** [comment]
Who does not recommend android:configChanges="orientation"? It's perfectly valid, and in some cases its preferable to tearing down the activity. Most system UI components support config changes, the action bar should do as well. Though I admit that if the original implementation does not do this it should be fixed there first.

**Comment by SimonVT** [comment]
It takes very few lines of code to re-start the ActionMode in onCreate, making it appear like it was never closed. Again, the default behavior is that it disappears.

**Comment by SimonVT** [comment]
http://developer.android.com/guide/topics/resources/runtime-changes.html
"This technique should be considered a last resort when you must avoid restarts due to a configuration change and is not recommended for most applications."

But still, ABS does not support it. There's already an issue open for this.
If you still have an ABS specific issue (as in, only happens with ABS, not the native implementation), please supply a sample showing this behavior, as well as an identical sample using the native implementation which does not show the same behavior. I'll be happy to take a look at it. Make sure your samples do not handle orientation changes.

**Comment by misapeic** [comment]
Already reported as Android bug: http://code.google.com/p/android/issues/detail?id=20493&q=configchanges&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
