### ISSUE TITLE
Can't  build with maven

### ISSUE THREAD

**Issue by manupeco** [JakeWharton/ActionBarSherlock#464]
HI,
I have downloaded the library and I tried to launch "mvn clean install".

When the process reach the Demos I get a list of "No resource found" like this:

\JakeWharton-ActionBarSherlock-4.
0.1-0-g8fcee10\JakeWharton-ActionBarSherlock-1a51cf7\samples\demos\target\unpack
\apklibs\com.actionbarsherlock_library_apklib_4.0.1\res\drawable\abs__tab_indica
tor_holo.xml:32: error: Error: No resource found that matches the given name (at
 'drawable' with value '@drawable/abs__tab_unselected_pressed_holo').

How can I get rid of all the errors?

Thanks
Emanuele Pecorari

**Comment by zhen9ao** [comment]
Are you using the HEAD of master branch, cause your error message shows it's version `4.0.1`, it should be `4.0.2` now.

**Comment by manupeco** [comment]
Same errors with 4.0.2. If I go to "\JakeWharton-ActionBarSherlock-4.
 0.1-0-g8fcee10\JakeWharton-ActionBarSherlock-1a51cf7\samples\demos\target\unpack
 \apklibs\com.actionbarsherlocklibrary_apklib_4.0.2\res\drawable\" folder the resource is not present. It is present in "drawable-hdpi". Why my build process doesn't pick the resource from the folder where it is present?

**Comment by zhen9ao** [comment]
Try the latest code, it should be `JakeWharton-ActionBarSherlock-4.0.2-0-gcf437ed`

**Comment by manupeco** [comment]
It is exactly what I've tried. If I go to \JakeWharton-ActionBarSherlock-4.0.2-0-gcf437ed\JakeWharton-ActionBarSherlock-2eabf25\samples\demos\target\unpack\apklibs\com.actionbarsherlock_library_apklib_4.0.2\res\drawable the resources is not present. It is present in drawable-hdpi...why it isn't recognized?

**Comment by manupeco** [comment]
Can it be a problem of the Android maven plugin? It seems it can't manage the hierarchy of the drawable folders. If a resource is not present in the drawable, it should search in the other drawable-\* folders. Am I wrong?

**Comment by JakeWharton** [comment]
Hi @manupeco. If you still were unable to get the project to build, please post to the mailing list at http://abs.io/forum. GitHub issues aren't the best place to have a back-and-forth about what's going on. Please include what version of Maven you are using.
