### ISSUE TITLE
= vs. == in a few places

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#465]
These were exposed by the appropriate compiler warning:

MenuBuilder:  Lines 1233 and 1255
ActionBarContainer: Line 234

Lines numbers as per the 4.0.2

**Comment by SimonVT** [comment]
Doesn't seem like an error, as it's the only place those variables are assigned. It might be bad style, but it's how they chose to do it in AOSP.

**Comment by androidmoney** [comment]
You are right -- wow -- I cannot believe they write code like that and it's not caught in the code review....
