### ISSUE TITLE
menuitem.setVisible(true) has no effect after visibility of all MenuItems has been set to false on ICS

### ISSUE THREAD

**Issue by hoelle** [JakeWharton/ActionBarSherlock#467]
I'm having 6 different MenuItems in the ActionBar, whereas at most 2 are visible depending on the application's state.

Because the application's state depends on dynamically loaded content I decided to hide all MenuItems in the beginning. Then I wanted to make those visible again, that the apps state requires to be.
I tried to hide the MenuItems in onCreateOptionsMenu() with MenuItem.setVisible(false) and within the menu XML with android:visible="true".

Once all MenuItems that are in the menu XML are invisible I can't show one or more of them up again.
I discovered that if at least one MenuItem stays visible, the bug is not present.

I could only detect this bug on ICS. Gingerbread works for me. I could not yet test it on Honeycomb.
running ABS 4.0.2

**Comment by JakeWharton** [comment]
If the bug is present on ICS only then it is a platform bug and not a library bug. ABS uses the native action bar when running on ICS. Can you reproduce the bug on an activity that's not using ActionBarSherlock?

**Comment by hoelle** [comment]
You are totally right. It has to be a plattform bug. 
Thank you!

**Comment by steveej** [comment]
ABS 4.1.0
Android Emulator using API8

i have the described behaviour too.
i create two invisible items in onCreateOptionsMenu().
in a TextWatcher on a EditText, i want to make those items visible again, with no success.

but if a only make one item invisible, the other one shows up on a textchange.

**Comment by chengbo** [comment]
I think you can set menu's state in onPrepareOptionMenu, and once your application's state is changed, call invalidateOptionsMenu, it works for me.

**Comment by stephanenicolas** [comment]
That's right, here is some sample code: 

``` java
@Override
    public boolean onPrepareOptionsMenu(Menu menu) {
        MenuItem menuItemCollapse = menu.findItem(R.id.menu_collapse);
        MenuItem menuItemExpand = menu.findItem(R.id.menu_expand);

        menuItemCollapse.setVisible(isSelectionModeActive);
        menuItemExpand.setVisible(!isSelectionModeActive);
        return true;
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getSupportMenuInflater().inflate(R.menu.menu_gallery, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean expandClicked = item.getItemId() == R.id.menu_expand;
        setSelectionModeActive(expandClicked);
        return true;
    }

```

**Comment by snooplsm** [comment]
if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.ICE_CREAM_SANDWICH) {
    invalidateOptionsMenu();
}

**Comment by KyleJahnke** [comment]
On my ICS device, setVisible also sometimes did not work, I fixed it by using view's .post(Runnable) method to put the setVisible method on the UI thread. I don't know why it works, but it does. Alternative to using the invalidateOptionsMenu.

**Comment by dinhvandev** [comment]
Hi all.
I have same problem but on Android 4.2.2
I have left menu for Activity when I choose one option in menu I will use replace Fragment by New Fragment
And I change some menu to hide but It hide in seconds and show again when loaded fragment
Pls let me know How to fix it
Thanks

**Comment by meetmehdi** [comment]
i am facing same problem. Any one can help?

**Comment by trinadhkoya** [comment]
Hi All,I have a problem with My Fragment .I Added a Menu item for a single fragment for what i need .It works fine ,But when i go for another fragment , it reflects the same (menu item ) showing.I have only one Activity FYI.
