### ISSUE TITLE
Collapsed tab navigation doesn't wrap text

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#468]
Please see the 2 screenshots, one running in an emulated ICS (4.0.3) session, the other a Nexus One running Gingerbread.  Notice how the the ABS implementation ellipsizes the text while the native implementation wraps the text.

Native:

https://docs.google.com/open?id=0B4cv2-AZ4shrTGR4LWZtOXNnN2s

ABS:

https://docs.google.com/open?id=0B4cv2-AZ4shrekU4d2tXX2pVa2c

**Comment by JakeWharton** [comment]
The library doesn't control text wrapping. It's entirely dependent on what
layout you use for your adapter.
On May 12, 2012 3:49 AM, "Tom" <
reply@reply.github.com>
wrote:

**Comment by androidmoney** [comment]
Well, I am not specifying an adapter.  It's the tab navigation style that turns into a list when there are too many tabs to show.

The screenshots show the result of identical code running on ICS vs. ABS on 800x480 screen size.  I would expect identical results on both.

**Comment by androidmoney** [comment]
Sorry, it's the Tab Navigation style, that turns into the drop down list when the screen is in landscape orientation on a small screen device.

**Comment by JakeWharton** [comment]
I was not able to reproduce this behavior. The following are two screenshots from a modified version of the "Tab Navigation" demo running on Android 2.3.3.

![](http://i.imgur.com/kXUt1.png)

![](http://i.imgur.com/yY2Tb.png)

Can you provide more information about how you were able to produce this? A test case (as a .zip or just the paste of the activity code) and the exact configuration that you used to create an emulator would be ideal.

**Comment by androidmoney** [comment]
Hi, I can put something together if needed, but maybe the difference is that I had one "long" word vs a few shorter words?

**Comment by JakeWharton** [comment]
Yes, probably. You are also likely seeing less text because of #427 which reduces the width of collapsed tab navigation because of some bug in the way Android measures views. Once a workaround for that bug is found you may see an additional word displayed before the ellipses.

**Comment by androidmoney** [comment]
Not sure.  The width appears to be the same/very close in both cases.  Can
you modify your test case and just change it to one long word?  My guess is
that this will come down to some difference in the word breaking algorithm
used on different platforms.
On May 14, 2012 11:30 AM, "Jake Wharton" <
reply@reply.github.com>
wrote:
