### ISSUE TITLE
ActionBar fades on the sides on API<14

### ISSUE THREAD

**Issue by martenlienen** [JakeWharton/ActionBarSherlock#470]
Hi,
the action bar fades on the sides if the API version is <14. With theme Theme.Sherlock.Light this looks like this:
http://s14.directupload.net/file/d/2888/9rielw5p_png.htm

ActionMode looks similar. As I analyzed this with hierarchyviewer, the effect has to be applied in ActionBarContainer, but I don't quite get the source code yet.

Thanks in advance,
CQQL

**Comment by martenlienen** [comment]
I still don't know, what triggered this but I fixed it by increasing the target version from 14 to 15.

**Comment by JakeWharton** [comment]
Looks like it was a bad build of the 9-patch drawables. Make sure your developer tools are up to date (and ADT plugin if you use eclipse).
