### ISSUE TITLE
Applying a native ICS actionDropDownStyle style value causes an invalid background to be displayed pre-4.0 in tab navigation mode

### ISSUE THREAD

**Issue by jgilfelt** [JakeWharton/ActionBarSherlock#473]
When I run the `styled` sample application straight out of the box (which uses a custom `actionDropDownStyle` whose parent is `Widget.Sherlock.Light.Spinner.DropDown.ActionBar`), on pre-4.0 devices I see a strange background artefact when the Action Bar is in tab navigation mode. The background container layout for the tabs appears to be using the custom default spinner background drawable:

![styled1](http://dl.dropbox.com/u/3982805/device-abs-styled1.png)

The problem goes away if I comment out the following item from the applied theme `Theme.AndroidDevelopers`:

```
<!-- <item name="android:actionDropDownStyle">@style/MyDropDownNav</item> -->
```

![styled2](http://dl.dropbox.com/u/3982805/device-abs-styled2.png)

...but the custom list/spinner background style is then not applied for ICS devices using the native Action Bar.

How can I create a custom style for both `actionDropDownStyle` and `actionBarTabStyle` in the same theme?

**Comment by JakeWharton** [comment]
Will take a look today. This sample was designed for the Android 3.0 action bar and was never updated to the Android 4.0 action bar so it's not unusual to find some things a bit off.

**Comment by JakeWharton** [comment]
Are you sure this wasn't just a bad `R.java`? I don't see this bug on one of our pre-ICS test phones:

![](http://i.imgur.com/jaHGW.png)

**Comment by jgilfelt** [comment]
Oops I should have tested more thouroughly. Looks like it is only reproducible on the Sony Ericsson Gingerbread roms (well my Xperia Play and X10i anyway). 

A workaround is to specify `values-v14` styles seperately.

I will include https://github.com/romainguy/ViewServer and see if I can figure out what's going on with these devices.
