### ISSUE TITLE
Layout problem in ActionMode

### ISSUE THREAD

**Issue by Konsumierer** [JakeWharton/ActionBarSherlock#475]
ABS Version 4.0.2
Android Version: 2.3.7

When adding menu items without icon, the layout gets broken, see picture.
The menu items are added like this: menu.add("Abgeben").setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM);

![Screenshot](http://s14.directupload.net/images/120515/n4izzlbk.png)

**Comment by SimonVT** [comment]
Can reproduce on ICS. Framework bug.
Protip: Use icons

**Comment by Konsumierer** [comment]
Yes, I will use icons, just came across this bug while playing around.

**Comment by JakeWharton** [comment]
File it on http://b.android.com so it's fixed in the next version of Android!

**Comment by JakeWharton** [comment]
ABS mimics API 14 which has this bug therefore we sadly cannot fix.
