### ISSUE TITLE
Split actionbar with pager - delayed action click

### ISSUE THREAD

**Issue by antoniy** [JakeWharton/ActionBarSherlock#476]
ABS version: 4.0.2
Android version: 2.x

I observe unexpected behavior when using split actionbar with pager. I implemented pager + actionbar tabs type of navigation and I added single action on my fragments inside the pager. When you click the tabs or swipe the pager, each fragment provides its own actions to the actionbar. And as I said - the actionbar is in split mode. 

When you enter the activity with the describe above type of navigation, the initial visible fragment and it's action items work fine. When you swipe to another fragment though, the action items become not clickable and you may click multiple times but nothing happens. It's only when you click different tab (or swipe to different fragment), all the clicks you've made are fired and it's clear it becomes a mess.

I reproduced this behavior with ABS Fragment demo application - just set the "Tabs and Pager" activity to use split actionbar ui in the manifest.

If you need any additional information that I could provide, please tell me.

Regards,
Antoniy

**Comment by JakeWharton** [comment]
Dupe #471. This is caused by some sort of race condition in `ViewPager` and not ABS. If you removing the paging functionality the split action bar works just fine. No workaround is currently known.

**Comment by antoniy** [comment]
Sorry for the duplicate and thank you for the quick response.

**Comment by antoniy** [comment]
Let me just update the issue. I found a working workaround for me. Instead of set the action items inside each fragment and give ViewPager the chance to mess everything up, I update action items for each fragment from the container fragment activity. I do this each time the user swipe the fragments from onPageSelected() callback method for ViewPager. By also do invalidateOptionsMenu() from this method to the containing fragment we gain faster actionbar redraw instead of wait of swipe animation to finish.

**Comment by jmcaffee** [comment]
Ahh! The answer (or at least a workaround).

Thanks for the tip @antoniy. I wrote a post detailing how I implemented your suggestion here: http://www.ktechsystems.com/actionbar-menu-items-firing-delayed-events/

**Comment by antoniy** [comment]
I'm glad my solution was useful to you.

Cheers,
Antoniy

**Comment by hjudez** [comment]
@antoniy, don't you have to clear the menu before you inflate it in onPrepareOptionsMenu? If I don't clear it the menu keeps growing with repeated icons every time the overflow menu opens.

**Comment by antoniy** [comment]
@hjudez, actually I haven't used onPrepareOptionsMenu() but only onCreateOptionsMenu() and when need to redraw - invalidateOptionsMenu() method on the Activity triggers the new invocation of onCreateOptionsMenu() and there is no old garbage. I chose this way because I didn't do any updates on the actions but rather I replace them all for each selected fragment.

**Comment by hjudez** [comment]
Inflating a dummy menu with an android:showAsAction="never" item from the Activity onCreateOptionsMenu() and then inflating the real menus from each Fragment onCreateOptionsMenu() also seems to solve the issue. However the menu has to be cleared inside each Fragment´s onCreateOptionsMenu() before it is inflated in order to remove the dummy item that was added by the Activity.

**Comment by antoniy** [comment]
I don't quite understand your workflow. What is the dummy menu for? And if you feel you need to clear the menu for your use-case, by all means - clear the menu. :) In my use-case I don't need to touch the actionbar from within the fragments. This is taken care of the container Activity. The Activity tracks which fragment is visible and set the appropriate actions for the current fragment.

**Comment by hjudez** [comment]
Sorry, my english is not really good. Here https://github.com/JakeWharton/ActionBarSherlock/issues/442#issuecomment-9959173 @TimMackenzie explains the solution. With this approach you can then let the fragment handle the menu creation as expected and you will not have to change anything at the Activity.

**Comment by antoniy** [comment]
Ah, okay. I'll check it out. Thanks.
