### ISSUE TITLE
state_activated causes problems pre-HC

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#477]
state_activated was introduced in SDK 11 as a kind of replacement for state_focused.   ABS refers to this state attribute in abs__primary_text_holo_dark for instance.

Trying to inflate a DatePicker causes the following exception:  

/ACRA    ( 2666): android.view.InflateException: Binary XML file line #20: Error inflating class android.widget.DatePicker
/ACRA    ( 2666):      at android.view.LayoutInflater.createView(LayoutInflater.java:518)
/ACRA    ( 2666):      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
/ACRA    ( 2666):      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
/ACRA    ( 2666):      at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
/ACRA    ( 2666):      at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
/ACRA    ( 2666):      at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
/ACRA    ( 2666):      at android.app.DatePickerDialog.<init>(DatePickerDialog.java:124)
/ACRA    ( 2666):      at android.app.DatePickerDialog.<init>(DatePickerDialog.java:86)
/ACRA    ( 2666):      at com.zvasvari.anmoneyp.widget.DateView.showDatePicker(DateView.java:119)
/ACRA    ( 2666):      at com.zvasvari.anmoneyp.widget.DateView.performClick(DateView.java:98)
/ACRA    ( 2666):      at android.view.View$PerformClick.run(View.java:9080)
/ACRA    ( 2666):      at android.os.Handler.handleCallback(Handler.java:587)
/ACRA    ( 2666):      at android.os.Handler.dispatchMessage(Handler.java:92)
/ACRA    ( 2666):      at android.os.Looper.loop(Looper.java:130)
/ACRA    ( 2666):      at android.app.ActivityThread.main(ActivityThread.java:3683)
/ACRA    ( 2666):      at java.lang.reflect.Method.invokeNative(Native Method)
/ACRA    ( 2666):      at java.lang.reflect.Method.invoke(Method.java:507)
/ACRA    ( 2666):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
/ACRA    ( 2666):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
/ACRA    ( 2666):      at dalvik.system.NativeStart.main(Native Method)
/ACRA    ( 2666): Caused by: java.lang.reflect.InvocationTargetException
/ACRA    ( 2666):      at java.lang.reflect.Constructor.constructNative(Native Method)
/ACRA    ( 2666):      at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
/ACRA    ( 2666):      at android.view.LayoutInflater.createView(LayoutInflater.java:505)
/ACRA    ( 2666):      ... 19 more
/ACRA    ( 2666): Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class android.widget.NumberPicker
/ACRA    ( 2666):      at android.view.LayoutInflater.createView(LayoutInflater.java:518)
/ACRA    ( 2666):      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
/ACRA    ( 2666):      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
/ACRA    ( 2666):      at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
/ACRA    ( 2666):      at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
/ACRA    ( 2666):      at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
/ACRA    ( 2666):      at android.widget.DatePicker.<init>(DatePicker.java:101)
/ACRA    ( 2666):      at android.widget.DatePicker.<init>(DatePicker.java:94)
/ACRA    ( 2666):      ... 22 more
/ACRA    ( 2666): Caused by: java.lang.reflect.InvocationTargetException
/ACRA    ( 2666):      at java.lang.reflect.Constructor.constructNative(Native Method)
/ACRA    ( 2666):      at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
/ACRA    ( 2666):      at android.view.LayoutInflater.createView(LayoutInflater.java:505)
/ACRA    ( 2666):      ... 29 more
/ACRA    ( 2666): Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class <unknown>
/ACRA    ( 2666):      at android.view.LayoutInflater.createView(LayoutInflater.java:518)
/ACRA    ( 2666):      at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
/ACRA    ( 2666):      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
/ACRA    ( 2666):      at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
/ACRA    ( 2666):      at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
/ACRA    ( 2666):      at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
/ACRA    ( 2666):      at android.widget.NumberPicker.<init>(NumberPicker.java:141)
/ACRA    ( 2666):      ... 32 more
/ACRA    ( 2666): Caused by: java.lang.reflect.InvocationTargetException
/ACRA    ( 2666):      at java.lang.reflect.Constructor.constructNative(Native Method)
/ACRA    ( 2666):      at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
/ACRA    ( 2666):      at android.view.LayoutInflater.createView(LayoutInflater.java:505)
/ACRA    ( 2666):      ... 38 more
/ACRA    ( 2666): Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x1010350 a=2}
/ACRA    ( 2666):      at android.content.res.Resources.loadColorStateList(Resources.java:1804)
/ACRA    ( 2666):      at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
/ACRA    ( 2666):      at android.widget.TextView.<init>(TextView.java:659)
/ACRA    ( 2666):      at android.widget.EditText.<init>(EditText.java:58)
/ACRA    ( 2666):      at android.widget.EditText.<init>(EditText.java:54)
/ACRA    ( 2666):      ... 41 mor

The solution is, of course, to create a color-v11 with state_activated and a base color resource with state_focused.

**Comment by SimonVT** [comment]
What device is this happening on?

**Comment by androidmoney** [comment]
Nexus One.Stock GB

**Comment by androidmoney** [comment]
This is actually not your problem -- the I still think the state_activated stuff should be factored out as who knows what happens on other devices when getting an unknown state_\* constant.
