### ISSUE TITLE
ICS ForceOverflow is actually possible

### ISSUE THREAD

**Issue by cherrydev** [JakeWharton/ActionBarSherlock#478]
I'm not sure how 'hacky' we want things to get here, but I've noticed a number of people complain that ForceOverflow doesn't work on ICS.  Personally, I think it's a terrible UI decision of Google to remove the indicator that informs the user that they have extra options to work with.  This forces the user to 'try' the menu button in order to determine if there are other things to do.

So, the overflow menu on ICS displays based on a single variable:  If there's a hard menu button, it will never show the overflow menu.  If there isn't a hard menu button, it will always show it.  It doesn't matter what size the screen is.  it determines if there is a hard menu button using the ViewConfiguration class, which turns out to be fairly trivial to hack.  The following code works:

``` java
if (Build.VERSION.SDK_INT >= 14) {
            ViewConfiguration config = ViewConfiguration.get(this);
            try {
                Field f = ViewConfiguration.class
                        .getDeclaredField("sHasPermanentMenuKey");
                f.setAccessible(true);
                if (f != null) {
                    f.set(config, false);
                    log.info("Successfully hacked permanent menu key");
                }
            } catch (Exception ex) {
                log.info("Unable to hack permanent menu key", ex);
            }
        }
```

Currently, I put this in my Application class, but it should be fairly simple to do with ActionBarSherlock.  As long as this gets run before the action menu gets laid out, you will then see the overflow menu (if there are enough items to show it).

So, this issue has been closed several times before based on the assumption that it wasn't possible to implement.  It clearly is possible, but do you want to take this approach?

**Comment by JakeWharton** [comment]
This will absolutely not be included in ActionBarSherlock simply based on the principle of delegating to the native behavior on the newest versions of the platform.

However, I admire your initiative in finding a solution however 'hacky' it may seem. Changing something like this may also have other side-effects that you should be mindful of and look out for.

Thanks for posting it though!
