### ISSUE TITLE
Split Action Bar 'hints' in the wrong location

### ISSUE THREAD

**Issue by cherrydev** [JakeWharton/ActionBarSherlock#481]
When you long-press an action bar item that does not have the text displaying, a 'hint' overlay appears, showing you the text for the item.  When the action bar is split and the icons are on the bottom, the hint overlay is still displaying on the top.  This incorrect behaviour is seen on pre-ICS but correct behaviour is seen on ICS.

**Comment by cherrydev** [comment]
Here's a screenshot:

![Screenshot](http://i.imgur.com/qqHAg.png)

**Comment by JakeWharton** [comment]
Can you provide a sample? Perhaps add to the 'knownbugs' sample and send a pull request?

**Comment by cherrydev** [comment]
I do not currently have a sample that I can extract from my larger code-base, but it should be trivial to reproduce:

In AndroidManifest.xml

``` xml
…
<application etc… android:uiOptions="splitActionBarWhenNarrow">
…
```

Create any menu resource with an icon and title, but without the title showing, such as:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:id="@+id/menu_search" android:showAsAction="always"
        android:title="Search" android:icon="@android:drawable/ic_menu_search"></item>
</menu>
```

Create any SherlockActivity, apply that menu resource as the options menu and then long-tap the icon on the action bar (which should be on the bottom, since the actionbar is set as split).  You will see a toast-style overlay that displays "Search" but is at the top of the screen (like the screenshot) instead of the bottom.

For reference, the screenshot was taken on a Nexus S running OS 2.3.6.  The Activity was a descendent of SherlockFragmentActivity.  If this isn't trivially reproducible, please let me know and I will find some extra time to package up a self-contained sample.

**Comment by JakeWharton** [comment]
Cannot reproduce. If you can create a reproducible test case, please submit a pull request with an example added to the 'knownbugs' sample and mention this issue number in the description and I'll re-open.

![](http://i.imgur.com/B5PYu.png)

**Comment by victorelli17** [comment]
This problem occurs when using the SherlockFragment class. 
![device-2013-03-16-205631](https://f.cloud.github.com/assets/3587219/267366/aa3fc4c2-8e7b-11e2-86f9-7e39594e673d.png)
