### ISSUE TITLE
FragmentTransaction is returning null on tab listener

### ISSUE THREAD

**Issue by geekkoz** [JakeWharton/ActionBarSherlock#482]
FragmentTransaction is returning null on tab listener

**Comment by JakeWharton** [comment]
Are you using `SherlockFragmentActivity`?

---

Jake Wharton
http://about.me/jakewharton

On Thu, May 17, 2012 at 3:26 PM, Julian Cardona <
reply@reply.github.com

**Comment by geekkoz** [comment]
Sorry bro, my mistake ;) i just realizing that when your email arrive. Thanks a lot ... awesome job!!.
