### ISSUE TITLE
menu key in ActionMode does not work

### ISSUE THREAD

**Issue by schildbach** [JakeWharton/ActionBarSherlock#483]
If using ABS with the "force overflow" feature, you can still use the (hardware) menu key to expand the overflow menu. However, this does not work in an ActionMode. The menu key is just ignored.

This is with ABS 4.1 on Android 2.3.6 (Nexus One).

**Comment by JakeWharton** [comment]
As per #241 we disable the hardware menu key when action modes are shown.

**Comment by schildbach** [comment]
Why is the menu key handling inconsistently handled between ActionBar and ActionMode? I'd expect it to be handled consistently: Either it shows the overflow menu or not.

**Comment by JakeWharton** [comment]
No clue. I'm just imitating what ICS does. Feel free to file a bug on
http://b.android.com to have the behavior changed and link to it here.

---

Jake Wharton
http://about.me/jakewharton

On Fri, May 18, 2012 at 3:31 PM, Andreas Schildbach <
reply@reply.github.com

**Comment by lodlock** [comment]
You can always capture the keyevent for the menu button and have to do your bidding. Personally I have it finish my ActionMode and then return the super so that it's business as usual. So something like:

```
@Override
public boolean onKeyDown(int keycode, KeyEvent event) {
    if (keycode == KeyEvent.KEYCODE_MENU) {
        if (mMode != null) {
            mMode.finish();
        }
    }
    return super.onKeyDown(keycode, event);
}
```
