### ISSUE TITLE
Android 2.1 crush when adding animation xml file to project

### ISSUE THREAD

**Issue by Ashot-KR** [JakeWharton/ActionBarSherlock#486]
Application crushes when activity extends one of the Sherlock activities (for example SherlockListActivity) and any animation xml file added to project. Animation do not using in code. Here is logcat messages

05-20 18:30:34.451: W/dalvikvm(226): threadid=3: thread exiting with uncaught exception (group=0x4001b188)
05-20 18:30:34.451: E/AndroidRuntime(226): Uncaught handler: thread main exiting due to uncaught exception
05-20 18:30:34.504: E/AndroidRuntime(226): java.lang.RuntimeException: Unable to start activity ComponentInfo{w.t.f/w.t.f.WtfActivity}: android.view.InflateException: Binary XML file line #31: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.app.ActivityThread.access$2200(ActivityThread.java:119)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.os.Handler.dispatchMessage(Handler.java:99)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.os.Looper.loop(Looper.java:123)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.app.ActivityThread.main(ActivityThread.java:4363)
05-20 18:30:34.504: E/AndroidRuntime(226):  at java.lang.reflect.Method.invokeNative(Native Method)
05-20 18:30:34.504: E/AndroidRuntime(226):  at java.lang.reflect.Method.invoke(Method.java:521)
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
05-20 18:30:34.504: E/AndroidRuntime(226):  at dalvik.system.NativeStart.main(Native Method)
05-20 18:30:34.504: E/AndroidRuntime(226): Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.createView(LayoutInflater.java:513)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:565)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:618)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:621)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.generateLayout(ActionBarSherlockCompat.java:1042)
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:912)
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.initActionBar(ActionBarSherlockCompat.java:137)
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchPostCreate(ActionBarSherlockCompat.java:306)
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.actionbarsherlock.app.SherlockListActivity.onPostCreate(SherlockListActivity.java:81)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1108)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2478)
05-20 18:30:34.504: E/AndroidRuntime(226):  ... 11 more
05-20 18:30:34.504: E/AndroidRuntime(226): Caused by: java.lang.reflect.InvocationTargetException
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.actionbarsherlock.internal.widget.ActionBarView.<init>(ActionBarView.java:235)
05-20 18:30:34.504: E/AndroidRuntime(226):  at java.lang.reflect.Constructor.constructNative(Native Method)
05-20 18:30:34.504: E/AndroidRuntime(226):  at java.lang.reflect.Constructor.newInstance(Constructor.java:446)
05-20 18:30:34.504: E/AndroidRuntime(226):  at android.view.LayoutInflater.createView(LayoutInflater.java:500)
05-20 18:30:34.504: E/AndroidRuntime(226):  ... 24 more
05-20 18:30:34.504: E/AndroidRuntime(226): Caused by: java.lang.NullPointerException
05-20 18:30:34.504: E/AndroidRuntime(226):  at com.actionbarsherlock.internal.widget.ActionBarView$HomeView.setUp(ActionBarView.java:1302)
05-20 18:30:34.504: E/AndroidRuntime(226):  ... 28 more

SherlockActionBar version 4.0.2

**Comment by SimonVT** [comment]
Doesn't sound like an ABS error. Try clean project. I have several animations in my projects, and have never experienced this.

**Comment by Ashot-KR** [comment]
Oh, i just clean sherlock action bar project and it works
