### ISSUE TITLE
ActionBar Tabs do not register key presses after configuration change

### ISSUE THREAD

**Issue by mcsarge** [JakeWharton/ActionBarSherlock#488]
I have added android:configChanges="keyboard|keyboardHidden|orientation|screenSize"  so that I can manage configuration changes myself. The issue is after rotating the device from portrait to landscape the action tabs no longer register a key press. This is happening on my 2.3.3 Droid and 2.3.5 Samsung galaxy player, on my ICS device, the tabs work perfectly after a roatation.

You can see this if you do the following:

Change the manifest in the SampleList to add the configChange.

```
   <activity android:label="@string/tab_navigation" android:name=".TabNavigation" android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="com.actionbarsherlock.sample.demos.EXAMPLE"/>
        </intent-filter>
    </activity>
```

Then run the sample on a pre-3.0 and you will see that the tabs are dead when you rotate the device. Go back to the original position and the tabs work. This is the same if you start the application while in landscape mode, if you rotate to portrait the tabs no longer work, back to landscape and the work fine.

Matt

**Comment by SimonVT** [comment]
ABS does not currently support handling configuration changes. An issue has already been registered for this.

**Comment by mcsarge** [comment]
OH, thanks for the information, I will track that issue, this one in unneeded.
