### ISSUE TITLE
Please add localized strings resource

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#489]
Please add the localized text resources (values-XX/strings.xml) for at least the top dozen or so languages.  My app is localized, but the ABS texts show up in English and there is no obvious way for me to override them.

**Comment by necronet** [comment]
well I don't think that is ABS main concern…… you can perfectly added yourself and push it.……. also there are some person that just don't need to localized string in that dozen of languages. Maybe a full-language distribution for ABS. 

Remember is not a closed project you can fork it and change it anytime you want.

**Comment by SimonVT** [comment]
The strings are all defined in library/res/values/strings.xml. You can copy the languages you need from AOSP, and prefix the strings with abs__.

**Comment by androidmoney** [comment]
Hi, thanks.  I know how to add the missing strings, but that's not the point.  There are only about 10 strings used by ABS.  Adding the top 10 languages would generate an additional 100 strings.  The size increase is insignificant, but users not having to do maintain a separate branch is I think desirable.

**Comment by necronet** [comment]
yes but what SimonTV said makes sense, you can download the string that you need in those language from the AOSP (http://source.android.com/source/index.html) or go to Grepcode, it has a clone of the repo (http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.0.3_r1/frameworks/base/core/res/res/)

**Comment by JakeWharton** [comment]
Done on `dev`.
