### ISSUE TITLE
onActionModeStarted/onActionModeFinished() not called on ICS

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#491]
The above callbacks are not called when running a SherlockActivity derived Activity.   Those callbacks are called as expected when running on a pre-ICS device.

I tested this on a Galaxy Nexus running 4.0.3 and a Nexus One running 2.3.7.

This is a showstopper for me.

Thanks for your attention.

**Comment by Sleepybear** [comment]
If this is happening only on ICS it is more than likely a framework bug.

Try it on ICS without ABS and see if you can reproduce. If the behavior is not present on ICS without the ABS library then something needs to be investigated.

**Comment by androidmoney** [comment]
It is NOT happening on pure ICS, only on ABS.  Will investigate why as I need to have this fixed today.

**Comment by Sleepybear** [comment]
What version of ABS?

**Comment by iNoles** [comment]
did you call startActionMode function?

**Comment by Sleepybear** [comment]
Also, are you overriding the correct onActionMode... callbacks, with the com.actionbarsherlock Imports?

**Comment by androidmoney** [comment]
4.1

**Comment by androidmoney** [comment]
Of course.  I just changed all my code from Ics\* to the built-in Android classes and it works like a charm.  The action bar is shown, just the callbacks are not invoked.

**Comment by androidmoney** [comment]
These are my callbacks:

```
@Override
public void onActionModeStarted(ActionMode actionMode)
{
    super.onActionModeStarted(actionMode);

    this.selectBar = actionMode;
    onActionModeStatusChanged();
}


@Override
public void onActionModeFinished(ActionMode actionMode)
{
    super.onActionModeFinished(actionMode);

    this.selectBar = null;
    onActionModeStatusChanged();
    unselectAll();
}
```

The ActionMode object is of class com.actionbarsherlock.view.ActionMode.

**Comment by iNoles** [comment]
@androidmoney did you call startActionMode function?

**Comment by androidmoney** [comment]
By the way, should probably make onActionModeStarted(android.view.onActionModeStarted) final in SherlockActivity so it cannot be overridden accidentally, though it's not the issue in my case.

**Comment by androidmoney** [comment]
@iNotes, yes, I already replied to you.  Of course I call startActionMode or it wouldn't work on ICS.  The Action Bar is shown, just the callbacks are not invoked.  Please don't take me for a dummy.

**Comment by iNoles** [comment]
oh sorry, I wasn't sure you did or not.

**Comment by androidmoney** [comment]
Well, ActionModeNative never seems to call onActionModeStarted(com.actionbarsherlock.view.ActionMode).  Matter of fact, the only place onActionModeStarted(com.actionbarsherlock.view.ActionMode) is called from ActionModeCompat.  So it's not surprising it's not working.

I believe the native Activity would call onActionModeStarted(android.view.ActionMode) with the wrapped object, so I might be able to use it as a (fragile) work around.

**Comment by androidmoney** [comment]
Oh, I can't use that as a workaround as the android.view.ActionBar classes don't exist pre-ICS.  So this needs a real fix.

**Comment by Sleepybear** [comment]
Try override both onActionModeStarted(com.actionbarsherlock.view.ActionMode) and onActionModeStarted(android.view.ActionMode) for now and see if that will catch both situations.

**Comment by androidmoney** [comment]
@Sleepybear :  Cannot.  android.view.ActionMode doesn't exist pre-HC.

**Comment by androidmoney** [comment]
For now, I fixed it by changing ActionBarSherlockNative:

```
@Override
public ActionMode startActionMode(com.actionbarsherlock.view.ActionMode.Callback callback)
{
    if (DEBUG)
        Log.d(TAG, "[startActionMode] callback: " + callback);

    if (mActionMode != null)
    {
        mActionMode.finish();
    }
    ActionModeCallbackWrapper wrapped = null;
    if (callback != null)
    {
        wrapped = new ActionModeCallbackWrapper(callback);
    }

    //Calling this will trigger the callback wrapper's onCreate which
    //is where we will set the new instance to mActionMode since we need
    //to pass it through to the sherlock callbacks and the call below
    //will not have returned yet to store its value.
    mActivity.startActionMode(wrapped);

   // androidmoney -- Added the next 3 lines
    if (mActionMode != null && mActivity instanceof OnActionModeStartedListener)
    {
        ((OnActionModeStartedListener)mActivity).onActionModeStarted(mActionMode);
    }

    return mActionMode;
}




    @Override
    public void onDestroyActionMode(android.view.ActionMode mode)
    {
        mCallback.onDestroyActionMode(mActionMode);

      // androidmoney -- Added the next 3 lines
        if (mActivity instanceof OnActionModeFinishedListener)
        {
            ((OnActionModeFinishedListener)mActivity).onActionModeFinished(mActionMode);
        }
    }
```
