### ISSUE TITLE
Action Mode

### ISSUE THREAD

**Issue by DineshAnandan** [JakeWharton/ActionBarSherlock#493]
I have use navigation mode  tab(5 tabs) and when i start action mode the tab background color appears white

**Comment by Sleepybear** [comment]
Is this on ICS or pre-ICS? What version of ABS? Got a screen shot and/or sample code?

**Comment by JakeWharton** [comment]
Upgrade to 4.1.0 and this will be fixed.

**Comment by DineshAnandan** [comment]
Thank you it's work fine :)
