### ISSUE TITLE
Overflow item on ActionMode menu

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#494]
I don't know if this is a bug or not.

On pre-ICS devices, if the ActionMode  has more action buttons than what fits on the screen, the 3-dot overflow menu is shown.  I would expect that, just like with the normal ActionBar, the 3-dot menu not be shown and the user would have to press the Menu key to get the additional options.  But perhaps this is by design so the user would know there is more they can do.  

Please close this if this is indeed how an ICS device with a menu button works, which I don't have one to test.

**Comment by JakeWharton** [comment]
This is the behavior that ICS exhibits. See #241.
