### ISSUE TITLE
dev branch compiles unsuccessful

### ISSUE THREAD

**Issue by zhen9ao** [JakeWharton/ActionBarSherlock#495]
When compile with `mvn -X clean install`, error occur, it says:

> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] ActionBarSherlock (Parent) ........................ SUCCESS [0.425s]
> [INFO] ActionBarSherlock ................................. SUCCESS [19.251s]
> [INFO] Sample (Parent) ................................... SUCCESS [0.120s]
> [INFO] Sample: Demos ..................................... SUCCESS [33.900s]
> [INFO] Sample: Fragments ................................. SUCCESS [31.126s]
> [INFO] Sample: Known Bugs ................................ FAILURE [23.995s]
> [INFO] Sample: RoboGuice ................................. SKIPPED
> [INFO] Sample: Styled .................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1:49.443s
> [INFO] Finished at: Wed May 30 15:34:31 CST 2012
> [INFO] Final Memory: 19M/84M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:
> 2.9.1:checkstyle (default) on project sample-known-bugs: An error has occurred i
> n Checkstyle report generation. Failed during checkstyle execution: There are 8
> checkstyle errors. -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
> rg.apache.maven.plugins:maven-checkstyle-plugin:2.9.1:checkstyle (default) on pr
> oject sample-known-bugs: An error has occurred in Checkstyle report generation.
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
> .java:217)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
> .java:153)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
> .java:145)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
> ct(LifecycleModuleBuilder.java:84)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
> ct(LifecycleModuleBuilder.java:59)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBu
> ild(LifecycleStarter.java:183)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
> eStarter.java:161)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
> java:39)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
> sorImpl.java:25)
>         at java.lang.reflect.Method.invoke(Method.java:597)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
> cher.java:290)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
> a:230)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
> uncher.java:409)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
> 352)
> Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred
>  in Checkstyle report generation.
>         at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenR
> eport.java:131)
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
> BuildPluginManager.java:101)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
> .java:209)
>         ... 19 more
> Caused by: org.apache.maven.reporting.MavenReportException: Failed during checks
> tyle execution
>         at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeRe
> port(AbstractCheckstyleReport.java:278)
>         at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(Che
> ckstyleReport.java:348)
>         at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMaven
> Report.java:196)
>         at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenR
> eport.java:104)
>         ... 21 more
> Caused by: org.apache.maven.plugin.checkstyle.CheckstyleExecutorException: There
>  are 8 checkstyle errors.
>         at org.apache.maven.plugin.checkstyle.DefaultCheckstyleExecutor.executeC
> heckstyle(DefaultCheckstyleExecutor.java:212)
>         at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeRe
> port(AbstractCheckstyleReport.java:259)
>         ... 24 more

**Comment by JakeWharton** [comment]
Yeah it's been broken for a week or two now. Take a look in `sample/known-bugs/target/checkstyle-results.xml` for the things that are failing it.
