### ISSUE TITLE
ShareActionProvider - Unable to share text to Facebook/Twitter.

### ISSUE THREAD

**Issue by TipTopJat** [JakeWharton/ActionBarSherlock#498]
I am using ActionBarSherlock in my app and have taken the source code available here for my own needs. https://github.com/JakeWharton/ActionBarSherlock/blob/master/samples/demos/src/com/actionbarsherlock/sample/demos/ShareActionProviders.java

Instead of sharing an image, as shown in the source code, I am sharing some text.

However, I am only allowed to share the text via Gmail, Evernote and Skype! Facebook, SMS, Twitter aren't available in the drop down list.

This problem does not occur when sharing an image.

Can someone help me so I can share text on Social Media.

Also, would it be possible to share an image and text in the same intent?

Here is my code sharing text:

```
public boolean onCreateOptionsMenu(Menu menu) {
    // Inflate your menu.
    getSupportMenuInflater().inflate(R.layout.share_action_provider, menu);

    // Set file with share history to the provider and set the share intent.
    MenuItem actionItem = menu
        .findItem(R.id.menu_item_share_action_provider_action_bar);
    ShareActionProvider actionProvider = (ShareActionProvider) actionItem
        .getActionProvider();

    actionProvider.setShareHistoryFileName(ShareActionProvider.DEFAULT_SHARE_HISTORY_FILE_NAME);
    actionProvider.setShareIntent(createShareIntent());
    return true;
}


private Intent createShareIntent() {
    Intent shareIntent = new Intent(Intent.ACTION_SEND);
    shareIntent.setType("plain/text");
    shareIntent.putExtra(android.content.Intent.EXTRA_TEXT, text);  

    return shareIntent;
}
```

**Comment by JakeWharton** [comment]
The `ShareActionProvider` queries the built-in package manager for intent targets.

If anyone has anything further to add please comment on [the StackOverflow version](http://stackoverflow.com/questions/10825905/android-sharing-content-to-facebook-twitter-via-actionbarsherlock) of this post.
