### ISSUE TITLE
Implement Checkstyle On All Files

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#50]
Currently it only checks the library.

**Comment by necronet** [comment]
what do you mean with Checkstyle ?

**Comment by JakeWharton** [comment]
Checkstyle is a maven plugin which will check your Java files for various syntactical stylings (e.g., using spaces and not tabs, uppercase variable names for static final constants, etc.).

You can see the checkstyle file on the main library project [here](https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/checkstyle.xml). If you are using maven you can run the following command to perform the checks:

```
mvn clean checkstyle:checkstyle
```

The output will be in `target/checkstyle-result.xml`.

Currently it's only run on the library and the maps plugin. I'd eventually like to have it be run on all the files since there are some styling inconsistencies with the samples and tests...

**Comment by iNoles** [comment]
I made a shell file for checkstyle in my own project. 

java -jar checkstyle/checkstyle-5.4-all.jar -c checkstyle/checkstyle_checks.xml -r $1/src

**Comment by JakeWharton** [comment]
The maven plugin will run it on everything under the `src/` directory for a module. Problem is that you have to include the `checkstyle.xml` file in each module. I think all I have to do is define the path to it as a variable in the root `pom.xml` and then use that variable to pass to the plugin in each module.

Just haven't gotten around to it. Merging in ACLv4r4 is more important :)
