### ISSUE TITLE
Cannot hide titlebar when using Theme.Sherlock.Light.Dialog

### ISSUE THREAD

**Issue by likebobby** [JakeWharton/ActionBarSherlock#500]
Calling 

``` java
requestWindowFeature(Window.FEATURE_NO_TITLE) 
```

in an Activity with theme **Theme.Sherlock.Light.Dialog** does not hide the title bar on older Android versions (tested on 2.1 and 2.3). It does hide the dialog when using Android 4.

Or am I doing something wrong. My code:

``` java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        super.onCreate(savedInstanceState);
...
```

**Comment by JakeWharton** [comment]
You need to import `com.actionbarsherlock.view.Window` so that it secretly uses the `long` version of this method.
