### ISSUE TITLE
Unable to make fragment animations work

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#501]
I am trying to hide one fragment with a fade out animation but I have not managed to do it.

I am using ActionBarSherlock 4.0.1 (sorry, need to upgrade, will do it soon :)) and this is the code I wrote

```
    FragmentManager fm = getSupportFragmentManager();
            Fragment fragment = fm.findFragmentByTag("myfragment");
            if(fragment != null) {
    FragmentTransaction ft = fm.beginTransaction();
    ft.setCustomAnimations(android.R.anim.fade_in, android.R.anim.fade_out);
                ft.hide(fragment);
                                ft.commit();
            }   
```

I am targeting api level 15.

Do fragment animations work properly?

Thanks

M

**Comment by JakeWharton** [comment]
Fragments are part of the support library which is a dependency of ActionBarSherlock. Any problems with it can be posted on [StackOverflow](http://stackoverflow.com/questions/tagged/android), the [official Android developer mailing list](http://groups.google.com/group/android-developers), or [the Android bug tracker](http://b.android.com).
