### ISSUE TITLE
After Orientation Change causes Navigation Tabs to change to Navigation List, the List item does not change when page is swiped using ViewPager

### ISSUE THREAD

**Issue by HyprGeek** [JakeWharton/ActionBarSherlock#502]
The portrait mode has NAVIGATION_MODE_TABS enabled, and uses ViewPager to swipe between, say 5 tabs. Selecting a tab swipes the page, and swiping the page selects the specific tab.

When the phone is rotated, and orientation is changed to landscape, the Tabs change to List. Selecting an item from the List slides to that page, but swiping the page now does not change the item displayed in the List.

**Comment by JakeWharton** [comment]
Dupe #240
