### ISSUE TITLE
NineLinearLayout makes call to constructor not introduced until API Level 11

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#504]
public NineLinearLayout(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        mProxy = AnimatorProxy.NEEDS_PROXY ? AnimatorProxy.wrap(this) : null;
    }

The 3 parameter constructor of LinearLayout doesn't exist prior to API Level 11 and the app crashes if somebody calls this constructor of NineLinearLayout.

**Comment by JakeWharton** [comment]
It's never called by the library.

**Comment by androidmoney** [comment]
Then why have it there?

**Comment by JakeWharton** [comment]
It's part of the internal API so it may be conditionally used in future versions of the library.
