### ISSUE TITLE
"Progress" not working in demos in V4.1.0

### ISSUE THREAD

**Issue by agarwlGaurav** [JakeWharton/ActionBarSherlock#506]
In demos of v4.1.0 the progess demo which says "The action bar included a standard progress bar. The methods for accessing it are prefixed with 'support'. See the source for more information." Nothing happens if you press the Go button.

**Comment by JakeWharton** [comment]
On what phone are you attempting this on?

Here's it running on some of my devices:
- Nexus One: http://i.imgur.com/lb2jb.png
- Galaxy Nexus: http://i.imgur.com/9Jkpb.png

**Comment by agarwlGaurav** [comment]
I am attempting to do this on a Emulator which has Android 2.2

Here is the screenshot http://i.imgur.com/TBzBH.png

**Comment by JakeWharton** [comment]
If you look closely it's there. The high contrast of the ugly white system bar against the black background makes it hard to see.

http://i.imgur.com/oHhgq.png

It's easier to see with the white theme that it's actually there:

http://i.imgur.com/WmDVz.png
