### ISSUE TITLE
Issue with home

### ISSUE THREAD

**Issue by mitrejcevski** [JakeWharton/ActionBarSherlock#509]
Hi!
I am using collapsible view to make a search functionality on the action bar.
When I click on the action (search) the view is opening and the arrow < is shown to the left of the home icon. That is exactly what I need.
Then I tap the edit text and the keyboard is shown.
The problem is, when I click the home icon of the action bar, the arrow from the left is gone (OK), the search view is collapsed (OK), but the keyboard is still showing.
I have tried to catch the event in onOptionsItemSelected using android.R.id.home and with R.id.homeAsUp. It is not caching the event if I  don`t explicitly set DisplayHomeAsUpEnabled(true). But in that case the arrow < left of the home will be shown all the time.
Any suggestions?

**Comment by JakeWharton** [comment]
You need to implement `CollapsibleActionView` interface on the action view so that you get a callback when collapsed. This way you can dismiss the keyboard. See `SearchView` on the `dev` branch for an example of this.
