### ISSUE TITLE
Fix for Bug in ABS for dropdown action selection

### ISSUE THREAD

**Issue by dkadlecek** [JakeWharton/ActionBarSherlock#513]
Fix in ScrollingTabContainer; please incorporate into main code base (See hack comment):

   public void setTabSelected(int position) {
        mSelectedTabIndex = position;
        final int tabCount = mTabLayout.getChildCount();
        for (int i = 0; i < tabCount; i++) {
            final View child = mTabLayout.getChildAt(i);
            final boolean isSelected = i == position;
            child.setSelected(isSelected);
            if (isSelected) {
                animateToTab(position);
            }
        }

```
    // Hack to set selection in spinner mode
    if(mTabSpinner != null)
        mTabSpinner.setSelection(position);
}
```

**Comment by JakeWharton** [comment]
This bug cannot be fixed until it's fixed in Android. Otherwise behavior across the API levels would be inconsistent which is much worse than having the same bug on all API levels. Dupe #240.

**Comment by dkadlecek** [comment]
Jake, I've tested he fix and it works on all API levels. Just trying to help here.

**Comment by JakeWharton** [comment]
It fixes it for pre-ICS only. On API 14 and newer the native action bar is used which will still exhibit the bug.

**Comment by dkadlecek** [comment]
Ok, thanks Jake. We'll hack our version for now. It is meeting our client's needs.

d
