### ISSUE TITLE
Handling actionbar share item click + history problem

### ISSUE THREAD

**Issue by vekexasia** [JakeWharton/ActionBarSherlock#514]
If you're going to override the default behaviour of the share action provider click via the _setOnShareTargetSelectedListener_ method, you'll lose the ability to get the custom handled activities inside the history file.

Infact i did create a my own OnShareTargetSelectedListener 

``` java
  public boolean onShareTargetSelected(ShareActionProvider source, Intent intent) {
    if ("com.facebook.katana".equals(intent.getComponent().getPackageName()) && mFacebookSharer != null) {
      mFacebookSharer.doShare();
      return true;
    }
    return false;
  }
```

So, if the user chooses facebook i'm going to handle the share returning true.

The problem is: returning true will not push facebook inside the history file so it will not gain "rank" on the actionbarprovider menu.

I didn't want to change the library source code so I tried different approaches :  Reflection, writing my own ActionProvider, ... 

Every solution I tried was shitty and not elegant so I simply changed two java access tokens inside ActivityChooserModel.java 

Below, the patch file

``` patch
 diff --git a/actionbarsherlock/library/src/com/actionbarsherlock/widget/ActivityChooserModel.java b/actionbarsherlock/library/src/com/actionbarsherlock/widget/ActivityChooserModel.java
index 3792074..bcbebb8 100644
--- a/actionbarsherlock/library/src/com/actionbarsherlock/widget/ActivityChooserModel.java
+++ b/actionbarsherlock/library/src/com/actionbarsherlock/widget/ActivityChooserModel.java
@@ -93,7 +93,7 @@ import java.util.concurrent.Executor;
  *
  * @hide
  */
-class ActivityChooserModel extends DataSetObservable {
+public class ActivityChooserModel extends DataSetObservable {

     /**
      * Client that utilizes an {@link ActivityChooserModel}.
@@ -700,7 +700,7 @@ class ActivityChooserModel extends DataSetObservable {
      * @param historicalRecord The record to add.
      * @return True if the record was added.
      */
-    private boolean addHisoricalRecord(HistoricalRecord historicalRecord) {
+    public boolean addHisoricalRecord(HistoricalRecord historicalRecord) {
         synchronized (mInstanceLock) {
             final boolean added = mHistoricalRecords.add(historicalRecord);
             if (added) {
```

Note: There's also a typo :)

**Comment by JakeWharton** [comment]
The `ShareActionProvider` is a class provided by Android too and I can't deviate its API from what the Android version provides.

If you want something like this I suggest you copy the three classes and resources that go into `ShareActionProvider`, make the customizations you require, and use your version instead.

You can also, optionally, file a request on http://b.android.com to have this supported in the next version of Android.
