### ISSUE TITLE
Getting two action bars in 3.1, 3.2

### ISSUE THREAD

**Issue by eburnette** [JakeWharton/ActionBarSherlock#516]
This doesn't happen in Android 4 where the native implementation is used.

When I go into an ActionMode, the regular ActionBar is pushed down and a new bar for the mode appears on top (with the 'Done' button). Actions and menus in the regular ActionBar are still active. In Android 4, the ActionMode bar replaces or appears on top of the regular ActionBar so you can't see it or tap its actions and menus.

I could send a screenshot but I don't see a way to attach one here.

Using ActionBarSherlock version 4.1.0.

**Comment by noloman** [comment]
why don't you please just use an image uploading service so we can see what's happening?

**Comment by JakeWharton** [comment]
Are you talking about native action modes (e.g., when editing text in an `EditText`)? If so, there's no real way to prevent this without breaking other things.

If you want to fix this yourself, you need to override `onStartActionMode(android.view.ActionMode.Callback)`, call `startActionMode(com.actionbarsherlock.view.ActionMode.Callback)` with a wrapper around the original callback instance, and return `null` to prevent the native action mode.

The reason this cannot be done by the library is that this would cause `onClick` handlers declared in XML to inexplicably fail (see [this blog post](http://corner.squareup.com/2012/08/getting-to-the-bottom.html)).

**Comment by eburnette** [comment]
Yes, that is the one I’m talking about. Thanks for the workaround.
