### ISSUE TITLE
Wrong style of IcsSpinner with Theme.Sherlock.Light.DarkActionBar

### ISSUE THREAD

**Issue by yanchenko** [JakeWharton/ActionBarSherlock#518]
I'm using an

```
IcsSpinner sp = new IcsSpinner(this, null);
getSupportActionBar().setCustomView(sp);
```

which displays just fine with `Theme.Sherlock` & `Theme.Sherlock.Light` but with `Theme.Sherlock.Light.DarkActionBar` it looks as it would with `Theme.Sherlock.Light`.
The behavior is the same on 2.3 & 4.0.

**Comment by JakeWharton** [comment]
Use `getThemedContext()` from the action bar for creation. You also shouldn't be using that class on your own since it's marked as being part of the 'internal' packages to ABS and therefore is not guaranteed to even exist in future versions of the library.

**Comment by yanchenko** [comment]
Yeah, I've seen it's package name, but I need a thing like that now. Replacing `this` with `getSupportActionBar().getThemedContext()` didn't change anything. Are there any other options?

**Comment by JakeWharton** [comment]
I don't know. The control wasn't set up or designed to be used outside the context of list navigation. Make sure your adapter is using the appropriate context rather than the one from the activity.

**Comment by yanchenko** [comment]
Jake, thanks. Proper adapter context solved it.
