### ISSUE TITLE
ActionMode and back to normal Actionbar (nullpointer)

### ISSUE THREAD

**Issue by kumien** [JakeWharton/ActionBarSherlock#519]
I created ActionMode with few button for selection in ListView (like in Messegaes). Every time when user click on button I will manually do mode.finish(). Everything works. When I use OK button to stop Actionmode there is problem with list. Every long press doesn't work and after click on list I have NullPointerException.

W/System.err(28613): java.lang.NullPointerException
W/System.err(28613):    at com.android.internal.app.ActionBarImpl$ActionModeImpl.invalidate(ActionBarImpl.java:699)
W/System.err(28613):    at com.actionbarsherlock.internal.ActionBarSherlockNative$ActionModeWrapper.invalidate(ActionBarSherlockNa
va:282)
W/System.err(28613):    at com.yokemessenger.friends.Friends.increaseSelection(Friends.java:592)
W/System.err(28613):    at com.yokemessenger.friends.FriendsList$1.onItemClick(FriendsList.java:86)
W/System.err(28613):    at android.widget.AdapterView.performItemClick(AdapterView.java:292)
W/System.err(28613):    at android.widget.AbsListView.performItemClick(AbsListView.java:1060)
W/System.err(28613):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2516)
W/System.err(28613):    at android.widget.AbsListView$1.run(AbsListView.java:3170)
W/System.err(28613):    at android.os.Handler.handleCallback(Handler.java:605)
W/System.err(28613):    at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err(28613):    at android.os.Looper.loop(Looper.java:137)
W/System.err(28613):    at android.app.ActivityThread.main(ActivityThread.java:4575)
W/System.err(28613):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(28613):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(28613):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
W/System.err(28613):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
W/System.err(28613):    at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Can you create a sample to reproduce the problem?

**Comment by kumien** [comment]
I will try to do it today.

**Comment by kumien** [comment]
I found bug in my code so sorry to disturb you. I close this issue.

**Comment by zooter** [comment]
Hey Kumien, can you please post the fix? I am facing the same issue.
