### ISSUE TITLE
android.view.InflateException: Binary XML file line #35: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView

### ISSUE THREAD

**Issue by DHuckaby** [JakeWharton/ActionBarSherlock#520]
I am using ABS 4.1.0 and I am seeing this error on some devices but not all devices, its a pre-3.0 bug so its not a native issue. I am using an overlay ActionBar and it is crashing when I call getSupportActionBar within my SherlockFragmentActivity's onCreate method. This is the file the line number is referring to: https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/res/layout/abs__screen_action_bar_overlay.xml

My first assumption was that I was referencing later attributes within my actionBarStyle style but I am not. Here is what my actionBarStyle style looks like:

&lt;style name="ActionBar" parent="Widget.Sherlock.ActionBar"&gt;
        &lt;item name="displayOptions"&gt;showCustom&lt;/item&gt;
        &lt;item name="customNavigationLayout"&gt;@layout/activity_main_logo&lt;/item&gt;
&lt;/style&gt;

If you have any ideas on as to what is going on I would greatly appreciate it. Since I do not actually have the device it is difficult to test and debug, the user is using a Huawei u8110 but I have had similar reports on the Galaxy Mini.

**Comment by JakeWharton** [comment]
#446 dupe?

**Comment by DHuckaby** [comment]
The solution within that issue does not work in this instance.

**Comment by iNoles** [comment]
i wonder this line would fix the problem

< style name="ActionBar" parent="@style/Widget.Sherlock.ActionBar" >

**Comment by DHuckaby** [comment]
That shouldn't be an issue, you can define a parent that way. You can also do it with android defined themes like this 'android:Theme'. I have been doing it that way for years now without issues.

**Comment by JakeWharton** [comment]
There's may be a resource ID collision with different types due to the custom ROM. This one doesn't happen in code though so it'll be hard to work around... I'll see if we have either of those devices at work and try to reproduce.

**Comment by DHuckaby** [comment]
Shouldn't the resource ids be changes after a clean/recompile? I have sent my tester multiple builds so it should have fixed it if it was a collision right?

**Comment by JakeWharton** [comment]
No, the collision could stem from custom OEM ROMs using resource IDs that clash with the ones that were added in Honeycomb and/or ICS. Since we read those resource IDs on platforms prior to 3.0, we could be clashing with something that they added. This will be something that's going to be really hard to track down. I forgot to look for a matching device, but I will this weekend or Monday.

**Comment by DHuckaby** [comment]
This was not an ABS issue.
