### ISSUE TITLE
splitActionBarWhenNarrow does not work on Xperia P

### ISSUE THREAD

**Issue by samlu** [JakeWharton/ActionBarSherlock#522]
The android:uiOptions="splitActionBarWhenNarrow" does not work on Xperia P (2.3.7) device.
The same code works well on 2.3 emulator.

I found the problem is caused by loadUiOptionsFromManifest() function

In ActionBarSherlockCompat class, loadUiOptionsFromManifest()
Runs on Xperia P, it only iterates the following tags
manifest, uses-sdk, skin

Neither application nor activity tags when runs on Xperia P

**Comment by JakeWharton** [comment]
I do not have access to one of these. Are you able to debug why it's not iterating over the activities?

**Comment by samlu** [comment]
Yes, I am more than happy to debug for fixing this problem.
As I mentioned, I tried to dump each iterated tag in loadUiOptionsFromManifest(), but only got manifest, uses-sdk, skin three tags. Let me know what I can do for the next step.

**Comment by Juggeli** [comment]
The same issue persists also on Sony Xperia GO. Sadly i cant get the phone to work with adb so i can't debug the problem more closely.

**Comment by iNoles** [comment]
@Juggeli Did you turn on USB Debugging options? If you type adb devices, it should have your phone device here.

**Comment by Juggeli** [comment]
@iNoles Yes. I think that i've been trying almost everything that i can think of to get adb to list this device. I've installed Sony PC Companion which let the adb to connect my older Xperia phone, but it didn't help on this one. Xperia developer site has adb drivers for other Xperias but not this one. I even tried to use the Xperia P adb drivers by modifying the .inf files hw id's. It let me install the drivers, but adb was still not listing the phone.

**Comment by iNoles** [comment]
Did you tried with http://developer.sonymobile.com/wportal/devworld/downloads/download/xperiapxperiauxperiasoladrivers

**Comment by Juggeli** [comment]
Yes those were the drivers that i tried with. Xperia Go wasn't supported by those drivers so i modified the .inf file with the correct hardware id's but it was still no go.

**Comment by nagoya0** [comment]
Is this issue already fixed?
My users report similar behavior.
(Xperia NX - 2.3.7, Xperia acroHD - 2.3.7)

**Comment by SimonVT** [comment]
Can't fix broken devices. Besides, pretty sure those are scheduled to get ICS.

**Comment by nagoya0** [comment]
Thank you for reply. OK... is there a workaround?
For example, set splitActionBarWhenNarrow by code or something...

**Comment by JakeWharton** [comment]
You can call
`getSherlock().setUiOptions(ActivityOptions.UI_OPTIONS_SPLIT_WHEN_NARROW)`
before calling `setContentView`
