### ISSUE TITLE
Concatenating String in loop

### ISSUE THREAD

**Issue by bepcyc** [JakeWharton/ActionBarSherlock#523]
Package package com.actionbarsherlock.internal.nineoldandroids.animation contains 3 classes (KeyframeSet, ObjectAnimator and ValueAnimator) which are concatenating a String variable in a for loop inside toString() method. 

That's a bad practice, you need to use StringBuilder instead. 

I guess it's a product of some code generation.

**Comment by JakeWharton** [comment]
Is `toString` ever called for any of these? They are likely there for debug purposes where slowness and String concatenation aren't really a concern.

**Comment by bepcyc** [comment]
I don't see direct usages, but other toString() methods are already implemented with StringBuilder.
Anyway, I already made a patch ;)

**Comment by JakeWharton** [comment]
Explanation on #523.
