### ISSUE TITLE
Fragment - onCreateOptionsMenu is not work

### ISSUE THREAD

**Issue by andreronquetti** [JakeWharton/ActionBarSherlock#526]
The method onCreateOptionsMenu in Fragment is not work. Tested in versions: 2.3 and small.

**Comment by JakeWharton** [comment]
Did you call `setHasOptionsMenu(true)`?

**Comment by andreronquetti** [comment]
Yes.

```
@Override
public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
    setHasOptionsMenu(true);
    inflater.inflate(R.menu.menu_split_principal, menu);
}
```

I have a idea: The package compatibility override hasOptionsMenu.

**Comment by JakeWharton** [comment]
You need to call that in your fragment's constructor or in a method that will be called when the fragment is created/attached such as `onActivityCreated` or `onAttach`
