### ISSUE TITLE
SubMenu with exclusive checkable item not working

### ISSUE THREAD

**Issue by bubbleguuum** [JakeWharton/ActionBarSherlock#53]
As the topic says. 

Create a SubMenu with exclusive checkable items. setChecked(true) on an item does not work. 
The last item of the list remains always checked. It works on Honeycomb.

**Comment by JakeWharton** [comment]
Try the latest from the `3.1.x` branch. I quite literally just pushed a fix for this an hour or two ago. Let me know how it works for you, it certainly works for the styled sample (navigation and background options).

**Comment by bubbleguuum** [comment]
It works perfectly. You're awesome Jake, thanks :)
