### ISSUE TITLE
Exception on Jelly Bean

### ISSUE THREAD

**Issue by peterfortuin** [JakeWharton/ActionBarSherlock#531]
I'm using ActionBarSherlock in my application and was trying that application on Android Jelly Bean and I get the following exception when I click on a menu item on the action bar:

06-30 10:10:14.442: E/AndroidRuntime(609): java.lang.IllegalStateException: Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment.
06-30 10:10:14.442: E/AndroidRuntime(609): at com.actionbarsherlock.internal.view.menu.MenuItemMule.getItemId(MenuItemMule.java:71)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.app.Activity.onMenuItemSelected(Activity.java:2540)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:351)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:288)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:586)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:191)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:958)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:514)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:99)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.view.View.performClick(View.java:4084)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.view.View$PerformClick.run(View.java:16966)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.os.Handler.handleCallback(Handler.java:615)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.os.Handler.dispatchMessage(Handler.java:92)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.os.Looper.loop(Looper.java:137)
06-30 10:10:14.442: E/AndroidRuntime(609): at android.app.ActivityThread.main(ActivityThread.java:4745)
06-30 10:10:14.442: E/AndroidRuntime(609): at java.lang.reflect.Method.invokeNative(Native Method)
06-30 10:10:14.442: E/AndroidRuntime(609): at java.lang.reflect.Method.invoke(Method.java:511)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
06-30 10:10:14.442: E/AndroidRuntime(609): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
06-30 10:10:14.442: E/AndroidRuntime(609): at dalvik.system.NativeStart.main(Native Method)

The strange part is that I use both the SherlockFragmentActivity and SherlockFragment. 

Tested with ActionBarSherlock 4.1.0.

**Comment by dirtyspark23** [comment]
I don't get an exception when I open a menu item on Jelly Bean. But Im using SherlockActivity... Jelly Bean actually fixed a lot of problems I was having just getting the application to like ActionBarSherlock.

**Comment by jemerick** [comment]
I am also getting reports of this same issue.  Galaxy Nexus devices running 4.1.  I have double checked that I am using SherlockFragments and SherlockFragmentActivities everywhere.  Also using ActionBarSherlock 4.1.0.

**Comment by iNoles** [comment]
I noticed com.actionbarsherlock.internal.view.menu.MenuItemMule.getItemId called after android.app.Activity.onMenuItemSelected, this will explained why there is errors. I have not seen any line for Waston.

**Comment by JakeWharton** [comment]
`MenuMule` and `MenuItemMule` do not exist in ABS v4.1.0. You need to update.

**Comment by gako** [comment]
On 4.2.1 the exceptions seems to reappear, at least i'm getting it again:

```
12-05 12:14:45.205: E/AndroidRuntime(15788): FATAL EXCEPTION: main
12-05 12:14:45.205: E/AndroidRuntime(15788): java.lang.IllegalStateException: Cannot interact with object designed for temporary instance passing. Make sure you using both SherlockFragmentActivity and SherlockFragment.
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.actionbarsherlock.internal.view.menu.MenuItemMule.getItemId(MenuItemMule.java:71)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.app.Activity.onMenuItemSelected(Activity.java:2554)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.support.v4.app.FragmentActivity.onMenuItemSelected(Unknown Source)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:288)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:586)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:191)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:980)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:156)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.widget.AbsListView$1.run(AbsListView.java:3423)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.os.Handler.handleCallback(Handler.java:725)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.os.Handler.dispatchMessage(Handler.java:92)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.os.Looper.loop(Looper.java:137)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at android.app.ActivityThread.main(ActivityThread.java:5039)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at java.lang.reflect.Method.invokeNative(Native Method)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at java.lang.reflect.Method.invoke(Method.java:511)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
12-05 12:14:45.205: E/AndroidRuntime(15788):    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by JakeWharton** [comment]
Update your ABS. The mule classes no longer exist.

**Comment by gandulf** [comment]
Thanks you are right. 
Just because I'm having the newest version of ABS in my development version, doesn't mean its also already in the "old" produtive one, which i tested. ;-)

**Comment by iamkingalvarado** [comment]
Hi, I have this problem but I'm using a Google Maps compatibility library and I cant fix it, how can I do?

**Comment by iNoles** [comment]
@danigarciaalva is it same stack trace? Which ABS version?

**Comment by iamkingalvarado** [comment]
It Looks like this, I'm using a based library with Google Maps support that extends from ABS

**Comment by peterfortuin** [comment]
You have a stacktrace MyMichael?
