### ISSUE TITLE
Theme.Sherlock.Light.DarkActionBar draws shadow too dark

### ISSUE THREAD

**Issue by MalcolmEvershed** [JakeWharton/ActionBarSherlock#536]
When using Theme.Sherlock.Light.DarkActionBar, the ActionBar's shadow is drawn too dark. Here is a screenshot of the ActionBarSherlock Demos app from Google Play reproducing the issue on Froyo and the proper behavior in ICS:

http://img259.imageshack.us/img259/9995/absdemofroyo.png
http://img401.imageshack.us/img401/7389/absdemoics.png

Steps to repro: Install the Demos app on Froyo, run the app, tap Theme, select Light (Dark Action Bar), tap Action Items.

I looked at the RGB values and in Froyo, the values are always off by 8 (i.e. a color that is supposed to be B8B8B8 is B0B0B0 on Froyo).

I looked at the ActionBarSherlock code and I think that the shadow comes from abs__screen_action_bar.xml using a NineFrameLayout with a foreground of windowContentOverlay which refers to abs__ab_solid_shadow_holo.9.png which is identical to the PNGs from ICS.

When I view the screenshots in the Hierarchy View, everything looks fine, which makes me think that the compositing is going wrong, for example, perhaps alpha is being used in the paint when the foreground drawable is drawn. That might explain why the colors are always off by 8.

I thought this might be somewhat related to https://github.com/JakeWharton/ActionBarSherlock/issues/435 but I don't know the codebase well enough to confirm. (Now that I look at 435 again, I'm not sure if it's related.)

Any ideas?

**Comment by JakeWharton** [comment]
Try adding `getWindow().setFormat(PixelFormat.RGBA_8888)` to the `onCreate`? Perhaps its in a different mode which is causing it to round colors up or down.

**Comment by MalcolmEvershed** [comment]
Thanks for the fast response. I added the setFormat() call to the onCreate and it produced a window that looks better, but seems to use dithering:

http://img515.imageshack.us/img515/9973/absdemofroyorgba8888.png

I also tried reading getWindow().getAttributes().format and the existing format was -1 (PixelFormat.OPAQUE) on both Froyo and ICS.

Hmm, I'm not sure what's going on. I'll try to debug into NineFrameLayout when it draws the foreground drawable to check the paint.

**Comment by iNoles** [comment]
NineFrameLayout has getAlpha() as float, you can check into that.

**Comment by MalcolmEvershed** [comment]
I debugged this further and found that no special paint is being used and the abs__ab_solid_shadow_holo.9.png file seems to be loading properly into memory (i.e. pixels values are the same as the file).

But I did notice that NineFrameLayout.draw() is passed a Canvas with mSurfaceFormat = 4. Looking at the Froyo source, 4 seems to refer to HAL_PIXEL_FORMAT_RGB_565 (aka PIXEL_FORMAT_RGB_565). So the Canvas seems to be 16-bit, if I'm interpreting this correctly.

I'm running this in the Android Emulator and it says [here](http://developer.android.com/tools/devices/emulator.html#overview) that the Android emulator has a 16-bit LCD "display" (though perhaps only when running older versions of Android).

So I guess old Android devices really only could display 16-bit color, so I guess the PNG could be to be reworked to alpha blend better when used on a 16-bit display. Argh, this is so annoying that I don't know whether it fits into the scope of ABS. Thoughts?

**Comment by iNoles** [comment]
I noticed Android stock browser is 24-bit in Gingerbread while other apps are under 16-bit.

RGB_565 seems to be default for android emulator.

**Comment by MalcolmEvershed** [comment]
I ran the demos app on the Gingerbread emulator:

http://img825.imageshack.us/img825/1072/absdemogingerbread.png

This is pretty much the same result as running under Froyo with an explicit call to setFormat(RGBA_8888) as Jake suggested.

[This XDA post](http://forum.xda-developers.com/showthread.php?t=1012278) suggests that Gingerbread made some changes around pixel formats, so perhaps that explains it.

I don't know about you guys, but I'm thinking to just live with this Froyo behavior and not mess with it further.

**Comment by JakeWharton** [comment]
More info [here](http://www.curious-creature.org/2010/12/08/bitmap-quality-banding-and-dithering/) and [here](https://plus.google.com/111962077049890418486/posts/Ytar76F56y5).

I think I'm going to deem this as out of scope for ABS since it only affects really old platforms. Thanks for taking the time to research it fully!
