### ISSUE TITLE
Update support library to r9

### ISSUE THREAD

**Issue by mcharmas** [JakeWharton/ActionBarSherlock#537]
Could you update support dependency version?
There are some fragment bug-fixes in new release of support library .

**Comment by JakeWharton** [comment]
There is no r9 available for Maven compilation so sadly, no. I will, of course, do it once available.

In the mean time, you can update the .jar yourself in your local copy (or by forking and updating your fork).

It's equally as frustrating for me to not be able to do this.

**Comment by mcharmas** [comment]
Ok. I guess I will do this locally. Thx for your awesome work.
