### ISSUE TITLE
Crash when restarting an SherlockFragmentActivity when all Fragments are detached

### ISSUE THREAD

**Issue by dlew** [JakeWharton/ActionBarSherlock#539]
Steps to reproduce:
1. Create SherlockFragmentActivity with Fragments added, but not attached (aka, in a detached state).
2. Rotate the screen to trigger an Activity restart.

!3. Crash.

Here is a very simple code example that you can use for step #1:

``` java
public class MyActivity extends SherlockFragmentActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (savedInstanceState == null) {
            Fragment fragment = new Fragment();
            getSupportFragmentManager().beginTransaction().add(fragment, "bgfrag").commit();
            getSupportFragmentManager().beginTransaction().detach(fragment).commit();
        }
    }
}
```

The problem seems to be _ActionBarSherlockTrojanHorse.java uses an incorrect null check in onCreatePanelMenu(), onPreparePanel() and onMenuItemSelected().  It checks whether if (mFragments.mActive != null), but then starts to use mFragments.mAdded.  It should check if (mFragments.mAdded != null), which is what the latest version of the FragmentManager (out of the support library) does these days.

**Comment by JakeWharton** [comment]
Fixed on `dev`. This will be released some time in the next few days. If you can use that branch for now it should fix the problem.
