### ISSUE TITLE
Custom Theme with: parent="Theme.Sherlock.Light" -> getSupportActionBar  is null in Honeycomb.

### ISSUE THREAD

**Issue by ChristopheVersieux** [JakeWharton/ActionBarSherlock#54]
Hello.

This is my custom Theme:

```
    <style name="CustomTheme" parent="Theme.Sherlock.Light"> 
            <item name="android:textColor">@color/darkblue</item> 
    </style> 
```

If I use in my project: android:theme="@style/Theme.Sherlock.Light", everything works fine.
If I use:  android:theme="@style/CustomTheme", getSupportActionBar() return null with Honeycomb devices.

**Comment by iNoles** [comment]
When I was look in http://developer.android.com/guide/topics/ui/themes.html#DefiningStyles

It should be parent="@style/Theme.Sherlock.Light"

**Comment by JakeWharton** [comment]
The demos sample showcases the use of a custom theme. If you look at `res/values/styles.xml` you can see how it is declared. I have included it below:

``` xml
<style name="Theme.SherlockCustom" parent="@style/Theme.Sherlock.Light">
    <item name="abBackground">@drawable/custom_bg</item>
    <item name="abIcon">@drawable/ic_magnifying_glass</item>
    <item name="abTitle">Custom Style!</item>
    <item name="abTitleTextStyle">@style/CustomTitle</item>
    <item name="abSubtitle">100% set from the style attributes</item>
</style>
```
