### ISSUE TITLE
support library 9

### ISSUE THREAD

**Issue by tasomaniac** [JakeWharton/ActionBarSherlock#541]
Update support library to version 9.
Actually we are using it in our projects. ABS also uses it. If the versions are not the same SDK complains and give errors. 
Can you drop this requirement? I guess not but I am asking.

Thank you.

**Comment by xDragonZ** [comment]
Please refer to this https://github.com/JakeWharton/ActionBarSherlock/issues/537#issuecomment-6741966

**Comment by tasomaniac** [comment]
Thank you. I did search the same issue before posting but o couldn't find
it.
On Jul 4, 2012 8:52 PM, "xDragonZ" <
reply@reply.github.com>
wrote:

**Comment by JakeWharton** [comment]
Yeah it'll come, just not yet. I'm working with the Googlers as best I can to speed things up.
