### ISSUE TITLE
Provide code style guide

### ISSUE THREAD

**Issue by Vandalko** [JakeWharton/ActionBarSherlock#542]
[Development](http://actionbarsherlock.com/development.html) page contains no information about code style used in project. [README.md](https://github.com/JakeWharton/ActionBarSherlock/blob/master/README.md) lacks of this information too.

Please provide some information about your code style: identations, variable naming, etc.

**Comment by JakeWharton** [comment]
Since a majority of the code is pulled from AOSP I follow [its guidelines](http://s.android.com/source/code-style.html). I'll put this somewhere...
