### ISSUE TITLE
Theme.Sherlock.Light.Dialog

### ISSUE THREAD

**Issue by alvarolb** [JakeWharton/ActionBarSherlock#546]
I am trying to set a fragment dialog with the theme Theme.Sherlock.Light.Dialog, using the following code:

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setStyle(DialogFragment.STYLE_NORMAL, R.style.Theme_Sherlock_Light_Dialog);
}
```

In ICS it works perfectly, and the dialog title is shown. But when running on Android 2.2, the dialog is shown with light theme but there is no way to get the title appearing.

**Comment by JakeWharton** [comment]
The dialog themes in ABS are for theming activities to look like dialogs and not for dialogs themselves. If you want to theme a dialog you have to provide your own styles.

**Comment by alvarolb** [comment]
ok! thanks!
