### ISSUE TITLE
Fragment hidden state is not saved

### ISSUE THREAD

**Issue by drsoran** [JakeWharton/ActionBarSherlock#55]
Release: 3.1.3

The hidden state of a Fragment instance is not saved during, e.g. device orientation change. If I have created a Fragment and hide it by calling the following code it becomes invisible:

``` java
final Fragment fragment = getMyFragment();
final FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();

transaction.hide( fragment );

transaction.commit();
```

After a orientation change it is visible again. The hidden state seems not to be saved and during recreation of the hidden Fragment, it becomes visible again.

Don't know if this is a bug or it behaves the same in the native 3.0+ world.

**Comment by JakeWharton** [comment]
If you call `setRetainInstance(true)` on the fragment (I usually put it in its constructor) the hidden state will be persisted. Leaving this out causes it to re-appear on orientation change. I've confirmed both behaviors using ActionBarSherlock, the official compatibility library r3 `.jar`, and native fragments on Android 3.0+.
