### ISSUE TITLE
Tabs and theming issue

### ISSUE THREAD

**Issue by arturdryomov** [JakeWharton/ActionBarSherlock#554]
I have an issue with action bar tabs and theming. The problem occurs when I’m trying to create my own theme for action bar with `displayOptions` set to `showTitle`-only for example. In such case I got tabs on top of the main action bar. When I set `displayOption` to include option `showHome` everything works fine and I have tabs on the bottom of the main action bar. I prepared a very simple [testing project](https://gist.github.com/3124619) to reproduce the error. Check out `README.md` to get steps-to-reproduce.

**Comment by JakeWharton** [comment]
This is how the action bar on ICS behaves which is why ABS behaves this way. In JB this was fixed only if you are targeting API 16.

**Comment by arturdryomov** [comment]
I run testing project on Jelly Bean emulator and tabs are still on top (I changed `targetSdkVersion` to 16 if this matters). Is this a framework bug and should I post it upstream?

**Comment by JakeWharton** [comment]
I will have to try later. I only saw the fix in the JB change log and have not yet had the chance to test myself.

**Comment by arturdryomov** [comment]
I checked this issue with a pure-Android realization of the action bar and it seems like a platform issue even in the Jelly Bean. Strange issue BTW. Let me know if you’ll check it and it would be a really platform problem.

**Comment by arturdryomov** [comment]
I have opened an [issue](http://code.google.com/p/android/issues/detail?id=35581) at the Android bug tracker but didn’t get any response yet :-(
