### ISSUE TITLE
setActionView - works on ICS, not on 2.3

### ISSUE THREAD

**Issue by indieboyalex** [JakeWharton/ActionBarSherlock#555]
I'm writing an app using ABS, and calling setActionView is working on ICS devices.  However when I call it on 2.3 devices it simply removes the button completely - the action seems to run but then setActionView(null) doesn't bring the original button back.  Is this a known issue???

**Comment by JakeWharton** [comment]
Please provide full reproducible demo code. I am unable to reproduce this with the latest `dev` branch. Closing for now, will re-open if a working demo is provided.
