### ISSUE TITLE
How I can add Edit Text field and button in ActionBar ?

### ISSUE THREAD

**Issue by sunasra** [JakeWharton/ActionBarSherlock#560]
I want to use Only Edit Text and one button in ActionBar. but have i gone through many documents and post but haven't found solution yet.

Please share your idea..

THanks
Sunasra

**Comment by JakeWharton** [comment]
Use `setCustomView` for the `EditText` and add a single action item through the normal menu.

Questions like this are best suited for [StackOverflow](http://stackoverflow.com/questions/tagged/android) or the [official Android developer mailing list](groups.google.com/group/android-developers).
