### ISSUE TITLE
ForceOverflow themes cause issues on devices with hardware keyboard

### ISSUE THREAD

**Issue by vekexasia** [JakeWharton/ActionBarSherlock#568]
When using a ForceOverflow theme ( or attr absForceOverflow set to true ) you get an issue with devices having the hadware keyboard.

Indeed, when typing inside an edittext on one of those devices, if you press the menu button then the keyboard stops working correctly because the keyboard start acting like the menu button is always on. (Which is not).

The following step by step procedure should replicate the issue:
- Make theme extend Theme.Sherlock.Light.ForceOverflow
- Make the activity extend SherlockActivity
- Place an edittext inside the layout
- Start the app
- put the device ( or emulator ) in landscape mode and select the edittext so you can write in it
- write something in it
- Press the hardware menu button 
- try pressing one of these keys: 
  - a -> should select all
  - c -> should copy the selection
  - v -> should paste the previously copied content

This behaviour cannot be toggled off.
Keyboard shortcut should be enabled only if the user holds the menu button.

The following is the config.ini file of the avd I used to replicate the  issue that was reported by an user.

``` ini
hw.lcd.density=240
sdcard.size=512M
skin.name=WVGA800
skin.path=platforms/android-8/skins/WVGA800
hw.cpu.arch=arm
hw.keyboard.lid=yes
abi.type=armeabi
hw.keyboard=yes
vm.heapSize=24
image.sysdir.2=platforms/android-8/images/
image.sysdir.1=add-ons/addon-google_apis-google-8/images/
```

**Comment by JakeWharton** [comment]
Because of this, and many other reasons, the force overflow support is going away in a future version. Thanks for reporting. See #617.
