### ISSUE TITLE
CustomView in bottom bar doesn't show up at the right place

### ISSUE THREAD

**Issue by mrmaffen** [JakeWharton/ActionBarSherlock#575]
I'm trying to display a customView inside the bottom split ActionBar, but it doesn't work correctly. Is there any way to achieve this?

I've explained my issue on stackoverflow
http://stackoverflow.com/questions/11937856/android-actionbarsherlock-how-to-display-my-customview-in-the-bottom-bar

Thanks :)

**Comment by JakeWharton** [comment]
ActionBarSherlock is simply a wrapper around the native API. Anything you can do with the native action bar you can also do with ABS. Conversely, you cannot do anything with ABS that cannot be done with the native action bar.

Only menu items show up in the split action bar with the current API.

**Comment by mrmaffen** [comment]
Thanks a lot dude :-)
