### ISSUE TITLE
FEATURE_INDETERMINATE_PROGRESS default behavior changing with ICS

### ISSUE THREAD

**Issue by pyricau** [JakeWharton/ActionBarSherlock#579]
If I create an activity with `Window.FEATURE_INDETERMINATE_PROGRESS` flag but without explicitly calling `setSupportProgressBarIndeterminateVisibility()` :

``` java
public class SomeActivity extends SherlockActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
        setContentView(R.layout.some_layout);
    }
}
```

On Android 2.3, the indeterminate progress appears in the action bar. On Android 4.0, it doesn't. So it's basically as if we had a default to `setSupportProgressBarIndeterminateVisibility(true)` on 2.3 and  to `setSupportProgressBarIndeterminateVisibility(false)` on 4.0

I may be wrong, but in `com.actionbarsherlock.internal.widget.ActionBarView.initIndeterminateProgress()` :

``` java
    public void initIndeterminateProgress() {
        mIndeterminateProgressView = new IcsProgressBar(mContext, null, 0, mIndeterminateProgressStyle);
        mIndeterminateProgressView.setId(R.id.abs__progress_circular);
        addView(mIndeterminateProgressView);
    }
```

Looks like it should be :

``` java
    public void initIndeterminateProgress() {
        mIndeterminateProgressView = new IcsProgressBar(mContext, null, 0, mIndeterminateProgressStyle);
        mIndeterminateProgressView.setId(R.id.abs__progress_circular);
        mIndeterminateProgressView.setVisibility(View.INVISIBLE);
        addView(mIndeterminateProgressView);
    }
```

What do you think ?

Edit : don't take my word too seriously. I'm not used yet to ABS codebase..

**Comment by JakeWharton** [comment]
On ICS the progress indicators are actually shown by default just by requesting the feature. This [was fixed for Jelly Bean](https://github.com/android/platform_frameworks_base/commit/45b075dd5cef54ed3412115ee199df1db1c90528) and I will revisit when I sync up with the Jelly Bean sources. It's a non-trivial problem to solve since we use the native action bar on API 14+.

**Comment by JakeWharton** [comment]
Basically, always set the desired visibility in your `onCreate` method _after_ calling `setContentView` to ensure it is being displayed properly.

**Comment by pyricau** [comment]
Yes sure, thanks :)
