### ISSUE TITLE
how can I bind click event to the home button

### ISSUE THREAD

**Issue by shaokun** [JakeWharton/ActionBarSherlock#58]
Hi,

Thanks for this great framework! I am new to android development.
And I cannot find the right way to bind click event to the home button.
I would like to go back one level when click the home button.
But by default, it does nothing.
I found that the home button id is a big number, and I don't know how to set it.
So I wrote code to default instead. But that seems not right. Any suggestion?

```
  // Handle item selection
  switch (item.getItemId()) {
    case Menu.FIRST:
        refreshBusLine();
        return true;
    default:
        finish();
        return true;
    }
```

**Comment by JakeWharton** [comment]
You should use `android.R.id.home`. More information about it can be found here: http://developer.android.com/guide/topics/ui/actionbar.html#Home

**Comment by shaokun** [comment]
Wow, that was fast!! It works! Thank you very much...
