### ISSUE TITLE
Shadow is not applied to ActionBar title

### ISSUE THREAD

**Issue by lexer** [JakeWharton/ActionBarSherlock#580]
Im trying to customize ActionBar title. Text size and color was customized succefully, but setting shadow color and size attributes has no effect.    

```
<style name="TextAppearance.MyTheme.Widget.ActionBar.Title" parent="@style/TextAppearance.Sherlock.Widget.ActionBar.Title">
    <item name="android:textColor">@color/actionbar_text</item>
    <item name="android:textSize">22sp</item>
    <item name="android:shadowColor">@color/actionbar_text_shadow</item>
    <item name="android:shadowDx">0</item>
    <item name="android:shadowDy">1</item>
    <item name="android:shadowRadius">1</item>
</style>
```

I'm using Galaxy Ace with Android 2.3.7

**Comment by JakeWharton** [comment]
Shadow cannot be applied to the action bar title due to how the styles are configured. This is a limitation of the native action bar as well and hence of ABS as well. If you feel like this should be changed you should file a bug on http://b.android.com.
