### ISSUE TITLE
SearchView starts android market

### ISSUE THREAD

**Issue by korniltsev** [JakeWharton/ActionBarSherlock#582]
I am trying to use SearchView backport from dev branch.

When i hit "enter" button on soft keyboard The android Market is tarted with the search query i typed in the SearchView.
it is tarted from SearchView.launchQuerySearch(int actionKey, String actionMsg, String query)  method.

Device HTC Desire HD, also don't know whether this is important: Market is not updated to google play. OS Version 2.3.3
On the same device with ICS ( i suggest the SearchView swithces to native implementation) everything works fine.

Thanks!

**Comment by JakeWharton** [comment]
Please try out the latest from the `dev` branch

**Comment by korniltsev** [comment]
Thanks! Fixed.
