### ISSUE TITLE
parentActivityName doesn't work with ABS

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#586]
Jelly Bean introduced the android:parentActivityName attribute in the manifest. Should make up navigation easier.
It stops working though if I switch to ABS. Is there an update for ABS needed or am I doing something wrong?

**Comment by JakeWharton** [comment]
The last version of ABS was released about 3 months ago. The Jelly Bean AOSP source was released about a month ago.

edit: That's a no. I'll get to it eventually.

**Comment by ghost** [comment]
I was not sure where this implementation actually resides, my hope was that it's in an AOSP class which you "just" extend making it reachable with a trick.
In this case though, thanks for the heads up, Jake!

**Comment by JakeWharton** [comment]
Not going to do this. Use `NavUtils` from the support library.
