### ISSUE TITLE
Add theme attribute: textColorPrimaryInverseDisableOnly

### ISSUE THREAD

**Issue by mrenouf** [JakeWharton/ActionBarSherlock#592]
Would be useful for setting the textColor for Spinner items in ActionBar spinner (List nav mode).
I still run into this when using Light.DarkActionBar based themes, where I need a custom spinner item layout with which has _textColor="?attr/textColorPrimaryInverseDisableOnly"._

Implement as:

_Theme.Sherlock_

```
<item name="textColorPrimaryInverseDisableOnly">@color/abs__primary_text_disable_only_holo_light</item>
```

_Theme.Sherlock.Light_

```
<item name="textColorPrimaryInverseDisableOnly">@color/abs__primary_text_disable_only_holo_dark</item>
```

**Comment by JakeWharton** [comment]
I'm not sure why I duplicated all the `textColor*` attributes in the first place. They're all available on the necessary API levels...

**Comment by SimonVT** [comment]
You're duplicating them so the holo colors are only used in the action bar, and not the rest of a users app.

**Comment by SimonVT** [comment]
@mrenouf I'm not sure you should be using the textColor\* attributes in your app.
For example, ?attr/textColorPrimaryInverseDisableOnly would resolve to nothing on API14+ if it was added.

**Comment by JakeWharton** [comment]
Yeah you're definitely better off with your own theme attributes to track these values.
