### ISSUE TITLE
"Native callback invoked. Create a test case and report!"

### ISSUE THREAD

**Issue by yukuku** [JakeWharton/ActionBarSherlock#593]
I just released a new version of my app today, for the first time using ABS, and I got 89 reports of:

```
java.lang.IllegalStateException: Native callback invoked. Create a test case and report!
at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchOptionsItemSelected(ActionBarSherlockCompat.java:355)
at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:194)
at com.android.internal.widget.ActionBarView$2.onClick(ActionBarView.java:226)
at android.view.View.performClick(View.java:3122)
at android.view.View$PerformClick.run(View.java:12006)
at android.os.Handler.handleCallback(Handler.java:587)
```

From the device info I got, only Android API Level 12 and 13 seem to be affected by this issue. I'm attaching the crash report with the last 2 columns are Build.DEVICE and Build.PRODUCT -> http://pastebin.com/DMftmYkj

ABS version 4.1.0 with support library r10.

**Comment by iNoles** [comment]
Can you posted source code for your options menu and selected here? It would be helpful if you do.

**Comment by yukuku** [comment]
I got access to a 3.2 device and found that the action bar is duplicated (on top is the native action bar, below it is the ABS actionbar). Then when the user clicks the logo on the native action bar, that exception is thrown.

It was because I have a code similar to this before using ABS, that didn't get removed when integrating ABS.

if (apilevel >= 11) { 
   setTheme(android.R.style.Theme_Holo)
}

That doesn't seem to affect 4.0+ devices, only 3.x devices. 

So I think it's my fault and there is no problem with ABS since ABS requires activities to use themes from ABS. Thanks for responding.
