### ISSUE TITLE
Deploy to Maven Repository

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#6]
Deploy compiled JAR to either the Maven central repository or my hosted repository (http://repository.jakewharton.com), or both.

**Blocked by #5.**

**Comment by manandbytes** [comment]
http://repository.jakewharton.com/ is unreachable due to

```
The DNS server returned:

    Name Error: The domain name does not exist.
```

**Comment by JakeWharton** [comment]
The artifacts are now in Maven Central.

**Comment by manandbytes** [comment]
I've found it already, thank you.
