### ISSUE TITLE
ActionBar gets behind notification bar

### ISSUE THREAD

**Issue by flavioarfaria** [JakeWharton/ActionBarSherlock#602]
It rarely happens, and it only does when I'm coming back to this activity from another one on top of it.
This happened on my Galaxy Nexus running Jelly Bean. I don't know whether it happens on other versions too.

http://img827.imageshack.us/img827/6881/device20120906160703cop.png

Note the two action buttons cropped on the right (a + button and the overflow one).

**Comment by JakeWharton** [comment]
If it happens on ICS or Jelly Bean then it is the native action bar, not the compatibility implementation provided by ActionBarSherlock. You should ensure you aren't doing anything funky with handling configChanges or the decor view and then file a bug on http://b.android.com/.
