### ISSUE TITLE
getting improper spacing inactionbar icons

### ISSUE THREAD

**Issue by raghunandantg** [JakeWharton/ActionBarSherlock#604]
how to give proper spacing between actionbar

**Comment by JakeWharton** [comment]
Please include a description of the problem, screenshots, code to reproduce, and/or an example application to reproduce your error.

**Comment by raghunandantg** [comment]
I am getting improper spacing in actionbar and i also want to remove title bar, as you see in this link i have a screenshot http://imagebin.org/227520. Do i have any special theme which will hide my window title in actionbarsherlock?
