### ISSUE TITLE
Improper spacing in actionbar

### ISSUE THREAD

**Issue by raghunandantg** [JakeWharton/ActionBarSherlock#605]
I am getting improper spacing in actionbar and i also want to remove title bar, as you see in this link i have a screenshot http://imagebin.org/227520. Do i have any special theme which will hide my window title in actionbarsherlock?

**Comment by JakeWharton** [comment]
This is not the proper avenue for asking support-related questions. If you are having trouble using the library I suggest posting to [StackOverflow](http://stackoverflow.com) under the 'actionbarsherlock' tag or by posting to [the mailing list](http://abs.io/forum) (but not both, please).
