### ISSUE TITLE
Bug with setHasOptionsMenu()

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#610]
If this is called more than once, the Action menu buttons get duplicated.

I am attaching the simplest project I could create that shows this problem.   Just start the app and rotate the screen.  On every rotation, a new set of action bar items get added.

If I remove the setHasOptionsMenu() from the Fragment's onCreate() and move it to the Activitiy's onCreate(), the problem goes away.   I have that line commented out.

I tested this with ABS 4.1.0 on a Galaxy Nexus running the official JB.

**Comment by JakeWharton** [comment]
Probably not an ABS bug.

**Comment by androidmoney** [comment]
Here's the link to the project:

https://docs.google.com/open?id=0B3ZnIh8rsoQxOHZQYzR6WDRLQnc

**Comment by androidmoney** [comment]
Very is setHasOptionsMenu() meant to be called from?  Not from the Fragment's onCreate()?

**Comment by androidmoney** [comment]
You are right -- not an ABS bug.  I guess I still don't understand how setHasOptionsMenu() meant to be used.

**Comment by JakeWharton** [comment]
The cause of your duplicates is because you are creating a new fragment each time. The framework automatically brings fragments back so every time you rotate the device you add another fragment.

**Comment by SimonVT** [comment]
On configuration changes, the FragmentManager will re-add any fragments that were previously added. This means that every time you rotate the screen, you add an extra instance of your fragment to your layout.
This is not an ABS issue, and it has nothing to do with setHasOptionsMenu(). It's just you adding several instances of the same fragment to your layout.
Hint: Check if your fragment already exists (give it a tag, and use FragmentManager.findFragmentByTag or something) before you add it.

**Comment by androidmoney** [comment]
Ok, I changed my code to only add the fragment if (state == null), but I still need to call setHasOptionsMenu() as it is not remembered.  So I am now calling it from onActivityCreated() and that seems to work. 

Thanks!
