### ISSUE TITLE
Content of Activity with style @style/Theme.Sherlock.Dialog can't utilize all avaiable width

### ISSUE THREAD

**Issue by teshca** [JakeWharton/ActionBarSherlock#611]
I have an activity with @style/Theme.Sherlock.Dialog. The content of activity has custom background and a small text message. The problem I see on 2.x devices is that background is not stretched to the size of dialog although I have fill_parent on the root of dialog content

In order to reproduce the problem you can modify demo application in the following way:
- com.actionbarsherlock.sample.demos.Dialog change text to something small (for example
  change R.string.dialog_content to R.string.dialog)
- in R.layout.text add solid background background, (for example android:background="#ffff0000")
- run modified application on 2.x device

![screenshot for 2.x](http://i.imgur.com/QJlIQ.png)
![same for 4.0](http://i.imgur.com/ngjIR.png)

My workaround for problem is to modify abs__dialog_title_holo.xml and set android:layout_width="fill_parent" for FrameLayout
But I'm not sure if it's the right way to go.

**Comment by JakeWharton** [comment]
Please don't use google docs links for image. Upload you image to http://imgur.com and link with `![](url)`.
