### ISSUE TITLE
CheckBox/ToggleButton not working in fragment SherlockFragment

### ISSUE THREAD

**Issue by kganesa** [JakeWharton/ActionBarSherlock#613]
Hi,
I created a view inside a fragment (extending from SherlockFragment)
Fragment calls setHasOptionsMenu(true), sets titlle and setDisplayHomeAsUpEnabled

CheckBox/ToggleButton does not check/uncheck 

Android 2.3.5 and 2.3.6, it works on ics

Thanks,
Aravind

**Comment by SimonVT** [comment]
ABS does not in any way modify how fragments display their views. Try stackoverflow or the android developers mailing list.
