### ISSUE TITLE
ActionMode

### ISSUE THREAD

**Issue by crossle** [JakeWharton/ActionBarSherlock#616]
View.startActionMode(ActionMode.Callback callback) 
ActionMode belong to android.view.ActionMode, not com.actionbarsherlock.view.ActionMode?
can you support?

**Comment by SimonVT** [comment]
This would require custom View implementations. Probably not very likely to make it into the library. At most you'd get something like ViewCompat.startActionMode(View, ActionMode.Callback), that would ultimately call back to Sherlock*Activity.startActionMode(), which seems pointless.
Handle this in your Activity.
