### ISSUE TITLE
icon get cropped

### ISSUE THREAD

**Issue by steren** [JakeWharton/ActionBarSherlock#62]
On my Nexus S, by default, the application icon is cropped at the bottom in the ActionBar.

See for example the demo application: http://i.imgur.com/blACl.png

I don't think it is an intended behavior and it really forces to add a specific graphic for the bar.

**Comment by JakeWharton** [comment]
This is because I did not follow the [official size guidelines](http://developer.android.com/guide/practices/ui_guidelines/icon_design_launcher.html#size5) when creating that icon. I've updated it in 46b8f42d471d80fc7baf766c30e3efbb0f00c364 and it will be fixed in the next release this weekend.

**Comment by JakeWharton** [comment]
It's also because launcher icons equate to `48dp` and the action bar is only `45dp` tall. On Honeycomb the action bar is a whopping `56dp` tall but that looks a bit ridiculous on phones so I arbitrarily chose `45dp` since that seemed to be what everyone else had been using.

**Comment by JakeWharton** [comment]
Released with 3.2.2. Couldn't wait...

**Comment by steren** [comment]
Thanks a lot for this fix. I will test this soon.
I really think your approach to stick to the official ActionBar API is the right way to do it. (comparing to other actionbar libraries)
