### ISSUE TITLE
Example project not working

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#621]
Downloaded the latest Sherlock, tried everything in the video, but I get errors in the project. 
I do all the things in the youtube video, but I get the "red x" icons on the project source folders too. 

Can anybody add a working version? Or a lib/jar file?

Thanks,
Leslie

**Comment by JakeWharton** [comment]
The issue tracker is not the right place to be asking for help. Try [the forum](http://abs.io/forum) or [StackOverflow](http://stackoverflow.com/tags/actionbarsherlock).
