### ISSUE TITLE
CheckBox/ToggleButton issue when using "android.R.id.content"

### ISSUE THREAD

**Issue by kganesa** [JakeWharton/ActionBarSherlock#623]
This issue is a duplicate of issue 613 (since it was closed I could not reopen it)
I created a view inside a fragment (extending from SherlockFragment)
Fragment calls setHasOptionsMenu(true), sets titlle and setDisplayHomeAsUpEnabled

CheckBox/ToggleButton does not check/uncheck 

Android 2.3.5 and 2.3.6, it works on ics

---

I was able to reproduce this issue:

Layout-----------------------------------------

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:gravity="top" >

```
<ToggleButton
    android:id="@+id/toggle"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:checked="true"
    android:text="test checkbox" />

<CheckBox
    android:id="@+id/chkbox"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:checked="true"
    android:text="test checkbox" />
```

</LinearLayout>
# 

Fragment--------------------------------------------------------------------

public class RoundedColourFragment extends SherlockFragment {
    public RoundedColourFragment() {

```
}

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
}

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container,
        Bundle savedInstanceState) {
    return inflater.inflate(R.layout.issue613_tb_checkbox, container, false);
}
```

}
# 

Activity---------------------------------------------------------------------------------------
public class Issue613 extends SherlockFragmentActivity {

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    FragmentManager fm = getSupportFragmentManager();
    FragmentTransaction ft = fm.beginTransaction();
    Fragment newFragment = Fragment.instantiate(this, RoundedColourFragment.class.getName(), null);
    ft.replace(android.R.id.content, newFragment);
    ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN);
    ft.addToBackStack(null);
    ft.commit();
}
```

}
# 
# 

I was able to find a workaround this issue by removing  "android.R.id.content"  and replacing it with an id in layout.

**Comment by codestream** [comment]
I've provided layout for activity and it works on 2.3.3. Maybe it works too on 2.3.5 and 2.3.6 because of same API level
