### ISSUE TITLE
Change artifactId to 'actionbarsherlock'

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#626]
`com.actionbarsherlock:actionbarsherlock:5.0.0`

**Comment by stephanenicolas** [comment]
This is a nice change. Hope other libraries will adopt that naming convention.

**Comment by rgladwell** [comment]
Could we do this sooner if we use the Maven relocation feature?

http://maven.apache.org/guides/mini/guide-relocation.html

This allows builds to work with the old "library" artifactId but gives a warning that the project has moved in the Maven namespace.

Please see pull request #632

**Comment by JakeWharton** [comment]
Relocation pom has been released. Should show up in central in a few hours.

**Comment by rgladwell** [comment]
+1
