### ISSUE TITLE
Provide Custom Menu Layouts On Pre-HC

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#627]
That look like ICS's native non-AB-based overflow. This will provide consistency for overflow (no icons, black/white background with theme).

**Comment by schildbach** [comment]
Yes, I second this. In my opinion this should have been implemented the same time as .ForceOverflow themes and the absForceOverflow attribute has been removed (v4.2.0). The old options menu is extremely ugly, with some entries having icons and some not, and all entries need a completely different icon set (remember, pre-HC there were no dark/light themes but all-in-one). The non-AB options menu would be a good compromise for devices with menu button.

**Comment by hrk** [comment]
Thank you. What kind of help could I provide to speed this development up?

**Comment by SimonVT** [comment]
Backport it.

**Comment by DHuckaby** [comment]
Here is an example of how to do it correctly.

http://sriramramani.wordpress.com/2012/08/30/custom-menu/

**Comment by JakeWharton** [comment]
Great link @DHuckaby, that is exactly the route I was going to take.

**Comment by KennyGoers** [comment]
As long as there are a number of eyes on this topic, does ActionbarSherlock
expose the methods necessary to show a menu in this fashion or is this
something that might be in 4.3?  I essentially have the same problem with
the 4.2 implementation.

Thanks,
Kenny.

**Comment by JakeWharton** [comment]
This is Android functionality not ABS. ABS is going to implement this as the default for pre-HC in future versions.

**Comment by KennyGoers** [comment]
I understood that it doesn't do it today, I was more wondering/hoping that
there might be a way of getting/popping up a themed menu from an exposed
method to make this implementation easier so as to know where to place my
efforts.

Thanks for the quick response.

**Comment by JakeWharton** [comment]
All the info for doing it yourself is in the link above.

**Comment by imminent** [comment]
@DHuckaby, doesn't that make your menu stick out from the rest of your own app though? I think the the most jarring effect is the clash between old Android look with ICS look (like the maps app directions dialog).

**Comment by Leandros** [comment]
Could someone provide a real example how to implement it?

**Comment by JakeWharton** [comment]
Started on [the `custom-menu` branch](https://github.com/JakeWharton/ActionBarSherlock/compare/dev...custom-menu).

**Comment by DHuckaby** [comment]
Any update on this? I am really looking forward to this feature.

**Comment by schildbach** [comment]
What is the status of this? I really hoped it will make it into 4.3.0. I'm still stuck at 4.1.0, because I cannot present an ugly options menu mixed with and without icons to pre-HC users.

**Comment by hrk** [comment]
@schildbach: if you'd rather have UI inconsistency across devices than having a ugly options menu, you can use this patch (http://pastebin.com/HecnkPib) to revert the removal of the ForceOverflow themes.

**Comment by hrk** [comment]
I'm sorry, the patch is missing a...

``` java
import android.content.res.TypedArray;
```

in the java class.

**Comment by schildbach** [comment]
@hrk ForceOverflow is nice to have, but not ideal. Really the best compromise would be a backport of these iconless menus that pop up from the bottom (otherwise look identical to the overflow menus). Thanks anyway.

**Comment by semaphore3000** [comment]
Sorry for asking again about the status of the custom-menu branch: Is the merge scheduled for the release of version 4.4? I really would appreciate that.

**Comment by fernandocamargoai** [comment]
Are there any news about this issue?

**Comment by VAdaihiep** [comment]
@hrk Thanks, your snippet works fine!

**Comment by JakeWharton** [comment]
This will never happen.
