### ISSUE TITLE
Overflow menu overlaps SearchView close button when actionbar is splitted

### ISSUE THREAD

**Issue by rciovati** [JakeWharton/ActionBarSherlock#629]
Using last version from dev branch (a4472932af95bfa94a3f71a8368a4e472b0f216c), if i put the SearchView in the splitted action bar, the SearchView close button is overlapped by the overflow button. See picture attached:

![Image Alt](http://i46.tinypic.com/2utmbg1.png)

Sorry if this is a duplicate :-)

**Comment by JakeWharton** [comment]
Can't reproduce. Are you using a `.ForceOverflow` theme or something?

**Comment by rciovati** [comment]
No, i'm not.
I've prepared a toy project that demonstrate the issue.

https://dl.dropbox.com/u/6260980/test-app.zip

(the code is not perfect but it is enough to show the problem).

**Comment by JakeWharton** [comment]
Happens with native `SearchView` as well. File a bug on http://b.android.com

**Comment by rciovati** [comment]
True, it happens also with native `SearchView`.
Anyway, making some other tests i found that using `android:showAsAction="collapseActionView|ifRoom"` (i was just using `android:showAsAction="ifRoom"`)  on the SearchView solves the problem because the SearchView is moved in the top ActionBar when it is not collapsed. 
Maybe i was just using it wrong...

Thanks.

**Comment by JakeWharton** [comment]
Ah! I can't believe I missed that. I was in an extreme hurry when testing this yesterday in case I had to patch ABS before the release.
