### ISSUE TITLE
setSubtitle not working sometimes

### ISSUE THREAD

**Issue by miroslavign** [JakeWharton/ActionBarSherlock#633]
If I set the subtitle in Activity.onCreate, 
then later in code I can change the subtitle.
But if in onCreate I do not setSubtitle, then
this code fired on some event is not performing
as expected:

```
    ActionBar aBar = getSupportActionBar();
    if (aBar != null)
    {
        aBar.setTitle(someString); // this WORKS - changes the title
        aBar.setSubtitle(otherString); // this does NOT, subtitle still hidden
    }
```

I followed and logged the code in ActionBarView.setSubtitle, and all values
are fine, nothing is null, the 
final boolean visible is set to true, mTitleLayout is != null and set to visible.

As I said, I resolved it by just setting the subtitle to some (almost) empty string
in Activity.onCreate. Seems like a workaround to me...

[UPDATE] No, the setSubtitle in onCreate in order to "unhide" did not resolve the problem. 
So sometimes, I still do not get the update when performing the
change somewhere in code.
[HINT] When this happens, the title does not show the whole text, it shows only a portion
and "..."
like when:
setTitle("Some title"), 
I get:
"Some t..." in the title portion.

**Comment by SimonVT** [comment]
Can you provide a sample project?

**Comment by miroslavign** [comment]
Hmm, it's a bit hard to extract what's relevant only for this purpose.
I am using ABS 4 and a ViewPager for content. 
Will try to describe it with sample images

The first one is when it does not set the subtitle
http://imageshack.us/a/img26/9480/device20120923234426.png

and if I swipe the viewpager to the next page (and back) it gets 
http://imageshack.us/a/img528/1036/device20120923234843.png
which is the correct one

**Comment by JakeWharton** [comment]
Framework bug: http://b.android.com/24034

**Comment by miroslavign** [comment]
OK then, will try some workaround.
Thanks for the time spent investigating.
