### ISSUE TITLE
CapitalizingTextView prevents from using Spannable

### ISSUE THREAD

**Issue by eric-taix** [JakeWharton/ActionBarSherlock#635]
The CapitalizingTextView convert a CharSequence to a String in the setTextCompat method.
This conversion prevents us from using a Spannable in a tab's title.

A typical use case is when you want to add an image with text into a tab's title.

A workaround is to use a customView, but it's only a workaround (in my opinion)

**Comment by SimonVT** [comment]
That's how the framework makes the text all caps as well, are you sure your spannables work in the native implementation?

**Comment by JakeWharton** [comment]
Confirmed this doesn't work natively either.
