### ISSUE TITLE
Don't work selector in home button

### ISSUE THREAD

**Issue by RobertoArtiles** [JakeWharton/ActionBarSherlock#638]
Hi Jake.

In native implementation  you can set selector for homebutton and it will clicks.
But in library implementation clicks only mHomeLayout.

Thank's

**Comment by JakeWharton** [comment]
Going to need a lot more info than that...

**Comment by RobertoArtiles** [comment]
If you make getSupportActionBar().setIcon(getResources().getDrawable(R.drawable.some_selector))
then it will change its state only in native implementation but not in abs.

**Comment by JakeWharton** [comment]
Doesn't work on ICS either, the version of Android on which ABS is based.

**Comment by RobertoArtiles** [comment]
Jake, are you sure?
With this piece of code it works on ICS.

```
public class MainActivity extends FragmentActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ActionBar actionBar = getActionBar();
        actionBar.setHomeButtonEnabled(true);
        actionBar.setIcon(R.drawable.menu_icon_selector);
    }
}
```

And this piece too (because it invokes native methods on ICS) but on Android 2.3.3 selector doesn't work:

```
public class MainActivity extends SherlockFragmentActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ActionBar actionBar = getSupportActionBar();
        actionBar.setHomeButtonEnabled(true);
        actionBar.setIcon(R.drawable.menu_icon_selector);
    }
}
```

**Comment by JakeWharton** [comment]
I don't see it on Android 4.0.3. Create a full working sample if you think otherwise.

**Comment by RobertoArtiles** [comment]
Oh, I finally understood. I've tested it on Android 4.0.3 and on Android 4.1. On 4.1 it works but on Android 4.0.3 doesn't.
