### ISSUE TITLE
java.lang.NoClassDefFoundError: com.actionbarsherlock.R$styleable

### ISSUE THREAD

**Issue by oceanfeeling** [JakeWharton/ActionBarSherlock#639]
I am getting the above exception when trying to open an activity which hosts a fragment that provides a menu.

The application project references a library project and ActionBarSherlock (as a library project and not as jar in libs).

Here's the hierarchy of the Activity and the fragments

CustomersActivity
  CustomersFragment
     BaseProviderSearchFragment
         BaseProviderFragment

In BaseProviderSearchFragment
@Override
public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
    inflater.inflate(R.menu.menu_search, menu); // this is where the exception is thrown
    super.onCreateOptionsMenu(menu, inflater);
}

The menu_search is declared in the library project
<menu xmlns:android="http://schemas.android.com/apk/res/android" >
    <item android:id="@id/menu_search"
        android:icon="@drawable/actionbar_search_btn"
        android:title="@string/bar_search_desc"
        android:orderInCategory="100"
        android:showAsAction="ifRoom" />
</menu>

Environment used: Windows 7 x64, Eclipse 4.2.0, Android SDK and ADT preview 21 rc.5

The full stack trace is provided below

09-28 12:56:10.124: E/AndroidRuntime(8466): java.lang.NoClassDefFoundError: com.actionbarsherlock.R$styleable
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.view.MenuInflater$MenuState.readItem(MenuInflater.java:328)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.view.MenuInflater.parseMenu(MenuInflater.java:147)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.view.MenuInflater.inflate(MenuInflater.java:97)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at slg.android.ui.BaseProviderSearchFragment.onCreateOptionsMenu(BaseProviderSearchFragment.java:39)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.support.v4.app._ActionBarSherlockTrojanHorse.onCreatePanelMenu(_ActionBarSherlockTrojanHorse.java:56)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:556)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchCreateOptionsMenu(ActionBarSherlockNative.java:60)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:154)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:393)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:747)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchInvalidateOptionsMenu(ActionBarSherlockNative.java:49)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:139)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:145)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at slg.android.ui.BaseProviderFragment.onCreate(BaseProviderFragment.java:43)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at slg.android.ui.BaseProviderSearchFragment.onCreate(BaseProviderSearchFragment.java:33)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:835)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1083)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:635)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1431)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:523)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.app.Activity.performStart(Activity.java:5018)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.app.ActivityThread.access$600(ActivityThread.java:130)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.os.Looper.loop(Looper.java:137)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at android.app.ActivityThread.main(ActivityThread.java:4745)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at java.lang.reflect.Method.invokeNative(Native Method)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at java.lang.reflect.Method.invoke(Method.java:511)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
09-28 12:56:10.124: E/AndroidRuntime(8466):     at dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
Nothing we can do about this, your build system is messing up. Check the mailing list if anyone is having the same issue.

**Comment by pflammertsma** [comment]
This appears to be related [to changes made in ADT 21 preview 5](http://tools.android.com/download/adt-21-preview#TOC-New-in-ADT-21-Preview-5):

> The R classes for library projects are generated with only the IDs needed by the libraries, reducing the risk of hitting dex files limits for fields and methods.

It appears that the new mechanism is prohibiting the generated R class from being exported out of the library. We'll have to wait and see if the ADT team intends on keeping it this way, so in the meantime I'd recommend reverting ADT back to the release channel.

See also [this discussion on Google Groups](https://groups.google.com/d/topic/actionbarsherlock/EZupRoP5kdg/discussion).

**Comment by pflammertsma** [comment]
I have a theory what's going wrong here: you must have two or more projects building with the same package names. It appears the generated R class is only exposed through one of them (not both).

I've dropped a line [on Tor Norbye's G+](https://plus.google.com/116539451797396019960/posts/KVax2483Erk), but in the meantime you'll have to either resolve the conflict or revert to ADT 20.

**Comment by dmostert** [comment]
I've found the following (http://tools.android.com/download/adt-21-preview)

There's a new flag to force "jumbo mode" for dex which allows a larger number of strings in the dex files; set **dex.force.jumbo=true** in _project.properties_

This seems to work

**Comment by Digipom** [comment]
I've fixed this by downgrading from ADT 21.1 to ADT 21 and same with the tools folder.

**Comment by khobaib** [comment]
@dmostert solution seems to work. Thank you.

**Comment by frmdstryr** [comment]
@dmostert your solution worked, thanks!
