### ISSUE TITLE
app can't exit when ABS is plugged in even if RuntimeException occurs

### ISSUE THREAD

**Issue by abchyw** [JakeWharton/ActionBarSherlock#640]
I want to have a option menu item that can help to exit my app.
the code is like: 
System.exit(0);
or
android.os.Process.killProcess(pid);
But unfortunately, whatever I tried, if I triggers the code not at the root Activity, the app will be restarted by the system for some reason instead of exiting. 
I look the code up from the logcat, the old process got killed, but a new process spawns with a new pid.

The reason why I associate this problem with ABS is because I also try my code above in the ABS sample. In the ContextMenus class and onOptionsItemSelected() method, I add the code. then when I run the modified sample and click the popped-up menu item by which it is suppose to quit the app, the sample restarts again! Take note that ContextMenus is not a root Activity, the root is SampleList. This problem occurs only when the current Activity is not a root Activity.

And I also found, when I test the my app, if I mess up somewhere and a RuntimeException is thrown, the app crashes and then gets restarted again immediately. That's really wired.

Does anyone have any idea about this bug?
I hope it can be fixed in the next ABS version.

**Comment by SimonVT** [comment]
ABS doesn't change how System.exit(0); works. Also, don't put an exit button in your app. Android apps don't have exit buttons.

**Comment by abchyw** [comment]
Thanks for your prompt reply.
Aside from exit stuff, when RuntimeException occurs, the app doesn't crash.
I know this problem sounds wired.
But could you please try throwing a RutimeException in the ABS sample( not at the root Activity ), the problem does happen.
