### ISSUE TITLE
Error inflating class com.actionbarsherlock.internal.widget.ActionBarContainer

### ISSUE THREAD

**Issue by ru-nekit-android** [JakeWharton/ActionBarSherlock#643]
On simulator on android 2.3.3 has an error 
07-21 22:36:32.772: E/AndroidRuntime(690): FATAL EXCEPTION: main
07-21 22:36:32.772: E/AndroidRuntime(690): java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.nekit.helpoid/ru.nekit.helpoid.MainActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class com.actionbarsherlock.internal.widget.ActionBarContextView
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.os.Handler.dispatchMessage(Handler.java:99)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.os.Looper.loop(Looper.java:123)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.app.ActivityThread.main(ActivityThread.java:3683)
07-21 22:36:32.772: E/AndroidRuntime(690):  at java.lang.reflect.Method.invokeNative(Native Method)
07-21 22:36:32.772: E/AndroidRuntime(690):  at java.lang.reflect.Method.invoke(Method.java:507)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
07-21 22:36:32.772: E/AndroidRuntime(690):  at dalvik.system.NativeStart.main(Native Method)
07-21 22:36:32.772: E/AndroidRuntime(690): Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class com.actionbarsherlock.internal.widget.ActionBarContextView
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.createView(LayoutInflater.java:518)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.generateLayout(ActionBarSherlockCompat.java:1049)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:919)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.initActionBar(ActionBarSherlockCompat.java:139)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchPostCreate(ActionBarSherlockCompat.java:308)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.app.SherlockFragmentActivity.onPostCreate(SherlockFragmentActivity.java:93)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1108)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1630)
07-21 22:36:32.772: E/AndroidRuntime(690):  ... 11 more
07-21 22:36:32.772: E/AndroidRuntime(690): Caused by: java.lang.reflect.InvocationTargetException
07-21 22:36:32.772: E/AndroidRuntime(690):  at java.lang.reflect.Constructor.constructNative(Native Method)
07-21 22:36:32.772: E/AndroidRuntime(690):  at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.LayoutInflater.createView(LayoutInflater.java:505)
07-21 22:36:32.772: E/AndroidRuntime(690):  ... 24 more
07-21 22:36:32.772: E/AndroidRuntime(690): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x2
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.View.<init>(View.java:2108)
07-21 22:36:32.772: E/AndroidRuntime(690):  at android.view.ViewGroup.<init>(ViewGroup.java:292)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.<init>(NineViewGroup.java:21)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.widget.AbsActionBarView.<init>(AbsActionBarView.java:65)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.widget.ActionBarContextView.<init>(ActionBarContextView.java:78)
07-21 22:36:32.772: E/AndroidRuntime(690):  at com.actionbarsherlock.internal.widget.ActionBarContextView.<init>(ActionBarContextView.java:74)
07-21 22:36:32.772: E/AndroidRuntime(690):  ... 27 more

In manifest 
 <uses-sdk
        android:minSdkVersion="10"
        android:targetSdkVersion="15" />

It is BIG EPIC FAIL

**Comment by JakeWharton** [comment]
Fix on `dev`.

**Comment by LulaV14** [comment]
How did you fix it :S?

**Comment by flipchen** [comment]
I seem to still have this bug. Only comes up with 2.3.x versions though.
Out of curiosity I switched to the dev branch and tried to get it working with it, but still no chance.

**Comment by ghost** [comment]
@JakeWharton  - sir how did you fix this? i still have the issue on android 2.3.6, please help .thanks
