### ISSUE TITLE
Menu Icon Background

### ISSUE THREAD

**Issue by VeeruPV** [JakeWharton/ActionBarSherlock#646]
Hi there
I am using ABS along with Sliding Menu

Everything works fine, just having some trouble trying to get the visual design right.

I have set a background for the titlebar via setCustomView . It works fine as expected, but the background is only set for the title and not for the icon.

Attached is a screenshot which will give a better understanding

http://i.imgur.com/84v9I.png

I would just want to set the background behind the icon on the left corner.

How can i do that?

And also, is there way i can remove the icon for certain activities/fragments?

Any help is highly appreciated.

**Comment by Alexious-sh** [comment]
You need to set background to all ActionBar? Right way to do this  - create custom theme for your activity.
Read this: http://actionbarsherlock.com/theming.html

**Comment by VeeruPV** [comment]
That worked pretty well - sorted the problem. Thanks a lot for pointing me in the right direction.

Some quick quesiton, 
how to remove the left arrow next to the icon?
How can i remove the icon itself for some activities/fragments?

**Comment by Alexious-sh** [comment]
Look at this sample:
https://github.com/JakeWharton/ActionBarSherlock/blob/master/samples/demos/src/com/actionbarsherlock/sample/demos/FeatureToggles.java
And this method working too:
http://developer.android.com/reference/android/app/ActionBar.html#setDisplayOptions(int)

Just set ActionBar options as you need in Activity's onCreate method, or any other place.

**Comment by SimonVT** [comment]
This sounds more like a question for stackoverflow or some other android developer forum.
