### ISSUE TITLE
Actionbar never shows action title even if there is only one item in portrait mode

### ISSUE THREAD

**Issue by lexer** [JakeWharton/ActionBarSherlock#647]
I've got a settings activity with single actionbar item that has icon and "Save" text.

```
<item android:id="@+id/save_menu_item"
      android:showAsAction="always|withText"
      android:title="@string/save_menu_item"
      android:icon="@drawable/ic_actionbar_done"/>
```

Action bar never shows action title in portrait mode. 

I've tested this on Galaxy Nexus that has very big screen. It definitely should fit its size.

**Comment by JakeWharton** [comment]
This is the native action bar behavior which cannot be changed.

See http://developer.android.com/guide/topics/ui/actionbar.html#ActionItems

**Comment by ErNaveen** [comment]
i have some problem in anctin bar

<item
        android:id="@+id/action_settings"
        android:actionLayout="@layout/action_button_foo"
        android:icon="@drawable/ic_launcher"
        android:showAsAction="ifRoom|withText"
        android:title="Home"/>

not coming Icon
