### ISSUE TITLE
Change ActionMenuItem font face when using custom theme for actionbar

### ISSUE THREAD

**Issue by moallemi** [JakeWharton/ActionBarSherlock#649]
Hi,

I can change ActionMenuItems when ussing default sherlock Light theme with this method:

@Override
public boolean onCreateOptionsMenu(Menu menu) {
        getSupportMenuInflater().inflate(R.menu.main, menu);

```
    getLayoutInflater().setFactory(new LayoutInflater.Factory() {
        public View onCreateView(String name, Context context,
                AttributeSet attrs) {

            if (name.equalsIgnoreCase("com.android.internal.view.menu.IconMenuItemView")
                    || name.equalsIgnoreCase("TextView")) {
                try {
                    LayoutInflater li = LayoutInflater.from(context);
                    final View view = li.createView(name, null, attrs);
                    new Handler().post(new Runnable() {
                        public void run() {

                            // here I change the font!
                        }
                    });
                    return view;
                } catch (InflateException e) {
                    // Handle any inflation exception here
                } catch (ClassNotFoundException e) {
                    // Handle any ClassNotFoundException here
                }
            }
            return null;
        }
    });

    return true;
}
```

But when I change the them and use a custom theme using this utility (http://jgilfelt.github.com/android-actionbarstylegenerator/), I can not change the font and the above code causes exception. what is the solution to this problem?

**Comment by JakeWharton** [comment]
This is a giant hack for non-standard functionality and is not supported in any way. Try StackOverflow.

I'll even give you a hint, `com.android.internal.view.menu.IconMenuItemView` is API 11+.

**Comment by moallemi** [comment]
would you please help me with this: http://stackoverflow.com/questions/12757094/how-to-change-actionbarsherlock-menu-item-font-face-when-using-custom-theme-for

I explained the problem in more details

thanks

**Comment by felipearimateia** [comment]
Error

02-14 14:55:54.625: E/AndroidRuntime(17743): FATAL EXCEPTION: main
02-14 14:55:54.625: E/AndroidRuntime(17743): java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
02-14 14:55:54.625: E/AndroidRuntime(17743):    at android.view.LayoutInflater.setFactory(LayoutInflater.java:277)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at br.com.aorta.radioskol.ui.HomeActivity.onCreateOptionsMenu(HomeActivity.java:132)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:45)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:559)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchCreateOptionsMenu(ActionBarSherlockNative.java:60)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:165)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:445)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:819)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:3148)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at android.os.Handler.handleCallback(Handler.java:615)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at android.os.Handler.dispatchMessage(Handler.java:92)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at android.os.Looper.loop(Looper.java:137)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at android.app.ActivityThread.main(ActivityThread.java:4898)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at java.lang.reflect.Method.invokeNative(Native Method)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at java.lang.reflect.Method.invoke(Method.java:511)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
02-14 14:55:54.625: E/AndroidRuntime(17743):    at dalvik.system.NativeStart.main(Native Method)

**Comment by iNoles** [comment]
@felipearimateia  java.lang.IllegalStateException: A factory has already been set on this LayoutInflater

It seems you can't set it more than once.

**Comment by mircobabini** [comment]
No solutions?

**Comment by NilaySheth** [comment]
Anyone got any solutions for this yet ??
