### ISSUE TITLE
Header/Footer Disapearing problem...

### ISSUE THREAD

**Issue by amirgalor** [JakeWharton/ActionBarSherlock#65]
Hi,

It seems I have stumbled upon a tiny annoying bug... at least I think so...

When a ListFragment (which setAdapter was called upon) returns from the BackStack, if a Header/Footer was added to that Fragment - the Header/Footer disappears. this is due to the fact "ListFragment.onDestrotyView()" puts a "null" in "mList".

upon returning to the ListFragment from backstack there's no option to add the header again (using addHeaderView) as the code will calls "ensureList" if trying to getListView on any overridden method method...

There's a way to circumvent this - just call "setListAdapter(null)" @ "onDestroyView" for example and remember to set it in some "onCreate" method...

I would consider this a bug... what do you think ?

**Comment by JakeWharton** [comment]
I would consider it a bug. However, it is a bug with the native compatibility library and not with ActionBarSherlock directly. I suggest you file a ticket for it on [b.android.com](http://b.android.com). This way it can get integrated in the next release of the official compat lib (and then updated in ABS once released).

I'm going to close this, but if (read: when!) you file a ticket please paste the link as a comment so I can track it as well.

Thanks for the report!

**Comment by amirgalor** [comment]
ThanX for the quick reply,

I was not sure if you are keeping a strict integration with the official
compatibility library.

the is the link for the bug-report,

http://code.google.com/p/android/issues/detail?id=20208&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

A.

**Comment by JakeWharton** [comment]
I'm only accepting bugfix patches for the compat lib since I have a faster release cycle. I'm not going out of my way to solve all the problems though, that would be far too much of a commitment (and headache) for me.

If a fix is posted to the issue before the release of the next compat lib revision I'll be sure to get it out as quickly as possible.
