### ISSUE TITLE
Publish version 4.2.0 to the maven repository

### ISSUE THREAD

**Issue by mr-thierry** [JakeWharton/ActionBarSherlock#651]
The latest version is still not in the maven repository. Any reason why? :)

**Comment by JakeWharton** [comment]
It's there for me: http://search.maven.org/#artifactdetails%7Ccom.actionbarsherlock%7Cactionbarsherlock%7C4.2.0%7Capklib

**Comment by JakeWharton** [comment]
Oh, I forgot to publish the stupid migration thing as well. Will do that today.

**Comment by mr-thierry** [comment]
Ah, you changed the artifactId from "library" to "actionbarsherlock". My mistake. ;)

**Comment by JakeWharton** [comment]
I was supposed to deploy a migration pom to central which would allow people to use 'library' but be warned that it changed. Of course, I forgot to do so. Oops!

**Comment by imminent** [comment]
Oh, cool I didn't know about migration pom's, but I like to read the
changelog when I upgrade a dependency and I think you mention the artifact
change there.

**Comment by JakeWharton** [comment]
Relocation pom has been released. Should show up in central in a few hours.
