### ISSUE TITLE
Force Overflow Alternative

### ISSUE THREAD

**Issue by MFlisar** [JakeWharton/ActionBarSherlock#654]
I know, you removed forced overflow, but I'm wondering if there is another way to get such a behaviour now or if there is none and I have to now use submenus if I want to "force" such a behaviour...

I think, it does not look good on old phones if the normal menu is used, especially using dark theme and bright items (as in the demo as well) leads to not visible items in the normal menu...

**Comment by intrications** [comment]
This issue says what ActionBarSherlock will do in the future to improve the look of the menu on pre-HC devices:
https://github.com/JakeWharton/ActionBarSherlock/issues/627

**Comment by MFlisar** [comment]
ok, thank you

**Comment by crossle** [comment]
If user abs 4.2,  how can I implement the ForceOverflow on pre-HC devices
