### ISSUE TITLE
Tab navigation does not use separate bar when using the compatibility action bar in portrait

### ISSUE THREAD

**Issue by pmecho** [JakeWharton/ActionBarSherlock#655]
When using tab navigation, the tab placement doesn't match that of 4.0+ which is using the native action bar in portrait (haven't tried Honeycomb).  On the gingerbread devices I tried (Kindle Fire and Gingerbread phone emulators) the tabs are integrated into the action bar whereas when the native action bar is used the tabs are below the action bar.  I think this only affects phones and 7" tablets in portrait, landscape is integrated as it should be.

Screenshot of a JellyBean Galaxy Nexus:
http://cl.ly/image/0v2c0T1s1D3v
![Galaxy Nexus](http://f.cl.ly/items/1d3O0J0q0j1F061r2m3L/Screen%20Shot%202012-10-12%20at%205.05.02%20PM.png)

Screenshot of Nexus 7:
http://cl.ly/image/1z0u2w0c2M39
![Nexus 7](http://f.cl.ly/items/3w1e1j273g1n3J181j3o/Screen%20Shot%202012-10-12%20at%205.04.55%20PM.png)

Screenshot of Gingerbread emulator:
http://cl.ly/image/0m221t3d2j22
![Gingerbread Emulator](http://f.cl.ly/items/0D1u21423Q0p3P07132F/Screen%20Shot%202012-10-12%20at%205.04.41%20PM.png)

**Comment by gauravar** [comment]
I am also Noticing the same issue With HoneyComb. ActionBar integrates with the tab bar in landscape mode.

**Comment by imminent** [comment]
Wouldn't ABS use the native Action Bar on those devices? It's left to the
Action Bar to decide if it can show the tabs inline or have to overflow
them to split action bar. It seems that Honeycomb may use slightly slimmer
tabs that fit easier into the Action Bar.

**Comment by pmecho** [comment]
gauravar: The issue is concerning pre-HC devices.  API 11+ devices will use the native action bar so there is no control over the tab layout.  Landscape on my Jelly Bean and ICS devices integrates the tabs into the action bar.  Portrait puts them below the action bar.

**Comment by JakeWharton** [comment]
When the width is greater than or equal to 480dp the action bar is embedded. When it is less than that, it is shown on a separate line. This is the exact same behavior as the native action bar (because it is a direct backport).

**Comment by gauravar** [comment]
Thanks.

**Comment by pmecho** [comment]
Ah! It looks like the embedded tab policy changed in JB.  This explains my issue
Extract:
"New ActionBar policy for embedded tabs: embedded tabs are now always stacked in the action bar when in portrait mode, regardless of the size of the screen."
From:
http://developer.android.com/reference/android/os/Build.VERSION_CODES.html#JELLY_BEAN

**Comment by JakeWharton** [comment]
Interesting policy. Thanks for the clarification. ABS will always reflect the ICS action bar since it would be unwise to exhibit JB behavior on pre-ICS and post-ICS but not on ICS itself.

**Comment by pmecho** [comment]
That makes sense.
