### ISSUE TITLE
SherlockDialogFragment wih Theme

### ISSUE THREAD

**Issue by Leandros** [JakeWharton/ActionBarSherlock#656]
Actually there is no possibility to apply a theme to a SherlockDialogFragment by using the `AlertDialog.Builder` like this `AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());`

**Comment by JakeWharton** [comment]
A dialog fragment is simply a wrapper around managing a dialog. A `SherlockDialogFragment` just adds support for ActionBarSherlock menu items to a normal `DialogFragment`. If you have questions about dialog fragments and their usage please try StackOverflow or the official Android developers mailing list.

**Comment by Leandros** [comment]
I explained it a bit wrong, was late at night.

I have a `SherlockFragment`, which open a `SherlockDialogFragment` via the `ContextualActionMode`. The Dialog contains a `Spinner` which closed state can't be themed. (I tried **everything**.)
If a simple `Activity` open the `DialogFragment` it work fine.

**Comment by SimonVT** [comment]
Add some samples to the known bugs project, then we'll take a look at it.
