### ISSUE TITLE
SplitActionBar not showing up on one certain device

### ISSUE THREAD

**Issue by nassendelft** [JakeWharton/ActionBarSherlock#657]
I'm using v4.1.0 and on the Sony Xperia S running android 2.3.7 it wont show the SplitActionBar for some reason. This is not a huge problem or anything but just a minor inconvenience. If you need any additional info i'm happy to give them. Didn't notice anything specific in the logcat. Works fine on a all other devices i tested on (about 10+).

**Comment by SimonVT** [comment]
Probably a duplicate of #522. Blame Sony Ericsson.
