### ISSUE TITLE
Styling SearchView problem

### ISSUE THREAD

**Issue by milek** [JakeWharton/ActionBarSherlock#658]
I have a bit of a problem with styling SearchView. I've noticed that there's style name searchAutoCompleteTextView declared in abs__styles.xml, yet when I try to style it, nothing happens

``` xml
  <style name="MyTheme" parent="Theme.Sherlock.Light.DarkActionBar">
        <item name="searchAutoCompleteTextView">@style/Widget.My.ActionBar.SearchView</item>
  </style>
  <style name="Widget.My.ActionBar.SearchView" parent="Widget.Sherlock.SearchAutoCompleteTextView">
        <item name="android:textColor">#ffffff00</item>
  </style>
```

Any idea? Maybe I'm doing something wrong?

**Comment by kevindmoore** [comment]
I'm having the same problem

**Comment by kevindmoore** [comment]
I think I see the problem. Since the search view is being created later in code, the style isn't applying. I seem to be able to apply the styles after I get the actionView in onCreateOptionsMenu when I expand my search menu.

**Comment by klevi** [comment]
any proper workaround for this?

**Comment by SimonVT** [comment]
The searchAutoCompleteTextView attribute is not part of the public android api.
