### ISSUE TITLE
Search Suggestions Provider with SearchView does not work

### ISSUE THREAD

**Issue by yincrash** [JakeWharton/ActionBarSherlock#659]
Leftover from https://github.com/JakeWharton/ActionBarSherlock/issues/70.

ABS SearchView does not support search suggestions via a SearchableInfo.

**Comment by yincrash** [comment]
Created pull request.
https://github.com/JakeWharton/ActionBarSherlock/pull/660

**Comment by JakeWharton** [comment]
This was merged to `dev`.

**Comment by AndroidGecko** [comment]
this issue seems to still be there

http://stackoverflow.com/questions/13798668/does-actionbarsherlock-4-2-support-search-suggestions-for-a-searchview/14260518#14260518

**Comment by JakeWharton** [comment]
Did you try the `dev` branch?

**Comment by AndroidGecko** [comment]
sorry Jake for not checking first, suggestions work fine in dev branch

**Comment by grendell** [comment]
Is there any reason why I wouldn't want to pull the fix (https://github.com/JakeWharton/ActionBarSherlock/commit/1e880a3a9f5d0e28d6e51cc9fdfb5bb08dee77ea) into my own fork of master?  Just want to make sure there isn't something lurking beneath the surface.  Thanks!
