### ISSUE TITLE
Menu items, weird behaviour

### ISSUE THREAD

**Issue by Konsumierer** [JakeWharton/ActionBarSherlock#661]
Android 2.3.7 (CM7) - HTC Desire
ABS 4.2

Just changed from ABS 4.1 to 4.2. In Activities where I am using menu items with android:showAsAction="ifRoom|withText", the menu items show up as an icon in the ActionBar. When I press the menu key of the device, the icons disappear from the ActionBar and walk into the oldschool menu. Does not feel like this is the intended behaviour ;)

**Comment by JakeWharton** [comment]
Please create a pull request against the `dev` branch which adds a sample demonstrating the bug in the 'known-bugs' sample.

**Comment by Konsumierer** [comment]
I am sorry. I posted this issue directly after the ABS 4.2 release in a wrong GitHub project. Now I cannot reproduce the problem.
