### ISSUE TITLE
Virtual menu button with getSupportActionBar().hide() and FullScreen

### ISSUE THREAD

**Issue by slartus** [JakeWharton/ActionBarSherlock#663]
I'm trying to implement a full-screen viewing.
How do I make A virtual menu button on android 3.0 and above for the menu in this mode?

code:
getSupportActionBar().hide();
getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);

The menu does not cause without hardware buttons.

**Comment by JakeWharton** [comment]
If you hide the action bar there simply is no menu, sorry.
