### ISSUE TITLE
Background color for theme light with dark actionbar

### ISSUE THREAD

**Issue by tbouron** [JakeWharton/ActionBarSherlock#664]
Hi.

I'm using ActionBarSherlock for my app and i came across a funny thing yesterday during my tests.
I'm using a custom theme that extends form the light theme with dark actionbar. When i run my app on the emulator (Android 2.x or 4.x) it looks as it's supposed to be:

![](https://dl.dropbox.com/u/12862719/SeriesAddict/1.2/dashboard-portrait.png)

But on the emulator (Android 3.x) and some phone (in this case, it's a Sony Ericsson Neo V with and official android 4.0.4 ROM from Sony), it looks like this:

![](https://dl.dropbox.com/u/12862719/SeriesAddict/bug/device-2012-10-16-230435.png)

So the question is, do you know why there is such behavior? And of course, can it be fixed somehow?

Thanks!

**Comment by JakeWharton** [comment]
ABS doesn't affect the theme background. Whatever you're seeing is from the platform's `Theme.Light.NoActionBar` or `Theme.Holo.NoActionBar` depending on what API level you are running. If you want consistency, you should specify your own `android:windowBackground` on your theme.

**Comment by tbouron** [comment]
Ok, I thought it was done directly on ABS. Thanks for the reply!
