### ISSUE TITLE
Update of android-support-v4 library

### ISSUE THREAD

**Issue by johnkil** [JakeWharton/ActionBarSherlock#665]
I use features from new android-support-v4 library (f.e. NotificationCompat.Bilder or other). But your libarary contains old version of that library that don't have compatibility with android 4.1 (Jelly Bean).

**Comment by SimonVT** [comment]
Duplicate of #537

**Comment by JakeWharton** [comment]
ABS compiles with Maven. Maven only has r7. Hence I keep the .jar in sync.

If you need a newer version you can simply replace it yourself for now.
