### ISSUE TITLE
Tabs loose click ability after rotating device

### ISSUE THREAD

**Issue by OS-Chris** [JakeWharton/ActionBarSherlock#668]
Can't trigger other tabs after rotating the device. It happens when tabs switch from inline (within the actionbar) (landscape) to just under actionbar (portrait) and vice-versa.

Once rotated back to the original orientation, click ability returns.

**Comment by JakeWharton** [comment]
Please create a pull request against the `dev` branch which adds a sample to the 'known-bugs' project which can demonstrate this behavior.

**Comment by OS-Chris** [comment]
In writing a simple test-case, the described issue has disappeared so it's something on my end (I'm using HoloEverywhere which extends SherlockActivity so it COULD be that, I'm guessing it's my code somehow screwing things up though).
