### ISSUE TITLE
OptionsMenu in ActionBar don's show some times?

### ISSUE THREAD

**Issue by crossle** [JakeWharton/ActionBarSherlock#669]
I have a ViewPager, it had a three Fragment in ActionBar Tab. I added optionmenu in every fragment,
when i swap viewpager, the optionsmenu on ActionBar don't show some times?
you know?

**Comment by imminent** [comment]
Did you also say setHasOptionsMenu in the onCreate in the Fragment too? The
ActionBar doesn't know about your Fragment options menu otherwise.

**Comment by JakeWharton** [comment]
This is a dupe of #351 and a framework bug which has been reported at http://b.android.com/29472
