### ISSUE TITLE
Change project name from 'library' to something more understandable

### ISSUE THREAD

**Issue by tucson-tom** [JakeWharton/ActionBarSherlock#670]
Importing this project into Eclipse imports the project as 'library' into the workspace.  The FAQ for this library includes a YouTube video that shows that the name can be set using an older SDK/Eclipse combination.  However, the latest Eclipse Juno with the latest Android SDK doesn't allow for changing the name to something more understandable.  It simply imports this library as 'library'.

Two things need to be done to resolve this issue:

1)  Change the default from 'library' to something else.

2)  Update the FAQ and general usage instructions with more precise directions for the latest Eclipse and Android SDK.

**Comment by JakeWharton** [comment]
I wish I could erase Eclipse from the history of the world. It's just awful for Android and Maven. I guess I have no choice but to rename the folder. Lame software is lame.

**Comment by kevinsawicki** [comment]
Don't change this, if you want to support Eclipse just check-in a `.project` file with the `name` element as ActionBarSherlock, or people using Eclipse can simply rename the project after they import it.

If anything I would shorten it from `library` to `lib`.

**Comment by JakeWharton** [comment]
That violates my rule of not checking in IDE files! However, if it will make Eclipse users' lives much easier then I'm all for it. Especially since I use this naming convention elsewhere which can cause collisions on importing project named 'library' which is just an awful user experience.

I'll grab Eclipse and do some experimentation to make sure it works for both normal library project importers and m2e-eclipse users.

**Comment by kevinsawicki** [comment]
IDE files make lives the easiest and allow you to enforce coding standards that will fail in the IDE before they fail in Travis for people making contributions.

**Comment by schildbach** [comment]
I think naming a project just "library" is indeed a bad idea, even if it's just a sub-project.

**Comment by JakeWharton** [comment]
Fixed on `dev`.

@Goonie the folder is named "library", not the project.
