### ISSUE TITLE
ShareActionProvider does not dismiss on rotating

### ISSUE THREAD

**Issue by AhmadTK** [JakeWharton/ActionBarSherlock#671]
i am using (android:configChanges="orientation|screenSize")  for my SherlockFragmentActivity where I prevent recreating the activity again. 

The issue that when I rotate the device while the shareActionProvider is showing, it does not dismiss after rotating, it also removes one item every rotation. 

android:minSdkVersion="8"
android:targetSdkVersion="16"

**Comment by SimonVT** [comment]
ABS does not support handling configuration changes.
