### ISSUE TITLE
.setDisplayShowHomeEnabled(false) flips tabs and actionbar

### ISSUE THREAD

**Issue by Leandros** [JakeWharton/ActionBarSherlock#674]
If I call `getSupportActionbar().setDisplayShowHomeEnabled(false);`, with `ActionBar.Tabs` enabled and in use, the app icon is hidden, as expected, but the ActionBar and TabBar fip their position. (Tabs are above the ActionBar).

Edit: `<item name="android:displayOptions">showTitle</item>` in the `ActionBarStyle` in `XML` has the same behaviour as above.

**Comment by JakeWharton** [comment]
This is the behavior of the native action bar which is mimicked by ABS. File a bug at http://b.android.com/

**Comment by Leandros** [comment]
Hm, yeah. I see. I should've searched more before opening a issue. 

There is already a bug on b.android.com http://code.google.com/p/android/issues/detail?id=36191
and an old issue of ABS https://github.com/JakeWharton/ActionBarSherlock/issues/327

Sorry. ;)

**Comment by Michael-Zinn** [comment]
We dealt with this by using a transparent icon with width = 0.
