### ISSUE TITLE
Tab automatically adds over scroll? 

### ISSUE THREAD

**Issue by thunderousNinja** [JakeWharton/ActionBarSherlock#676]
I downloaded the most recent demo file from the website (http://actionbarsherlock.com/download.html) and also the previous demo file ,Version 4.2.0 — 2012-10-07  and  Version 4.1.0 — 2012-05-18, respectively. 

On the older demo the "Tab Navigation" demo activity works fine, the tabs are fixed and have no scroll. However, the same "Tab Navigation" activity with the newest library seems to be acting weird, there is automatically a horizontal scroll added to the tabs if there are 2 or more.  This only seems to be an issue with older devices ( 2.3 and below). 

Can this be fixed? If not how can I make the tabs fixed with no horizontal scroll?

**Comment by JakeWharton** [comment]
Dupe #673.
