### ISSUE TITLE
Crash on Android 3.1 on getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

### ISSUE THREAD

**Issue by dschuermann** [JakeWharton/ActionBarSherlock#68]
On Android 3.1 my app crashes on `getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);`

But it works on Android 3.2

Stacktrace:
    09-28 09:23:37.272: ERROR/AndroidRuntime(386): FATAL EXCEPTION: main
    09-28 09:23:37.272: ERROR/AndroidRuntime(386): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.adaway/org.adaway.ui.ListsActivity}: java.lang.NullPointerException
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1748)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1764)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.app.ActivityThread.access$1500(ActivityThread.java:122)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1002)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.os.Handler.dispatchMessage(Handler.java:99)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.os.Looper.loop(Looper.java:132)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.app.ActivityThread.main(ActivityThread.java:4025)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at java.lang.reflect.Method.invokeNative(Native Method)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at java.lang.reflect.Method.invoke(Method.java:491)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at dalvik.system.NativeStart.main(Native Method)
    **09-28 09:23:37.272: ERROR/AndroidRuntime(386): Caused by: java.lang.NullPointerException**
    **09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at org.adaway.ui.ListsActivity.onCreate(ListsActivity.java:77)**
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1048)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1712)
    09-28 09:23:37.272: ERROR/AndroidRuntime(386):     ... 11 more

Code:
    /*
     \* Copyright (C) 2011 Dominik Schürmann dominik@dominikschuermann.de
     *
     \* This file is part of AdAway.
     \* 
     \* AdAway is free software: you can redistribute it and/or modify
     \* it under the terms of the GNU General Public License as published by
     \* the Free Software Foundation, either version 3 of the License, or
     \* (at your option) any later version.
     *
     \* AdAway is distributed in the hope that it will be useful,
     \* but WITHOUT ANY WARRANTY; without even the implied warranty of
     \* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     \* GNU General Public License for more details.
     *
     \* You should have received a copy of the GNU General Public License
     \* along with AdAway.  If not, see http://www.gnu.org/licenses/.
     *
     */

```
package org.adaway.ui;

import org.adaway.R;

import android.content.Intent;
import android.content.res.Configuration;
import android.os.Bundle;
import android.support.v4.app.ActionBar;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentTransaction;
import android.support.v4.app.ActionBar.Tab;
import android.support.v4.view.MenuItem;

public class ListsActivity extends FragmentActivity implements ActionBar.TabListener {

    /**
     * Set ActionBar to include sign to Home
     */
    @Override
    protected void onStart() {
        super.onStart();
        ActionBar actionBar = this.getSupportActionBar();
        actionBar.setDisplayHomeAsUpEnabled(true);
    }

    /**
     * Menu item to go back home in ActionBar, other menu items are defined in Fragments
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
        case android.R.id.home:
            // app icon in Action Bar clicked; go home
            Intent intent = new Intent(this, BaseActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
            startActivity(intent);
            return true;
        default:
            return super.onOptionsItemSelected(item);
        }
    }

    /**
     * Set up Tabs on create
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // start with blacklist
        BlacklistFragment blacklistFragment = new BlacklistFragment();
        getSupportFragmentManager().beginTransaction().add(android.R.id.content, blacklistFragment)
                .commit();

        getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

        ActionBar.Tab tab1 = getSupportActionBar().newTab();
        ActionBar.Tab tab2 = getSupportActionBar().newTab();
        ActionBar.Tab tab3 = getSupportActionBar().newTab();

        tab1.setTabListener(this);
        tab2.setTabListener(this);
        tab3.setTabListener(this);

        // longer names for landscape mode or tablets
        if (getResources().getConfiguration().orientation == Configuration.ORIENTATION_LANDSCAPE
                || getResources().getConfiguration().screenLayout == Configuration.SCREENLAYOUT_SIZE_XLARGE) {
            tab1.setText(getString(R.string.lists_tab_blacklist));
            tab2.setText(getString(R.string.lists_tab_whitelist));
            tab3.setText(getString(R.string.lists_tab_redirection_list));

        } else {
            tab1.setText(getString(R.string.lists_tab_blacklist_short));
            tab2.setText(getString(R.string.lists_tab_whitelist_short));
            tab3.setText(getString(R.string.lists_tab_redirection_list_short));
        }

        getSupportActionBar().addTab(tab1);
        getSupportActionBar().addTab(tab2);
        getSupportActionBar().addTab(tab3);
    }

    @Override
    public void onTabReselected(Tab tab, FragmentTransaction ft) {
    }

    /**
     * Open Fragment based on selected Tab
     */
    @Override
    public void onTabSelected(Tab tab, FragmentTransaction ft) {
        // choose current fragment based on tab position
        Fragment fragment = null;
        switch (tab.getPosition()) {
        case 0:
            fragment = new BlacklistFragment();
            break;
        case 1:
            fragment = new WhitelistFragment();
            break;
        case 2:
            fragment = new RedirectionListFragment();
            break;
        default:
            fragment = new BlacklistFragment();
            break;
        }

        FragmentManager fragmentManager = getSupportFragmentManager();
        FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
        fragmentTransaction.replace(android.R.id.content, fragment);
        fragmentTransaction.commit();
    }

    @Override
    public void onTabUnselected(Tab tab, FragmentTransaction ft) {
    }
}
```

**Comment by JakeWharton** [comment]
The problem here is that fragment transactions are asynchronous and the action bar is only set up when a view is first attached to the activity. Even though you are committing your transaction, the actual attaching of the fragment to the view does not take place until later. In this time your code has moved on and calls `getSupportActionBar()` which returns `null`.

The solution is to force fragment manager to execute your transaction synchronously so that the action bar setup will occur immediately. You can do this by adding the following line after your commit your transaction:

```
getSupportFragmentManager().executePendingTransactions();
```

**Comment by dschuermann** [comment]
Thanks for the fast response.

Unfortunately it does not work. My new code looks like this:
    /**
     \* Set up Tabs on create
     */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

```
    // start with blacklist
    BlacklistFragment blacklistFragment = new BlacklistFragment();
    getSupportFragmentManager().beginTransaction().add(android.R.id.content, blacklistFragment)
            .commit();

    // execute transactions before using ActionBar. ActionBar will be null because without this
    // fragment transactions are asynchronous and ActionBar is not ready at once
    getSupportFragmentManager().executePendingTransactions();

    getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

    ActionBar.Tab tab1 = getSupportActionBar().newTab();
    ActionBar.Tab tab2 = getSupportActionBar().newTab();
    ActionBar.Tab tab3 = getSupportActionBar().newTab();
```

Exception is the same:
09-28 11:23:47.503: ERROR/AndroidRuntime(463): Caused by: java.lang.NullPointerException
09-28 11:23:47.503: ERROR/AndroidRuntime(463):     at org.adaway.ui.ListsActivity.onCreate(ListsActivity.java:81)
09-28 11:23:47.503: ERROR/AndroidRuntime(463):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1048)
09-28 11:23:47.503: ERROR/AndroidRuntime(463):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1712)
09-28 11:23:47.503: ERROR/AndroidRuntime(463):     ... 11 more

As said before it does not occur on Android 3.2

**Comment by JakeWharton** [comment]
Are you declaring Theme.Sherlock or Theme.Sherlock.Light as your activity or
application theme in the manifest? Or using a custom theme that inherits
from one of these two?

---

Jake Wharton
http://about.me/jakewharton
On Sep 28, 2011 7:28 AM, "Dominik Schrmann" <
reply@reply.github.com>
wrote:

**Comment by dschuermann** [comment]
I am using Theme.Sherlock defined in AndroidManifest.

See my sourcecode on gitorious:
https://gitorious.org/adaway/adaway/trees/master

**Comment by JakeWharton** [comment]
Alright. Despite executing synchronously via `executePendingTransactions` the fragment does not seem to be triggering the native action bar attachment on 3.0 (didn't test 3.1).

Here is my solution:

``` java
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    //FORCE the attachment of the action bar on all platforms as inexpensively as possible.
    setContentView(new FrameLayout(this));

    //*** Delete all your code that was here ***//

    getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

    //Everything else...
```

The first tab added will automatically have its `select()` method called so you do not need to attach its contents manually.

I might add a check for this crazy edge-case inside the library itself to mitigate the error. Something like on the first call to `getSupportActionBar()` if `setContentView()` was never called and a fragment transaction was committed to be attached to `android.R.id.content` then automatically call `setContentView` with `new FrameLayout(this)`.

Let me know if this works out for you. Crazy, crazy bug.

**Comment by JakeWharton** [comment]
Closing. Hit up the [Google Group](http://abs.io/group) if you need more assistance.

**Comment by dschuermann** [comment]
thanks, that worked!
