### ISSUE TITLE
ActionTab can't click ?

### ISSUE THREAD

**Issue by crossle** [JakeWharton/ActionBarSherlock#680]
I used ActionTab in ActionBar and viewpager.but on the Android2.3,I can flip viewpager chage tab framgent on the landscape ,but it's cant click ActionTab change fragment....

**Comment by crossle** [comment]
I resolved ..the Class implements ActionBar.TabListener is OK, before I used inner class ,It's no.!!!

**Comment by crossle** [comment]
the problem can't resolve? it's occur agagin?

**Comment by crossle** [comment]
I found if the first in the portrait the ActionTab can click,but change the oritation to Landscape, the ActionTab can't click.. And vice versa?

**Comment by SimonVT** [comment]
Did you add android:configChanges="orientation"?
