### ISSUE TITLE
Up button not working on Android 2

### ISSUE THREAD

**Issue by Michael-Zinn** [JakeWharton/ActionBarSherlock#681]
Since we updated to ABS 4.2.0, the up button behaves strangely on Android 2 (it works correctly on Android 3 and 4):
- Tapping it seems to do nothing
- When you first tap up and then any other active GUI element (button, action item, settings checkbox...), the action gets performed and immediately the up event gets performed (we see this in our app where tapping "share" briefly opens the share menu before the whole activity gets finished by the up event).

This happens in all our screens. We typically set up the Actionbar like this in onCreate after we inflated the layout:

ActionBar ab = getSupportActionBar();
ab.setTitle("Bla");
ab.setHomeButtonEnabled(true);
ab.setDisplayHomeAsUpEnabled(true);
ab.setDisplayShowTitleEnabled(true);

...and we react to it like this:
public boolean onOptionsItemSelected(MenuItem item) {
    switch (item.getItemId()) {
        case android.R.id.home:
            Intent intent = ...
            startActivity(intent);
            return true;

**Comment by Michael-Zinn** [comment]
Maybe it's Samsung? We have this problem on these devices only (But we don't have that many test devices so maybe it's not really a pattern):
- Samsung Gio
- Samsung SGS2

It works in the emulator.

**Comment by Michael-Zinn** [comment]
Apparently this problem only occurs SOMETIMES. It's now working on the Gio again, without any changes.

**Comment by Michael-Zinn** [comment]
Further inspection indicates that the problem has to do with the ABS+HoloEverywhere combination.

I recommend not working on this issue until I found out more.

**Comment by JakeWharton** [comment]
Closing for now. If you can create a sample project which demonstrates the issue we can re-open.
