### ISSUE TITLE
Cannot instantiate class: res/drawable-mdpi/ic_voice_search.png

### ISSUE THREAD

**Issue by elprl** [JakeWharton/ActionBarSherlock#683]
Hi, 
On a Galaxy Tab 750 (GT-P7500) (OS 3.1) I'm seeing the following Exception:

`10-30 10:30:35.830: W/dalvikvm(14406): dvmFindClassByName rejecting 'res/drawable-mdpi/ic_voice_search.png'
10-30 10:30:35.860: W/MenuInflater(14406): Cannot instantiate class: res/drawable-mdpi/ic_voice_search.png
10-30 10:30:35.860: W/MenuInflater(14406): java.lang.ClassNotFoundException: res/drawable-mdpi/ic_voice_search.png in loader dalvik.system.PathClassLoader[/data/app/com.o2.office2android-2.apk]
10-30 10:30:35.860: W/MenuInflater(14406):  at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:251)
10-30 10:30:35.860: W/MenuInflater(14406):  at java.lang.ClassLoader.loadClass(ClassLoader.java:540)
10-30 10:30:35.860: W/MenuInflater(14406):  at java.lang.ClassLoader.loadClass(ClassLoader.java:500)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.view.MenuInflater$MenuState.newInstance(MenuInflater.java:463)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.view.MenuInflater$MenuState.readItem(MenuInflater.java:366)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.view.MenuInflater.parseMenu(MenuInflater.java:147)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.view.MenuInflater.inflate(MenuInflater.java:97)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.o2.office2android.O2MainActivity.onCreateOptionsMenu(O2MainActivity.java:156)
10-30 10:30:35.860: W/MenuInflater(14406):  at android.support.v4.app._ActionBarSherlockTrojanHorse.onCreatePanelMenu(_ActionBarSherlockTrojanHorse.java:45)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:556)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:483)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:273)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.actionbarsherlock.internal.ActionBarSherlockCompat$1.run(ActionBarSherlockCompat.java:988)
10-30 10:30:35.860: W/MenuInflater(14406):  at android.os.Handler.handleCallback(Handler.java:587)
10-30 10:30:35.860: W/MenuInflater(14406):  at android.os.Handler.dispatchMessage(Handler.java:92)
10-30 10:30:35.860: W/MenuInflater(14406):  at android.os.Looper.loop(Looper.java:132)
10-30 10:30:35.860: W/MenuInflater(14406):  at android.app.ActivityThread.main(ActivityThread.java:4028)
10-30 10:30:35.860: W/MenuInflater(14406):  at java.lang.reflect.Method.invokeNative(Native Method)
10-30 10:30:35.860: W/MenuInflater(14406):  at java.lang.reflect.Method.invoke(Method.java:491)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
10-30 10:30:35.860: W/MenuInflater(14406):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
10-30 10:30:35.860: W/MenuInflater(14406):  at dalvik.system.NativeStart.main(Native Method)`

The log above is from abs 4.1 but it also happens on latest 4.2 version. I don't see the issue on other devices (works fine on Xoom, Nexus 7, LG-990 phone). I don't use the search bar or icon in my app and I can't see the png anywhere in my workspace - other than the abs__ic_voice_search.png. So none of my <item>'s in my xml menu (that gets inflated) use a search icon. 

Line 156 in my activity is this:
        `inflater.inflate(R.menu.main_menu, menu);`

If this helps, my styles.xml has this:
`<style name="AppTheme" parent="Theme.Sherlock.Light.DarkActionBar">
        <item name="android:panelFullBackground">@android:color/black</item>
</style>`

Anyone seen this before?

**Comment by larham** [comment]
yes, but only on galaxy tab 10 running Android 3.2, and then as warning-level logging from a library layer.  I think it was the 3.1 -> 3.2 OS update that triggered it.  I just updated firmware (3x in a row!) to 4.x and that warning is gone.

**Comment by elprl** [comment]
I'm seeing the issue on Android 3.1. It seemed to cause display issues also (I'll see if I could dig out a screenshot). Do you know of any workarounds?

**Comment by larham** [comment]
Have you considered adding icons with the names given? IF you are lucky, it won't use them, just be satisfied it can find them.

For me, it caused no issues.  Given that firmware updates both caused and fixed the problem, I'd say it was in the Samsung layer.

**Comment by elprl** [comment]
Cheers for the response. I did try to add the icons to the ABS Library project to no effect, but I haven't tried added them to my main project. I'll also try different themes to see if that was a cause. I agree it sounds like a Samsung specific UI, but I haven't tried it on other 3.1 tablets. My other tablets are on ICS and above.

**Comment by elprl** [comment]
Adding the icons to my main project didn't resolve the exception, but as you say it causes no issue. I had thought it was effecting the display of something in my code, but that turned out to be my own issue.
