### ISSUE TITLE
IllegalStateException in Action Bars/Tabs and Pager example

### ISSUE THREAD

**Issue by eburnette** [JakeWharton/ActionBarSherlock#69]
I was playing around with the Action Bars/Tabs and Pager example, flipping back and forth to different tabs and selecting things and got a Force Close. I can't tell you the exact steps to reproduce it. Here's the log:

09-30 16:48:32.650: INFO/LoaderCustom(2520): Item clicked: 7
09-30 16:48:33.460: INFO/LoaderCustom(2520): Item clicked: 4
09-30 16:48:34.840: INFO/FragmentComplexList(2520): Item clicked: 636
09-30 16:48:35.780: INFO/FragmentComplexList(2520): Item clicked: 1294
09-30 16:48:36.270: INFO/FragmentComplexList(2520): Item clicked: 220
09-30 16:48:36.290: DEBUG/AndroidRuntime(2520): Shutting down VM
09-30 16:48:36.290: WARN/dalvikvm(2520): threadid=1: thread exiting with uncaught exception (group=0x4012d760)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520): FATAL EXCEPTION: main
09-30 16:48:36.300: ERROR/AndroidRuntime(2520): java.lang.IllegalStateException: Content view not yet created
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.app.ListFragment.ensureList(ListFragment.java:328)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.app.ListFragment.setListShown(ListFragment.java:280)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.app.ListFragment.setListShownNoAnimation(ListFragment.java:266)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at com.actionbarsherlock.sample.demos.app.LoaderThrottleSupport$ThrottledLoaderListFragment.onLoadFinished(LoaderThrottleSupport.java:516)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at com.actionbarsherlock.sample.demos.app.LoaderThrottleSupport$ThrottledLoaderListFragment.onLoadFinished(LoaderThrottleSupport.java:1)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:413)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:385)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.content.Loader.deliverResult(Loader.java:88)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:81)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.content.CursorLoader.deliverResult(CursorLoader.java:1)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:224)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:62)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.os.AsyncTask.finish(AsyncTask.java:590)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.os.AsyncTask.access$600(AsyncTask.java:149)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:603)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.os.Looper.loop(Looper.java:132)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at android.app.ActivityThread.main(ActivityThread.java:4123)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at java.lang.reflect.Method.invokeNative(Native Method)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at java.lang.reflect.Method.invoke(Method.java:491)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)
09-30 16:48:36.300: ERROR/AndroidRuntime(2520):     at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
This is not really an error with this framework (nor the compat lib, really) but rather an oversight in whomever made the samples for the current compat lib. I can't even remember the exact operation that causes the problem but what happens is a loader or handler is created to load the list content and if you page too far away before it resolves the `ViewPager` will detach the fragment. Obviously since there's no fragment there's no `ListView` so the `ListFragment` throws an exception when the callback tries to populate the adapter.

If the demo fragment was written properly the loader/handler would be aborted when the fragment was detached. I didn't bother fixing since it's an edge case bug that exists only in the samples and not the library itself.

..and no one had bothered reporting it yet! Thanks for the report regardless, though.

**Comment by eburnette** [comment]
Ok, thanks

-----Original Message-----
