### ISSUE TITLE
Add build.xml to `library` 

### ISSUE THREAD

**Issue by pyricau** [JakeWharton/ActionBarSherlock#690]
When using ActionBarSherlock in a project (without Maven), I usually add a git submodule to my project that points to the ActionBarSherlock Git repo, so that we don't loose track of the exact version of ActionBarSherlock that was used.

When building with Ant (doh...), however, we need the library projects to have a `build.xml` file (and `local.properties`) .

It would be nice if ActionBarSherlock could have this `build.xml` file. We don't want to add this manually, and the only other option is to fork ActionBarSherlock, add the build.xml and let the git submodule point to that fork.

The build.xml should be the standard (almost empty) build.xml that is generated by the Android tools.

`local.properties` should not be on the repo, but maybe a `local.properties.example` for people to edit. I don't really know if that's a good idea though.

Ultimately, one of the goals is to have a CI server be able to download the git repo of a project (and the git repos of its submodules), be able to build, without having to create any extra files first (such as the build.xml)

**Comment by JakeWharton** [comment]
You can run `android update project -p library` to get a configured build for ant. If you are using it as a submodule you can invoke this command from your `build.xml` if one in the `library/` folder is not present. This will not be supported in the repository because I'm not going to maintain a fragile, broken "build system" that I don't use.

Once the new Gradle-based build system matures a bit I will support it, however.

**Comment by pyricau** [comment]
I was wondering why the `build.xml` was in `.gitignore`, now I know :) .

I understand your decision, and I won't try to change your mind, but let me just explain my thoughts:

Running `android update project -p library` from the project `build.xml` will obviously work. However, it puts the effort of writing the extra Ant conf on the user side, for each new project. On the other side, the `build.xml` is merely an empty shell, with no maintenance required (it's an import of the sdk `build.xml`).

Ant is certainly a broken build system, but sadly it's the one maintained by the Android team, and therefore it's widely used. I can't wait for the new Gradle build system :) .

Maybe updating [usage.html](https://github.com/JakeWharton/ActionBarSherlock/blob/master/website/usage.html#L37)  with the extra Ant conf to automatically do the `android update project -p library` would help Ant users without needing any Ant file mess on the ActionBarSherlock repo ?

**Comment by slott** [comment]
I have have had the exact same system - the lack of the basic build.xml for easy integration with ant which is the de facto build tool for Android. For others with the same issue here is a simple build target to help you solve the problem - it is easy to add multiple dependencies as you will see.

```
<target name="update-project">
    <echo>${path}</echo>
    <exec executable="android" failonerror="true">
        <arg value="-s"/>
        <arg value="update"/>
        <arg value="project"/>
        <arg value="-p"/>
        <arg value="${path}"/>
    </exec>
</target>

<target name="update-deps">
    <antcall target="update-project">
        <param name="path" value="../dependencies/ActionBarSherlock/actionbarsherlock"/>
    </antcall>
    <antcall target="update-project">
        <param name="path" value="../dependencies/facebook-sdk/facebook"/>
    </antcall>
    <antcall target="update-project">
        <param name="path" value="../dependencies/SlidingMenu/library"/>
    </antcall>
    <antcall target="update-project">
        <param name="path" value="../dependencies/ViewPagerIndicator/library"/>
    </antcall>
</target>
```
