### ISSUE TITLE
ActionBarSherlock does not fetch Activity's logo from a Theme (API 9 / 10)

### ISSUE THREAD

**Issue by carlospuk** [JakeWharton/ActionBarSherlock#692]
I have different logos for my activities depending upon the current theme, therefore the manifest does not declare the android:logo, instead it is set in the activity's theme.xml:

```
 <style name="Theme.BCBase.WithLogo" parent="Theme.BCBase">
 <item name="android:logo">@drawable/main_icon_and_logo7</item>
</style>
```

   (Theme.BCBase inherits from Theme.Sherlock)

On API 9 / 10 the Logo is never displayed, because the special pull parser you have written in the ActionBarView class only searches the manifest and not the current theme.

Is there any chance of a fix for this?

**Comment by JakeWharton** [comment]
The theme is checked first here: https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/internal/widget/ActionBarView.java#L187

**Comment by JakeWharton** [comment]
You need to also include an attribute without the `android` prefix for pre-ICS.

**Comment by carlospuk** [comment]
Thanks Jake - appreciate the additional clarification about the attributes too
