### ISSUE TITLE
issue action bar draw line in jelly bean

### ISSUE THREAD

**Issue by Yria** [JakeWharton/ActionBarSherlock#697]
action bar draw gradient line at bottom in jelly bean.

how remove this line?

**Comment by SimonVT** [comment]
I don't see how this is a bug.

**Comment by Yria** [comment]
The UX should be same throughout the versions.  Some apps may experience unexpected broken UI Layouts.

**Comment by SimonVT** [comment]
ActionBar behavior/look can and do change between platforms. It's up to you as a developer to ensure your app still works. ABS only serves to provide the ActionBar API to older platforms, which is done by backporting the ICS ActionBar. Any changes in JB and later platforms are not something ABS controls, nor is it likely these changes will make it into ABS.

**Comment by Yria** [comment]
Ok. I understand. thank you.
