### ISSUE TITLE
SearchView not fill_parent width in ActionBar on landscape

### ISSUE THREAD

**Issue by Yria** [JakeWharton/ActionBarSherlock#698]
If my device landscape, SearchView not fill_parent width in ActionBar

and, SearchView in ActionBar not working OnCloseListener. so I think ..

@Override
    public void onActionViewCollapsed() {
        if (mOnCloseListener != null) {         // fix
            mOnCloseListener.onClose();        // fix
        }        // fix
        clearFocus();
        updateViewsVisibility(true);
        mQueryTextView.setImeOptions(mCollapsedImeOptions);
        mExpandedInActionView = false;
    }

is that right?

**Comment by JakeWharton** [comment]
Collapsible action items have a max width that they can occupy (something like 400dp). It will not always fill the entire width of the action bar.

**Comment by StingerAJ** [comment]
Sorry, but I have to disagree. This screenshot is on a Nexus 10 and the width of the searchview is more like 256dp, an estimated fifth of the screen width (2560px and logical density of 2.0px per dp):

![device-2014-01-08-172430](https://f.cloud.github.com/assets/335391/1870026/cb6ac34a-7881-11e3-8f61-96bd966703bc.png)

**Comment by JakeWharton** [comment]
OK then maybe it's 256dp max width. Check the code, it should be defined in a dimension probably.

**Comment by ghost** [comment]
@JakeWharton - sir cant this size be changed ? through xml or anything like that?

**Comment by StingerAJ** [comment]
According to this line, there should be possibility to set the maxWidth in XML or in code:

https://github.com/JakeWharton/ActionBarSherlock/blob/master/actionbarsherlock%2Fsrc%2Fcom%2Factionbarsherlock%2Fwidget%2FSearchView.java#L301

I think I used setMaxWidth in code and set it to 4000 to accomplish something like fill_parent.
