### ISSUE TITLE
Update support library to rev 11

### ISSUE THREAD

**Issue by hameno** [JakeWharton/ActionBarSherlock#699]
An upgrade to the latest support lib would be really great, as it now supports fragmentception (fragments inside fragments) which is a really useful feature...

**Comment by JakeWharton** [comment]
When it's available in Maven central I will update. If you need this update a fork or your local copy manually.

**Comment by Prototik** [comment]
@JakeWharton What's stopping you create an artifact support-library in your groupId and hand deploy there newer versions? Yes, not quite right, but the gap to five releases - it is too.

**Comment by JakeWharton** [comment]
Because then everyone who is depending on `com.google.android:support-v4` transitively through two libraries (this and another) will get dex errors since all the classes will be added twice.

**Comment by serj-lotutovici** [comment]
by the way... who knows why google is not adding these libs to the maven central? it's quite strange realty...  I already had a  few problems with google analytics when moving all projects to our CI server...

**Comment by JakeWharton** [comment]
Google is pushing artifacts starting with API 17.

**Comment by schildbach** [comment]
@JakeWharton Where does Google push to exactly? API 17 is out for several days now, still no sign pushed artifacts. And who is Google?

**Comment by imminent** [comment]
@Goonie I've used http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.android%22 for 4.1, my guess is someone(s) on the Android team have said somewhere/to Jake that they will make sure to push the artifacts. My guess is they will show up there, when that happens.

**Comment by JakeWharton** [comment]
I'll do this as soon as it's available. I'm eager for this as much as the next person. Closing the issue for now.

**Comment by hameno** [comment]
I figured out how to do this without forking or modifying external libraries:
just add the following dependency declarations to your pom and use the maven android sdk deployer to deploy the compatibility-v4

```
        <dependency>
            <groupId>android.support</groupId>
            <artifactId>compatibility-v4</artifactId>
            <version>11</version>
        </dependency>
        <dependency>
            <groupId>com.google.android</groupId>
            <artifactId>support-v4</artifactId>
            <version>r7</version>
            <scope>provided</scope>
        </dependency>
```

It will work just fine and you can use the new APIs from rev 11

**Comment by JakeWharton** [comment]
It's more clear in my opinion to add an `<exclude>` for the support library on the `<dependency>`  for ABS and then have the separate `<dependency>` for the newer revision.

**Comment by hameno** [comment]
What? I think your post is missing some words... :)

**Comment by JakeWharton** [comment]
Haha. The GitHub app doesn't escape entities. 1sec, will fix on the site.

**Comment by hameno** [comment]
Yes, this would be cleaner but unfortunately IntelliJ seems to have an issue with exclusions for apklibs (atleast version 12.0.1), where it won't find the classes inside the apklibs, so for me (and I think many other) this is probably the easiest solution - at least until maven central repo is updated...

**Comment by JakeWharton** [comment]
Good point. We deploy the support library to our local repo with the same groupId and artifactId but with a newer version and IntelliJ seems to handle that properly. Is there a bug filed with JetBrains? They're usually pretty good about fixing things like that.

**Comment by hameno** [comment]
I'm not sure, I did a quick search but didn't find anything in their tracker. But since it's 3:00 AM here in Berlin, Germany I'm going to bed now :) 
Maybe if I have some time in the coming days I will submit an issue...

**Comment by schildbach** [comment]
I wonder if all of you have version 11 bundled themselves (under whatever groupId), why doesn't anyone push this to Maven Central? This would solve the problem for all of us.

**Comment by JakeWharton** [comment]
Because deploying to Maven central is a lot more complicated than uploading a .jar into your local repo or your own Nexus.

**Comment by imminent** [comment]
I made an issue for this: http://youtrack.jetbrains.com/issue/IDEA-98114

**Comment by mingfai** [comment]
Perhaps we need more people to vote for putting the support library to Maven central
https://code.google.com/p/android/issues/detail?id=54697

**Comment by JakeWharton** [comment]
I bug Xav about it all the time :)

**Comment by schildbach** [comment]
The tricky part is not preparing and pushing the support library, but the android sdk dependency. Is Xav aware of that? If someone confident in building the sdk (and c in general) helps, we can manage that. I failed because I just don't know what went wrong - don't know anything about all these C warnings and errors.
