### ISSUE TITLE
wrong direction of up arrow in android 4.2 when using rtl locale

### ISSUE THREAD

**Issue by moallemi** [JakeWharton/ActionBarSherlock#705]
android 4.1 has support for number of RTL languages e.g. persian:

![android 4.1](http://i45.tinypic.com/x0s7kw.png)

in android 4.2 RTL when switching to RTl language the back button in actionbar and logo goes to right and the direction of back button changes:

![android 4.2](http://i46.tinypic.com/dx0lyx.png)

but in ABS this does not happens. whats the problem?! is it a bug? or we have to set something in code?

![abs in android 4.2](http://i46.tinypic.com/2mpze60.png)

**Comment by imminent** [comment]
Are you saying that the action bar didn't flip for you but the up icon did?
The action bar worked for me. They use the native action bar when it
exists, so it should worked. I tested on nexus 7. Did you add the manifest
flag and set your min SDK correctly?

**Comment by JakeWharton** [comment]
ABS doesn't really do anything on Android 4.0 or newer. Are you sure you configured this correctly?

**Comment by moallemi** [comment]
@imminent  @JakeWharton Thank you for your tip. I forgot to add the 

```
android:supportsRtl
```

in the manifest file. now this is the result:

![fixed rtl support ](http://i46.tinypic.com/zjcc34.png)

**Comment by motameni** [comment]
Siavash name should appear every where :+1:
