### ISSUE TITLE
Adding a Search Image View in the Action Bar

### ISSUE THREAD

**Issue by rsvijay** [JakeWharton/ActionBarSherlock#708]
Guys, first of all, this is not an issue with the ActionBarSherlock library. I need a workaround for this. Someone please help us.

I am using ActionBarSherlock library in my app. I got a strange issue. Let me explain it clearly.

I want to put a Search Image in the right end of the Action bar in my Android app.

For this, I added a Search menu item to the Action bar. It appears, as expected, in the right end of the Action bar in the Android Tablets but not in the Phones.

In Android phones, the Search menu appears in a panel beneath the Action bar even i put showAsAction="always". I don't want this appearance. I want this Search Image in the Action bar itself and not in a panel beneath the Action bar.

So I wrote a small piece of code to achieve this.

```
LinearLayout searchView = (LinearLayout) getLayoutInflater().inflate(R.layout.actionview_search, null);

searchView.setLayoutParams(new LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT, 1f));

searchView.findViewById(R.id.img_search).setOnClickListener(new OnClickListener() {

@Override
public void onClick(View view) {
    onSearchRequested();
}

});

View view = new View(context);
tab.setCustomView(view);

LinearLayout tabContainer = (LinearLayout) view.getParent().getParent();
tabContainer.addView(searchView);

tab.setCustomView(null);
```

where tab is an object of ActionBar.Tab class.

This code works as expected in many phones(Neo L with ICS, Neo V with ICS, Galaxy S with GingerBread, even on Froyo) expect Galaxy S with ICS, Galaxy S3 with ICS.

It ended with the following exception

ClassCasting Exception at ScrollingTabContainerView$TabView.onMeasure(int,int)

Am i did anything wrong? Why the code fails for only certain devices and worked in other devices? Is there any alternate solution to make the Search Image appear in the right corner of Action bar? Please help me out in this issue.

**Comment by iNoles** [comment]
It looks like in some cases getParent () that wouldn't be LinearLayout. You could check to see that function is really from Linearlayout

**Comment by rsvijay** [comment]
Thanks for replying me, Jonathan. The above code is a function within MyActivity class.

I am sure that the exception is not thrown at line "LinearLayout tabContainer = (LinearLayout) view.getParent().getParent();" because i surrounded the whole block with try {} catch (Exception e) {}. It was never caught atleast once.

I am thinking that adding a LinearLayout object to the Action bar has resulted the issue. Because the Actionbar may be designed to contain only TabView(subclass of LinearLayout class) objects.

Further the code works fine in many Android mobiles(Sony with ICS, Gingerbread, Samsung with Gingerbread, Froyo, Jellybean) except Galaxy S, Galaxy S3(may be a lot of mobiles like this). I can't figure out why so...
