### ISSUE TITLE
Issue with Settings Application in Android Honeycomb

### ISSUE THREAD

**Issue by amithrai13** [JakeWharton/ActionBarSherlock#71]
Here are the details of the issue that I'm facing.

Issue: Cannot display APN list when switch from landscape to portrait mode.

These are the steps that leads to the problem.

Boot Android device with SIM card inserted
Wait until device connect to 3G network
Verify APN list in landscape mode
Switch to portrait mode.

Upon switch the APN list vanishes, and if switched back from Portrait to Landscape, the APN list appears back. Here is the log details that I captured..

I/ActivityManager( 2624): Config changed: {1.0 0mcc0mnc en_US sw768dp w1366dp h720dp xlrg long land -touch qwerty/v/v -nav/h s.5}

W/LoaderManager( 3271): Called doRetain when not started: LoaderManager{a06acfa0 in ApnSettings{a06af630}}

W/LoaderManager( 3271): java.lang.RuntimeException: here

W/LoaderManager( 3271):     at android.app.LoaderManagerImpl.doRetain(LoaderManager.java:733)

W/LoaderManager( 3271):     at android.app.Activity.performStop(Activity.java:4515)

W/LoaderManager( 3271):     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:2909)

W/LoaderManager( 3271):     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:2968)

W/LoaderManager( 3271):     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3165)

W/LoaderManager( 3271):     at android.app.ActivityThread.access$600(ActivityThread.java:122)

W/LoaderManager( 3271):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1028)

W/LoaderManager( 3271):     at android.os.Handler.dispatchMessage(Handler.java:99)

W/LoaderManager( 3271):     at android.os.Looper.loop(Looper.java:132)

W/LoaderManager( 3271):     at android.app.ActivityThread.main(ActivityThread.java:4123)

W/LoaderManager( 3271):     at java.lang.reflect.Method.invokeNative(Native Method)

W/LoaderManager( 3271):     at java.lang.reflect.Method.invoke(Method.java:491)

W/LoaderManager( 3271):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:841)

W/LoaderManager( 3271):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:599)

W/LoaderManager( 3271):     at dalvik.system.NativeStart.main(Native Method)

**Comment by amithrai13** [comment]
There was one previous issue, which was related to this doRetain in LoaderManager.java which you looked into, can you please have a look and let me direct.

**Comment by JakeWharton** [comment]
This issue is related to the built-in classes of the Android operating system that your tablet is running and not this library. I suggest that you contact your manufacturer's support and raise this issue with them.
