### ISSUE TITLE
Actionbar icon padding/size

### ISSUE THREAD

**Issue by velvetk** [JakeWharton/ActionBarSherlock#711]
I am using ActionbarSherlock 4.2 and having an issue with the size of the icon. I would like to have the search icon as tall as the action bar and without any padding. I use this option for Widget.Sherlock.ActionButton style

``` xml
<style name="MyActionButton" parent="Widget.Sherlock.ActionButton">
    <item name="android:maxWidth">48dip</item>
</style>
```

This works for Android 4.1.x Jelly Bean, but it does NOT seem to work on verison 4.0.4 and lower. Here is the screenshot:

![](http://s16.postimage.org/c6gog0kkl/actionbar_icon.png)

What other options do I need to set. Thank you for your help.

**Comment by JakeWharton** [comment]
How are you referencing your new style? Did you duplicate the attribute in the theme with and without the `android:` prefix?

**Comment by velvetk** [comment]
Hi Jake,

Here is how I reference it:

``` xml
<item name="android:actionButtonStyle">@style/MyActionButtonStyle</item>
<item name="actionButtonStyle">@style/MyActionButtonStyle</item>

<style name="MyActionButtonStyle" parent="Widget.Sherlock.ActionButton">
         <item name="android:maxWidth">48dip</item>
<style>
```

Thanks for your response. Happy Thanksgiving.

**Comment by niftynei** [comment]
In my tests, this isn't related to ActionBarSherlock -- the issues is that the onMeasure logic for ActionBarMenuItems has changed from 4.0.x to 4.1.x.  

Adding a height attribute to your ActionBar style seems to fix it for 4.0.x:  

```
<style name="MyActionBar"  parent="whoever">
<item name="android:height">56dp</item>
<item name="height">56dp</item>
</style>
```

**Comment by SimonVT** [comment]
Since you say this happens with the native action bar on ICS, I can only assume it's the expected behavior. Will re-open if you have a test case that shows this doesn't happen without ABS.

**Comment by magicgoose** [comment]
Same problem. All attempts to change size/padding of action buttons gave nothing, on android 2.3 there is padding around buttons.

**Comment by Rahulrsannidhi** [comment]
i am using Default Action Bar instead of Sherlock Action Bar also using the custom theme also how to increase the size of action bar and size of the icons.
