### ISSUE TITLE
Add ability to force overflow for 2.2-2.3 devices.

### ISSUE THREAD

**Issue by lexer** [JakeWharton/ActionBarSherlock#715]
It is possible to hack ICS devices to show overflow even on devices with hardware button like Galaxy S3.

try {
        ViewConfiguration config = ViewConfiguration.get(this);
        Field menuKeyField = ViewConfiguration.class.getDeclaredField("sHasPermanentMenuKey");
        if(menuKeyField != null) {
            menuKeyField.setAccessible(true);
            menuKeyField.setBoolean(config, false);
        }
    } catch (Exception ex) {
        // Ignore
    }

But this hack doesn't work for ABS since force overflow support was removed.

I think many people faced that problem (http://stackoverflow.com/questions/9286822/how-to-force-use-of-overflow-menu-on-devices-with-menu-button). Since designers doesn't like that inconsistency and prefer to show overflow button even if hardware button exists.

**Comment by JakeWharton** [comment]
The goal of this library is to backport the action bar to create consistent behavior across all APIs. Since this functionality is counter to the native action bar it will not be added.
