### ISSUE TITLE
Custom Action View...

### ISSUE THREAD

**Issue by nishal** [JakeWharton/ActionBarSherlock#716]
How to create a custom action view that is clickable like a standard Action item?

**Comment by JakeWharton** [comment]
If you have questions please use StackOverflow or the mailing list.

**Comment by JakeWharton** [comment]
Also, this is really an action bar question not an ActionBarSherlock question.

**Comment by nishal** [comment]
Sorry about posting it in here.

I found the ActionProviders.java demo which is loading my layout correctly for me, but the layout file doesn't have a button, so the entire view is not clickable. Was wondering how I could make it clickable retaining the proper ActionBarSherlock theming.

If thats not possible, I might have to add an empty button behind the custom layout to make it clickable.

**Comment by jjara22** [comment]
??

Date: Mon, 26 Nov 2012 12:17:19 -0800
