### ISSUE TITLE
Lint checks fails with 239 errors and many warnings

### ISSUE THREAD

**Issue by danielesegato** [JakeWharton/ActionBarSherlock#719]
On version 4.2.0 running Android Lint checks gives 13 errors and many warning.

Errors are in 3 categories:
- Attribute is missing the Android namespace prefix [2]

abs__search_dropdown_dark.xml
abs__search_dropdown_light.xml

 color="#A00080FF" with no android: namespace

this should be easy to fix
- <feature> requires API level X (current min is 7) [232]

there are a lot of error here!
- The required layout_width and layout_height attributes are missing [5]

happen in many layouts

Every Lint error should  be fixed.
Every Lint warning (they are a lot too) should be checked carefully and, only if really inoffensive, suppressed with a comment on your check so that if you change that part later you know about the suppress.

**Comment by SimonVT** [comment]
> color="#A00080FF" with no android: namespace

Looks like an oversight, open an issue if we forget.

> requires API level X (current min is 7) [232]

Waste of time to "fix" these, and imo it just adds extra complexity. Especially in a library like ABS. In some cases it's not even possible. Keeping the source as close to aosp as possible has its benefits as well.

> The required layout_width and layout_height attributes are missing [5]

Most likely not needed in the way they're used. If it causes issues at runtime, open an issue.

> Every Lint error should be fixed.

Failing a lint check isn't an error. You can probably set it up to fail your build, but it isn't really an error. Lint is there in case you forget about recommendations and best practices, but ultimately you as a developer have to decide whether it makes sense to follow it.

**Comment by danielesegato** [comment]
I know a lint check isn't an error.
I'm just saying that it should be suppressed when it is not.

But I understand adding suppress may cause issues in merging from upstream.

Even if I think it could be a minor issue if you suppress in "new lines", git will threat it as a new hunk and more easily merge.
It may cause issue in merging in a very few cases and all of them should be very easy to fix

**Comment by SimonVT** [comment]
Suppressing a lint check is worse than ignoring it. If you want to pay attention to them, you should handle it appropriately. But if you just want to suppress them, add a lint.XML that does just that.

**Comment by danielesegato** [comment]
I disagree.

If your suppress without checking It IS bad. 
But if you check and you know it is a false alarm you can safely suppress. 

The conditions being:
- you suppress in the smaller section of code possible 
- you comment above explaining why it is safe to suppress
- you go and also comment in the section of code that may invalidate your suppress (if applicable) 

That's important for lint errors, less important for warnings. 

Example: that method or layout is only used in API level X or greater: it is safe to suppress an error and it is correct to do so because you intended to write that method / layout targeting that API level. 

A conflict where you wrote the suppress comment may actually help catch an issue that would be introduced by merging.

**Comment by SimonVT** [comment]
I don't see how this adds any value.

ABS will by definition fail api level checks, so it's something that's paid
very close attention to during development, and not really an issue.

Other failed lint checks can be caused by buggy framework code, and the
general consensus here is that we leave them in, unless they can be worked
around in the native implementation.

Generally abs issues wouldn't be any easier to solve if failed lint checks
were handled. There's a lot you have to pay attention to when backporting
APIs, none of which lint can help with.
Implementing this isn't just a one-time deal. It has to be maintained. When
it adds no value to the people who maintain the library, it shouldn't be
added.

**Comment by danielesegato** [comment]
Ok then, I'll not insist anymore :)
Thank you for your replies on the topic.
