### ISSUE TITLE
Crash when trying to create option menu item with ActionView in the Fragment for Android 2.3.3 and below

### ISSUE THREAD

**Issue by johnkil** [JakeWharton/ActionBarSherlock#721]
11-28 15:50:17.443: E/AndroidRuntime(3658): java.lang.NullPointerException
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.view.View.dispatchRestoreInstanceState(View.java:6290)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:1211)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.view.View.restoreHierarchyState(View.java:6274)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at com.actionbarsherlock.internal.view.menu.MenuBuilder.restoreActionViewStates(MenuBuilder.java:361)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.preparePanel(ActionBarSherlockCompat.java:503)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.dispatchInvalidateOptionsMenu(ActionBarSherlockCompat.java:272)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at com.actionbarsherlock.app.SherlockFragmentActivity.invalidateOptionsMenu(SherlockFragmentActivity.java:150)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at com.actionbarsherlock.app.SherlockFragmentActivity.supportInvalidateOptionsMenu(SherlockFragmentActivity.java:156)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1095)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:635)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1431)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:420)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.os.Handler.handleCallback(Handler.java:587)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.os.Handler.dispatchMessage(Handler.java:92)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.os.Looper.loop(Looper.java:130)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at android.app.ActivityThread.main(ActivityThread.java:3835)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at java.lang.reflect.Method.invokeNative(Native Method)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at java.lang.reflect.Method.invoke(Method.java:507)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
11-28 15:50:17.443: E/AndroidRuntime(3658):     at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Already fixed on `dev`
