### ISSUE TITLE
Action Bar can't be removed on Google TV

### ISSUE THREAD

**Issue by mttkay** [JakeWharton/ActionBarSherlock#722]
I am using a custom activity theme which is being applied on all devices classified as large. In this style, I remove the Action Bar:

```
<item name="android:windowNoTitle">true</item>
<item name="android:windowActionBar">false</item>
<item name="windowActionBar">false</item>
```

This works on my ICS tablet, but not on my Google TV (Revue, Honeycomb MR2). The Action Bar still shows up. I could only get rid of it using a hack, where I set the title maxLines to 0, but this will still show the blue line under the bar.

**Comment by mttkay** [comment]
Calling `hide()` on the `ActionBar` instance does the trick. However, according to the documentation, there shouldn't even be an AB reference when windowActionBar is false.

**Comment by JakeWharton** [comment]
Does this manifest itself on the emulator? If so I'll actually be able to test.

**Comment by mttkay** [comment]
Hi Jake,

I figured out the issue was that I didn't mirror the windowNoTitle attribute. I thought you only have to mirror those specific to the Honeycomb and newer API levels.

My bad.
