### ISSUE TITLE
NoClassDefFoundError in setHasOptionsMenu(true)

### ISSUE THREAD

**Issue by felipelalli** [JakeWharton/ActionBarSherlock#726]
http://stackoverflow.com/questions/13672957/actionbarsherlock-bizarre-noclassdeffounderror-on-sethasoptionsmenu

**Comment by JakeWharton** [comment]
This looks like a bad tools problem, not an ABS problem. I bet if you deploy from the command line or 'export' the application every time you wouldn't see this.

**Comment by felipelalli** [comment]
Really? I'll make more tests and tell you again.
