### ISSUE TITLE
Jar mismatch! Fix your dependencies

### ISSUE THREAD

**Issue by trysathish** [JakeWharton/ActionBarSherlock#727]
Hi, I am doing project related ActionBar in Android SDK. My minimum SDK is 2.0. I got Jar mismatch! Fix your dependencies error when I add ActionBarSherlock library. How to solve this problem?

I am using Eclipse to develop android projects.

**Comment by JakeWharton** [comment]
You are using two different revisions of the support library. Delete all of the support library jars and re-copy them into your app, ActionBarSherlock, and any other dependencies.
