### ISSUE TITLE
SearchView restores with empty text

### ISSUE THREAD

**Issue by stschwark** [JakeWharton/ActionBarSherlock#730]
[SearchView](https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/widget/SearchView.java) looses its text after the options menu is invalidated. In my case this happens as part of a fragment transaction.

This is because SearchView sets the text to blank in onActionViewExpanded(). Moving mQueryTextView.setText(""); to onActionViewCollapsed() has solved the problem for me.

**Comment by JakeWharton** [comment]
I cannot change `SearchView` behavior unless an associated change is accepted into AOSP for `android.view.SearchView`. Once that is done I will modify its behavior (and we can re-open this issue).
