### ISSUE TITLE
[Feature Request] setTypeface (Roboto font) only on ABS!

### ISSUE THREAD

**Issue by observ33r** [JakeWharton/ActionBarSherlock#731]
It's very annoying when we have completly app with roboto font on GB/Froyo and we can't easy set typeface on abs title, subtitle and menu item without dirty hacks...

This future only request for ABS, no need on native actionbar!

**Comment by JakeWharton** [comment]
Assets can't be bundled in library projects so I couldn't do this even if I wanted to. Plus I don't think most would appreciate the extra 161K (pre-dex).

**Comment by atermenji** [comment]
Assets can be bundled in library project with some kind of hack (http://stackoverflow.com/questions/7610355/font-in-android-library). 
The other thing if this is really needed.

**Comment by observ33r** [comment]
No need to add any font to abs library, just add the setTypeface(Typeface tf) to getSherlock() which will then apply to all textviews in abs...

**Comment by SimonVT** [comment]
Handle it yourself, e.g. by overriding Activity#onCreateView and checking for TextViews.

**Comment by observ33r** [comment]
Thanks Simon! Amazing tip! Work like charm! :+1:

**Comment by observ33r** [comment]
god damn... too much beautiful to work :(

```
@Override
public View onCreateView(String name, Context context, AttributeSet attrs) {
    if ("TextView".equals(name)) {
        TextView text = new TextView(context, attrs);
        text.setBackgroundColor(Color.RED);
        Typeface tf = Typeface.createFromAsset(getAssets(),"fonts/roboto_regular.ttf");
        text.setTypeface(tf);
        return text;
    } else if ("com.actionbarsherlock.internal.widget.CapitalizingButton".equals(name)) {
        CapitalizingButton text = new CapitalizingButton(context, attrs);
        Typeface tf = Typeface.createFromAsset(getAssets(),"fonts/roboto_regular.ttf");
        text.setTypeface(tf);
        return text;
    } else
        return super.onCreateView(name, context, attrs);
}
```

CapitalizingButton is ok, but with TextView not work at all... background is red, but typeface is not correct!

Any suggestions?
