### ISSUE TITLE
Action Bar Sherlock(Action Mode)

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#735]
can i use  " MultiChoiceModeListener  " in listview with Action Bar Sherlock  for Android 2.0 to upper?

**Comment by JakeWharton** [comment]
No. You have to handle that case yourself. This might help https://snipt.net/tweakt/sherlocklistviewjava/ for now. Not sure if that will ever make it into the library, however.

**Comment by yccheok** [comment]
Dear JakeWahrton, just wondering, do you wrote https://snipt.net/tweakt/sherlocklistviewjava/ ? Is there any reason why it is not being accepted into your great actionbarsherlock?

**Comment by StingerAJ** [comment]
Does that mean there is no support for CHOICE_MODE_MULTIPLE or CHOICE_MODE_MULTIPLE_MODAL in ABS, neither for ListView nor for GridView?

Or is it only not available on all API levels below API level 11 (Honeycomb)?
