### ISSUE TITLE
Application starts too long on Android 4.x with Sherlock  

### ISSUE THREAD

**Issue by abredykhin** [JakeWharton/ActionBarSherlock#737]
We have recently discovered that if user launches our app on Android 4.x there is a visible delay between the actual app start time and when all the UI shows up. So user first sees a black screen with app title for about a second, and only then everything else is shown

After a bit of profiling and debugging it seems that it takes Sherlock library too long to perform initialization. Moreover, in my tests the most CPU/time consuming method was the ActionBarSherlockNative::setContentView(int layoutResId). I've no idea why is that may be happening, considering the fact that it just redirects the call into Android platform code

So that there are any proves on this - try to launch the Forsquare app which also relies on Sherlock lib, and you will see the very same problem I'm describing. In their case it's white background and blue title bar. 

So, have anybody seen this before and are there any suggestions on how to improve startup time? Any help would be very much appreciated

Thanks,

**Comment by apkelly** [comment]
I'm seeing the same problem too, I thought it might have been my code, but this gives me hope that it maybe related to the library...however I haven't seen it happen with the ABS Demos or Fragments applications.

**Comment by JakeWharton** [comment]
ABS does almost nothing on Android 4.0+ so it's hard to imagine the library affecting anything.

**Comment by apkelly** [comment]
@abredykhin Do you have a custom Application class in your app? I do and in there I create my image cache for downloads etc, I wonder if creating the disk part of the cache is causing the delay in startup.

**Comment by SimonVT** [comment]
The ui isn't going to show until onCreate/onResume/etc returns, and your ui has been drawn. Doing less work in the life cycle methods and reducing the complexity of your layout is going to speed this up. I find it hard to believe that ABS is slowing this down significantly, especially on 4.0+.
And yes, doing work in your Applications onCreate is also going to slow this down, tho just on first launch.
