### ISSUE TITLE
First Tab padding

### ISSUE THREAD

**Issue by karabox** [JakeWharton/ActionBarSherlock#739]
When using the TAB navigation in the first tab has extra padding on the left. Clearly visible in the blue line under the active tab. Is this a bug or am I wrong?

![Screenshot_2012-12-12-22-29-49](https://f.cloud.github.com/assets/1209583/8879/224bb448-448b-11e2-9715-f79c8190b488.png)

**Comment by SimonVT** [comment]
Is this the native actionbar? We have no control of that.

**Comment by karabox** [comment]
Yep =(

Android 4.2.1 

+

package="com.actionbarsherlock"
android:versionCode="100"
android:versionName="4.2.0"

+

android-support-v13.jar 350 075  bytes

**Comment by SimonVT** [comment]
You'll have to blame Google then.

**Comment by karabox** [comment]
http://stackoverflow.com/questions/11992173/android-actionbar-padding-left-of-first-tab

a similar problem ?

**Comment by karabox** [comment]
tried to use the latest android-support-v13.jar  402,581 bytes the bug remains =(

**Comment by karabox** [comment]
I did some tests, it is a bug to Google Framework

pardon me =)

Android 2.3.3  + SAB

![a2 3 3](https://f.cloud.github.com/assets/1209583/10040/e9da5546-44e5-11e2-8c51-ff7bb84fb955.png)

is normal
