### ISSUE TITLE
android.view.InflateException: Binary XML file line #33: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView

### ISSUE THREAD

**Issue by iNoles** [JakeWharton/ActionBarSherlock#74]
10-04 23:30:41.391: E/AndroidRuntime(267): Uncaught handler: thread main exiting due to uncaught exception
10-04 23:30:41.422: E/AndroidRuntime(267): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.itnoles.nolesfootball/com.itnoles.nolesfootball.ui.MainActivity}: android.view.InflateException: Binary XML file line #33: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.ActivityThread.access$2200(ActivityThread.java:119)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.os.Handler.dispatchMessage(Handler.java:99)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.os.Looper.loop(Looper.java:123)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.ActivityThread.main(ActivityThread.java:4363)
10-04 23:30:41.422: E/AndroidRuntime(267):  at java.lang.reflect.Method.invokeNative(Native Method)
10-04 23:30:41.422: E/AndroidRuntime(267):  at java.lang.reflect.Method.invoke(Method.java:521)
10-04 23:30:41.422: E/AndroidRuntime(267):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
10-04 23:30:41.422: E/AndroidRuntime(267):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
10-04 23:30:41.422: E/AndroidRuntime(267):  at dalvik.system.NativeStart.main(Native Method)
10-04 23:30:41.422: E/AndroidRuntime(267): Caused by: android.view.InflateException: Binary XML file line #33: Error inflating class com.actionbarsherlock.internal.widget.ActionBarView
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.createView(LayoutInflater.java:513)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:565)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:618)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:621)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.inflate(LayoutInflater.java:407)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
10-04 23:30:41.422: E/AndroidRuntime(267):  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:198)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.Activity.setContentView(Activity.java:1622)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.support.v4.app.FragmentActivity.ensureSupportActionBarAttached(FragmentActivity.java:227)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.support.v4.app.FragmentActivity.setContentView(FragmentActivity.java:298)
10-04 23:30:41.422: E/AndroidRuntime(267):  at com.itnoles.nolesfootball.ui.MainActivity.onCreate(MainActivity.java:40)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
10-04 23:30:41.422: E/AndroidRuntime(267):  ... 11 more
10-04 23:30:41.422: E/AndroidRuntime(267): Caused by: java.lang.reflect.InvocationTargetException
10-04 23:30:41.422: E/AndroidRuntime(267):  at com.actionbarsherlock.internal.widget.ActionBarView.<init>(ActionBarView.java:100)
10-04 23:30:41.422: E/AndroidRuntime(267):  at java.lang.reflect.Constructor.constructNative(Native Method)
10-04 23:30:41.422: E/AndroidRuntime(267):  at java.lang.reflect.Constructor.newInstance(Constructor.java:446)
10-04 23:30:41.422: E/AndroidRuntime(267):  at android.view.LayoutInflater.createView(LayoutInflater.java:500)
10-04 23:30:41.422: E/AndroidRuntime(267):  ... 24 more
10-04 23:30:41.422: E/AndroidRuntime(267): Caused by: java.lang.NullPointerException
10-04 23:30:41.422: E/AndroidRuntime(267):  at com.actionbarsherlock.internal.widget.ActionBarView.<init>(ActionBarView.java:132)
10-04 23:30:41.422: E/AndroidRuntime(267):  ... 28 more

I am testing it on Android API level 7 and is using Theme.Sherlock.
When I did researched on this, it telling me that (TextView)findViewById(R.id.abs__action_bar_title); is NULL

**Comment by iNoles** [comment]
SDK Revision 13 = OK
SDK Revision 14 = Problem like this one.

**Comment by JakeWharton** [comment]
Haven't had a change to play with r14 yet but you're not the first to report issues with it. I'll try to experiment with it this weekend if I get a chance.

**Comment by appamatto** [comment]
I'm running into the same problem. I printed out the view hierarchy with ids, and the id we're looking for is indeed present in the hierarchy. For some reason findViewById is unable to find it--does it need to be called in an onFinishInflate method?

**Comment by appamatto** [comment]
I'm not on r14 by the way. Surprisingly, I think this coincided with a long overdue upgrade from r12 to r13.

**Comment by appamatto** [comment]
User error--apparently the way my build system wasn't handling abs resources correctly. The id was slightly different and I think this means findViewById's null was correct after all.

**Comment by JakeWharton** [comment]
I've updated the repo for ADT 14 and instructions for updating implementing projects is [here](https://github.com/JakeWharton/ActionBarSherlock/issues/79#issuecomment-2464701). Let me know if this hasn't been resolved.
