### ISSUE TITLE
SearchView text is incorrectly colored with theme Theme.Sherlock.Light.DarkActionBar

### ISSUE THREAD

**Issue by sevar83** [JakeWharton/ActionBarSherlock#744]
Using Theme.Sherlock.Light.DarkActionBar the SearchView text is black (it should be white or some lighter color). Also the magnifying glass icon is somewhat smaller than the default Holo Dark theme.

Tested on ABS 4.1
ICS 4.0.3 and JellyBean 4.1

P.S. And also the Context ActionBar "Done" button text is gray instead of white and very small sized font. Tested on Galaxy Tab 2 with ICS 4.0.3

**Comment by SimonVT** [comment]
Are you using ActionBar#getThemedContext() when inflating the searchview?

We have no control of the "Done" button on ICS+, it's a framework bug.

**Comment by sevar83** [comment]
Hi Simon, 10x for the reply! I create the searchview like one of the samples...

```
            @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater)
    {
        inflater.inflate(R.menu.activity_project_list, menu);

        // Place an action bar item for searching.
        MenuItem itemSearch = menu.findItem(R.id.action_search);
        View searchView = SearchViewCompat.newSearchView(getActivity());
        if (searchView != null)
        {
            SearchViewCompat.setOnQueryTextListener(searchView, new OnQueryTextListenerCompat()
            {
                @Override
                public boolean onQueryTextChange(String newText)
                {
                    // Called when the action bar search text has changed. Since this
                    // is a simple array adapter, we can just have it do the filtering.
                    mCurFilter = !TextUtils.isEmpty(newText) ? newText : null;
                    getListAdapter().getFilter().filter(mCurFilter);
                    return true;
                }
            });
            itemSearch.setActionView(searchView);
        }
    }
```

**Comment by SimonVT** [comment]
Yeah, you have to pass it the themed context.

**Comment by sevar83** [comment]
Cool, 10x very much, bro! It looks as it should now!

I made it in this way:

ProjectListActivity activity = (ProjectListActivity) getActivity();
View searchView = SearchViewCompat.newSearchView(activity.getSupportActionBar().getThemedContext());

If the devs are reading this... I suggest them to make this change in LoaderCustomSupport sample of ABS Demos accordingly.

**Comment by JakeWharton** [comment]
Fixed on `dev`.
