### ISSUE TITLE
homeAsUp Not Enabling Home Action Item

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#746]
This behavior changed in API 16 but we can fix it for all API levels easily. Read the attribute on 14+ and manually call the API. On pre-14 just "fix the glitch".

**Comment by SimonVT** [comment]
What changed exactly?

**Comment by JakeWharton** [comment]
When setting homeAsUp in the theme's displayOptions the home action item was NOT enabled on pre-16. Starting with API 16 they now correctly enable the item when set in the theme.

We should be able to correct this behavior ourselves.
