### ISSUE TITLE
menu.performIdentifierAction() opens and closes the menu

### ISSUE THREAD

**Issue by chomi3** [JakeWharton/ActionBarSherlock#751]
I'm trying to open / close the PopupMenu with hardware button (I've forced the overflow like submenu to be in all android versions under the R.id.menu_0). Basically I want the hardware menu button to always open / close this menu. 

Here's what I came up with:

@Override
public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode ==  KeyEvent.KEYCODE_MENU &&  
                event.getAction() == KeyEvent.ACTION_DOWN) {
            mMenuReference.performIdentifierAction(R.id.menu_0, 1);  
            return true;
        }  
        return super.onKeyDown(keyCode, event);
}

It works fine, but when I hold the button for too long, on the ACTION_UP event , the MenuPopupHelper method is called:

 public boolean onKey(View v, int keyCode, KeyEvent event) {
      if (event.getAction() == KeyEvent.ACTION_UP && keyCode == KeyEvent.KEYCODE_MENU){
            dismiss();  
            return true;
        }
        return false;
    }

which closes the popupmenu.

I'm able to make a dirty fix to check the status of opened menu through context, but it only works only on pre ICS devices, as I have no access to edit methods that closes the popupmenu in real Action Bar.

is there any way to prevent closing the popupmenu (or edit action bar methods) ?

**Comment by SimonVT** [comment]
Doesn't sound like an ABS issue.. Try stackoverflow or one of the mailing lists

**Comment by sherpya** [comment]
you need to intercept onKeyUp
