### ISSUE TITLE
Use MapQuest instead of google maps

### ISSUE THREAD

**Issue by rotosonic** [JakeWharton/ActionBarSherlock#756]
I have upgraded my app to use sherlock with google maps thru use of android-support-v4-r6-googlemaps.jar. For the kindle fire version, I used mapquest. Is it possible to branch the source to use mapquest instead of google maps. If someone could provide direction then I could try it. Thanks the Sherlock droids.

**Comment by JakeWharton** [comment]
Nothing in ActionBarSherlock prevents this functionality. Copy one of the provided base activities and change it to work with whatever base activity they require.

**Comment by rotosonic** [comment]
Thanks. It worked great, my app is in review at Amazon. I blogged about it also. http://radarbuddy.wordpress.com/2013/01/01/android-ui-update-to-halo-for-android-2-x-to-4-x-devices/  

Have a belated Happy New Years.
