### ISSUE TITLE
onResumeFragments Undefined for SherlockFragment

### ISSUE THREAD

**Issue by mattdonders** [JakeWharton/ActionBarSherlock#757]
According to the Android developer documentation `onResumeFragments()` is the fragment-orientated version of onResume() that you can override to perform operations in the Activity at the same point where its fragments are resumed.

I am trying to only call some code when a tab is Active and was hoping to try to do that via the `onResume()` of the SherlockFragment, but looking at a logcat `onResume()` is called when the main Activity is started.

Is `onResumeFragments()` not supposed to be supported for the type SherlockFragment? Or am I misinterpreting its use?

Thanks.

**Comment by iNoles** [comment]
I think you supposed to call it on SherlockFragmentActivity but not in any sherlockfragments

**Comment by SimonVT** [comment]
Fragment handling is entirely up to the support library, ABS just extend the classes that handle this.
