### ISSUE TITLE
Could not find method com.actionbarsherlock.internal.nineoldandroids.widget.NineFrameLayout.onHoverEvent

### ISSUE THREAD

**Issue by harshamv** [JakeWharton/ActionBarSherlock#759]
I find this unusual Error in the LogCat

http://pastebin.com/z53WSjbS

I have a list view which doesnt appear until i touch the screen once. I hope it is not because of this error in the logcat

I have posted a question on SO also with my code: http://stackoverflow.com/questions/14009262/android-listview-text-disappears-on-load

**Comment by SimonVT** [comment]
That's just dalvik complaining that certain methods, which are referenced in code, do not exist. Unless they are actually called, there is no issue (it'd crash if they were).
