### ISSUE TITLE
Need DialogWhenLarge theme

### ISSUE THREAD

**Issue by DineshAnandan** [JakeWharton/ActionBarSherlock#761]
Can u please add support for DialogWhenLarge theme in ABS?

**Comment by JakeWharton** [comment]
This will not be included. Dialog themes are being removed in the next version as well.

In `values/`:

``` xml
<style name="Theme.MyApp.DialogWhenLarge" parent="Theme.Sherlock">
</style>
```

In `values-v14/`:

``` xml
<style name="Theme.MyApp.DialogWhenLarge" parent="android:Theme.Holo.DialogWhenLarge">
</style>
```

**Comment by DineshAnandan** [comment]
When i apply the android:Theme.Holo.DialogWhenLarge theme in values-v14 folder in samsung galaxy tab 10.1 getSupportActionBar() returns null

**Comment by JakeWharton** [comment]
Dialogs don't have action bars so you need to guard agains that.

**Comment by stephanenicolas** [comment]
Our base class, which provides a lot of features inside our app inherits from RoboSherlockFragmentActivity. I guess a lot of apps are organized this way. The absence of DialogThemes in ABS 4.3.x will lead to code deduplication of the base class, which is quite an horrible pattern. Getting stuck to 4.2.0 is not a nice solution either.

Is there any chance that this feature could be added back ?

**Comment by SimonVT** [comment]
You can quite easily create the dialog themes yourself.

**Comment by stephanenicolas** [comment]
Is there any example somewhere that should be mentionned on the wiki of ABS
?
I feared to have to add new resources has the commit that removed that
feature contained a lot of code + theme + resources.

Thx for your very fast answer.

2013/5/24 Simon Vig Therkildsen notifications@github.com

> You can quite easily create the dialog themes yourself.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/JakeWharton/ActionBarSherlock/issues/761#issuecomment-18406443
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - blog.octo.com
www.usievents.com
...........................................................

**Comment by SimonVT** [comment]
Look at the commit, that's exactly how you do it.
