### ISSUE TITLE
How to Change Position of ListNavigation in ActionBarSherlock

### ISSUE THREAD

**Issue by blastering66** [JakeWharton/ActionBarSherlock#764]
Hai, im new at Android and just started learn using ActionBarSherlock. i want to ask how to costumize a little about the position of the ListNavgation (Spinner) from right of title the ActionBar, to LEFT OF MENU (on the right ). this is my layout looklike. Please help me....

![ask](https://f.cloud.github.com/assets/3015184/33813/45247014-50ce-11e2-9053-1dd26d802f2e.png)

**Comment by SimonVT** [comment]
I don't believe this is possible. Try asking on stackoverflow or the android developers mailing list.
