### ISSUE TITLE
setSupportProgressBarIndeterminateVisibility not working on Android 2.3.6

### ISSUE THREAD

**Issue by cesards** [JakeWharton/ActionBarSherlock#765]
I'm trying to show indeterminate progress on my action bar, but whatever I do, it doesn't work.

I've tried almost everything...

@Override
 public void onCreate(Bundle savedInstanceState) {
    requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_search);
        setSupportProgressBarIndeterminateVisibility(Boolean.TRUE);
        ...
        getSherlock().setProgressBarIndeterminateVisibility(true);
        getSherlock().setProgressBarVisibility(true);
        getSherlock().setProgressBarIndeterminate(true);
}

But I get nothing. What's wrong?

Thank you in advance.

**Comment by Prototik** [comment]
Try replace `requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);` on `requestWindowFeature(com.actionbarsherlock.view.Window.FEATURE_INDETERMINATE_PROGRESS);
`

**Comment by cesards** [comment]
Solved. Thank you!!

**Comment by alaeri** [comment]
This fix works in my app.
