### ISSUE TITLE
Can't dismiss IcsListPopupWindow with Sherlock.Light.DarkActionBar

### ISSUE THREAD

**Issue by JulienDev** [JakeWharton/ActionBarSherlock#768]
Hi,

I have a problem using ListPopupWindow backport (IcsListPopupWindow) while using Sherlock.Light.DarkActionBar theme. Indeed, the user can't dismiss the widget by touching another area on screen. I can't reproduce the issue with other themes (Sherlock and Sherlock.Light).

Thanks Jake for your amazing lib.

Julien

**Comment by SimonVT** [comment]
Is there an issue with ABS, or are you just wondering why internal ABS classes doesn't work when you using them in your own code?

**Comment by JulienDev** [comment]
I made some tests and I found this is an IcsListPopupWindow issue, not a theme one. Indeed, using ListPopupWindow there is no problem. On the following screenshots, you can also notice different look & feel. The first one use ListPopupWindow, second one use IcsListPopupWindow.

![device-2013-01-21-214734](https://f.cloud.github.com/assets/71345/84359/eeda26bc-640b-11e2-88cb-8dcefd0ad459.png)
![device-2013-01-21-214818](https://f.cloud.github.com/assets/71345/84360/f24fc4c8-640b-11e2-94ac-a56fd24a7968.png)

**Comment by JakeWharton** [comment]
The class is not meant to be created nor used outside of the context of the action bar.

**Comment by guillaumelachaud** [comment]
I know this issue has been closed for a while now but it might be helpful to others : 

Just add

```
     <item name="listPopupWindowStyle">@style/Widget.Sherlock.Light.ListPopupWindow</item>
```

to your theme whom parent is Sherlock.Light.DarkActionBar and everything works fine.
