### ISSUE TITLE
NPE when user press 'HOME'

### ISSUE THREAD

**Issue by marvinlix** [JakeWharton/ActionBarSherlock#770]
I use abs in my app, which has ActionBar whith tab, but when I press 'HOME', there NPE happened. need update android-support-v4.jar to fix it.

**Comment by JakeWharton** [comment]
Stack trace? Sample? Can't really do anything with this report.

**Comment by marvinlix** [comment]
![QQ 20130109155113](https://f.cloud.github.com/assets/1639869/52827/60b8d24a-5a31-11e2-8ad8-4d6b1775ffd3.png)

**Comment by JakeWharton** [comment]
This is a support library bug, not an ABS bug. As you said it can be fixed by updating the dependency to the latest. This library will be updated to include it when it's present in the central repo. For now just update your local copy.
