### ISSUE TITLE
Menu Options

### ISSUE THREAD

**Issue by lawrence615** [JakeWharton/ActionBarSherlock#771]
Hi, I have a problem in implementing menu options using abs. The problem is, when I add menu options in form of buttons to appear on the action bar there is a duplicate. The image below shows the issue
![login](https://f.cloud.github.com/assets/3224157/53003/5f6ff078-5a3e-11e2-9c18-fdbdfc9c09e5.png)

This is my code

---

package com.sanisani.kindergarten;

import java.util.prefs.Preferences;

import android.app.Activity;
import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.os.Bundle;
import android.widget.Toast;

import com.actionbarsherlock.ActionBarSherlock;
import com.actionbarsherlock.ActionBarSherlock.OnCreateOptionsMenuListener;
import com.actionbarsherlock.app.SherlockActivity;
import com.actionbarsherlock.view.Menu;
import com.actionbarsherlock.view.MenuInflater;
import com.actionbarsherlock.view.MenuItem;

public class LoginActivity extends SherlockActivity implements
        OnCreateOptionsMenuListener {
    ActionBarSherlock mSherlock = ActionBarSherlock.wrap(this);

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    // setTheme(SampleList.THEME); //Used for theme switching in samples
    super.onCreate(savedInstanceState);
    //
    // mSherlock
    // .setUiOptions(ActivityInfo.UIOPTION_SPLIT_ACTION_BAR_WHEN_NARROW);
    mSherlock.setContentView(R.layout.login);

    // ((TextView)findViewById(R.id.text)).setText(R.string.static_attach_content);
}

// @Override
// public boolean onCreateOptionsMenu(android.view.Menu menu) {
// return mSherlock.dispatchCreateOptionsMenu(menu);
// }
public boolean onCreateOptionsMenu(Menu menu) {
    MenuInflater inflater = getSupportMenuInflater();
    inflater.inflate(R.menu.items, menu);
    return true;
}

public boolean onOptionsItemSelected(MenuItem item) {

    Intent intent;

    switch (item.getItemId()) {
    case R.id.cancel:

        // Launch Preference Activity
        intent = new Intent(getBaseContext(), Preferences.class);
        startActivity(intent);
        break;
    }

    return false;
}

public void Quit(int id) {
    Toast.makeText(this, "function 2 called", Toast.LENGTH_SHORT).show();

}
```

}

---

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical" >

    <TextView
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="20dip"
        android:layout_marginTop="20dip"
        android:paddingBottom="2dip"
        android:paddingTop="6dip"
        android:text="Sign in to view your child&apos;s school diary"
        android:textColor="#43bd00"
        android:textSize="16sp"
        android:textStyle="bold" />

    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:paddingLeft="20dip"
        android:paddingRight="20dip" >

        <EditText
            android:id="@+id/username"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:hint="Username" >
        </EditText>
    </LinearLayout>

    <LinearLayout
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:paddingLeft="20dip"
        android:paddingRight="20dip" >

        <EditText
            android:id="@+id/password"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:hint="Password" >
        </EditText>
    </LinearLayout>
</LinearLayout>
```

</LinearLayout>

---

<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >

```
<item
    android:id="@+id/cancel"
    android:icon="@drawable/cancel"
    android:showAsAction="ifRoom|withText"
    android:title="@string/cancel"/>
<item
    android:id="@+id/login"
    android:icon="@drawable/sign_in_2"
    android:showAsAction="ifRoom|withText"
    android:title="@string/sign_in_2"/>
```

</menu>

Please help 

Thanks in advance

**Comment by imminent** [comment]
Where is mSherlock coming from, and why are you using it? Have you
successfully done it without any actions?

Also cancel and sign in shouldn't be actions on the action bar, nor are
they the right iconography.

**Comment by SimonVT** [comment]
ActionBarSherlock mSherlock = ActionBarSherlock.wrap(this);
SherlockActivity already does this. Your activity is being wrapped twice, leading to two action bars.

**Comment by lawrence615** [comment]
Hey Simon,

Thanks a lot for your help. I removed the mSherlock and the other action bar disappeared. The reason for having it was because initially the class was extending Activity instead of SherlockActivity. Since I was not understanding that line I left it that way when I was modifying the class.

The sign in and cancel buttons were initially at the bottom but decided to put them at the action bar just to change the way I always design my login page. But I can remove them if that's not the right way to do it.

The icons I will change them, they were just for testing.

Thanks again for the help, I greatly appreciate.
