### ISSUE TITLE
Actionbarsherlock custom theme on Lenovo p700

### ISSUE THREAD

**Issue by IHNEL** [JakeWharton/ActionBarSherlock#773]
HI,
I am using Actionbarsherlock with a custom theme.  All things work fine with simulators (many versions)  Samsung sprint 4G - android 2.3.6. But when I test my app on Lenovo P700 (android 4.0.3), It always show the default theme, which has red background and white text color. The menu items at right side is good. But these things are not: custom background, home icon and custom text color.
I wish this issue just occurs with me only but I think that you should test on this device. There are some thing wrongs with it.

This is my theme:
<resources xmlns:android="http://schemas.android.com/apk/res/android">

```
<style name="Theme.Styled" parent="Theme.Sherlock">
    <item name="actionBarStyle">@style/Widget.Styled.ActionBar</item>
    <item name="android:actionBarStyle">@style/Widget.Styled.ActionBar</item>
</style>

<style name="Widget.Styled.ActionBar" parent="Widget.Sherlock.Light.ActionBar">
    <item name="background">@drawable/actionbar_background</item>
    <item name="android:background">@drawable/actionbar_background</item>
    <item name="backgroundSplit">@drawable/actionbar_background</item>
    <item name="android:backgroundSplit">@drawable/actionbar_background</item>
    <item name="titleTextStyle">@style/Widget.Styled.ActionBar.TextAppearance</item>
    <item name="android:paddingBottom">15dp</item>
    <item name="android:homeAsUpIndicator">@drawable/buttonback</item>

</style>

<style name="Widget.Styled.ActionBar.TextAppearance" parent="@style/TextAppearance.Sherlock.Widget.ActionBar.Menu">
    <item name="android:textSize">16sp</item>
    <item name="android:textColor">#F00</item>
</style>
```

</resources>

**Comment by SimonVT** [comment]
The native action bar is used on ICS+, so ABS has nothing to do with how it is styled. If the device is broken, you'll have to report it to the manufacturer or possibly http://b.android.com.

**Comment by IHNEL** [comment]
I don't want to publish 2 version of my app for android pre ICS and android ICS+. Is there any way to use ABS for android ICS+? My app run on android 2.x +, of course it should run on ICS.
