### ISSUE TITLE
How do we set UiOptions nowadays?

### ISSUE THREAD

**Issue by xylian** [JakeWharton/ActionBarSherlock#774]
I was checking this thread: https://github.com/JakeWharton/ActionBarSherlock/issues/278

Couldn't find any mentioned method in the newest version of sherlock. How do I set UIPtions now? And what's more important, how to clear the activity UiOptions?

**Comment by JakeWharton** [comment]
You should set them in the manifest, same as always and same as the normal
action bar. You cannot disable UI options once set.

The linked thread was for setting programmatically which should be a very
rare need.

**Comment by xylian** [comment]
I got a feeling that when list navigation enabled, actions are always moved to bottom, no matter if there is space or not. It's not such a big pain, but it starts to be when I enable action mode. I got whole upper action bar free, but still action mdoe actions are on the bottom

**Comment by JakeWharton** [comment]
If the split action bar is enabled the action items are _always_ at the bottom on phones in portrait. This behavior mirrors the native action bar exactly, obviously.

**Comment by xylian** [comment]
Didn't know that. Still kinda curious, where are the UI set methods gone?

**Comment by JakeWharton** [comment]
Hasn't changed: `getSherlock().setUiOptions(int)`

**Comment by xylian** [comment]
getSherlock()? What class owns such method? There is none I can use from SherlockFragmentActivity

**Comment by JakeWharton** [comment]
Yes there is. https://github.com/JakeWharton/ActionBarSherlock/blob/master/library/src/com/actionbarsherlock/app/SherlockFragmentActivity.java#L30-35

**Comment by xylian** [comment]
Oh it's protected. That explains a lot. Thanks
