### ISSUE TITLE
OnTouchEvent  Method of SherlockActivity is not working

### ISSUE THREAD

**Issue by eyildiz** [JakeWharton/ActionBarSherlock#775]
Hello,
i'm using gesture detector in sherlock activity. So I override OnTouchEvent  but when i touched to screen, onTouchEvent method didn't work. 

When i change the "extends SherlockActivity" to "extends Activity" , it worked. But i need ABS :) 

Where is the problem ? I'll  be so glad for your replies.

Thanks, Ersin.

**Comment by SimonVT** [comment]
Please add a test case to the known bugs sample on the dev branch.
