### ISSUE TITLE
Using Actionbarsherlock on ICS+

### ISSUE THREAD

**Issue by IHNEL** [JakeWharton/ActionBarSherlock#776]
I have posted a question here:https://github.com/JakeWharton/ActionBarSherlock/issues/773.  SimonVT  said that ABS does not change the style of native ActionBar on ICS+. It's ok. But I think that ABS should support ICS+. In my case, I have an android app which runs on android 2.x+. I don't want to deploy 2 separated apps, one for android pre ICS and one for ICS+. Since ABS work great, I have no reason to use native actionbar. 
So, what if I just want to use ABS for my app? I want to re-styled the actionbar and It's should show an identical UI for any android versions I support.

**Comment by serj-lotutovici** [comment]
Yes, it should... I've build already 2 apps using ABS... and one had custom ActionBar. ABS works great on all versions...

**Comment by JakeWharton** [comment]
What he said was that ABS does nothing extraordinary on ICS+ and delegates to the native action bar for everything. The whole point of the library is providing action bar functionality where it doesn't already exist. When present, the native functionality is used. The library is not designed nor destined to replace the built-in action bar.
