### ISSUE TITLE
ShareActionProvider Popup Menu and Auto Hide ActionBar issue

### ISSUE THREAD

**Issue by ghost** [JakeWharton/ActionBarSherlock#777]
I have a VideoView activity has ActionBar Auto Hide when user inactive for 4 secs. I would like to keep the ActionBar visible (not hiding after 4 secs) in case user click on Share menu item (when list of share item menu popup), but user hasn't pick which application it want to share. 

My problem is I couldn't find a event or flag to let Auto Hide Timer know when Share List is showing. 

 I already tried to hook up event "addOnMenuVisibilityListener(ActionBar.OnMenuVisibilityListener listener)", but it doesn't get invoked in this case.

Pls help

**Comment by SimonVT** [comment]
Soo.. Is there an issue with ABS or are you just asking questions? Stackoverflow and the mailing list is for questions, not github.

**Comment by ghost** [comment]
sorry, it is a question, i am new to github. please close this issue, i will ask it on stackoverflow
