### ISSUE TITLE
getSupportActionBar() returns null with themes that contain windowNoTitle

### ISSUE THREAD

**Issue by milek** [JakeWharton/ActionBarSherlock#779]
This happens only on Android 2.x. In AndroidManifest.xml you specify theme for activity that has following styles:

``` xml
<item name="windowNoTitle">true</item>
<item name="android:windowNoTitle">true</item>
```

In Activity in onCreate(Bundle) just before call to super, we set up theme that contains ActionBar, e.g. theme that don't have windowNoTitle and android:windowNoTitle set at all.
On Android 4.x works fine, but on 2.x old value for windowNoTitle is carried through to new theme.

Workaround for that is to set manually windowNoTitle to true.

**Comment by SimonVT** [comment]
Try setting windowNoTitle to false in your new theme. If that doesn't work, it's just a limitation on older platforms.

**Comment by JakeWharton** [comment]
The action bar _is_ the title bar on pre-Honeycomb. Setting `windowNoTitle` to `true` is telling it that you don't want an action bar.

**Comment by milek** [comment]
I've probably not stated myself very correctly. I understand that setting `windowNoTitle` to `true` will result in ActionBar not there, and `getSupportActionBar()` returning `null`, that's very correct. But my problem is a bit different. Let my try to explain once more

I have activity that in AndroidManifest.xml has setup theme that contains following entries in style

``` xml
<style name="ThemeNoTitle" parent="Theme.Sherlock.Light.DarkActionBar">
    <item name="windowNoTitle">true</item>
    <item name="android:windowNoTitle">true</item>
</style>
```

Now when Activity is launched, in `onCreate()` I have following code

``` java
protected void onCreate(Bundle bundle)
{
    setTheme(createCinema().getCinemaTheme());
    super.onCreate(bundle);

    getSupportActionBar().setLogo(R.drawable.helios_logo);
    getSupportActionBar().setTitle("");
}
```

Method `getCinemaTheme()` returns theme `ThemeHelios` which looks like this

``` xml
<style name="ThemeHelios" parent="Theme.Sherlock.Light.DarkActionBar">
    <item name="actionBarStyle">@style/Widget.Helios.ActionBar</item>
    <item name="actionBarItemBackground">@drawable/actionbar_item_background</item>
    <item name="android:actionBarStyle">@style/Widget.Helios.ActionBar</item>
    <item name="android:actionBarItemBackground">@drawable/actionbar_item_background</item>
</style>
```

Now the reason I'm posting:
- On _Android 4.0.4_ this works correctly, I don't have `NullPointerException` on `getSupportActionBar()`
- On _Android 2.3.4_ (real device and emulator) this doesn't work, I receive `NullPointerException` when I want to access ActionBar. Reason for that is, original theme that came from manifest contains style `windowNoTitle` and ActionBarSherlock (or Android 2.x, for that matter) when applying new theme still thinks that `windowNoTitle` is set, while it isn't and should be ignored.

I hope I stated this correctly :-)

At the moment I've found workaround to add 

``` xml
<item name="windowNoTitle">false</item>
```

to theme `ThemeHelios` which will explicitly override previous value.

I filled this as issues, as this is not consistent across native implementation and custom.

**Comment by JakeWharton** [comment]
Interesting and odd use-case. Will investigate. Thanks for the detailed explanation.

**Comment by SimonVT** [comment]
There is no default value for windowNoTitle in the sherlock themes, so the
previous value is not overridden when calling setTheme (it applies the
attributes from the new theme to the existing Theme instance). We need to
provide defaults for all custom attributes.

**Comment by mdumrauf** [comment]
Happens also with Jelly Bean.

**Comment by SimonVT** [comment]
That must be another issue, which is out of our control. It's handled entirely by the framework on JB.

**Comment by JakeWharton** [comment]
FIxed on `dev`.

**Comment by thphuoc** [comment]
for the problem getSupportActionBar() always return NULL
That is because you set theme NoActionBar in AndroidManifest.xml

Theme.Sherlock.Light.NoActionBar

If your application does not use action bar then no need use that method.
