### ISSUE TITLE
How to use  SearchView

### ISSUE THREAD

**Issue by yaming116** [JakeWharton/ActionBarSherlock#782]
I view demos inside SearchView but no description of how to use the suggestions ,search query, voice ,can teach me how to use.

**Comment by JakeWharton** [comment]
The API (like all of the ActionBarSherlock APIs) mirrors that of the [native `SearchView`](https://developer.android.com/reference/android/widget/SearchView.html). Please refer to its documentation and tutorials for proper usage.
