### ISSUE TITLE
Missing android Prefix on abs__search_dropdown

### ISSUE THREAD

**Issue by iNoles** [JakeWharton/ActionBarSherlock#787]
res/drawable/abs__search_dropdown_dark.xml:19: Error: Attribute is missing the Android namespace prefix [MissingPrefix]
 `<stroke android:width="2dp" color="#A00080FF"/>`
                                ~~~~~~~~~~~~~~~~~
res/drawable/abs__search_dropdown_light.xml:19: Error: Attribute is missing the Android namespace prefix [MissingPrefix]
`<stroke android:width="1dp" color="#A00080FF"/>`

**Comment by IgorGanapolsky** [comment]
Is this a Lint error, or a compilation error?  If it is just a lint error then you can get rid of it by right clicking your android project (in Eclipse) and choose Android Tools-> Clear Lint Markers

**Comment by JakeWharton** [comment]
It's a valid lint error that needs fixed.

**Comment by JakeWharton** [comment]
Actually this one might not be, but the other one definitely is. This one is copied code from AOSP so if it's broken there then we need to emulate broken behavior here.

**Comment by JakeWharton** [comment]
This is also "broken" in AOSP so for now we're correctly matching their behavior.
