### ISSUE TITLE
persistFloat in custom EditTextPreference causes crash

### ISSUE THREAD

**Issue by jkwiecien** [JakeWharton/ActionBarSherlock#790]
I've made custom EditTextPreference for use with my SherlockPreferenceActivity

I got this method that persists value: 

```
private void peristValue() {
    persistFloat(value);
}
```

Value gets persisted actually, but when I reopen this activity, the app get crashed. Here is the log:

01-19 18:58:45.261: E/AndroidRuntime(21912): java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.trustee.kantory/pl.trustee.kantor.activities.SettingsActivity}: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2049)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2083)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.ActivityThread.access$600(ActivityThread.java:134)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1233)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.os.Looper.loop(Looper.java:137)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.ActivityThread.main(ActivityThread.java:4697)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at java.lang.reflect.Method.invokeNative(Native Method)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at java.lang.reflect.Method.invoke(Method.java:511)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at dalvik.system.NativeStart.main(Native Method)
01-19 18:58:45.261: E/AndroidRuntime(21912): Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:220)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.Preference.getPersistedString(Preference.java:1396)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.EditTextPreference.onSetInitialValue(EditTextPreference.java:154)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.Preference.dispatchSetInitialValue(Preference.java:1312)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.Preference.onAttachedToHierarchy(Preference.java:1124)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:156)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:97)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:38)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.GenericInflater.rInflate(GenericInflater.java:488)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.GenericInflater.inflate(GenericInflater.java:326)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.GenericInflater.inflate(GenericInflater.java:263)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:269)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1476)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at pl.trustee.kantor.activities.SettingsActivity.onCreate(SettingsActivity.java:21)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.Activity.performCreate(Activity.java:4539)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
01-19 18:58:45.261: E/AndroidRuntime(21912):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2013)

**Comment by SimonVT** [comment]
SherlockPreferenceActivity just attaches an ActionBar to a PreferenceActivity, it has nothing to do with how the preferences are actually handled.

**Comment by iNoles** [comment]
the real error message was java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
