### ISSUE TITLE
SearchView does not fire suggestion.

### ISSUE THREAD

**Issue by lity** [JakeWharton/ActionBarSherlock#791]
When I use "android.widget.SearchView", the search suggestion is fired, "query" method of my  ContentProvider is invoked.

When I change to "com.actionbarsherlock.widget.SearchView", the search suggestion isn't fired.

Other code except "import ...SearchView" are completely the same.

Do you forget this feature?

**Comment by yaming116** [comment]
I also encountered the same problem, even I click SearchButton, onOptionsItemSelected method will not be executed.

**Comment by lity** [comment]
I created a project to show this issue. Please see https://github.com/lity/BugReproduce

**Comment by SimonVT** [comment]
This should be fixed by #653. For future reference, please add test cases to the known bugs project in the dev branch and submit a pull request.
