### ISSUE TITLE
Support usage of SearchView outside the ActionBar

### ISSUE THREAD

**Issue by SimonVT** [JakeWharton/ActionBarSherlock#798]
Is currently not possible when using the DarkActionBar theme.

**Comment by MattyBoy4444** [comment]
This also happens to me.  If you switch to Theme.Sherlock.Light it seems to work.

**Comment by JakeWharton** [comment]
Yes, anything not based on `.DarkActionBar` will work.

**Comment by MattyBoy4444** [comment]
Anything we can do to get it to work??

**Comment by JakeWharton** [comment]
Use `ContextThemeWrapper` with one of the two other themes as the inflation context.

**Comment by xiaoym** [comment]
So many thanks,  this puzzled me for a few days. Wish quickly fixed.
