### ISSUE TITLE
NumberFormatException on some 2.3.5 firmwares when dialog are show

### ISSUE THREAD

**Issue by petrnalevka** [JakeWharton/ActionBarSherlock#801]
Hello, we are suffering an issue on some 2.3.X firmwares regardless of manufacturer. When we use AlerDialog.Builder within an SherlockActivity we get the following error when inflating alert_dialog.xml. It is related to ABS as if the activity does not extent SherlockActivity the error does not occur. 

I tries to search forums but cannot find any reference to this problem. It is difficult how many users are affected. Currently I have comtact with ~6 users suffering this issue. Any idea what may be the cause or where to look? It's very difficult for us to simulate this as we don't have an affected device. The affected firmwares include:

lge/thunderg/thunderg:2.3.3/GRI40/LG-P500-V20h.19D34B612E:user/release-keys
samsung/GT-S5830/GT-S5830:2.3.4/GINGERBREAD/XXKPH:user/test-keys
samsung/GT-I9003/GT-I9003:2.3.6/GINGERBREAD/XWLF2:user/release-keys
kobo/WiFi_gb/pegasus:2.3.4/GRJ22/eng.GB.20120604.161157:user/release-keys
kobo/WiFi_aus_nz/pegasus:2.3.4/GRJ22/eng.AUS_NZ.20120604.161231:user/release-keys

Thank you very much. 

The full stacktrace:

--------- Stack trace ---------
android.view.InflateException: Binary XML file line #21: Error inflating class <unknown>
    android.view.LayoutInflater.createView(LayoutInflater.java:518)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
    android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    com.android.internal.policy.impl.PhoneWindow.setContentView(Unknown Source)
    com.android.internal.app.AlertController.installContent(AlertController.java:216)
    android.app.AlertDialog.onCreate(AlertDialog.java:260)
    android.app.Dialog.dispatchOnCreate(Dialog.java:307)
    android.app.Activity.createDialog(Activity.java:886)
    android.app.Activity.showDialog(Activity.java:2557)
    android.app.Activity.showDialog(Activity.java:2524)
    com.urbandroid.sleep.alarmclock.AlarmClock.menuAction(AlarmClock.java:454)
    com.urbandroid.sleep.alarmclock.AlarmClock.onOptionsItemSelected(AlarmClock.java:214)
    android.support.v4.app.Watson.onMenuItemSelected(Watson.java:119)
    com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:603)
    com.actionbarsherlock.internal.ActionBarSherlockCompat.onMenuItemSelected(ActionBarSherlockCompat.java:529)
    com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:738)
    com.actionbarsherlock.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:82)
    com.actionbarsherlock.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
    com.actionbarsherlock.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:879)
    com.actionbarsherlock.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:158)
    android.widget.AdapterView.performItemClick(AdapterView.java:284)
    android.widget.ListView.performItemClick(ListView.java:3513)
    android.widget.AbsListView$PerformClick.run(AbsListView.java:1849)
    android.os.Handler.handleCallback(Handler.java:587)
    android.os.Handler.dispatchMessage(Handler.java:92)
    android.os.Looper.loop(Looper.java:130)
    android.app.ActivityThread.main(ActivityThread.java:3962)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:507)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
##     dalvik.system.NativeStart.main(Native Method)

----------- Cause -----------
java.lang.reflect.InvocationTargetException
    java.lang.reflect.Constructor.constructNative(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    android.view.LayoutInflater.createView(LayoutInflater.java:505)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
    android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    com.android.internal.policy.impl.PhoneWindow.setContentView(Unknown Source)
    com.android.internal.app.AlertController.installContent(AlertController.java:216)
    android.app.AlertDialog.onCreate(AlertDialog.java:260)
    android.app.Dialog.dispatchOnCreate(Dialog.java:307)
    android.app.Activity.createDialog(Activity.java:886)
    android.app.Activity.showDialog(Activity.java:2557)
    android.app.Activity.showDialog(Activity.java:2524)
    com.urbandroid.sleep.alarmclock.AlarmClock.menuAction(AlarmClock.java:454)
    com.urbandroid.sleep.alarmclock.AlarmClock.onOptionsItemSelected(AlarmClock.java:214)
    android.support.v4.app.Watson.onMenuItemSelected(Watson.java:119)
    com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:603)
    com.actionbarsherlock.internal.ActionBarSherlockCompat.onMenuItemSelected(ActionBarSherlockCompat.java:529)
    com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:738)
    com.actionbarsherlock.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:82)
    com.actionbarsherlock.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
    com.actionbarsherlock.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:879)
    com.actionbarsherlock.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:158)
    android.widget.AdapterView.performItemClick(AdapterView.java:284)
    android.widget.ListView.performItemClick(ListView.java:3513)
    android.widget.AbsListView$PerformClick.run(AbsListView.java:1849)
    android.os.Handler.handleCallback(Handler.java:587)
    android.os.Handler.dispatchMessage(Handler.java:92)
    android.os.Looper.loop(Looper.java:130)
    android.app.ActivityThread.main(ActivityThread.java:3962)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:507)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
##     dalvik.system.NativeStart.main(Native Method)

----------- Cause -----------
java.lang.NumberFormatException
    org.apache.harmony.luni.util.FloatingPointParser.parseFltImpl(Native Method)
    org.apache.harmony.luni.util.FloatingPointParser.parseFloat(FloatingPointParser.java:321)
    java.lang.Float.parseFloat(Float.java:323)
    android.content.res.TypedArray.getFloat(TypedArray.java:287)
    com.android.internal.widget.WeightedLinearLayout.<init>(WeightedLinearLayout.java:46)
    java.lang.reflect.Constructor.constructNative(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    android.view.LayoutInflater.createView(LayoutInflater.java:505)
    android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
    android.view.LayoutInflater.inflate(LayoutInflater.java:386)
    android.view.LayoutInflater.inflate(LayoutInflater.java:320)
    android.view.LayoutInflater.inflate(LayoutInflater.java:276)
    com.android.internal.policy.impl.PhoneWindow.setContentView(Unknown Source)
    com.android.internal.app.AlertController.installContent(AlertController.java:216)
    android.app.AlertDialog.onCreate(AlertDialog.java:260)
    android.app.Dialog.dispatchOnCreate(Dialog.java:307)
    android.app.Activity.createDialog(Activity.java:886)
    android.app.Activity.showDialog(Activity.java:2557)
    android.app.Activity.showDialog(Activity.java:2524)
    com.urbandroid.sleep.alarmclock.AlarmClock.menuAction(AlarmClock.java:454)
    com.urbandroid.sleep.alarmclock.AlarmClock.onOptionsItemSelected(AlarmClock.java:214)
    android.support.v4.app.Watson.onMenuItemSelected(Watson.java:119)
    com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:603)
    com.actionbarsherlock.internal.ActionBarSherlockCompat.onMenuItemSelected(ActionBarSherlockCompat.java:529)
    com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:738)
    com.actionbarsherlock.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:82)
    com.actionbarsherlock.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
    com.actionbarsherlock.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:879)
    com.actionbarsherlock.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:158)
    android.widget.AdapterView.performItemClick(AdapterView.java:284)
    android.widget.ListView.performItemClick(ListView.java:3513)
    android.widget.AbsListView$PerformClick.run(AbsListView.java:1849)
    android.os.Handler.handleCallback(Handler.java:587)
    android.os.Handler.dispatchMessage(Handler.java:92)
    android.os.Looper.loop(Looper.java:130)
    android.app.ActivityThread.main(ActivityThread.java:3962)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:507)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
    dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
I'd imagine it has to do with you having theme attributes that don't exist on 2.3 in values/

**Comment by petrnalevka** [comment]
Hello, thanks a lot for the response. I will try to investigate this. But on the other hand this would probably cause the dialogs to fail on on all 2.3 firmwares. But unfortunately I cannot simulate this issue on some 5 phones with 2.3.X in my surrounding...

**Comment by SimonVT** [comment]
No, some devices are just broken. It doesn't cause issues on AOSP.

**Comment by JakeWharton** [comment]
As @SimonVT said, this is usually the result of an OEM ROM declaring a bunch of custom attributes and overlapping with ones from future versions of Android.

**Comment by petrnalevka** [comment]
Thank you guys for your help. But is there anything we could do about it apart from using a custom layout in all our dialogs? I need to approve this but it seems only dialogs with items (adapter) are affected. But for example the whole PreferenceActivity would need to be replaced as the issue occurs for example when changing a ListPreference.  Thank you.

**Comment by SimonVT** [comment]
Don't put attributes that don't exist on 2.3 in values/

**Comment by petrnalevka** [comment]
Is this equivalent to "Don't use ABS" or am I missing something? 

In fact we don't use any special attributes or styles. The issue may be reproduced on the affected firmwares just by creating a SherlockActivity with the Theme.Sherlock and making the following call:

```
    AlertDialog.Builder builder = new AlertDialog.Builder(context);
    builder.setTitle("Hello");
    builder.setItems(new String[] {"test1", "test2"}, new DialogInterface.OnClickListener() {...});
    builder.create();
```

This will cause the NumberFormatException

Thanks a lot.

**Comment by SimonVT** [comment]
It means, if you have attributes like android:actionBarStyle, only have it in your themes on platforms where it actually exists (v11+ in this case, tho it isn't used until 14).

**Comment by petrnalevka** [comment]
Hello Simon, you are completely right. Thanks a lot for pointing this out and resolving our issue. We did indeed have such attributes in the pre-v11 values. Sorry for choosing probably a wrong place for the issue and again many thanks.
