### ISSUE TITLE
SearchView.setIconifiedByDefault UI Inconsistency

### ISSUE THREAD

**Issue by Ruxton** [JakeWharton/ActionBarSherlock#805]
It seems when searchview is set to IconifiedByDefault, it works, however.

Prior to iconified by default when searchview gets expanded it looks like this:
![not iconified by default](https://f.cloud.github.com/assets/382760/92412/e63175dc-65ce-11e2-92d5-56373c8510ec.png)

When iconified by default it looks like this:
![iconified by default](http://puu.sh/1RNag.jpg)

**Comment by JakeWharton** [comment]
Did you correctly include the [`collapseActionView` `showAsAction` attribute](http://developer.android.com/reference/android/R.attr.html#showAsAction)?

**Comment by JakeWharton** [comment]
Also, please add a test case to the 'known-bugs' sample on the `dev` branch.

**Comment by gabrielittner** [comment]
I was able to reproduce this by just adding the SearchVIew as custom view to the ActionBar.

**Comment by JakeWharton** [comment]
I can't repro this. Add a sample to the known bugs sample on the dev branch in a pull request.

**Comment by gabrielittner** [comment]
This is actually a platform bug. When you have an activity with just the following code you will see the behavior:

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    SearchView searchView = new SearchView(this);
    searchView.setIconifiedByDefault(false);
    getActionBar().setCustomView(searchView);
    getActionBar().setDisplayShowCustomEnabled(true);
}
```

Removing the searchView.setIconifiedByDefault(false) line will make the SearchView look like a normal one, when it's expanded.

**Comment by Ruxton** [comment]
Yeap sorry for not following up more, I can confirm this is indeed a Platform bug.

**Comment by webbp** [comment]
workaround:

``` xml
<SearchView
android:iconifiedByDefault="false"
android:paddingLeft="-48dp"
android:layout_marginLeft="10dp" />
```
