### ISSUE TITLE
SherlockDialogFragment width wrapped to content and no title

### ISSUE THREAD

**Issue by gfreh** [JakeWharton/ActionBarSherlock#815]
When using a SherlockDialogFragment, on a Gingerbread device and using the following lines to set the dialog's style...

``` java
public void onCreate(Bundle savedInstanceState) {
 super.onCreate(savedInstanceState);
 setStyle(SherlockDialogFragment.STYLE_NORMAL, R.style.Theme_Sherlock_Light_Dialog);
 ...
}
```

...I get a fragment dialog that is wrapped to its content and has no title area. 

On ICS, for the same code, I have a fragment dialog that fills the whole screen horizontally (except for the borders) and the title area is available.

**Comment by SimonVT** [comment]
How SherlockDialogFragment looks and behaves is completely controlled by the support library and the framework.
Also, Theme.Sherlock.Light.Dialog no longer exists.
