### ISSUE TITLE
IcsSpinner dropdown list doesn't respect dialog height

### ISSUE THREAD

**Issue by tonnyavery** [JakeWharton/ActionBarSherlock#818]
When using IcsSpinner in a dialog, height for the list is calculated using the whole screen as a reference, that results in list items clipping with dialog borders and not scrolling properly.

I believe the problem is in following code:
IcsListPopupWindow.getMaxAvailableHeight(View anchor, int yOffset, boolean ignoreBottomDecorations)
It uses anchor.getWindowVisibleDisplayFrame(displayFrame) - that doesn't respect dialog height if it's present on the screen.

I understand that IcsSpinner is an internal widget that might not get actual support, but it turned out to be particuralry handy when implementing spinners ICS look and feel on android 2.2-2.3 handsets.

**Comment by SimonVT** [comment]
The ics-prefixed classes are internal so we don't have to maintain them for use cases other than ABS. If they were public, they'd be much more complete, and take a lot more time to create/maintain.
You're free to maintain your own backport of the spinner, but it's not going to be maintained in abs.
