### ISSUE TITLE
Add @Suppess or tools:ignore="NewApi" on the components that warns use of older android components.

### ISSUE THREAD

**Issue by peterbetos** [JakeWharton/ActionBarSherlock#819]
I am seeing a lot of "Call requires API level 11 (current min is 7)" errors during the build while my lint is activated. Please have the supress / ignore lines added so that only the real build errors would appear on the Problems window. Thanks.

**Comment by SimonVT** [comment]
No. Unnecessary and wrong to simply suppress the checks. Add a lint.xml to the abs project that disables the api checks if you wish to ignore them
