### ISSUE TITLE
Using sherlock_spinner_item for drop-down navigation generates NullPointerException

### ISSUE THREAD

**Issue by bostone** [JakeWharton/ActionBarSherlock#820]
In the code below if I uncomment 3rd line I will get NullPointerException. Works fine with default spinner item     

```
    actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_LIST);
    ArrayAdapter<CharSequence> adapter = new ArrayAdapter<CharSequence>(actionBar.getThemedContext(),
            //com.actionbarsherlock.R.layout.sherlock_spinner_item,
            com.actionbarsherlock.R.layout.sherlock_spinner_dropdown_item, getResources().getTextArray(
                    R.array.action_list));
```

Here's a stack trace:

02-02 22:18:57.841: E/AndroidRuntime(19952): FATAL EXCEPTION: main
02-02 22:18:57.841: E/AndroidRuntime(19952): java.lang.NullPointerException
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:392)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.Spinner.onMeasure(Spinner.java:439)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.View.measure(View.java:15513)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1052)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.View.measure(View.java:15513)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at com.android.internal.widget.ActionBarView.onMeasure(ActionBarView.java:912)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.View.measure(View.java:15513)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at com.android.internal.widget.ActionBarContainer.onMeasure(ActionBarContainer.java:260)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.View.measure(View.java:15513)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.View.measure(View.java:15513)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2176)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.View.measure(View.java:15513)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1874)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1089)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1265)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.Choreographer.doFrame(Choreographer.java:532)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.os.Handler.handleCallback(Handler.java:725)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.os.Handler.dispatchMessage(Handler.java:92)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.os.Looper.loop(Looper.java:137)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at android.app.ActivityThread.main(ActivityThread.java:5039)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at java.lang.reflect.Method.invokeNative(Native Method)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at java.lang.reflect.Method.invoke(Method.java:511)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
02-02 22:18:57.841: E/AndroidRuntime(19952):    at dalvik.system.NativeStart.main(Native Method)

**Comment by SimonVT** [comment]
Please add a test case to the known-bugs sample on the dev branch.

**Comment by JakeWharton** [comment]
Without a sample we cannot reproduce. If you can create a reproducible sample, send a pull request against the `dev` branch adding it to the 'known-bugs' sample.
