### ISSUE TITLE
cannot set icon in search view

### ISSUE THREAD

**Issue by cliu903** [JakeWharton/ActionBarSherlock#823]
Please focus on class LoaderCursorSupport.java in SampleList ' Tabs' .

Even though change this line to other image, finally always show  icon 'search'.   why ?

item.setIcon(android.R.drawable.ic_input_add);

@Override public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
            // Place an action bar item for searching.
            MenuItem item = menu.add("Search");
            item.setIcon(android.R.drawable.ic_menu_search);
            item.setShowAsAction(MenuItem.SHOW_AS_ACTION_ALWAYS);
            View searchView = SearchViewCompat.newSearchView(getActivity());
            if (searchView != null) {
                SearchViewCompat.setOnQueryTextListener(searchView,
                        new OnQueryTextListenerCompat() {
                    @Override
                    public boolean onQueryTextChange(String newText) {
                        // Called when the action bar search text has changed.  Update
                        // the search filter, and restart the loader to do a new query
                        // with this filter.
                        mCurFilter = !TextUtils.isEmpty(newText) ? newText : null;
                        getLoaderManager().restartLoader(0, null, CursorLoaderListFragment.this);
                        return true;
                    }
                });
                item.setActionView(searchView);
            }
        }

**Comment by SimonVT** [comment]
You're only changing the icon of the menuitem, which has nothing to do with how the SearchView looks.

**Comment by cliu903** [comment]
I means the icon always show "  icon :  ic_menu_search ", even though change to other image. 

![img](https://f.cloud.github.com/assets/3437279/139169/74990d44-71e1-11e2-9595-9f47480ed4ab.png)

**Comment by SimonVT** [comment]
The icon is the collapsed action view, the menu items text/icon isn't shown.

**Comment by cliu903** [comment]
Can override this icon ?
I try to using searchViewSearchIcon to override parent style. But it's also not work. 

```
<style name="myTheme" parent="Theme.Sherlock">
        <item name="searchViewSearchIcon">@drawable/icon_search</item>
</style>
```

**Comment by kylebuch8** [comment]
@cliu903, did you get this figured out? I'm also trying to change the search icon to use the most recently released version of the icon pack from developer.android.com.

**Comment by Artgit** [comment]
the same issue, this is my question http://stackoverflow.com/questions/16971359/couldnt-change-actionbarsherlock-searchview-icon

**Comment by iNoles** [comment]
@cliu903 you already have item.setIcon(android.R.drawable.ic_menu_search); Which is a big No-no because any OEM can change the search icon. I don't see the sherlock theme can change the search icon.

**Comment by Artgit** [comment]
What is the difference between

android:showAsAction="ifRoom"

and 

android:showAsAction="ifRoom|collapseActionView"

In the second variant I'm able to change icon via android:icon="@android:drawable/ic_menu_search"

**Comment by emmx** [comment]
http://stackoverflow.com/questions/20123177/how-to-keep-expanded-searchview-on-the-right-side-of-actionbar-while-using-cust

Using ActionBarSherlock that would be:

``` java
((View) searchView.getParent()).setLayoutParams(new android.app.ActionBar.LayoutParams(Gravity.RIGHT));
```

**Comment by Artgit** [comment]
@mparodi , thanks!

**Comment by Igna1980** [comment]
Any news on the original post?
