### ISSUE TITLE
Reattaching same Fragment instance fails

### ISSUE THREAD

**Issue by btalb** [JakeWharton/ActionBarSherlock#824]
I have been struggling with code in my application that creates any given screen based on what screen is requested. While not the most efficient coding solution, it simply un-attaches every fragment from the screen, and re-attaches the correct ones (creating or reusing depending on their existence). The stackoverflow question can be seen here:
http://stackoverflow.com/questions/14764043/fragments-remove-all-fragments-in-a-view

I believe I have narrowed it down to when using ActionBarSherlock (specifically `SherlockFragmentActivity`), reattaching (and specifically `FragmentTransaction.replace()`), fails if the given `Fragment` is the same instance as that of the already attached Fragment.

While it seems like an issue that should just be avoided with a more clever coding structure, I have verified it does not happen in API 11+ with the standard fragment functions, doesn't happen using the Android Compatibility Packages, and is only introduced when moving to `SherlockFragmentActivity` from `Activity` or `FragmentActivity`.

The code I have used that confirmed this is below:

``` java
package com.test.test;

import com.actionbarsherlock.app.SherlockFragmentActivity;

import android.os.Bundle;
import android.content.Context;
import android.graphics.Color;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.LinearLayout.LayoutParams;
import android.widget.TextView;

public class MainActivity extends SherlockFragmentActivity {
    // Context
    public static Context context = null;
    myFragment myFrag = null;
    // Views
    FrameLayout fl = null;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        context = this;

        LinearLayout ll = new LinearLayout(context);
        ll.setOrientation(LinearLayout.VERTICAL);

        Button b = new Button(context);
        b.setText("Repeat");
        b.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {

                // Reattach the same fragment
                getSupportFragmentManager().beginTransaction().replace(fl.getId(), myFrag).commit();

            }
        });

        fl = new FrameLayout(context);
        fl.setId(200);
        fl.setLayoutParams(new LinearLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT));

        myFrag = new myFragment();
        getSupportFragmentManager().beginTransaction().add(fl.getId(), myFrag).commit();

        ll.addView(b);
        ll.addView(fl);

        setContentView(ll);
    }

    public static class myFragment extends Fragment {

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                Bundle savedInstanceState) {
            TextView tv = new TextView(MainActivity.context);
            tv.setText("My fragment");
            tv.setGravity(Gravity.CENTER);
            tv.setBackgroundColor(Color.RED);

            return tv;
        }
    }

}
```

As you can see, all I am adding from abs is the `SherlockFragmentActivity` (other than that, everything is still linked to compatibility support library). By breaks I mean the following:
- [ ] When using `replace()`, it just removes the Fragment and displays none
- [ ] Exactly the same happens if I run and commit equivalent `remove()` / `add()` or `detach()` / `attach()` pairs
- [ ] The issue is fixed by changing the calls from using the same Fragment instance (myFrag) to `new myFragment()` which is obviously not desirable as retaining the old `Fragment` is in most cases essential
- [ ] None of these issues occur without abs

Thanks

**Comment by SimonVT** [comment]
Please add a test case to the known bugs sample on the dev branch.

**Comment by btalb** [comment]
Done, if you could just check I did it correctly, that would be great (new to GitHub)
