### ISSUE TITLE
ActionbarSherlock TabBar with two tabview has strange paddings on Android Jellybean 

### ISSUE THREAD

**Issue by brannpark** [JakeWharton/ActionBarSherlock#829]
![Screenshot_2013-02-13-15-52-29](https://f.cloud.github.com/assets/608776/151997/34e11526-75aa-11e2-9e13-92b4f4122b53.png)

This bug seems to be appeared at tabbar which has two tabviews on android 4.1.2
Anyone who knows this bug? How can I fix this?

**Comment by JakeWharton** [comment]
On Android 4.0 and newer the native action bar is used. This is the built-in action bar behavior and cannot be modified.

**Comment by brannpark** [comment]
Okay, Anyway thanks for your reply! :)
