### ISSUE TITLE
Tapping on title with ABS does nothing, while on 4.2.2, it's the same as tapping the icon.

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#830]
This was a new feature for 4.2.2, would be nice to see it implemented in ABS.

**Comment by JakeWharton** [comment]
ABS is a backport of the 4.0.x action bar to pre-ICS. On API 14 and up the native impl is always used. Adding this functionality would only make it work on API 7 to 13 which doesn't make sense.
