### ISSUE TITLE
Menu Items not showing up on actionbar

### ISSUE THREAD

**Issue by kaushikwavhal** [JakeWharton/ActionBarSherlock#831]
I am using android 2.3.3 API 10. 
Firstly I am unable to add menu items to the actionbar.
and
If i override onCreateOptionsMenu method in my mainActivity.java the default menu shows up when i hit the menu key. 
if i override  onCreateOptionsMenu method in the Sherlock Activity.java and when i het the menu button,the app crashes.

I want to add menu items to the actionbar with an overflow. many forums say that device with a hard menu key cannot have menu in the action bar or overflow.
if it is so, then whats the use if this library?

**Comment by JakeWharton** [comment]
Are you setting `showAsAction` properly? Look at the samples.

**Comment by JakeWharton** [comment]
You might want to ask on StackOverflow, the mailing list, or the official Android mailing list. Issues are for bugs.

**Comment by kaushikwavhal** [comment]
i've tried every possible value for the showAsAction property.Still not helping.
