### ISSUE TITLE
minWidth attribute doesn't seem to work for tabs 

### ISSUE THREAD

**Issue by leonman30** [JakeWharton/ActionBarSherlock#834]
First of all, thank you for your awesome library which has been a great help for me!

I ran into an issue that I'd like to get some feedback on possible fix or workaround.

I have a pretty simple app which has 4 tabs. Those tabs should very happily fit on the screen, without having to scroll. Alas, these 4 tabs just miss the very common 320dp screen width (ex WVGA screen with hdpi), as illustrated by the portion of the screen capture. The names of the tabs, just for illustrative purposes, are single letter. This is done to show that there is no problem fitting the text. The top one has tab #1 highlighted, while the bottom one has the last tab, #4 highlighted. If you look closely, you will see a slight shift in the bars. This shift is much more annoying in "real life" because you do see that the bar moves.

![froyo_tabs_comparison](https://f.cloud.github.com/assets/1729097/170267/c20ef95a-7a5e-11e2-9ef1-1cc44637d7c3.png)

I believe that the reason for the 4 bars not fitting, is because there is a minimum width defined of 80dp. 80x4 is of course 320dp, but not to forget those pesky separators between tabs - which cause the overflow.

I checked that Android, has that 80dp set perhaps here in styles.xml:

<style name="Widget.Holo.Light.Tab" parent="Widget.Holo.Light.ActionBar.TabView">
      <item name="android:background">@android:drawable/tab_indicator_holo</item>
      <item name="android:layout_width">0dip</item>
      <item name="android:layout_weight">1</item>
      <item name="android:minWidth">80dip</item>
</style>

Based on that, I tried to set it with my ActionBar as follows:

```
<style name="MyAppTheme" parent="Theme.Sherlock.Light">
    <item name="android:actionBarTabStyle">@style/cl_ActionBarTabStyle</item>
    <item name="actionBarTabStyle">@style/cl_ActionBarTabStyle</item>
</style>

<style name="cl_ActionBarTabStyle" parent="Widget.Sherlock.Light.ActionBar.TabView">
    <item name="android:minWidth">60dp</item>
</style>
```

This DOES work on native Action Bar - on my ICS device all tabs now fit. However, for the same screen size on earlier releases (say Froyo), that minWidth doesn't seem to take effect. On ICS if I set this minWidth to something large - I do see larger tabs. On Froyo, setting it larger than 80 does make the difference, but setting it less than 80 doesn't seem to make any difference. Strange...

I would appreciate any suggestion.

Thanks

**Comment by JakeWharton** [comment]
This might be fixed on `dev` by @SimonVT already. Trying to release a 4.3.0 this week. Have you tried the `dev` branch?

**Comment by leonman30** [comment]
Just pulled in dev branch, rebuilt and TADA the problem went away!
Looking forward to the official 4.3.0 release
Thank you!

**Comment by JakeWharton** [comment]
Glad to hear it. Thanks for checking!
