### ISSUE TITLE
Feature Request: 4.2.2-style up button

### ISSUE THREAD

**Issue by arnestockmans** [JakeWharton/ActionBarSherlock#835]
Since 4.2.2, the text next to the up button is also clickable. It would be great if ABS also implemented this behavior.

**Comment by SimonVT** [comment]
Duplicate of #832

**Comment by JakeWharton** [comment]
Beat me to it!

**Comment by arnestockmans** [comment]
Ahh, didn't see it was already requested :) Strangely enough it didn't appear in the list of issues :/
