### ISSUE TITLE
Error while traversing through Fragments in ViewPager with changing NavigationMode

### ISSUE THREAD

**Issue by smarek** [JakeWharton/ActionBarSherlock#836]
I've created bug report, and I think it would be great, if community around ABS would stay in touch with it.

http://stackoverflow.com/questions/15002748/actionbar-bug-list-mode-navigation-not-visible-after-using-searchview

Two reasons:
- If this bug will be fixed, there should be appropriate change in ABS codebase
- Maybe someone from community has solved this issue already

Thanks for attention

**Comment by SimonVT** [comment]
We can't change the behavior of the native action bar, you're going to have to work around the issue (and report it on http://b.android.com if it's actually a bug).

**Comment by smarek** [comment]
This is simulated with both, native and ABS. So I think this should not be closed.

**Comment by JakeWharton** [comment]
If it happens on both it's behaving correctly. This is also a dupe of an
old ticket.

**Comment by smarek** [comment]
Can you please link the old one? Thanks
