### ISSUE TITLE
Failed to create BuildConfig class

### ISSUE THREAD

**Issue by pratamawijaya** [JakeWharton/ActionBarSherlock#837]
I got some error when i am import actionbarsherlock library..

[2013-02-22 14:10:13 - ActionBarSherlockLibrary] Failed to create BuildConfig class

i am using ADT 21.1.0 and SDK 21.1.0

i got these error message after i am updating my ADT and SDK to 21.1.0

anyone can help me..?

**Comment by JakeWharton** [comment]
This question is probably better suited to StackOverflow, the mailing list, or the official Android developer mailing list. Please ask in one of those locations as it will reach more people.
