### ISSUE TITLE
`layout-land` Should Use Inline Tabs

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/ActionBarSherlock#84]
As per ICS.

**Comment by nelenkov** [comment]
This has the side effect(?) of pushing the action items on top of the tabs in portrait mode on my N1. Is this intended? If so, anyway to revert to previous layout?

**Comment by JakeWharton** [comment]
Can you email me a test case? I added a ton of tabs and the max action items in landscape on my N1 without a problem.

![tabs](http://i.imgur.com/vu8x7.png)

**Comment by nelenkov** [comment]
Works fine in landscape, but portrait has changed from one row to tow rows. 

Here's how it used to look with ABS 3.2:
http://wwwjdic.googlecode.com/svn/branches/2.0/site/screenshots/dictionary.png

Here's how it looks now:
http://wwwjdic.googlecode.com/svn/branches/2.0/site/screenshots/two-row-ab.png

I'd like to keep the original layout. I'll try to put a test project together.

**Comment by JakeWharton** [comment]
Ah, sorry I missed that you said portrait.

This was introduced [in v3.3.0](https://github.com/JakeWharton/ActionBarSherlock/blob/master/CHANGELOG.md) when the videos of Ice Cream Sandwich started leaking and showed the tabs displayed below the action bar. If you open your app in an SDK 14 emulator you will see this behavior too. The goal was to make sure that ActionBarSherlock provides the same interaction and layouts as the native action bar on Android 3.0+ which is why the move to this style was made.

**Comment by franciscojunior** [comment]
I think nelenkov screens will get much better when the action bar buttons be able to flow to the screen bottom. This way you will get the tabs row at the top and the actionbar buttons at the bottom.

At least this was the impression I got from the ics presentation.

**Comment by nelenkov** [comment]
Thanks, so it's not (directly) related to #84 then. I may try to override the layouts in my own project to keep the layout (for now). Not a big fan of the two row/split action bar idea, but we'll see :)

**Comment by nelenkov** [comment]
@franciscojunior I think it's a waste of space (precious on smaller screens), especially with only one or two action items.The ICS presentation shows how cool ICS on the Galaxy Nexus, but it will take quite some time till most people have a similar device.
