### ISSUE TITLE
Styling support action mode

### ISSUE THREAD

**Issue by xylian** [JakeWharton/ActionBarSherlock#842]
I've managed to style ActionMode, but it works only on native API. I used this style:

``` xml
<style name="exchanger_ActionMode" parent="@style/Widget.Sherlock.ActionBar.Solid">
    <item name="background">@drawable/action_mode_background</item>
    <item name="backgroundStacked">@drawable/ab_stacked_solid_exchanger</item>
    <item name="backgroundSplit">@drawable/ab_bottom_solid_exchanger</item>
    <item name="android:background">@drawable/action_mode_background</item>
    <item name="android:backgroundStacked">@drawable/ab_stacked_solid_exchanger</item>
    <item name="android:backgroundSplit">@drawable/ab_bottom_solid_exchanger</item>
</style>
```

What do I have to do to make support ActionMode has styled background aswell? On older apis it has stock dark blue background and blue accent line

**Comment by SimonVT** [comment]
Please add a sample to the known bugs project on the dev branch

**Comment by JakeWharton** [comment]
Make sure you are setting the style with a duplicated attribute as well.

**Comment by xylian** [comment]
Which duplicated attribute?

**Comment by SimonVT** [comment]
The one not prefixed by android.

**Comment by xylian** [comment]
I did that, didn't I?

**Comment by SimonVT** [comment]
You've only shown your style, not where you're using it.
