### ISSUE TITLE
WebView within a Tab interface hosted SherlockFragment fails to render Jquery Mobile native select menus after initial selection

### ISSUE THREAD

**Issue by andrew-knott** [JakeWharton/ActionBarSherlock#845]
When using JQuery Mobile inside of a WebView that is inside of a Sherlock Fragment That inside of a Tab. If you try to use JQuery Mobile dropdown / select menus of the native type (data-native-menu = true), the select menu will display once and then fail to display on subsequent clicks. All select menus will stop working on devices and emulator > Android 3.0. It works fine on older Android versions.

JQuery Mobile Custom menus (data-native-menu = false) work fine though.

If you load this into the standard Android Browser and the standard WebView, the select menus work consistently every time. Both the native versions and the custom versions (data-native-menu = false) on all Android versions. 

However if you load the same URL into a WebView hosted **inside a SherlockFragment** and run it on a > Android 3 device or emulator, the native select menus (data-native-menu = true) only work once. You click the select menu and it displays and then it becomes no longer responsive.

My test case was to load the demo examples from JQuery Mobile into the ActionBarSherlock FragmentTabs example.

http://jquerymobile.com/demos/1.0a4.1/docs/forms/forms-selects.html#../../docs/lists/lists-forms.html

The above URL is loaded into a 'WebFragment' SherlockFragment subclass with a WebView.

**Comment by JakeWharton** [comment]
What happens in a normal `Fragment`? Fragments are not UI components so they would have no effect on this beyond what a normal `WebView` would. Furthermore, `SherlockFragment` doesn't have much code in it except for a few menu related methods.

**Comment by andrew-knott** [comment]
I've left some detail out of the issue which is important (issue updated). I think it's something to do with the tabbed interface since that is what changes depending on the Android Version.

**Comment by andrew-knott** [comment]
It would be great if someone else could confirm this issue?

**Comment by andrew-knott** [comment]
Example case... Created from the builtin ABS samples,
1. Replace FragmentStackSupport.java with https://gist.github.com/andrew-knott/5070472
2. Add the web.xml layout https://gist.github.com/andrew-knott/5070477
3. Replace FragmentTabs with  https://gist.github.com/andrew-knott/5070465
4. Add  android.permission.INTERNETto manifest.

Run the samples and select Tabs example at bottom of Sample list.
Scroll down to the 'Choose Shipping Method' select menu.

You will notice that the Jquery Mobile native select menu works once and then they all fail.

I've tested using the examples page on JqueryMobile:

http://jquerymobile.com/demos/1.0a4.1/docs/forms/forms-selects.html#../../docs/lists/lists-forms.html

The selects on the same page work in the browser.
The selects work in a standard WebView inside a standard Android TabHost in all versions
The selects fail in a standard WebView inside a SherlockFragment/Fragment in a Tabbed interface provided by ActionBarSherlock

**Comment by SimonVT** [comment]
Removed any notion of ActionBarSherlock from your sample, still didn't work. Not ABS related.
