### ISSUE TITLE
ActionMenuPresenter: Actions may not overflow; actions can become lost/inaccessible

### ISSUE THREAD

**Issue by ckra** [JakeWharton/ActionBarSherlock#846]
Use case:
Add actions to an activity that can have a split action bar. Mark some of them as SHOW_AS_ACTION_ALWAYS and at least one as default (SHOW_AS_ACTION_IF_ROOM), not at the end of the menu (somwhere in the middle). Make sure the show always actions fill up the entire bar's available space to make it obvious.

In this situation, the required (show as always) items may take up all the cells on the action bar. The expected (and correct) behavior is for requested actions (show if room) to get moved to the overflow menu. 

The observed behavior is inconsistent with the normal (wide) action bar: The requested action that should be overflowed is left on the bar, and subsequent required action(s) may get lost because there is not enough room for them that would otherwise exist if the requested action had been moved to overflow.

The root cause was found in ActionMenuPresenter's algorithm for enabling actions when in split mode (mStrictWidthLimit):
1. ActionMenuView.measureChildForCells(...)'s result was being compared to 0. However, that method's algorithm has a lower bound of 1, not 0, resulting in requsted actions never being overflowed as intended.
2. The comparisons that initialize isAction for requested actions inappropriately checked to see if any cells remained. This short-circuited the overflow check logic before all required actions were added. Any requested actions not exactly at the end of the menu would be left on had room run out.

---

See http://gridlox.net/diff/abs_fix_bottomBar_overflow.patch

**Comment by JakeWharton** [comment]
On what API levels?

**Comment by ckra** [comment]
API  8 - I can test 10 as well. I will also look at 17.

I've de-trashed the patch - no more project garbage.

**Comment by ckra** [comment]
I took a look at API 17 sources, and found that the defect is upstream. I'll open an Android ticket.

https://code.google.com/p/android/issues/detail?id=52297

**Comment by JakeWharton** [comment]
Since ABS aims to remain consistent with API 14 I'm going to close this since there's nothing we can do. Hopefully one day it will be fixed.
