### ISSUE TITLE
NPE when running monkeyrunner

### ISSUE THREAD

**Issue by abidk** [JakeWharton/ActionBarSherlock#849]
Hi, got a NPE error whilst running monkeyrunner. 

// java.lang.NullPointerException
//      at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:78)
//      at com.actionbarsherlock.app.SherlockPreferenceActivity.onOptionsItemSelected(SherlockPreferenceActivity.java:159)
//      at android.app.Activity.onMenuItemSelected(Activity.java:2548)
//      at com.android.internal.widget.ActionBarView$3.onClick(ActionBarView.java:167)
//      at android.view.View.performClick(View.java:4204)
//      at android.view.View.onKeyUp(View.java:7790)
//      at android.view.KeyEvent.dispatch(KeyEvent.java:2633)
//      at android.view.View.dispatchKeyEvent(View.java:7205)
//      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1354)
//      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
//      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
//      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
//      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1359)
//      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchKeyEvent(PhoneWindow.java:1920)
//      at com.android.internal.policy.impl.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1395)
//      at android.app.Activity.dispatchKeyEvent(Activity.java:2370)
//      at com.actionbarsherlock.app.SherlockPreferenceActivity.dispatchKeyEvent(SherlockPreferenceActivity.java:116)
//      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1847)
//      at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3701)
//      at android.view.ViewRootImpl.deliverKeyEvent(ViewRootImpl.java:3626)
//      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3161)
//      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4292)
//      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4271)
//      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4363)
//      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
//      at android.os.MessageQueue.nativePollOnce(Native Method)
//      at android.os.MessageQueue.next(MessageQueue.java:125)
//      at android.os.Looper.loop(Looper.java:124)
//      at android.app.ActivityThread.main(ActivityThread.java:5041)
//      at java.lang.reflect.Method.invokeNative(Native Method)
//      at java.lang.reflect.Method.invoke(Method.java:511)
//      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
//      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
//      at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Dupe #701.
