### ISSUE TITLE
menuitem not displaying title while showAsAction set as "withText"

### ISSUE THREAD

**Issue by ipisliao** [JakeWharton/ActionBarSherlock#856]
the setting is android:showAsAction="always|withText", but no title display, I also try set this option in my code, but still not work, the only way to show the title is remove the android:icon option.

the version is 4.2.0

**Comment by JakeWharton** [comment]
Titles only display for action items on sw600dp devices or in landscape. The flags are hints, not law. (Though 'always' is always respected).
