### ISSUE TITLE
Unable to resolve superclass of Landroid/support/v4/app/Watson

### ISSUE THREAD

**Issue by linxingyun** [JakeWharton/ActionBarSherlock#857]
Hello,

When use this lib in my project, I am getting following error message. Could anyone tell me how to resolve it? Thanks a lot!

03-11 02:12:59.284: W/dalvikvm(1085): Unable to resolve superclass of Landroid/support/v4/app/Watson; (149)
03-11 02:12:59.284: W/dalvikvm(1085): Link of class 'Landroid/support/v4/app/Watson;' failed
03-11 02:12:59.284: W/dalvikvm(1085): Unable to resolve superclass of Lcom/actionbarsherlock/app/SherlockFragmentActivity; (161)

**Comment by JakeWharton** [comment]
This means the support library wasn't included in your app somehow. `Watson` extends from `FragmentActivity` so you need to make sure the `android-support-v4.jar` is included in your app.

**Comment by linxingyun** [comment]
Great! Thanks a lot for the help!

**Comment by KonstantinEfimenko** [comment]
Hi! But I have same problem. It worked fine until yestarday, when I updated sdk. Now my project compiles, but when it start, I get this errors:

05-18 16:20:43.478: W/dalvikvm(15143): Unable to resolve superclass of Landroid/support/v4/app/Watson; (111)
05-18 16:20:43.478: W/dalvikvm(15143): Link of class 'Landroid/support/v4/app/Watson;' failed
05-18 16:20:43.478: W/dalvikvm(15143): Unable to resolve superclass of Lcom/actionbarsherlock/app/SherlockFragmentActivity; (119)
05-18 16:20:43.478: W/dalvikvm(15143): Link of class 'Lcom/actionbarsherlock/app/SherlockFragmentActivity;' failed
05-18 16:20:43.478: W/dalvikvm(15143): Unable to resolve superclass of Lua/privatbank/gps/android/view/outlays/OutlaysListActivity; (277)
05-18 16:20:43.478: W/dalvikvm(15143): Link of class 'Lua/privatbank/gps/android/view/outlays/OutlaysListActivity;' failed
05-18 16:20:43.478: E/dalvikvm(15143): Could not find class 'ua.privatbank.gps.android.view.outlays.OutlaysListActivity', referenced from method ua.privatbank.gps.android.view.MainActivity.onClick
05-18 16:20:43.478: W/dalvikvm(15143): VFY: unable to resolve const-class 754 (Lua/privatbank/gps/android/view/outlays/OutlaysListActivity;) in Lua/privatbank/gps/android/view/MainActivity;
05-18 16:20:43.478: D/dalvikvm(15143): VFY: replacing opcode 0x1c at 0x000a

What else? I have another small project with just one SherlockActivity and one SherlockListActivity, and this project works fine.
I tried to create another workspace and restore code in another IDE - same effect.
I use ActionBarSherlock like progect.

**Comment by Tolriq** [comment]
Because the SDK 22 is now more smart about library dependency :)

With the side effect that now when you compile external library of your libraries are no more automatically embed in the final APK.

You just need to copy your libraries external JARs to your main application libs :)

**Comment by xiegeo** [comment]
Real smart.
For me I also had to include libs, which now appears under 'Android Private Libraries', in export.

http://code.google.com/p/android/issues/detail?id=55304

> Nikolay's workaround works for me:
> For all projects (app and library):
> 1. Right click the project, and choose Properties
> 2. Go to Java Build Path-Order and Export.
> 3. Tick 'Android Private Libraries'

**Comment by KonstantinEfimenko** [comment]
xiegeo, thank You. It works.

**Comment by kutothe** [comment]
This was driving me mad, thank you xiegeo.

**Comment by jasonhaihuang** [comment]
Thank you Tolriq, your solution helped me fix my issue, which came up recently after I upgraded my SDK to version 22. 
Thank you so much!

**Comment by Cealtea** [comment]
It works now. Thanks a lot. This was driving me mad too :)

**Comment by fabiancz** [comment]
Thanks Xiengeo for help. I needed to reorder "Android Private Libraries" to first position, to get it working.

**Comment by Felixomni** [comment]
God bless you, Xiegeo.

**Comment by DicksonGT** [comment]
Thank you, Xiegeo!
Interestingly its a warning, not an error, ignored for a while until I spent hours...
//Remember to clean all libs and projects

**Comment by dauglus** [comment]
Thanks, Xiegeo!

**Comment by daimajia** [comment]
Thanks, Xiegeo and Tolriq !!

**Comment by jayhilwig** [comment]
Xiego/Nikolay solution worked for me as well, thanks.

Oddly, my project would run when built from my Mac but not from Eclipse on my Win7 box.

**Comment by ghost** [comment]
Xiego/Nikolay - thank you!

**Comment by Dellaso** [comment]
thanks, xiegeo!

**Comment by NagaMalleshM** [comment]
How to do this in Android Studio on Mac? I dont find a option to tick 'Android Private Libraries'
