### ISSUE TITLE
Application crashes on Android 2.x when /res/xml folder exists

### ISSUE THREAD

**Issue by Dacesilian** [JakeWharton/ActionBarSherlock#858]
Application crashes on Android 2.x when /res/xml folder exists, even with empty folder. It took me 2 hours to investigate why my application crashes. On Android 4.1 it was working.

So I had to move preferences.xml file to /res/layout, changed code and application works.

**Comment by SimonVT** [comment]
The samples have an xml folder, and they work fine. This doesn't sound ABS related.

**Comment by Dacesilian** [comment]
Yes, I understand. It's unbelievable but I don't have anythink else then basic ABS code and it behaves like this.
