### ISSUE TITLE
ReOrder problem as clicking on an item; after setting custom adapter for SherlockListFragment, for only api<10

### ISSUE THREAD

**Issue by beyzabasoglu** [JakeWharton/ActionBarSherlock#861]
Hi,
I have an interesting problem for api level =10. I have tested for api level 12, it has worked fine.
After setting custom adapter that extends ArrayAdapter for SherlockListFragment with items that are fetched from the server, as I click on an item, item order is changing in the list. However, I do not call setListAdapter or notifyDataCahnge methods as clicking on an item. I also comment out onListItemClick method, but the order is still changing randomly. 
Also I have debugged; when I click on the item, it gives the correct position and  item's name which is the item before reordering; It just display the wrong item name (because it reorders everytime I click on an item). 
For your information, I have used the layout from ActionBarSherlock Fragment; simple_list_item_checkable_1.xml for items' layout.
What could be the problem? Could it be a bug?
I really appreciate a quick response.
Thank you in advance.

Beyza

**Comment by JakeWharton** [comment]
This is not ABS related. Try StackOverflow or the Android developer mailing list.
