### ISSUE TITLE
NineOldAndroid. Translate animation crash.

### ISSUE THREAD

**Issue by konstantin-kiriushyn** [JakeWharton/ActionBarSherlock#870]
03-20 13:11:42.740: E/AndroidRuntime(25146): FATAL EXCEPTION: main
03-20 13:11:42.740: E/AndroidRuntime(25146): java.lang.NullPointerException
03-20 13:11:42.740: E/AndroidRuntime(25146):    at com.actionbarsherlock.internal.nineoldandroids.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:515)
03-20 13:11:42.740: E/AndroidRuntime(25146):    at com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:386)
03-20 13:11:42.740: E/AndroidRuntime(25146):    at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:539)
03-20 13:11:42.740: E/AndroidRuntime(25146):    at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:929)
03-20 13:11:42.740: E/AndroidRuntime(25146):    at com.actionbarsherlock.internal.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:952)
03-20 13:11:42.740: E/AndroidRuntime(25146):    at com.actionbarsherlock.internal.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:364)

Code is here

```
    ObjectAnimator headerAnimator = ObjectAnimator.ofFloat(mHeader, "y", -mHeader.getHeight());
    headerAnimator.setDuration(500);
    headerAnimator.start();
```

Also I've changed code too look like in an example 
ObjectAnimator.ofFloat(mHeader, "translationY", -mHeader.getHeight()).start();

Got next errors
 E/PropertyValuesHolder(28763): Couldn't find setter property translationY for RelativeLayout with value type float
 E/PropertyValuesHolder(28763): RelativeLayout - Couldn't find no-arg method for property translationY: java.lang.NoSuchMethodException: getTranslationY

**Comment by SimonVT** [comment]
com.actionbarsherlock. **internal**
Internal classes are not intended for use outside of ABS.
