### ISSUE TITLE
Android 3.2 forcing to use list navigation instead of tabs

### ISSUE THREAD

**Issue by RomanTruba** [JakeWharton/ActionBarSherlock#873]
Hello!

I have setup actionbar using 

```
getSupportActionBar().setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);
```

but Galaxy Tab Honeycomb forcing to use navigation list.
Is there any workaround? I'm not sure, is it bug in ActionBarSherlock, or system feature.

**Comment by exister** [comment]
I have the same problem with api level 12 and 13.

**Comment by iNoles** [comment]
How many tabs you created? like 5 or 6?

**Comment by exister** [comment]
No, just 3.

**Comment by JakeWharton** [comment]
Please add an example to the 'known-bugs' sample so I can easily reproduce.

**Comment by JakeWharton** [comment]
Can't repro. Add a sample to 'known-bugs' (or just ignore 3.2 users!):

![screen shot 2013-07-02 at 10 54 36 pm](https://f.cloud.github.com/assets/66577/741357/4d8080ee-e3a5-11e2-886b-07d3df05acc7.png)
