### ISSUE TITLE
Android 4.2 Spinner Overlap and Intermediate Progress not going away

### ISSUE THREAD

**Issue by alphamu** [JakeWharton/ActionBarSherlock#875]
On the Galaxy Nexus updated to JB using the stock rom, the intermediate progress indicator is displayed from a loader onCreateLoader. Then it is removed in onLoaderFinished. This works find on all phones except the Galaxy Nexus on JB.

Other points to note:
- There is a spinner in the action bar.
- There are 2 menu items set to showAsAction="always"

I've been able to reproduce this on 2 Galaxy Nexus phones with stock JB.

The demos app from Google Play does not have this issue.

There also seems to be some issue with overlap in Spinners in the action bar (same phones).

Also asked the question on [StackOverflow](http://stackoverflow.com/questions/15612853/android-spinner-selection-overlap-in-sherlockactionbar-4-2-on-jellybean-4-2)

![6AAI6](https://f.cloud.github.com/assets/844940/297464/f1a8ffe0-9538-11e2-9ee1-eff83114836e.png)

![device-2013-03-25-190949](https://f.cloud.github.com/assets/844940/297461/b6d70ff6-9538-11e2-9618-499812f6ad9e.png)

**Comment by apkelly** [comment]
Have you tried using the latest dev branch? ActionBarSherlock as far as I know doesn't do an awful lot on ICS and JB devices as they already have a native ActionBar, it's only on earlier devices where ABS gets heavily involved.

**Comment by alphamu** [comment]
The problem is only on Android 4.2 only... and some how it seems to be acting peculiar because of how the project is set up. I downloaded the sherlock api demos and they work perfectly! 

Whats so peculiar about the setup I dont know, I have a BaseActivity which is extended by MyMainActivity in which I setup the Spinner and the Intermediate progress indicator... 

I can reproduce it without fail on the Galaxy Nexus on JB 4.2. I dont have the Nexus 4, but I'll try it on my Nexus 7 and see if the same issue occurs.

**Comment by coreform** [comment]
You should find that without ActionBarSherlock, this same problem manifests. Because this problem is to do with Android's native ActionBar implementation it should be reported to Google as an Android bug, not to this project.

PS: G'day.

**Comment by alphamu** [comment]
I have changed my code to the point where it is near identical to the api samples and the problem still persists.
I'm reverting to ABS 4.1 to see if that works better. If the problem is not there in the API samples app, it can't be an OS issue. the only thing that explains that the API samples dont have the same issue is that they are either built on newer or older source.

**Comment by alphamu** [comment]
Okay, after using Sherlock 4.1 the issue(s) disappeared. This is definitely a problem with Sherlock 4.2 on JB 4.2.
That being said my code seems broken now for other reasons :-P

**Comment by JakeWharton** [comment]
All of this is the native action bar so it's unlikely that it's cased by ABS. Don't use showAsAction="always".

**Comment by alphamu** [comment]
The problem came down the me setting this style attribute
`<item name="android:windowBackground">@null<item>`
This was _supposed_ to prevent over draw... however it seems to mess around with the spinner in the actionbar and the progress indicator... the problems were only observed in JB 4.2.2 with Sherlock 4.2 and on GB 2.3.3 with Sherlock 4.1... not sure if this is a real bug or not any more.

Note: Issue disappeared on Android 4.2 when using ABS 4.1 but then it appeared on Android 2.3.3. Similarly when using ABS 4.2 the issue disappears on 2.3.3 but appears on Android 4.2.

**Comment by JakeWharton** [comment]
If you are removing the window background then you need to use a theme with an action bar background or add one yourself. The action bar draws on the window background so if it is not present you will see ghosting artifacts like the one above.
