### ISSUE TITLE
How to test abs__action_bar_tab

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/ActionBarSherlock#877]
Hello,
I am designing unit tests for the Styled sample project.  I would like to test tab selection.  Like when the project loads, the first tab is always selected, and I want to verify that.  However, I cannot find the code that is responsible for selecting this tab.  All I found was code in abs__action_bar_tab.xml and mTabScrollView.addTab(tab, position, setSelected) in ActionBarImpl.class.  However, what code actually tells it that the first tab should be selected by default?

Thank you,
Igor

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/ActionBarSherlock/blob/4.2.0/library/src/com/actionbarsherlock/internal/app/ActionBarImpl.java#L438

**Comment by IgorGanapolsky** [comment]
I see the addTab(Tab tab, boolean setSelected) method, but where in the Styled project is that method called to set the first tab as selected?

**Comment by JakeWharton** [comment]
It just calls `addTab` and then it's called internally.

**Comment by IgorGanapolsky** [comment]
You mean in ActionBarImpl.java?  
    @Override
    public void addTab(Tab tab) {
        addTab(tab, mTabs.isEmpty());
    }

I just don't see where that method is referenced by the library...

**Comment by SimonVT** [comment]
addTab(tab, mTabs.isEmpty()); <- it calls it right there

**Comment by IgorGanapolsky** [comment]
Aaah, I see the method documentation now:
"Add a tab for use in tabbed navigation mode. The tab will be added at the end of the list. If this is the first tab to be added it will become the selected tab."

Thank you!
