### ISSUE TITLE
Question: IcsListPopupWindow missing setSelection(int). Why?

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#878]
Any reason this method was removed from the ABS version of ListPopupWindow?  It's used to position the drop down list to the currently selected item.

**Comment by JakeWharton** [comment]
Probably because it's not used by ABS. You can expect everything in the internal package to not be usable outside ABS. Hence the package name.

**Comment by androidmoney** [comment]
But it is -- it's used by IcsSpinner.DropdownPopup

**Comment by androidmoney** [comment]
You don't get a compiler error because it calls down to setSelection() in IcsAbsSpinner() instead.  But it should be calling IcsListPopupWindow's setSelection().

**Comment by SimonVT** [comment]
If there are any inconsistencies between the native ActionBar behavior and ABS, feel free to file an issue.

**Comment by androidmoney** [comment]
The issue nazi strikes again.

Yes, there would be inconsistencies -- if there were many navigation items on the spinner, on a real Action Bar it would display the currently selected item, but on ABS it would display the first item.

No, I won't create a sample project, if you cannot see that this is an issue, I don't really care.

**Comment by JakeWharton** [comment]
I haven't seen this in practice. Create an example on the known-bugs sample which demonstrates the behavior.

**Comment by androidmoney** [comment]
Created #882
