### ISSUE TITLE
android:showAsAction="never|collapseActionView" not working on Android < Honeycomb

### ISSUE THREAD

**Issue by nagoya0** [JakeWharton/ActionBarSherlock#880]
I tried this on Android 2.1 & 2.3.3 emulator.

When I use android:showAsAction="always|collapseActionView", everything is OK, but if i use  android:showAsAction="never|collapseActionView", I select the menu item and nothing happens.

Perhaps the cause is that Android legacy menu doesn't trigger expandActionView() when user selects the menu item.

**Comment by JakeWharton** [comment]
I believe that is exactly the case. I remember seeing this early on in the 4.x days and just hoping nobody would ever try this :)

**Comment by JakeWharton** [comment]
Dupe #709
