### ISSUE TITLE
Window.FEATURE_LEFT_ICON is not working on 2.x devices

### ISSUE THREAD

**Issue by andreynovikov** [JakeWharton/ActionBarSherlock#884]
The following code:

```
import com.actionbarsherlock.app.SherlockActivity;
import com.actionbarsherlock.view.Window;

public class WaypointInfo extends SherlockActivity
{
    @Override
    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_LEFT_ICON);
        setContentView(R.layout.act_waypoint_info);
        setFeatureDrawableResource(Window.FEATURE_LEFT_ICON, android.R.drawable.ic_dialog_map);
    }
}
```

does not show an icon on 2.x devices. If SherlockActivity is replaced by native Activity then it works both on 2.x and 4.x devices. Activity uses Theme.Sherlock.Dialog style so I can not use ActionBar.setIcon().

**Comment by JakeWharton** [comment]
`Theme.Sherlock.Dialog` is going away in the next release as per the release notes of the last version. Like you said, it doesn't have an action bar so there is little point in having ActionBarSherlock provide dialog themes.

Out of curiosity, what does setting the left icon flag do on ICS+?

**Comment by andreynovikov** [comment]
Just the same as in 2.x - sets an icon before title. If Theme.Holo.Dialog is used.

As "workaround" I've switched to SherlockDialogFragment which appeared to be more conceptually right in my case. (I'm slowly redesigning my old 2.x application, not writing it from scratch.)
