### ISSUE TITLE
Searchview white background and white text

### ISSUE THREAD

**Issue by bdovaz** [JakeWharton/ActionBarSherlock#885]
I use ActionBarSherlock with HoloEverywhere and I set the "<application>" theme to "@style/Holo.Theme.Light".

In 4.2.2 I have no problems but in 2.2 and 2.3.3 I see it like this:

It's a bug?
![Sin t tulo](https://f.cloud.github.com/assets/950602/329153/5e0374ac-9bad-11e2-900f-5304e99106d6.png)

Help!!

**Comment by JakeWharton** [comment]
You should be using `Theme.Sherlock.Light` as your theme. Using `SearchView` without using a `Theme.Sherlock.*` theme OR using it outside of the action bar is not supported.
