### ISSUE TITLE
Tab Fragment transaction replace not working

### ISSUE THREAD

**Issue by guentoan** [JakeWharton/ActionBarSherlock#888]
I use android 4.0.4, When I transaction from tab fragment to another fragment not working.

**Comment by JakeWharton** [comment]
ActionBarSherlock doesn't have anything to do with fragments or the fragment manager. It just gives you the tab selection callback and then your code reacts to it. If you're having a problem with fragments as a result of a tab callback then I suggest you ask on StackOverflow or the Android developer mailing list.
