### ISSUE TITLE
Selecting text and clicking “Web Search” crashes the app

### ISSUE THREAD

**Issue by dungelin** [JakeWharton/ActionBarSherlock#889]
I have an app use custom webview and ABS. The exception appear when select the text in webview and select "Web Search" button (It run normaly if not use ABS).

This is the logcat:
04-04 16:50:15.629: V/WebViewInputDispatcher(7535): blockWebkitDraw
04-04 16:50:15.629: V/WebViewInputDispatcher(7535): blockWebkitDraw lockedfalse
04-04 16:50:19.469: D/AbsListView(7535): Get MotionRecognitionManager
04-04 16:50:22.524: V/webview(7535): clearSelection : mSelectCallbackSec.finish() called .
04-04 16:50:22.554: V/webcore(7535): webkitSelctionControlDraw Selection unable to select
04-04 16:52:02.449: E/InputEventReceiver(7535): Exception dispatching input event.
04-04 16:52:02.454: E/MessageQueue-JNI(7535): Exception in MessageQueue callback: handleReceiveCallback
04-04 16:52:02.619: E/MessageQueue-JNI(7535): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.app.ContextImpl.startActivity(ContextImpl.java:1049)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.app.ContextImpl.startActivity(ContextImpl.java:1043)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.content.ContextWrapper.startActivity(ContextWrapper.java:283)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.webkit.SelectActionModeCallbackSec.onActionItemClicked(SelectActionModeCallbackSec.java:233)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onActionItemClicked(PhoneWindow.java:2809)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.app.ActionBarImpl$ActionModeImpl.onMenuItemSelected(ActionBarImpl.java:948)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:164)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.widget.AdapterView.performItemClick(AdapterView.java:301)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.widget.AbsListView.performItemClick(AbsListView.java:1280)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.widget.AbsListView$PerformClick.run(AbsListView.java:3071)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.widget.AbsListView.onTouchEvent(AbsListView.java:3988)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.View.dispatchTouchEvent(View.java:7350)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2412)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2147)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2161)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1857)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.View.dispatchPointerEvent(View.java:7535)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3415)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3347)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4456)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4434)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4538)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.os.MessageQueue.nativePollOnce(Native Method)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.os.MessageQueue.next(MessageQueue.java:125)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.os.Looper.loop(Looper.java:124)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at android.app.ActivityThread.main(ActivityThread.java:4921)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at java.lang.reflect.Method.invokeNative(Native Method)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at java.lang.reflect.Method.invoke(Method.java:511)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
04-04 16:52:02.619: E/MessageQueue-JNI(7535):   at dalvik.system.NativeStart.main(Native Method)
04-04 16:52:02.649: D/dalvikvm(7535): threadid=1: still suspended after undo (sc=1 dc=1)

**Comment by iNoles** [comment]
Not ABS bug.  android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by dungelin** [comment]
Yes, this is not ABS.
