### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by kaciula** [JakeWharton/ActionBarSherlock#891]
Is it possible to add gradle support for the library? I'm trying to switch to using the new android build system and I need to get an .aar for the ActionbarSherlock library.

I've tried creating a build.gradle file for the library and everything compiles but the app crashes when first starting somewhere inside the library. Integration with my other libraries with gradle seem to be ok.

Here is the build.gradle:

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.3'
    }
}

apply plugin: 'android-library'
apply plugin: 'maven'

dependencies {
    compile files (
        'libs/android-support-v4.jar',
    )
}

android {
    compileSdkVersion 17

```
sourceSets {
    main {
        manifest.srcFile 'AndroidManifest.xml'
        java.srcDirs = ['src']
        resources.srcDirs = ['src']
        res.srcDirs = ['res']
        assets.srcDirs = ['assets']
    }
}
```

}

group = 'com.actionbarsherlock'
archivesBaseName = 'actionbarsherlock'
version = '4.2.0'

uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: uri("/home/ka/dev/.myrepo"))
        }
    }
}

**Comment by iNoles** [comment]
You don't need maven plugin.

you can do compile 'com.actionbarsherlock:library:4.2.0'

**Comment by JakeWharton** [comment]
That'll only incorrectly pull the jar, right?

**Comment by iNoles** [comment]
@JakeWharton It will download jar file from the maven central and uses that jar file. Yeah.

**Comment by JakeWharton** [comment]
ABS isn't a jar...

**Comment by kaciula** [comment]
On maven, the format of the library is apklib. What is needed is the format aar  . I don't really need for the aar to be up on maven, but just to be able to create the aar for ABS locally. 

The build.gradle listed above creates the .aar successfully but it crashes when run on device so maybe there are some subtle things I'm missing in regard to ABS. Or maybe the build system is buggy when creating the aar.

**Comment by twaddington** [comment]
+1 for having an `.aar` file up in maven central.

**Comment by JakeWharton** [comment]
The Gradle library format is not finalized so I wouldn't publish it to central even if support was added. That said, I'm not opposed to adding the build configuration into the repo for people to deploy locally.

**Comment by gary-cloudsherpas** [comment]
+1 to AAR considering "Android Studios" now revolves around gradle

**Comment by devesh** [comment]
Although I still haven't seen any official Android announcements, I've confirmed with @ducrohet that it's now fine to publish AARs to maven repos, which implies that the package format is now final: https://plus.google.com/u/1/+XavierDucrohet/posts/jYgsQikmSK5

**Comment by JakeWharton** [comment]
d1ea971fe3ea4dc8f401c31af3426cb1c207ffb2

**Comment by mosabua** [comment]
We are hoping to add aar support to the Android Maven Plugin soon. Xavier is writing up a bit of a doc and hopefully somebody can implement this soon. Then abs can easily publish the aar to central..

**Comment by danielesegato** [comment]
I don't think an official announcement saying the aar format is final will come.

But according to Xavier Ducrohet you can push aars to maven repositories.

See here comments in here:
https://plus.google.com/u/1/+XavierDucrohet/posts/jYgsQikmSK5

Specifically:

Devesh Parekh 
Is there any news about aar that I missed? Should library authors publish aars to maven repos now?﻿

Xavier Ducrohet
+Devesh Parekh yes you can upload to repositories. ﻿

They are not going to upload support library and sdk library to maven because they want the user to accept a licence agreement before downloading the library, you can read the discussion here for details:
https://plus.google.com/116539451797396019960/posts/QnCgxgs2fzR

**Comment by stefanhoth** [comment]
@mosabua Any news on this front? I would LOVE to kick the downloaded version of ASB off my gradle project and include the remote aar just like maven users can.

**Comment by mosabua** [comment]
Nope.. I have been flooded and not had time to look at it anymore so far. There is branch with a copy of the apklib codebase but nobody has done anything more..

**Comment by ankushg** [comment]
@stefanhoth @mosabua I'd love to be able to use an AAR too; I can't even get the dev branch to compile in Android Studio as a module... I always get errors with the R.java or resources.

I found this: https://github.com/skyisle/abs-aar but am running into an issue with it detecting ABS's resources (https://github.com/skyisle/abs-aar/issues/2) so I'm just hoping someone will get something published as an AAR soon...
