### ISSUE TITLE
title bar not shown with Theme.sherlock.light.Dialog

### ISSUE THREAD

**Issue by jerryfan2000** [JakeWharton/ActionBarSherlock#892]
When set activity with Theme.sherlock.light.Dialog, Dialog title box won't show on 2.2 and 2.3. Have to manually update to android:windowNoTitle="false" in theme.xml.

**Comment by SimonVT** [comment]
All .Dialog themes are going to be removed in the next version of ABS, as per the release notes. You shouldn't use them.

**Comment by codinguser** [comment]
So @SimonVT what is recommended to use instead. Release notes just say "removed dialog themes".

**Comment by JakeWharton** [comment]
The dialog themes weren't anything special. Just a 9-patch for the background that had transparency and a layout for the activity to show the dialog. You should be able to mimic this yourself with a drawable and layout XML.
