### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Nelugo** [JakeWharton/ActionBarSherlock#893]
Hi!
Thank you so mucho for this awesome library.
Since I change to 4.3.0, I'm having a weird issue when I call setContentView in a SherlockFragmentActivity.

It didn't always trigger, but when it does, it force close the app.

04-16 16:51:42.224: E/AndroidRuntime(15563): FATAL EXCEPTION: main
04-16 16:51:42.224: E/AndroidRuntime(15563): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test/com.example.test.DetailActivityExtended}: android.view.InflateException: Binary XML file line #101: Error inflating class <unknown>
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.os.Handler.dispatchMessage(Handler.java:99)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.os.Looper.loop(Looper.java:137)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.ActivityThread.main(ActivityThread.java:5041)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at java.lang.reflect.Method.invokeNative(Native Method)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at java.lang.reflect.Method.invoke(Method.java:511)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at dalvik.system.NativeStart.main(Native Method)
04-16 16:51:42.224: E/AndroidRuntime(15563): Caused by: android.view.InflateException: Binary XML file line #101: Error inflating class <unknown>
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:270)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:135)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.Activity.performCreate(Activity.java:5104)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
04-16 16:51:42.224: E/AndroidRuntime(15563):    ... 11 more
04-16 16:51:42.224: E/AndroidRuntime(15563): Caused by: java.lang.reflect.InvocationTargetException
04-16 16:51:42.224: E/AndroidRuntime(15563):    at java.lang.reflect.Constructor.constructNative(Native Method)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
04-16 16:51:42.224: E/AndroidRuntime(15563):    ... 26 more
04-16 16:51:42.224: E/AndroidRuntime(15563): Caused by: java.lang.OutOfMemoryError
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:502)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:355)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:785)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.content.res.Resources.loadDrawable(Resources.java:1965)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.widget.ImageView.<init>(ImageView.java:120)
04-16 16:51:42.224: E/AndroidRuntime(15563):    at android.widget.ImageView.<init>(ImageView.java:110)
04-16 16:51:42.224: E/AndroidRuntime(15563):    ... 29 more

**Comment by JakeWharton** [comment]
```
04-16 16:51:42.224: E/AndroidRuntime(15563): at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:270)
04-16 16:51:42.224: E/AndroidRuntime(15563): at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:135)
04-16 16:51:42.224: E/AndroidRuntime(15563): at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
```

This means you are calling `setContentView` and ABS is just calling through to the native `setContentView` on the window. Whatever you have in the layout you are using (specifically on line 101) is what is causing the exception, not this library.
