### ISSUE TITLE
Fragment options menu not prepared when using ViewPager on Android 2.3

### ISSUE THREAD

**Issue by veeti** [JakeWharton/ActionBarSherlock#90]
On an app where I have a bunch of fragments in a `ViewPager`, the `onPrepareOptionsMenu` function isn't called on the selected fragment when sliding the pager. Calling `invalidateOptionsMenu` also does nothing. (On ICS, everything works properly). 

I've written a quick demo app to demonstrate the problem and you can find it [here](https://github.com/veeti/ABSViewPagerMenuTest). (I think I asked you about this in IRC a few days back.)

**Comment by JakeWharton** [comment]
Sample project helped immensely despite being a bit difficult to figure out at first :)
