### ISSUE TITLE
AndroidManifest.xml versionName not updated for 4.3.0

### ISSUE THREAD

**Issue by austynmahoney** [JakeWharton/ActionBarSherlock#901]
I checked out the 4.3 tag at https://github.com/JakeWharton/ActionBarSherlock/tree/4.3.0 and `AndroidManifest.xml` file still has the version name set to `android:versionName="4.2.0"`

**Comment by JakeWharton** [comment]
Manifests have no effect on the library or your app.

But yeah, I'll update it on the `dev` branch for the next release.

**Comment by austynmahoney** [comment]
You're right, just wanted to make sure you didn't forget it :)

**Comment by JakeWharton** [comment]
This is what happens when you don't make a release for 6 months. You forget everything that needs to be done!

**Comment by JakeWharton** [comment]
Updated. Also added a release walkthrough so I don't miss it again.
