### ISSUE TITLE
android-support-v4.jar

### ISSUE THREAD

**Issue by RuiRoque** [JakeWharton/ActionBarSherlock#904]
Why is the Support Library packed in the libs folder so old? Is there any incompatibility with more recent ones?

**Comment by JakeWharton** [comment]
It matches the one in Maven central, r7. You should always replace it with the latest version no matter what build system you are using.

Blame Google for setting dependency management back a decade :(  Hopefully the move to Gradle will force them to publish artifacts somewhere reasonable.
