### ISSUE TITLE
Prevent simultaneous interaction with action bar and content

### ISSUE THREAD

**Issue by bkhall** [JakeWharton/ActionBarSherlock#910]
Relates to Android Bug 8034744

https://github.com/android/platform_frameworks_base/commit/d28f30a9e0f30cb48e88958ae4b95f3243e8a0f9

These same changes need to be made to the analogous files within ABS.

**Comment by JakeWharton** [comment]
This would only affect Honeycomb users since that API was introduced in Honeycomb. I suppose it wouldn't hurt...

**Comment by JakeWharton** [comment]
Done on `dev`.
