### ISSUE TITLE
how to get click event of home item?

### ISSUE THREAD

**Issue by ohmerhe** [JakeWharton/ActionBarSherlock#911]
I just can not find the method of getting click event of home item?
Is there anyone can help me!
thanks !

**Comment by JakeWharton** [comment]
> When the user touches the icon, the system calls your activity's onOptionsItemSelected() method with the `android.R.id.home` ID. In response, you should either start the home activity or take the user one step up in your application's structural hierarchy.

via http://developer.android.com/guide/topics/ui/actionbar.html#Home

**Comment by ohmerhe** [comment]
Thank you!
I get it and solve it perfect.

------------------ 原始邮件 ------------------
发件人: "Jake Wharton"; 
发送时间: 2013年4月24日(星期三) 晚上11:32
收件人: "JakeWharton/ActionBarSherlock"; 
抄送: "ohmerhe"; 
主题: Re: [ActionBarSherlock] how to get click event of home item? (#911)

When the user touches the icon, the system calls your activity's onOptionsItemSelected() method with the android.R.id.home ID. In response, you should either start the home activity or take the user one step up in your application's structural hierarchy.

via http://developer.android.com/guide/topics/ui/actionbar.html#Home
