### ISSUE TITLE
Possible to set title/subtitle text size/color?

### ISSUE THREAD

**Issue by kdhr83** [JakeWharton/ActionBarSherlock#912]
SherlockActionBarCompat can be tweaked for bigger/smaller text size in Title/Subtitle, but seems SherlockActionBarNative has no way to make it.

Is it possible to break it?

**Comment by SimonVT** [comment]
For questions about the action bar API, please see stackoverflow or the android developers mailing list.

**Comment by kdhr83** [comment]
I also raised a question on stackoverflow, from where I think it not a question about API, but how to style action bar in xml.

**Comment by JakeWharton** [comment]
There is `titleTextStyle` and `subtitleTextStyle` attributes in the style referenced by the `actionBarStyle` theme attribute.

**Comment by kdhr83** [comment]
this is what I asked and some nice guy suggested a possibility while I couldnt follow it to make it effect
http://stackoverflow.com/questions/16189877/possible-to-change-text-size-color-for-actionbar/16205463#16205463

**Comment by kdhr83** [comment]
Hi, great to see reply from author. In values/themes.xml

```
<style name="Widget.Carrental.TitleTextStyle" parent="TextAppearance.Sherlock.Widget.ActionBar.Title">
    <item name="android:textSize">@dimen/action_bar_title_text_size</item>
</style>
<style name="Theme.Carrental.Light.DarkActionBar" parent="Theme.Sherlock.Light.DarkActionBar">
    <item name="titleTextStyle">@style/Widget.Carrental.TitleTextStyle</item>
</style>
```

</resources>

and in values-v11/themes.xml

```
<style name="Theme.Carrental.Light.DarkActionBar" parent="Theme.Sherlock.Light.DarkActionBar">
    <item name="titleTextStyle">@style/Widget.Carrental.TitleTextStyle</item>
    <item name="android:titleTextStyle">@style/Widget.Carrental.TitleTextStyle</item>
</style>
```

I thought the android:textSize will override that defined in your library, but it makes no difference.

**Comment by JakeWharton** [comment]
`titleTextSize` is an attribute on the action bar style referenced from the `actionBarStyle` attribute on the theme:

Here's some pseudo-XML

``` xml
<style name="theme" parent="abs theme">
  <item name="android:actionBarStyle">@style/myactionbarstyle</item>
  <item name="actionBarStyle">@style/myactionbarstyle</item>
</style>

<style name="myactionbarstyle" parent="abs action bar style">
  <item name="android:titleTextStyle">@style/Widget.Carrental.TitleTextStyle</item>
  <item name="titleTextStyle">@style/Widget.Carrental.TitleTextStyle</item>
</style>
```
