### ISSUE TITLE
Theme.Sherlock.Dialog referenced in the doc but not in the code

### ISSUE THREAD

**Issue by jobi** [JakeWharton/ActionBarSherlock#916]
Hi,

http://actionbarsherlock.com/theming.html mentions a Theme.Sherlock.Dialog, but it seems it was removed in 4.3.0? Is there a replacement I should use to theme dialogs?

**Comment by JakeWharton** [comment]
You should make a dialog theme yourself. I'll remove from the documentation this weekend.

**Comment by jobi** [comment]
ok thanks

**Comment by JakeWharton** [comment]
Done.
