### ISSUE TITLE
Nullpointer exception in ActionMenuItem

### ISSUE THREAD

**Issue by nassendelft** [JakeWharton/ActionBarSherlock#919]
Hi,

I just updated to 4.3.1 and now my app crashes when i click a menu item. It crashes because somewhere in the debug logging it tries to call onString() of the menu item title. but the menu item doesn't have a title, so it crashes.

04-29 15:29:43.244: E/AndroidRuntime(9462): FATAL EXCEPTION: main
04-29 15:29:43.244: E/AndroidRuntime(9462): java.lang.NullPointerException
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.internal.view.menu.MenuItemImpl.toString(MenuItemImpl.java:489)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at java.lang.StringBuilder.append(StringBuilder.java:203)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at android.support.v4.app.Watson.onMenuItemSelected(Watson.java:115)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:603)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.onMenuItemSelected(ActionBarSherlockCompat.java:516)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:744)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:885)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:510)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.actionbarsherlock.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:146)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at android.view.View.performClick(View.java:2485)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at android.view.View$PerformClick.run(View.java:9080)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at android.os.Handler.handleCallback(Handler.java:587)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at android.os.Handler.dispatchMessage(Handler.java:92)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at android.os.Looper.loop(Looper.java:130)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at android.app.ActivityThread.main(ActivityThread.java:3683)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at java.lang.reflect.Method.invokeNative(Native Method)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at java.lang.reflect.Method.invoke(Method.java:507)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
04-29 15:29:43.244: E/AndroidRuntime(9462):     at dalvik.system.NativeStart.main(Native Method)

**Comment by JakeWharton** [comment]
Dupe #902.
