### ISSUE TITLE
FAQ Video Out of Date for New ZIP Structure

### ISSUE THREAD

**Issue by commonsguy** [JakeWharton/ActionBarSherlock#921]
(reported to me by a diligent reader of my book...)

You changed the directory structure of the ZIP archive, such that ABS is in an `actionbarsherlock/` directory, rather than the `library/` directory that it had been in. The video on your FAQ page refers to the old `library/` structure. It might be worth tucking a note on that FAQ entry pointing out the discrepancy.

FWIW, the first `library/` reference in the video occurs around the 1:30 mark.

**Comment by JakeWharton** [comment]
Done.
