### ISSUE TITLE
setProgressBarIndeterminateVisibility(false); has no effect on Android 2.3(.4)

### ISSUE THREAD

**Issue by mandrachek** [JakeWharton/ActionBarSherlock#922]
Using ABS 4.3.0 with Android 2.3.4, in a SherlockFragmentActivity, this code results in indeterminate progress spinner that won't turn off.  This same code works fine and has the desired effect on Android 4.2.2.

``` java
@Override
public void setContentView(int layoutResId) {
    requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
    super.setContentView(layoutResId);
    setProgressBarIndeterminate(true);
    setProgressBarIndeterminateVisibility(false);   
}

```

**Comment by JakeWharton** [comment]
What package are you importing Window from?

**Comment by mandrachek** [comment]
import com.actionbarsherlock.view.Window;

**Comment by JakeWharton** [comment]
Have you tried the indeterminate example in the 'demos' sample app on the
device? It works pre-ICS for me.

**Comment by mandrachek** [comment]
The sample (https://github.com/JakeWharton/ActionBarSherlock/blob/master/actionbarsherlock-samples/demos/src/com/actionbarsherlock/sample/demos/IndeterminateProgress.java) is a SherlockActivity, not a SherlockFragmentActivity.  I'm also overriding setContentView(), rather than doing it in onCreate().  I will try moving it to onCreate() later this evening.

**Comment by JakeWharton** [comment]
The base activity shouldn't matter. They all delegate to the `ActionBarSherlockCompat` class on pre-ICS. Make sure you're calling super before setting the indeterminate progress. The decor view has to be initialized before any UI state can be triggered. You can make a dummy call to `getSupportActionBar()` to trigger decor view initialization as well.

**Comment by mandrachek** [comment]
DOH.

set **Support** ProgressBarIndeterminateVisibility(false);
