### ISSUE TITLE
Background color of Android pre-3.0 options menu

### ISSUE THREAD

**Issue by signpainter** [JakeWharton/ActionBarSherlock#926]
I'm using ABS 4.2.0 and a custom Theme which I created with http://jgilfelt.github.io/android-actionbarstylegenerator/ It relies on the Dark Theme. The icons I use are white (80% opacity as suggested by Google). On pre-3.0 devices the overflowing menu entries are moved to the options menu accessed via the menu key.
The problem is that the background color of the options menu still is white and therefore the icons are nearly invisible and only the text is visible. How can this be solved?
I would expect the color of the options menu to be changed to a dark color. Otherwise it might be possible to use dark icons for the overflowing items.

**Comment by ds23** [comment]
Learn to script by linux or another programs( ubuntu or pyton) another
think there's aks or view it on gifhub thx and have a nice day from
berlin...
Am 05.05.2013 18:41 schrieb "signpainter" notifications@github.com:

**Comment by JakeWharton** [comment]
Dupe #627
