### ISSUE TITLE
Question:  Why custom "background" attribute?

### ISSUE THREAD

**Issue by androidmoney** [JakeWharton/ActionBarSherlock#927]
Any particular reason ABS declares its own attribute named "background" as opposed to using "android:background"?

I am referring to, for example, the Widget.Sherlock.ActionBar style.

Because of this, I have to write ABS specific code to retrieve the background of an ActionBar, which is no big deal, but this appears unnecessary.

**Comment by JakeWharton** [comment]
All attributes are duplicated in ABS styles. It's much easier to say duplicate all attributes than just X, Y, and Z.

The mailing list is a great place to ask these question in the future rather than GitHub issues.

**Comment by androidmoney** [comment]
Thanks.  Perhaps a blurb on top of abs__styles or adding the abs__ prefix to the same-named attributes would be useful.  I just wasted about 90 mins on this as it's not obvious what's going on.
