### ISSUE TITLE
how to change the background of ActionBarSherlock's Tab ?

### ISSUE THREAD

**Issue by yuzhongxingke** [JakeWharton/ActionBarSherlock#931]
I want to change the background of the ActionBarSherlock's Tab or its title, but I don't know where to change it,it has not the method. please help me!

**Comment by JakeWharton** [comment]
The 'styled' sample shows you how to change the background through a theme and tab style.

Questions like this are better directed to StackOverflow or the mailing list.

**Comment by yuzhongxingke** [comment]
thank you very much!You are very good!
