### ISSUE TITLE
Use a new attribute for textAllCaps

### ISSUE THREAD

**Issue by yincrash** [JakeWharton/ActionBarSherlock#934]
Setting android:textAllCaps results in an android lint error if the minSdk is < 14 (which is normal for an ABS project :) ). To avoid this, CapitalizingTextView should rely on a new non-"android:" namespaced attribute.

**Comment by JakeWharton** [comment]
This lint warning is disabled on the `dev` branch and if you are using `CapitalizingTextView` outside of ABS then you shouldn't. Having your strings be in uppercase is much easier.

**Comment by yincrash** [comment]
I am not using `CapitalizingTextView` outside of ABS. I am specifically attempting to set the style of the `actionBarTabTextStyle` to not use all caps. I can't do that without getting a lint error in my styles file. I can write an example if you'd like.
