### ISSUE TITLE
Galaxy Ace Spinner DropDown ActionBar outside visible area

### ISSUE THREAD

**Issue by brokedi** [JakeWharton/ActionBarSherlock#937]
Hello,

when running ActionBarSherlock v4.3.1 (current master Release) on a Samsung Galaxy Ace (GT-S5830), rotating the App to landscape mode, pressing the DropDown Spinner then it happens nothing.

Then when rotating back to the Portrait mode, then I'm able to see the dropdown list (what should have been appeared bevore).

On the Galaxy Ace I've Android 2.3.6

In The Portrait Mode I see Tabs, there everything is ok.
Console output while rotating:
`05-11 18:12:48.909: D/ActionBarSherlock(24141): [dispatchConfigurationChanged] newConfig: { scale=1.0 imsi=222/1 loc=de_DE touch=3 keys=1/1/2 nav=1/1 orien=2 layout=18 uiMode=17 seq=153}
05-11 18:12:48.939: W/dalvikvm(24141): VFY: unable to resolve static method 7147: Lcom/actionbarsherlock/internal/widget/IcsAbsSpinner;.resolveSizeAndState (III)I
05-11 18:12:48.959: W/dalvikvm(24141): VFY: unable to resolve virtual method 4355: Landroid/view/ViewGroup;.onInitializeAccessibilityEvent (Landroid/view/accessibility/AccessibilityEvent;)V
05-11 18:12:48.959: W/dalvikvm(24141): VFY: unable to find class referenced in signature (Landroid/view/accessibility/AccessibilityNodeInfo;)
05-11 18:12:48.959: W/dalvikvm(24141): VFY: unable to resolve virtual method 4356: Landroid/view/ViewGroup;.onInitializeAccessibilityNodeInfo (Landroid/view/accessibility/AccessibilityNodeInfo;)V
05-11 18:12:48.959: W/dalvikvm(24141): VFY: unable to resolve virtual method 4359: Landroid/view/ViewGroup;.onRequestSendAccessibilityEvent (Landroid/view/View;Landroid/view/accessibility/AccessibilityEvent;)Z
05-11 18:12:48.999: W/dalvikvm(24141): VFY: unable to resolve direct method 4819: Landroid/widget/PopupWindow;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V`

The Problem appears when adding configChanges="orientation" to the Maifest of the Activity.

**Comment by JakeWharton** [comment]
Are you handling config changes in the manifest for orientation? Because if so, that's not supported.

**Comment by androidmoney** [comment]
@JakeWharton As per his last line, yes.....

**Comment by JakeWharton** [comment]
Handling orientation changes can't be supported properly because the compatibility view exists inside the content view.
