### ISSUE TITLE
setOnItemClickListener in custom ListView not Work

### ISSUE THREAD

**Issue by takashius** [JakeWharton/ActionBarSherlock#938]
This code works fine in 2.x but not in 4.x

The click only works in versions 2.x not working in 4.x versions I've tried many ways and I can not make the click function

what is the problem?

import java.util.ArrayList;
import android.app.Activity;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import com.actionbarsherlock.app.SherlockListActivity;

public class Inicio extends SherlockListActivity {
    private ListView mListView;
    private ArrayList<Capitulos> listado;

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    mListView = getListView();

    listado = new ArrayList<Capitulos>();

    for(int i = 0; i < 20; i++){
        listado.add(new Capitulos("Titulo " + i, "descripcion " + i));
    }

    AdaptadorTitulares adaptador = new AdaptadorTitulares(Inicio.this);
    setListAdapter(adaptador);
    mListView.setOnItemClickListener(new OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> a, View v, int position, long id) {
            Toast.makeText(Inicio.this, "hazlo", 0).show();
        }
    });
}

class AdaptadorTitulares extends ArrayAdapter {
    Activity context;

    @SuppressWarnings("unchecked")
    AdaptadorTitulares(Activity context) {
        super(context, R.layout.lista, listado);
        this.context = context;
    }

    public View getView(int position, View convertView, ViewGroup parent) {
        LayoutInflater inflater = context.getLayoutInflater();
        View item = inflater.inflate(R.layout.lista, null);

        TextView titulo = (TextView)item.findViewById(R.id.titulo_art);
        titulo.setText(((Capitulos)getItem(position)).getTitulo());
        TextView subtitulo = (TextView)item.findViewById(R.id.desc_art);
        subtitulo.setText(((Capitulos)getItem(position)).getDescrip());

        return(item);
    }

}
```

}

**Comment by JakeWharton** [comment]
What happens when you use a normal `ListActivity`?

**Comment by takashius** [comment]
well, the click does not work

**Comment by JakeWharton** [comment]
If it doesn't work with a normal `ListActivity` then it's not an ActionBarSherlock problem (nor did I expect it to be one, really). ABS doesn't have anything to do with `ListView` or how it works.
