### ISSUE TITLE
CapitalizingTextView doesn't capitalize

### ISSUE THREAD

**Issue by EurigJones** [JakeWharton/ActionBarSherlock#939]
Unless you programatically use setTextCompat() method. 

Is this on purpose or not? I would have thought you'd want to run the setTextCompat logic in the setText overriding property.

**Comment by JakeWharton** [comment]
And I use that. Are you seeing this not work or are you trying to use this outside of ABS? The latter is not supported

**Comment by EurigJones** [comment]
My project is using ABS, and I'm using CapitalizingTextView within a view which is not part of the ABS project. If that is what you mean by outside of ABS.

**Comment by JakeWharton** [comment]
`setText` is a `final` method on `TextView` so it cannot be override. You have to use `setTextCompat`. That said, using this control is not supported outside of within ABS (hence the `internal` package name). If you need uppercase text you're better of making it uppercase in your strings directly.
