### ISSUE TITLE
Fragment.onPrepareOptionsMenu not called until menu button pressed

### ISSUE THREAD

**Issue by petedoyle** [JakeWharton/ActionBarSherlock#94]
In 3.3.1 Fragment#onCreateOptionsMenu(...) is called when a fragment is displayed, but Fragment#onPrepareOptionsMenu(android.view.Menu) is only called after pressing the Menu button.  This is on a 2.3 device.

I have a fragment that effectively has Play/Pause/Stop actions, and I use onPrepareOptionsMenu() to disable them depending on the current state.  Without calling onPrepareOptionsMenu(), all three show until I press the menu key.

Just for reference (in case its helpful), the stock ACL dispatches onPrepareOptionsMenu() from FragmentActivity#onPreparePanel(int featureId, View view, Menu menu).

**Comment by JakeWharton** [comment]
If you could, try the `dev` branch. It has the upcoming 3.4.0 version which is based on the r4 ACL that was just released. It also contains a bug fix that should fix the situation you describe.

**Comment by petedoyle** [comment]
Thanks Jake, the `dev` branch definitely fixes this. :)  Seeing another issue that I'll file separately.

**Comment by petedoyle** [comment]
Nevermind on the other issue (mentioned above).  I had all my menu items' `showAsActions` set to `always` and was seeing too many items in the action bar.
