### ISSUE TITLE
setDisplayHomeAsUpEnabled(false) not working

### ISSUE THREAD

**Issue by dominicthomas** [JakeWharton/ActionBarSherlock#940]
I am trying to hide the the show home up arrow and the above call doesn't work. 

I set these in my theme:
<item name="homeAsUpIndicator">@color/transparent</item>
<item name="android:homeAsUpIndicator">@color/transparent</item>

and they hid the arrow but the logo then displayed too far to the left and off the screen a little.

Please let me know if there is a workaround or a solution.

**Comment by JakeWharton** [comment]
Space is always reserved for the up icon. Whether it is visible or not the home icon does not move.
