### ISSUE TITLE
New DrawerLayout use MenuItem from v4 to make toggle using App icon

### ISSUE THREAD

**Issue by ethervoid** [JakeWharton/ActionBarSherlock#941]
With the new DrawerLayout if you want to toggle the slide menu using the app icon you have to use the onOptionsItemSelect that only accept MenuItem from android :(

**Comment by vinceng** [comment]
This is because ActionBarDrawerToggle expects the android version of MenuItem not the actionbar sherlock version.

**Comment by ethervoid** [comment]
Yep i had not make the question correctly. What im asking for is if there
will be a way to implement this with ABS :)

## 

Mario de Frutos

El 16/05/2013, a las 21:48, vinceng notifications@github.com escribió:

This is because ActionBarDrawerToggle expects the android version of
MenuItem not the actionbar sherlock version.

—
Reply to this email directly or view it on
GitHubhttps://github.com/JakeWharton/ActionBarSherlock/issues/941#issuecomment-18024584
.

**Comment by willlunniss** [comment]
Search for SherklockNavigationDrawer for how to do it. 
https://github.com/tobykurien/SherlockNavigationDrawer

Basically create a new MenuItem with same id (android.R.id.home) as the Sherklock MenuItem

**Comment by troymccabe** [comment]
Quick temporary workaround:

```
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                if (mDrawerLayout.isDrawerOpen(mDrawerList)) {
                    mDrawerLayout.closeDrawer(mDrawerList);
                } else {
                    mDrawerLayout.openDrawer(mDrawerList);
                }
                return true;
```

**Comment by tokudu** [comment]
There is another issue is that the up caret icon is not replaced with the new sliding ic_drawer icon.

**Comment by troymccabe** [comment]
@tokudu That isn't ABS, you're missing the initialization that is mentioned here: http://developer.android.com/training/implementing-navigation/nav-drawer.html#ActionBarIcon (more comments here: http://www.reddit.com/r/androiddev/comments/1eldjx/android_ui_patterns_the_new_navigation_drawer/ca1q5ox?context=3 )

**Comment by tokudu** [comment]
Weird. For some reason it still doesn't work for me. I'll debug. Thanks!

**Comment by troymccabe** [comment]
Feel free to message me (reddit, here, troymccabe at gmail) if it's still not cooperating.

**Comment by tokudu** [comment]
It's weird, but it only worked when I manually called syncState:

``` java
mMenuToggle = new ActionBarDrawerToggle(this, mMenuDrawer, R.drawable.ic_drawer, R.string.app_name, R.string.app_name);
mMenuToggle.syncState();
mMenuDrawer.setDrawerListener(mMenuToggle);
```

**Comment by ethervoid** [comment]
Great i,ve seen that issue yesterday but i have not time to debug it. Thx
:)

## 

Mario de Frutos

El 22/05/2013, a las 04:29, Anton Lopyrev notifications@github.com
escribió:

It's weird, but it only worked when I manually called syncState:

mMenuToggle = new ActionBarDrawerToggle(this, mMenuDrawer,
R.drawable.ic_drawer, R.string.app_name,
R.string.app_name);mMenuToggle.syncState();mMenuDrawer.setDrawerListener(mMenuToggle);

—
Reply to this email directly or view it on
GitHubhttps://github.com/JakeWharton/ActionBarSherlock/issues/941#issuecomment-18253999
.

**Comment by leofirespotter** [comment]
Same issue for me, I have all the. Even when I build https://github.com/tobykurien/SherlockNavigationDrawer

**Comment by kyungkoo** [comment]
@tokudu But in Gingerbread, syncState() doesn't work. :( "ic_drawer" doesn't applied.

**Comment by ethervoid** [comment]
Indeed

What i've done is a new style called Root, that applies style for the icon

<style name="Theme.XXX.Root" parent="Theme.XXX">
        <item name="homeAsUpIndicator">@drawable/ic_slide_menu</item>
    </style>

**Comment by kyungkoo** [comment]
@ethervoid Thanks :) it works well :)

**Comment by patriksletmo** [comment]
@kyungkoo Make sure you call syncState() in onPostCreate(Bundle savedInstanceState), like this:

``` java
@Override
protected void onPostCreate(Bundle savedInstanceState) {
    super.onPostCreate(savedInstanceState);

    actionbarDrawerToggle.syncState();
}
```

**Comment by ethervoid** [comment]
In my case i'm doing there and does not work.

**Comment by kyungkoo** [comment]
@patriksletmo  yes, I used that method.
@ethervoid This is my sample app, try this :D 
https://github.com/kyungkoo/SampleNavigationDrawer.git

**Comment by aeroperf** [comment]
I'm having an issue where the ic_drawer icon remains full extended and does not animate to a narrower state when the drawer is opened. Anyone dealt with that?

**Comment by kyungkoo** [comment]
@aeroperf  maybe this sample will help you. :D 
https://github.com/antoniolg/LimeApp

**Comment by aeroperf** [comment]
@kyungkoo Great source, thanks. But still not working :-(

I have to use the ethervoid's style fix from above to even get the three line to show instead of the up caret. And even then, it only shows for GB and not ICS and on. There's something else I'm missing here...

**Comment by kyungkoo** [comment]
@aeroperf  sorry. if you upload your code like gist, maybe other people can help you easier.

**Comment by cyberrob-zz** [comment]
[sample app](https://github.com/kyungkoo/SampleNavigationDrawer/blob/master/src/com/mc2e/sample/drawer/MainActivity.java) from @kyungkoo worked for me.

make sure overwrite the right onOptionsItemSelected() function, which is the 2nd one:

```
public boolean onOptionsItemSelected(MenuItem item) 

public boolean onOptionsItemSelected(com.actionbarsherlock.view.MenuItem item) 
```

**Comment by zaslam3** [comment]
I know I am late in this discussion. I'm having an issue where the ic_drawer icon remains full extended and does not animate to a narrower state when the drawer is opened. It animate on 4.0 and above. but on 2.3.5 and lower it does not animate. I have used 
    @Override
    protected void onPostCreate(Bundle savedInstanceState) {
        super.onPostCreate(savedInstanceState);
        // Sync the toggle state after onRestoreInstanceState has occurred.
        mDrawerToggle.syncState();
    }

```
@Override
public void onConfigurationChanged(Configuration newConfig) {
    super.onConfigurationChanged(newConfig);
    mDrawerToggle.onConfigurationChanged(newConfig);
}
```

but still does not animate. Anyone know about this. Thanks

**Comment by JakeWharton** [comment]
AppCompat is the only way to get DrawerLayout support.

**Comment by grosssmutttr** [comment]
Change import android.support.v4.app.ActionBarDrawerToggle; to 
import android.support.v7.app.ActionBarDrawerToggle;

and remove the icon when you create a new instance of the mDrawerToggle:

mDrawerToggle = new ActionBarDrawerToggle(
                getActivity(),                    /\* host Activity _/
                mDrawerLayout,                    /_ DrawerLayout object _/
                R.string.navigation_drawer_open,  /_ "open drawer" description for accessibility _/
                R.string.navigation_drawer_close  /_ "close drawer" description for accessibility */
        )

This helped on my side...
