### ISSUE TITLE
Completely disable ABS logging [feature request]

### ISSUE THREAD

**Issue by marcosalis** [JakeWharton/ActionBarSherlock#948]
This is a very low priority feature request: it would be very nice to be able to disable completely ActionBarSherlock logging even when the application is in debug mode. ABS logs are quite massive in number and easily flood the process logcat, which can be a bit annoying when looking for other logs during development in a heavily structured application.

Using BuildConfig.DEBUG flag all over the library requires modifying the whole codebase in order to change the logging behavior as it's an automatically generated class and cannot be edited.

**Comment by GBouerat** [comment]
A method like FragmentManager.enableDebugLogging(boolean enabled) or LoaderManager.enableDebugLogging(boolean enabled) will be great.

**Comment by minlite** [comment]
I agree the logging is quite too verbose and floods the Logcat easily. +1

**Comment by iNoles** [comment]
in the monitor window for logcat, you can set filter such as app: and tag:. You have to set own log prefix in your applications, so you can hide abs logging code.

**Comment by marcosalis** [comment]
Using the app: filter won't hide ABS logs as they're coming from the same process, and some apps might not use the same logging tag. I still think that being able to disable the logging completely would be useful.

**Comment by karllindmark** [comment]
@marcosalis:

You could setup your filters to be excluding, rather than including. I'm currently using these settings (at the moment) as they tend to clog the log:

<img src="http://puu.sh/39AnA.png" alt="Filter settings (Eclipse)" />

That way, I don't see the ActionbarSherlock messages, nor dalvikvm/ResourceCompat. Hope I didn't misinterpret your post. :-)

**Comment by marcosalis** [comment]
This definitively works, thank you for the suggestion!
