### ISSUE TITLE
Update to build against Android 4.0

### ISSUE THREAD

**Issue by ianhanniballake** [JakeWharton/ActionBarSherlock#95]
Build ActionBarSherlock against Android 4.0 libraries.

This will prevent run time errors when projects use new methods such as MenuItem.getActionProvider().

While the solution currently compiles, a run time error occurs when the method is called as the method is not implemented in MenuItemImpl:

E/AndroidRuntime(653): java.lang.AbstractMethodError: abstract method not implemented
E/AndroidRuntime(653):  at com.actionbarsherlock.internal.view.menu.MenuItemWrapper.getActionProvider(MenuItemWrapper.java)

**Comment by JakeWharton** [comment]
Android 4.0 support will be coming with #23. Unfortunately it's not trivial to support on the current 3.x versions of this library. Only waiting on the release of the Ice Cream Sandwich sources now...
