### ISSUE TITLE
ShareActionProvider - Bug - Change fixed item

### ISSUE THREAD

**Issue by leandrose** [JakeWharton/ActionBarSherlock#953]
When i use the ShareActionProvider at the very begining the first item is correctly fixed, but when i hold pressed the share button, the first app doens't do anything , but when I pressed other application to share the first one is used.
Like I put on the picture, i tried first with the SMS share button, after tried with FACEBOOK button, but  when I press the sencond time the button the share optin is the first selected(in this case the SMS type).

![captura de tela de 2013-05-27 08 27 29](https://f.cloud.github.com/assets/545876/567943/7fb0d104-c6c7-11e2-9e9d-d5599e955131.png)

**Comment by leandrose** [comment]
When I select a different item of Twitter is not marked as default.

**Comment by JakeWharton** [comment]
It's based on most used not last used. Share to Facebook 10 times and it'll probably take over. Also, make sure you're using the themed context from the action bar to create views.
