### ISSUE TITLE
Upgrade the revision of Android Support Library?

### ISSUE THREAD

**Issue by jelgh** [JakeWharton/ActionBarSherlock#956]
Hello,

I can't Override the onViewStateRestored in a SherlockFragment and I think it is because it depend on revision 7 instead of a newer one. However, I can override it on a "normal" Fragment and I'm using revision 12.

I think it might have been in revision 9 they added the onViewStateRestored to the support fragments.

From http://developer.android.com/tools/extras/support-library.html :
"Fixed many bugs for Fragment, including proper handling of onActivityResult() when the target fragment no longer exists, dispatching selection events to invisible fragments, improved FragmentTransaction.replace() behavior and added better state handling for fragments being moved out of view."

**Comment by JakeWharton** [comment]
Update it in your local copy. ABS is deployed to Maven central which means that all of its dependencies need to also be in Maven central. Since r7 is the latest there, that's the one ABS references. Google _should_ be deploying a new revision soon which is when I will update this dependency. You should definitely upgrade it locally, however.

**Comment by jelgh** [comment]
How can I upgrade it locally? Do you mean I should get the ABS source code, set it to a higher revision, rebuild and upload to our own Maven Repository? Or can I force ABS to use another version of its dependency?

**Comment by iNoles** [comment]
Did you look in https://plus.google.com/+AndroidDevelopers/posts/4Yhpn6p9icf ? com.android.support:support-v4:13.0.0

**Comment by JakeWharton** [comment]
Yes. It's not in central.

**Comment by jelgh** [comment]
@JakeWharton Alright, I'll rebuild ABS then. Thanks for your help!

@iNoles Too bad they didn't upload it to Maven central.

**Comment by iNoles** [comment]
Is there is any kind of policy that prevent Google to push it to the maven central?

**Comment by davidmontemayor** [comment]
Any updates on this front? Seems a bit ridiculous that the latest support library version in Central is a year+ old. :unamused:

**Comment by JakeWharton** [comment]
What's ridiculous is that the community has to support its creation and
upload not Google.

**Comment by davidmontemayor** [comment]
"Open source!" ¬¬ 

.... Yeah. Oh well.
