### ISSUE TITLE
actionbar does not refresh tab selection

### ISSUE THREAD

**Issue by tkiela** [JakeWharton/ActionBarSherlock#957]
I use a TabSwipeFragment from HoloEverywhere.
In this, I use 3 tabs.

The third tab should not be accessible every time. So I use a TabSelectedListener to check this:

```
this.setOnTabSelectedListener(new OnTabSelectedListener(){

    @Override
    public void onTabSelected(int position) {
        switch(position){
            case 0:
            default:
                break;      
            case 1:
                break;      
            case 2:
                if(PlayerPage.accessable!=1) {
                    getSupportActionBar().setSelectedNavigationItem(1);
                }
            break;
        }           
    }         
});
```

The Fragment Tab is changed properly, but the Navigation not. The third "PlayerPage" is marked blue, as this is selected.

**Comment by JakeWharton** [comment]
Does it work on ICS and up?

**Comment by tkiela** [comment]
Tested on 2.3.6. and 4.2.2 and it does not work.

**Comment by JakeWharton** [comment]
Then ABS is behaving correctly by mirroring the native action bar behavior. Try posting a `Runnable` which changes the selection maybe.

**Comment by tkiela** [comment]
Posting a     Runnable worked. Thanks.
