### ISSUE TITLE
Either title, logo or icon doesn't work on pre honeycomb devices

### ISSUE THREAD

**Issue by cesards** [JakeWharton/ActionBarSherlock#959]
I have a very strange problem with action bar in my new application. It only shows up the action items, but not the logo, title or icon (only in 2.2 and 2.3 Android devs)

<img src="http://img854.imageshack.us/img854/3852/sc20130604075657.png" />

Here is my code, I think I'm doing everything ok in my Manifest application tag:

<pre>
android:name=".Loodic"
android:allowBackup="true"
android:icon="@drawable/ic_launcher"
android:label="@string/app_name"
android:logo="@drawable/logo_loodic"
android:theme="@style/Theme.Loodic">

</pre>

Why it's happening this?

Thanks in advance!

**Comment by ksperling** [comment]
@m3n0R is your app theme extending an ABS theme? http://actionbarsherlock.com/theming.html

**Comment by cesards** [comment]
@ksperling yep!

<pre>
style name="X.Theme" parent="Theme.Sherlock.Light.DarkActionBar"
        item name="android:windowBackground">@drawable/background_window /item
        item name="android:actionBarStyle">@style/X.Theme.ActionBar /item
        item name="actionBarStyle">@style/X.Theme.ActionBar /item
 /style
</pre>

and

<pre>
style name="X.Theme.ActionBar" parent="android:Widget.Holo.Light.ActionBar">
        item name="android:background">@drawable/background_actionbar /item
        item name="background">@drawable/background_actionbar /item
        item name="android:titleTextStyle">@style/X.Theme.ActionBar.TitleTextStyle /item
/style
</pre>

**Comment by cesards** [comment]
@ksperling shit I realized of that at the same time I was answering you....

I don't know why this happened : 
...android:Widget.Holo.Light.ActionBar ...

Thanks so much!
