### ISSUE TITLE
InflateException on using ShareActionProvider

### ISSUE THREAD

**Issue by gauravsapiens** [JakeWharton/ActionBarSherlock#962]
I've literally spent half of my day trying to work out this bug. Basically, this bug occurs whenever I add         android:actionProviderClass="com.actionbarsherlock.widget.ShareActionProvider"
in the menu item.

I've no idea on why this occurs. Any help would be greatly appreciated. Thanks !

06-05 18:02:05.264: E/AndroidRuntime(24199): FATAL EXCEPTION: main
06-05 18:02:05.264: E/AndroidRuntime(24199): android.view.InflateException: Binary XML file line #26: Error inflating class <unknown>
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.actionbarsherlock.widget.ActivityChooserView.<init>(ActivityChooserView.java:229)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.actionbarsherlock.widget.ActivityChooserView.<init>(ActivityChooserView.java:202)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.actionbarsherlock.widget.ActivityChooserView.<init>(ActivityChooserView.java:192)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.actionbarsherlock.widget.ShareActionProvider.onCreateActionView(ShareActionProvider.java:164)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.actionbarsherlock.internal.view.ActionProviderWrapper.onCreateActionView(ActionProviderWrapper.java:23)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.ActionProvider.onCreateActionView(ActionProvider.java:98)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.MenuItemImpl.getActionView(MenuItemImpl.java:580)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:155)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:404)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1048)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:87)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:188)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:244)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:946)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:969)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:450)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:769)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:201)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.Choreographer.doFrame(Choreographer.java:531)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.os.Handler.handleCallback(Handler.java:725)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.os.Handler.dispatchMessage(Handler.java:92)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.os.Looper.loop(Looper.java:137)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.app.ActivityThread.main(ActivityThread.java:5039)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at java.lang.reflect.Method.invokeNative(Native Method)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at java.lang.reflect.Method.invoke(Method.java:511)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at dalvik.system.NativeStart.main(Native Method)
06-05 18:02:05.264: E/AndroidRuntime(24199): Caused by: java.lang.reflect.InvocationTargetException
06-05 18:02:05.264: E/AndroidRuntime(24199):    at java.lang.reflect.Constructor.constructNative(Native Method)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
06-05 18:02:05.264: E/AndroidRuntime(24199):    ... 37 more
06-05 18:02:05.264: E/AndroidRuntime(24199): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f01000f a=-1}
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.content.res.Resources.loadDrawable(Resources.java:1927)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.View.<init>(View.java:3328)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.view.ViewGroup.<init>(ViewGroup.java:431)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.widget.FrameLayout.<init>(FrameLayout.java:101)
06-05 18:02:05.264: E/AndroidRuntime(24199):    at android.widget.FrameLayout.<init>(FrameLayout.java:97)

**Comment by JakeWharton** [comment]
Dupe #603.
