### ISSUE TITLE
Menu Button Crash

### ISSUE THREAD

**Issue by renclav** [JakeWharton/ActionBarSherlock#972]
Using ABS 4.3.1 (direct from http://actionbarsherlock.com/) on API 17,

Touching the menu button occasionally causes the app to crash.

The options menu is created:

@Override
public boolean onCreateOptionsMenu(Menu menu) {
MenuInflater inflater = getSupportMenuInflater();
inflater.inflate(R.menu.main_tabs_menu, menu);
StyledButton unread = (StyledButton)
menu.findItem(R.id.menu_unread).getActionView();
unread.setImageResource(R.drawable.social_chat);
ureadimagebutton = unread;
ureadimagebutton.setOnClickListener(ureadimagebuttonlistener);
return super.onCreateOptionsMenu(menu);
}

And my main_tabs_menu.xml:

<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android" >

```
<item
    android:id="@+id/menu_unread"
    android:actionViewClass="com.projectname.Custom.StyledButton"
    android:icon="@drawable/social_chat"
    android:orderInCategory="1"
    android:showAsAction="always"
    android:title="Unread"/>
<item
    android:id="@+id/menu_edit"
    android:icon="@drawable/content_edit"
    android:orderInCategory="2"
    android:showAsAction="always"
    android:title="Options">
    <menu>
        <item
            android:id="@+id/submenu_edit_add_contact"
            android:orderInCategory="1"
            android:title="Add Contact"/>
        <item
            android:id="@+id/submenu_edit_add_gchat"
            android:orderInCategory="2"
            android:title="Add Group Chat"/>
        <item
            android:id="@+id/submenu_edit_broadcast"
            android:orderInCategory="3"
            android:title="Broadcast Message"/>
        <item
            android:id="@+id/submenu_edit_my_profile"
            android:orderInCategory="4"
            android:title="My Profile"/>
    </menu>
</item>
```

</menu>

The crash log:

06-13 09:46:51.209: D/AbsListView(20892): Get MotionRecognitionManager
06-13 09:46:51.234: D/AndroidRuntime(20892): Shutting down VM
06-13 09:46:51.234: W/dalvikvm(20892): threadid=1: thread exiting with uncaught exception (group=0x4101d2a0)
06-13 09:46:51.299: E/AndroidRuntime(20892): FATAL EXCEPTION: main
06-13 09:46:51.299: E/AndroidRuntime(20892): java.lang.ClassCastException: com.android.internal.view.menu.ActionMenuView$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:311)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.View.measure(View.java:15473)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5056)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1396)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1038)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:576)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at com.android.internal.view.menu.ActionMenuView.onMeasure(ActionMenuView.java:176)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.View.measure(View.java:15473)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at com.android.internal.widget.AbsActionBarView.measureChildView(AbsActionBarView.java:213)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at com.android.internal.widget.ActionBarView.onMeasure(ActionBarView.java:1047)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.View.measure(View.java:15473)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5056)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at com.android.internal.widget.ActionBarContainer.onMeasure(ActionBarContainer.java:173)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.View.measure(View.java:15473)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5056)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1396)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.View.measure(View.java:15473)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5056)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2361)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.View.measure(View.java:15473)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1974)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1217)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1390)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1112)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4472)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.Choreographer.doFrame(Choreographer.java:525)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.os.Handler.handleCallback(Handler.java:615)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.os.Handler.dispatchMessage(Handler.java:92)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.os.Looper.loop(Looper.java:137)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at android.app.ActivityThread.main(ActivityThread.java:4898)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at java.lang.reflect.Method.invokeNative(Native Method)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at java.lang.reflect.Method.invoke(Method.java:511)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
06-13 09:46:51.299: E/AndroidRuntime(20892):    at dalvik.system.NativeStart.main(Native Method)

I have tested this with and without overflow menu items with the same result.

Could this be related to my manifest attribute:
android:alwaysRetainTaskState="true"
?

Thank You

**Comment by renclav** [comment]
Sorry, the com.projectname.Custom.StyledButton class referenced in the menu xml is just a simple extended ImageButton.

public class StyledButton extends ImageButton {

```
public StyledButton(Context context) {
    super(context, null, R.attr.actionButtonStyle);
}

public StyledButton(Context context, AttributeSet attrs) {
    super(context, attrs, R.attr.actionButtonStyle);
}

public StyledButton(Context context, AttributeSet attrs, int defStyle) {
    super(context, attrs, R.attr.actionButtonStyle);
}
```

}

I needed the menu item view to attach a badge to it (displays unread message count)

**Comment by JakeWharton** [comment]
Are you handling config changes for 'orientation' by any chance?

**Comment by renclav** [comment]
Yes I am. Which is to say, they are ignored (the app requirement is to not rotate the screen).

Example activity in the manifest

```
    <activity
        android:name="com.private.Screens.WelcomeScreen"
        android:configChanges="orientation|screenSize"
        android:label="Welcome"
        android:screenOrientation="nosensor" >
    </activity>
```

**Comment by JakeWharton** [comment]
Handling orientation changes with ABS is not supported. It doesn't allow the library to properly reconfigure itself on rotation.

If you want to lock the app from rotation use the `orientation` attribute on the activity declaration.

**Comment by renclav** [comment]
The problem being that ! already lock the app from rotation (see previous comment).

Although I have sidestepped this issue by changing my design, I am still interested as to reasoning behind this crash.
