### ISSUE TITLE
Crash with android:background=“?activatedBackgroundIndicator”

### ISSUE THREAD

**Issue by nicolasjafelle** [JakeWharton/ActionBarSherlock#973]
I have a problem related to this statement with ActionBarSherlock:

``` xml
android:background="?activatedBackgroundIndicator"
```

The problem is, If I use this value in a layout like this:

``` xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
       xmlns:tools="http://schemas.android.com/tools"
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:background="?activatedBackgroundIndicator">
.....
```

The adapter that contains this XML crash if I use the Theme:

``` xml
<style name="AppTheme" parent="@style/Theme.Sherlock.Light.DarkActionBar">
```

But it works if I change the theme to:

``` xml
<style name="AppTheme" parent="@style/Theme.Sherlock.Light">
```

Is this a bug of ActionBarSherlock?? Or I am doing something wrong? Repeat it crashes If I use the Light.DarkActionBar theme but works if I use the Light theme.

Thanks in advance.

**Comment by intrications** [comment]
activatedBackgroundIndicator was only added in API level 11 but I don't know if this is causing your specific crash.

**Comment by nicolasjafelle** [comment]
Sorry... I forgot to mention that this crash in my Razr I with 4.1.2 but not in Android 2.3.7, weird.

**Comment by intrications** [comment]
If the problem is on 4.1 then have you tried just testing the
Theme.Holo.Light.DarkActionBar theme to see if it is the Sherlock version
of the theme that is causing the problem?

**Comment by SimonVT** [comment]
We don't set attributes on the DarkActionBar theme we don't use in ABS.

**Comment by nicolasjafelle** [comment]
Sorry SimonVT I don't understand, are you saying that ActionBarSherlock does not use Light.DarkActionBar?

Intrications yes! I tested to change the:

``` xml
android:background="?activatedBackgroundIndicator"
```

for this:

``` xml
android:background="?android:attr/activatedBackgroundIndicator"
```

Which is the original attribute and works.

The stacktrace:

 FATAL EXCEPTION: main
E/AndroidRuntime( 1574): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
E/AndroidRuntime( 1574):        at android.view.LayoutInflater.createView(LayoutInflater.java:613)
E/AndroidRuntime( 1574):        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
E/AndroidRuntime( 1574):        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
E/AndroidRuntime( 1574):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
E/AndroidRuntime( 1574):        at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
E/AndroidRuntime( 1574):        at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime( 1574):        at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
E/AndroidRuntime( 1574):        at android.view.View.inflate(View.java:16119)
E/AndroidRuntime( 1574):        at com.senddinero.app.view.PlatformItemView.init(PlatformItemView.java:37)
E/AndroidRuntime( 1574):        at com.senddinero.app.view.PlatformItemView.<init>(PlatformItemView.java:23)
E/AndroidRuntime( 1574):        at com.senddinero.app.adapter.PlatformsAdapter.getView(PlatformsAdapter.java:50)
E/AndroidRuntime( 1574):        at android.widget.AbsListView.obtainView(AbsListView.java:2267)
E/AndroidRuntime( 1574):        at android.widget.ListView.makeAndAddView(ListView.java:1769)
E/AndroidRuntime( 1574):        at android.widget.ListView.fillDown(ListView.java:672)
E/AndroidRuntime( 1574):        at android.widget.ListView.fillFromTop(ListView.java:733)
E/AndroidRuntime( 1574):        at android.widget.ListView.layoutChildren(ListView.java:1622)
E/AndroidRuntime( 1574):        at android.widget.AbsListView.onLayout(AbsListView.java:2102)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1574):        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1574):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1574):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1574):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1574):        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
E/AndroidRuntime( 1574):        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
E/AndroidRuntime( 1574):        at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1574):        at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime( 1574):        at android.view.View.layout(View.java:13754)
E/AndroidRuntime( 1574):        at android.view.ViewGroup.layout(ViewGroup.java:4362)
E/AndroidRuntime( 1574):        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
E/AndroidRuntime( 1574):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
E/AndroidRuntime( 1574):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
E/AndroidRuntime( 1574):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
E/AndroidRuntime( 1574):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
E/AndroidRuntime( 1574):        at android.view.Choreographer.doCallbacks(Choreographer.java:555)
E/AndroidRuntime( 1574):        at android.view.Choreographer.doFrame(Choreographer.java:525)
E/AndroidRuntime( 1574):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
E/AndroidRuntime( 1574):        at android.os.Handler.handleCallback(Handler.java:615)
E/AndroidRuntime( 1574):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 1574):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1574):        at android.app.ActivityThread.main(ActivityThread.java:4745)
E/AndroidRuntime( 1574):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1574):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1574):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime( 1574):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 1574):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1574): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 1574):        at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 1574):        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
E/AndroidRuntime( 1574):        at android.view.LayoutInflater.createView(LayoutInflater.java:587)
E/AndroidRuntime( 1574):        ... 55 more
E/AndroidRuntime( 1574): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010047 a=-1}
E/AndroidRuntime( 1574):        at android.content.res.Resources.loadDrawable(Resource

**Comment by SimonVT** [comment]
I mean, ABS does not define attributes in the DarkActionBar theme on api14+ that it doesn't use itself. The library isn't meant to help you theme your app.

**Comment by nicolasjafelle** [comment]
But why it works with Theme.Sherlock.Light ?? It should be the same. So if I need to use Theme.Sherlock.Light.DarkActionBar I cannot use the attribute defined by ABS for 14+ ?

**Comment by SimonVT** [comment]
Because it uses the same base theme as the <API14 themes. DarkActionBar does not.

**Comment by nicolasjafelle** [comment]
Oooh!! So is it a bug? Or a expected behaviour?

**Comment by SimonVT** [comment]
Entirely expected. As I said, unless ABS uses the attribute we don't set them.

**Comment by nicolasjafelle** [comment]
So what do you recommend?? Create a layout-v11 and put there the value that it works?

**Comment by ghost** [comment]
Still no solution ??

**Comment by nicolasjafelle** [comment]
I could fix it by creating a values-v11 and create specific xml for this.
