### ISSUE TITLE
Cannot modify 'Up' drawable when action items are expanded/collapsed

### ISSUE THREAD

**Issue by bri822** [JakeWharton/ActionBarSherlock#975]
My application replaces the 'Up' icon by overwriting the 'homeAsUpIndicator' attribute to a custom icon.  I'm replacing it with 3 bars to indicate a slide out menu as mentioned in the last Android Design Guidelines.

Based on the design of Ice Cream sandwich apps, when a search action item is expanded on the action bar, the Home icon should switch to the original 'Up' arrow.  I was unable to find a way to programmatically access the ImageView or to change the drawable in the ImageView (id: abs__up). 

If ActionBarSherlock could replace a custom Up drawable with the default Up arrow when the user expands an action item, that'd be great.  Otherwise, I can manually change the icon if some API is provided to allow me to set the Drawable of the Up ImageView.

If some existing work around exists, then I'm sorry to open this issue and please let me know how I can resolve this issue.  Thank you!

**Comment by SimonVT** [comment]
The ActionBar does not currently expose any API to change the up button in java. Look at e.g. the support library drawer for how it changes the icon.

**Comment by bri822** [comment]
Thanks Simon, I found the ActionBarDrawerToggle was merged in two days ago. https://github.com/JakeWharton/ActionBarSherlock/pull/946

The ActionBarDrawerToggle is exactly what I am looking for and am excited to see the support libs finally updated to allow ABS to merge it in.  Can't wait for the next release to try it out.

**Comment by felipecsl** [comment]
is this in the latest release already? can't find in the changelog
