### ISSUE TITLE
NullPointerException in TitlePageIndicator.java

### ISSUE THREAD

**Issue by Starksoft** [JakeWharton/ActionBarSherlock#976]
Hi!
I`m developing very popular balance tracker in Russia and CIS.
In my BugSense Account sometimes i see a NullPointerException in TitlePageIndicator.java:573
Heare is a stacktrace:
0java.lang.NullPointerException
1at android.support.v4.view.ViewPager.fakeDragBy(ViewPager.java:1733)
2at com.viewpagerindicator.TitlePageIndicator.onTouchEvent(TitlePageIndicator.java:573)
3at android.view.View.dispatchTouchEvent(View.java:5579)
4at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1987)
5at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
6at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
7at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
8at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
9at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
10at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1965)
11at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1734)
12at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1983)
13at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1442)
14at android.app.Activity.dispatchTouchEvent(Activity.java:2421)
15at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1931)
16at android.view.View.dispatchPointerEvent(View.java:5759)
17at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2970)
18at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2529)
19at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:869)
20at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2538)
21at android.os.Handler.dispatchMessage(Handler.java:99)
22at android.os.Looper.loop(Looper.java:154)
23at android.app.ActivityThread.main(ActivityThread.java:4945)
24at java.lang.reflect.Method.invokeNative(Native Method)
25at java.lang.reflect.Method.invoke(Method.java:511)
26at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
27at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
28at dalvik.system.NativeStart.main(Native Method)

fix it please.
My solution was surround code block with try/catch.

**Comment by SimonVT** [comment]
Wrong project
