### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by cffan** [JakeWharton/ActionBarSherlock#986]
Sherlockactionbar is working on most devices but throws java.lang.NoClassDefFoundError on some devices (e.g. Sony Xperia arc s LT18i, Motorola Zoom MZ606). All sherlockactionbar codes are in my project instead of referenced library. Here's the log:

07-03 22:28:32.273 W/dalvikvm( 4612): VFY: unable to resolve static field 1213 (SherlockTheme) in Lcom/morpheus/ar/R$styleable;
07-03 22:28:32.273 D/dalvikvm( 4612): VFY: replacing opcode 0x62 at 0x0014
07-03 22:28:32.273 D/dalvikvm( 4612): VFY: dead code 0x0016-00e6 in Lcom/actionbarsherlock/internal/ActionBarSherlockCompat;.generateLayout ()Landroid/view/ViewGroup;
07-03 22:28:32.273 W/dalvikvm( 4612): VFY: unable to resolve static field 1213 (SherlockTheme) in Lcom/morpheus/ar/R$styleable;
07-03 22:28:32.273 D/dalvikvm( 4612): VFY: replacing opcode 0x62 at 0x0116
07-03 22:28:32.273 D/dalvikvm( 4612): VFY: dead code 0x0118-0122 in Lcom/actionbarsherlock/internal/ActionBarSherlockCompat;.installDecor ()V
07-03 22:28:32.283 D/ActionBarSherlock( 4612): [<ctor>] activity: com.morpheus.ar.android.plugin.activities.SettingsActivity@40582ca0, flags: 1
07-03 22:28:32.283 D/ActionBarSherlock( 4612): [setContentView] layoutResId: 17367121
07-03 22:28:32.283 D/ActionBarSherlock( 4612): [installDecor]
07-03 22:28:32.283 D/ActionBarSherlock( 4612): [generateLayout]
07-03 22:28:32.283 D/AndroidRuntime( 4612): Shutting down VM
07-03 22:28:32.283 W/dalvikvm( 4612): threadid=1: thread exiting with uncaught exception (group=0x40018e08)
07-03 22:28:32.713 E/AndroidRuntime( 4612): FATAL EXCEPTION: main
07-03 22:28:32.713 E/AndroidRuntime( 4612): java.lang.NoClassDefFoundError: com.morpheus.ar.R$styleable
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.generateLayout(ActionBarSherlockCompat.java:976)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:905)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:839)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at com.actionbarsherlock.app.SherlockPreferenceActivity.setContentView(SherlockPreferenceActivity.java:230)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:107)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at com.morpheus.ar.android.plugin.activities.SettingsActivity.onCreate(SettingsActivity.java:16)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1660)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1716)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.app.ActivityThread.access$1500(ActivityThread.java:124)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:968)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.os.Looper.loop(Looper.java:130)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at android.app.ActivityThread.main(ActivityThread.java:3806)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at java.lang.reflect.Method.invokeNative(Native Method)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at java.lang.reflect.Method.invoke(Method.java:507)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
07-03 22:28:32.713 E/AndroidRuntime( 4612):     at dalvik.system.NativeStart.main(Native Method)

I've been looking around and found no similar issues. Anyone knows how to solve this?

**Comment by JakeWharton** [comment]
We've had a couple of these on the mailing list and issues. There's nothing wrong with ABS that's causing this. The fact that it can't find an R class usually indicates something is seriously wrong with the VM. Nothing I can do here.
