### ISSUE TITLE
Enable setTypeface for Custom Title View

### ISSUE THREAD

**Issue by shivakumars** [JakeWharton/ActionBarSherlock#989]
I am trying to set Typeface for a textview which is a child of custom title view. But nothing works. I read that it is possible via hacks in an issue reported in this repository. So if that is possible, can you help me to achieve it.

**Comment by JakeWharton** [comment]
If you are using a custom view for the title then you can adjust the typeface like any other normal TextView. StackOverflow or the official Android development mailing list is a better place for this question.
