### ISSUE TITLE
NotificationCompat does not wok with ActionBarSherlock

### ISSUE THREAD

**Issue by strgev** [JakeWharton/ActionBarSherlock#990]
NotificationCompat.Builder notificationBuilder = 
    new NotificationCompat.Builder(this);
notificationBuilder
    .setContentTitle("Your Application")
    .setContentText("Downloading data from the server")
    .setSmallIcon(android.R.drawable.ic_media_next);
((NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE))
    .notify(001, notificationBuilder.build());

Replacing with the latest android-support-v4.jar in ActionBarSherlock project didn't help. Please help to solve this issue.

**Comment by JakeWharton** [comment]
These classes are from the support library, not ActionBarSherlock. ABS ships with an old version so you have to update it to r13. Make sure you use r13 everywhere. Not much more I can help with.

**Comment by strgev** [comment]
Thank you very much!!! It is worked by adding r13.
