### ISSUE TITLE
Margin TOP issue in MenuItem

### ISSUE THREAD

**Issue by matrad** [JakeWharton/ActionBarSherlock#991]
Hello,

I've detected an issue with the margin-top Value in a CustomView of the MenuItem, like described here:
http://stackoverflow.com/questions/17487859/actionbarsherlock-menuitem-actionlayout-issue

I've seen recently that there are sometimes also different margins on devices > 11 api, so it doesn't depends only on the api level < or > 11.

**Comment by JakeWharton** [comment]
Er, this is a bug in RelativeLayout, not ABS. No?

**Comment by SimonVT** [comment]
Yes. ABS doesn't know about the child views of your RelativeLayout.
