### ISSUE TITLE
SherlockDialogFragment expands to whole screen if setStyle is used

### ISSUE THREAD

**Issue by rishabhmhjn** [JakeWharton/ActionBarSherlock#998]
I have been using the following code to display a SherlockDialogFragment to be a floating dialog.
**Before update (this worked)**

``` java
  fragment.setStyle(SherlockDialogFragment.STYLE_NORMAL,
      R.style.Theme_Sherlock_Dialog);
```

But when I updated to the latest version of the ABS (4.3.1), it doesn't show a floating dialog, but rather a dialog filling up the whole screen.

**After update (not working)**

``` java
  fragment.setStyle(SherlockDialogFragment.STYLE_NORMAL,
      R.style.Sherlock___Theme);
```

The `R.style.Theme_Sherlock_Dialog` is missing in the current version. So I'm not sure if this is the problem.

Please pardon if this is a trivial question but it will be greate if someone can help me to set the style (dark holo) to the SherlockDialogFragment which will be a floating dialog.
Thank you

**Comment by JakeWharton** [comment]
The dialog themes were removed. If you want consistent dialog theming then you'll have to craft your own theme.
