### ISSUE TITLE
Actionbarsherlock style attrs conflict with android-support-v7-appcompat

### ISSUE THREAD

**Issue by bobbyflowstate** [JakeWharton/ActionBarSherlock#999]
Hey guys, I'm having an issue when I add the android-support-v7-appcompat to my project.  Basically I'm getting a bunch of these build errors:

/libs/actionbarsherlock/res/values/abs__attrs.xml:4: error: Attribute "titleTextStyle" has already been defined

The attrs from appcompat library are the same.  Is there no workaround for this?  Do I need to manually change the styles in the library myself?  Seems like there should be a workaround for this.

Thanks!

**Comment by JakeWharton** [comment]
Why are you using both? The libraries are mutually exclusive.

**Comment by bobbyflowstate** [comment]
Thanks Jake.  Sorry for the non-issue.  I don't know what I was thinking.

**Comment by bobbyflowstate** [comment]
Hey Jake, I'm still having issues with this. Basically I need to include android.support.v7.mediarouter in my project, which depends on appcompat library.  How can I do this when my project also depends on actionbarsherlock?

**Comment by JakeWharton** [comment]
You can probably just copy out the classes that you need. I don't know, really. The two projects weren't meant to coincide and if Google put more than just the action bar in AppCompat then that's really not smart.

**Comment by bobbyflowstate** [comment]
Agreed.  Hmm so this is pretty bad because apps using actionbarsherlock will not be able to integrate chromecast without major modifications to libraries.  Is there anyway to remove appcompat from actionbarsherlock so that i can add it to my workspace as a separate project?

**Comment by bobbyflowstate** [comment]
I've filed a bug against google-cast sdk.  Hopefully it will get looked at.  Just an FYI, here's a related stackoverflow thread: http://stackoverflow.com/questions/17864891/unable-to-find-package-com-google-cast

google-cast-sdk bug: https://code.google.com/p/google-cast-sdk/issues/detail?id=13&thanks=13&ts=1375199054

**Comment by chrisbanes** [comment]
MediaRouter builds upon AppCompat. If you want to use MediaRouter with ActionBarSherlock then you're going to need to get the source, and modify it to use ABS' classes instead.

**Comment by dadatuputi** [comment]
Black tiger, did you ever resolve this? I'm going to be adding Chromecast compatibility to my app soon, and wonder if you solved this problem.

**Comment by pschichtel** [comment]
@JakeWharton Just out of curiosity: Why are the libraries mutually exclusive?

**Comment by JakeWharton** [comment]
They both back port action bars. The Chromecast stuff obviously isn't.

**Comment by pschichtel** [comment]
Sure, it doesn't make sense, but are there technical reasons?

**Comment by JakeWharton** [comment]
aapt doesn't support custom attributes declared multiple times.

**Comment by pschichtel** [comment]
Thank you

**Comment by kernhu** [comment]
i meet the troublesome too····
